AP2.exam.part('exam1-ps', {
  t: 'Handlungsschritt 2: Anforderungen analysieren und modellieren (25 Punkte)',
  tasks: [
    {pts: 4, q: 'Nennen Sie zwei Unterschiede zwischen Lastenheft und Pflichtenheft (Ersteller, Inhalt).',
      a: ['- **Lastenheft:** vom **Auftraggeber** (FitPlan) erstellt, beschreibt **was** und **wofür** gebraucht wird (Anforderungen, Wünsche).', '- **Pflichtenheft:** vom **Auftragnehmer** (Softwarehaus) erstellt, beschreibt **wie und womit** die Anforderungen umgesetzt werden (konkrete Lösung, technische Umsetzung); es wird vertragliche Grundlage und Basis der Abnahme.']},
    {pts: 5, q: 'Das Projekt wird mit Scrum durchgeführt. Nennen Sie die drei Scrum-Rollen mit je einer Aufgabe und zwei Scrum-Ereignisse.',
      a: ['- **Product Owner:** verantwortet das Product Backlog und den Nutzen des Produkts (priorisiert Anforderungen).', '- **Scrum Master:** sorgt dafür, dass Scrum verstanden und gelebt wird, beseitigt Hindernisse.', '- **Entwicklungsteam:** setzt die Anforderungen im Sprint um, organisiert sich selbst.', 'Ereignisse (zwei genügen): Sprint Planning, Daily Scrum (15 Minuten), Sprint Review, Sprint Retrospective.']},
    {pts: 4, q: 'Beschreiben Sie ein Anwendungsfalldiagramm für das Portal: Nennen Sie zwei Akteure und vier Anwendungsfälle. Erklären Sie die Beziehung include an einem Beispiel.',
      a: ['- Akteure: **Mitglied**, **Trainer** (auch Verwaltung, Zahlungsdienst als Nebenakteur).', '- Anwendungsfälle: Kurs suchen, Termin buchen, Buchung stornieren, Kurs anlegen, Teilnehmerliste ansehen.', '- **include:** Ein Anwendungsfall bindet einen anderen **zwingend** ein: "Termin buchen" **include** "Anmelden" (ohne Anmeldung keine Buchung).']},
    {pts: 7, rows: 7, q: 'Entwerfen Sie ein Klassendiagramm (als Beschreibung: Klassen mit je zwei Attributen, Beziehungen mit Multiplizitäten). Anforderungen: Ein Kurs hat mehrere Termine, ein Termin gehört zu genau einem Kurs. Ein Trainer leitet mehrere Termine, ein Termin hat genau einen Trainer. Mitglieder buchen Termine; ein Mitglied kann mehrere Termine buchen, ein Termin hat viele Teilnehmer.',
      a: ['- Klassen: **Kurs** (titel, beschreibung), **Termin** (datum, plaetze), **Trainer** (name, qualifikation), **Mitglied** (name, email).', '- Kurs 1 zu 0..* Termin (Kurs hat Termine; Komposition möglich, da Termine ohne Kurs nicht existieren).', '- Trainer 1 zu 0..* Termin (leitet).', '- Mitglied 0..* zu 0..* Termin (bucht): **n:m**, wird in der Datenbank zur Zwischentabelle **Buchung**; im Klassendiagramm kann eine Assoziationsklasse **Buchung** (datum, status) stehen.', 'Je 1 Punkt für Klassen mit Attributen, 3 Punkte für richtige Beziehungen und Multiplizitäten.'],
      sol: [['diagram', {w: 760, h: 230, keep: 640, cap: 'Mögliches Klassendiagramm', nodes: [
        {id: 'k', k: 'cls', x: 90, y: 100, w: 150, t: {name: 'Kurs', attrs: ['titel', 'beschreibung']}}, {id: 't', k: 'cls', x: 330, y: 100, w: 150, t: {name: 'Termin', attrs: ['datum', 'plaetze']}}, {id: 'tr', k: 'cls', x: 330, y: 200, w: 150, t: {name: 'Trainer', attrs: ['name', 'qualifikation']}}, {id: 'm', k: 'cls', x: 650, y: 100, w: 150, t: {name: 'Mitglied', attrs: ['name', 'email']}},
      ], edges: [{a: 'k', b: 't', sa: 'diaf', ea: 'none', ta: '1', tb: '0..*', t: 'hat'}, {a: 'tr', b: 't', ea: 'none', ta: '1', tb: '0..*', t: 'leitet'}, {a: 'm', b: 't', ea: 'none', ta: '0..*', tb: '0..*', t: 'bucht'}]}]]},
    {pts: 5, rows: 5, q: 'Eine Buchung durchläuft Zustände. Nennen Sie mindestens vier Zustände einer Buchung mit den auslösenden Ereignissen für die Übergänge (Zustandsdiagramm).',
      a: ['- Start: Mitglied bucht, Zustand **angefragt**.', '- Zahlung/Platzprüfung erfolgreich: **bestätigt** (ist kein Platz frei: **Warteliste**).', '- Mitglied storniert oder Frist verstrichen: **storniert** (Endzustand), Platz wird frei, Nachrücker aus Warteliste.', '- Termin findet statt: **durchgeführt/abgeschlossen** (Endzustand).', 'Je Zustand und Übergang mit Ereignis gibt es Punkte; ein Zustandsdiagramm hat Start- und Endzustand.']},
  ],
});
