AP2.add('eua-onotation', [
  ['h', 'Best, Average, Worst Case'],
  ['p', 'Die Laufzeit hängt oft von den **Daten** ab, nicht nur von n. Beispiel lineare Suche: Steht das Gesuchte **ganz vorne**, braucht man 1 Schritt (**Best Case O(1)**). Steht es **ganz hinten oder gar nicht** da, braucht man n Schritte (**Worst Case O(n)**). Im Durchschnitt sind es etwa n/2 Schritte (**Average Case**, ebenfalls O(n)). In der Prüfung ist meist der **Worst Case** gefragt, weil er eine **Garantie** liefert.'],
  ['table', ['Algorithmus', 'Best Case', 'Average Case', 'Worst Case'], [
    ['Lineare Suche', 'O(1)', 'O(n)', 'O(n)'],
    ['Binäre Suche', 'O(1)', 'O(log n)', 'O(log n)'],
    ['Bubblesort (mit Flag)', 'O(n)', 'O(n²)', 'O(n²)'],
    ['Insertionsort', 'O(n)', 'O(n²)', 'O(n²)'],
    ['Quicksort', 'O(n log n)', 'O(n log n)', 'O(n²)'],
    ['Mergesort', 'O(n log n)', 'O(n log n)', 'O(n log n)'],
    ['Hashtabelle: get', 'O(1)', 'O(1)', 'O(n) (viele Kollisionen)'],
    ['BST: Suche', 'O(1)', 'O(log n)', 'O(n) (entartet)'],
  ]],
  ['h', 'Speicherkomplexität'],
  ['p', 'Auch der **zusätzliche Speicherbedarf** wird in O-Notation angegeben. Beispiel: Bubblesort braucht nur wenige Hilfsvariablen: **O(1)**. Mergesort braucht ein Hilfsfeld: **O(n)**. Eine rekursive Funktion mit Rekursionstiefe n braucht **O(n)** Stack-Speicher. Oft kann man **Zeit gegen Speicher tauschen**: Eine Hashtabelle (mehr Speicher) beschleunigt die Suche.'],
  ['h', 'Praktische Bedeutung'],
  ['list', ['Bei **kleinen Datenmengen** ist ein "schlechter" Algorithmus oft gut genug (und einfacher).', 'Bei **großen** Datenmengen entscheidet die Klasse: O(n²) bei 1 Million Datensätzen bedeutet 10^12 Schritte, also **Stunden** statt Millisekunden.', '**Konstante Faktoren** zählen in der Praxis trotzdem (Cache, Overhead).', 'Die O-Notation ist eine **obere Schranke**, genauer sind Θ (genau) und Ω (untere Schranke). Für die Prüfung genügt O.']],
  ['h', 'Aufgaben im Prüfungsstil'],
  ['qa', 'Bestimmen Sie die Komplexität: for (int i = 0; i < n; i++) { for (int j = 0; j < n; j++) { zaehler++; } }', '**O(n²)**: Die innere Schleife läuft bei jedem der n Durchläufe der äußeren n-mal, also n mal n = n² Ausführungen von `zaehler++`.', 3],
  ['qa', 'Bestimmen Sie die Komplexität: int i = n; while (i > 1) { i = i / 2; }', '**O(log n)**: i wird in jedem Schritt halbiert. Nach etwa log2(n) Schritten ist i gleich 1.', 3],
  ['qa', 'Ein Algorithmus benötigt 3n² + 10n + 25 Schritte. Wie lautet die O-Notation und warum?', '**O(n²)**. Konstanten (3, 25) werden ignoriert und von den Termen zählt nur der mit dem stärksten Wachstum (n²). Für große n dominiert n² alle anderen Anteile.', 3],
  ['qa', 'Algorithmus A hat die Laufzeit O(n²), Algorithmus B O(n log n). Bei n = 100.000: Wie viele Schritte etwa? Welcher ist besser?', ['A: 100.000² = **10^10** (10 Milliarden) Schritte.', 'B: 100.000 mal log2(100.000) ≈ 100.000 mal 17 = **1,7 Millionen** Schritte.', 'B ist um den Faktor ca. 6.000 schneller und damit für große Daten deutlich besser.'], 5],
  ['qa', 'Nennen Sie je einen Algorithmus mit O(1), O(log n), O(n) und O(n²).', ['- **O(1):** Zugriff auf ein Array-Element über den Index', '- **O(log n):** binäre Suche', '- **O(n):** lineare Suche', '- **O(n²):** Bubblesort'], 4],
  ['quiz', [
    {q: 'Welche Komplexität hat die binäre Suche?', o: ['O(log n)', 'O(n)', 'O(1)', 'O(n²)'], a: 0, e: 'Der Suchbereich wird jeweils halbiert.'},
    {q: 'Vereinfachen Sie O(5n² + 3n + 2).', o: ['O(n²)', 'O(5n²)', 'O(n)', 'O(n³)'], a: 0, e: 'Nur der dominierende Term ohne Konstante: n².'},
    {q: 'Welche Komplexität hat eine einfache Schleife von 1 bis n?', o: ['O(n)', 'O(1)', 'O(n²)', 'O(log n)'], a: 0, e: 'n Durchläufe: linear.'},
    {q: 'Was beschreibt der Worst Case?', o: ['Den ungünstigsten Fall, der die Obergrenze der Laufzeit angibt', 'Den schnellsten Fall', 'Den Durchschnitt', 'Fehler im Code'], a: 0, e: 'Der Worst Case liefert eine Garantie.'},
    {q: 'Welche dieser Klassen wächst am schnellsten?', o: ['O(2^n)', 'O(n²)', 'O(n log n)', 'O(n)'], a: 0, e: 'Exponentielles Wachstum übertrifft jedes Polynom.'},
  ]],
]);
