AP2.page('eua-onotation', {
  b: 'eua', g: 'Algorithmen', t: 'Komplexität und O-Notation (Best, Average, Worst Case)',
  d: 'Die **O-Notation (Landau-Notation)** beschreibt, **wie stark der Aufwand** (Laufzeit oder Speicher) eines Algorithmus **mit der Eingabegröße n wächst**. Sie nennt nur den **dominierenden Term** und ignoriert Konstanten: Zum Beispiel ist 3n² + 5n + 7 gleich **O(n²)**. Man unterscheidet **Best Case** (günstigster Fall), **Average Case** (Durchschnitt) und **Worst Case** (ungünstigster Fall).',
  m: '**O(1) < O(log n) < O(n) < O(n log n) < O(n²) < O(2^n).** Regeln: **Konstanten weglassen, nur den stärksten Term behalten.** Eine Schleife über n = O(n), eine Schleife in einer Schleife = O(n²), Halbieren = O(log n).',
  cheat: [
    ['Wichtige Klassen', ['**O(1)** konstant: Array-Zugriff, Hash-Zugriff', '**O(log n)** logarithmisch: binäre Suche, BST (balanciert)', '**O(n)** linear: lineare Suche, eine Schleife', '**O(n log n)**: Mergesort, Quicksort (Mittel)', '**O(n²)** quadratisch: Bubble-, Insertion-, Selectionsort, verschachtelte Schleifen', '**O(2^n)** exponentiell: naive Fibonacci-Rekursion, Brute Force']],
    ['Regeln', ['Konstanten weglassen: O(3n) = O(n)', 'Nur dominanten Term: O(n² + n) = O(n²)', 'Hintereinander: **addieren** (dann größten nehmen)', 'Verschachtelt: **multiplizieren**', 'Halbieren pro Schritt: **log n**']],
    ['Fälle', ['**Best Case:** günstigste Eingabe (zum Beispiel Treffer sofort)', '**Worst Case:** ungünstigste Eingabe (**in der Prüfung meist gefragt**)', '**Average Case:** typische Eingabe']],
    ['Begriffe', ['**Zeitkomplexität:** Anzahl Schritte', '**Speicherkomplexität (Platz):** zusätzlicher Speicher', '**Skalierung:** Verhalten bei wachsendem n']],
  ],
  blocks: [
    ['h', 'Warum messen wir Komplexität?'],
    ['p', 'Ein Algorithmus kann bei 100 Elementen schnell sein und bei 100.000 Elementen unbrauchbar. Die **Laufzeit in Sekunden** hängt vom Rechner ab. Die O-Notation misst deshalb **nicht Sekunden**, sondern **wie viele Schritte** in Abhängigkeit von n nötig sind. So kann man Algorithmen **unabhängig von der Hardware** vergleichen.'],
    ['chart', {kind: 'line', w: 720, h: 340, labels: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], series: [{n: 'O(log n)', d: [0, 1, 1.6, 2, 2.3, 2.6, 2.8, 3, 3.2, 3.3], k: 'ok'}, {n: 'O(n)', d: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], k: 'accent'}, {n: 'O(n log n)', d: [0, 2, 4.8, 8, 11.6, 15.5, 19.7, 24, 28.5, 33.2], k: 'text'}, {n: 'O(n²)', d: [1, 4, 9, 16, 25, 36, 49, 64, 81, 100], k: 'text3'}, {n: 'O(2^n)', d: [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024], k: 'bad'}], ymax: 100, yl: 'Schritte (bei n = 1 bis 10)', cap: 'Wachstum der wichtigsten Klassen. Die rote Kurve (2^n) schießt schon bei kleinem n aus dem Diagramm.'}],
    ['table', ['Klasse', 'Name', 'n = 10', 'n = 100', 'n = 1.000', 'Beispiel'], [
      ['O(1)', 'konstant', '1', '1', '1', 'Zugriff auf `a[i]`, Hash-Lookup'],
      ['O(log n)', 'logarithmisch', '3', '7', '10', 'Binäre Suche'],
      ['O(n)', 'linear', '10', '100', '1.000', 'Lineare Suche, Summe eines Arrays'],
      ['O(n log n)', 'linearithmisch', '33', '664', '9.966', 'Mergesort, Quicksort (Mittel)'],
      ['O(n²)', 'quadratisch', '100', '10.000', '1.000.000', 'Bubblesort, doppelte Schleife'],
      ['O(n³)', 'kubisch', '1.000', '1.000.000', '10^9', 'Naive Matrixmultiplikation'],
      ['O(2^n)', 'exponentiell', '1.024', '10^30', 'unbrauchbar', 'Naives Fibonacci, alle Teilmengen'],
      ['O(n!)', 'faktoriell', '3.628.800', 'unbrauchbar', 'unbrauchbar', 'Alle Permutationen (Traveling Salesman, Brute Force)'],
    ]],
    ['h', 'Regeln für die Berechnung'],
    ['steps', ['**Konstanten weglassen:** O(5n) = O(n), O(100) = O(1). Wachstum, nicht Faktor.', '**Nur den größten Term behalten:** O(n² + 3n + 7) = O(n²), O(n + log n) = O(n).', '**Hintereinander ausgeführte Teile addieren:** erst O(n), dann O(n²) ergibt O(n + n²) = O(n²).', '**Verschachtelte Schleifen multiplizieren:** n mal n = O(n²).', '**Wird bei jedem Schritt halbiert**, ergibt das O(log n).', '**Teile und herrsche** mit Halbieren und linearer Arbeit pro Ebene: O(n log n).']],
    ['h', 'Code analysieren'],
    ['table', ['Code', 'Analyse', 'Komplexität'], [
      ['`x = a[5];`', 'Eine Anweisung, unabhängig von n', '**O(1)**'],
      ['`for (i = 0; i < n; i++) summe += a[i];`', 'Eine Schleife mit n Durchläufen', '**O(n)**'],
      ['`for (i...n) for (j...n) tue();`', 'n mal n Durchläufe', '**O(n²)**'],
      ['`for (i...n) for (j = i; j < n; j++)`', 'n + (n-1) + ... + 1 = n(n+1)/2, also O(n²)', '**O(n²)**'],
      ['`for (i = 1; i < n; i *= 2)`', 'i verdoppelt sich: etwa log2(n) Durchläufe', '**O(log n)**'],
      ['`for (i...n) { for (j = 1; j < n; j *= 2) }`', 'n mal log n', '**O(n log n)**'],
      ['`for (i...n) tue(); for (j...n) tue();`', 'Zwei Schleifen hintereinander: n + n = 2n', '**O(n)**'],
      ['`fib(n-1) + fib(n-2)` (naiv)', 'Zwei Aufrufe je Ebene, n Ebenen', '**O(2^n)**'],
    ]],
  ],
});
