AP2.add('course-csharp', [
  ['h', 'Entwurfsprinzipien und Muster in C#'],
  ['table', ['Prinzip / Muster', 'Idee', 'C#-Umsetzung'], [['**SOLID**', 'Single Responsibility, Open/Closed, Liskov, Interface Segregation, Dependency Inversion', 'Kleine Klassen, Interfaces, Dependency Injection'], ['**Dependency Injection**', 'Abhängigkeiten von außen übergeben statt `new` in der Klasse', 'Konstruktor-Parameter `IRepo`, Container'], ['**Repository**', 'Datenzugriff hinter Interface kapseln', '`IKundenRepo` mit EF Core'], ['**Observer**', 'Benachrichtigung bei Änderung', '`event` / `IObservable<T>`'], ['**Strategy**', 'Algorithmus austauschbar', 'Interface oder `Func<>`'], ['**Singleton**', 'Genau eine Instanz', 'DI mit `AddSingleton` (statt statischer Singleton-Klasse)'], ['**Factory**', 'Objekterzeugung kapseln', 'Statische Methode, `Func<T>`']]],
  ['h', 'Häufige Fallen'],
  ['table', ['Falle', 'Erklärung', 'Lösung'], [
    ['Strings in Schleifen verketten', 'Jedes `+=` erzeugt einen neuen String', '`StringBuilder`'],
    ['`double` für Geld', 'Rundungsfehler (`0.1 + 0.2`)', '`decimal`'],
    ['`NullReferenceException`', 'Zugriff auf `null`', 'Nullable Reference Types, `?.`, Guard Clauses'],
    ['Sammlung beim `foreach` ändern', '`InvalidOperationException`', 'Kopie iterieren oder `RemoveAll`'],
    ['`==` bei Referenztypen', 'Vergleicht Verweise, außer `string` und `record`', '`Equals` überschreiben oder `record`'],
    ['Closure über Schleifenvariable', 'Lambda erfasst Variable, nicht Wert (`for`)', 'Lokale Kopie in der Schleife'],
    ['`async void`, `.Result`', 'Verlorene Fehler, Deadlocks', '`async Task`, `await`'],
    ['LINQ mehrfach ausführen', 'Deferred Execution', '`ToList()`'],
    ['Struct als große Daten', 'Kopierkosten', 'Kleine Structs, sonst `class`/`record`'],
  ]],
  ['list', ['**Namenskonventionen:** `PascalCase` für Typen, Methoden, Properties; `camelCase` für Parameter und lokale Variablen; `_camelCase` für private Felder; Interfaces beginnen mit `I`.', '**Eine Klasse pro Datei**, Namespace entspricht Ordnerstruktur.', 'Kommentare erklären das **Warum**; XML-Doku `/// <summary>` für öffentliche APIs.', 'Analyzer und `.editorconfig` erzwingen einheitlichen Stil.']],
  ['h', 'Aufgaben im Prüfungsstil'],
  ['qa', 'Erklären Sie den Unterschied zwischen Wert- und Referenztypen in C#.', '**Werttypen** (`int`, `struct`, `enum`) speichern den Wert selbst (Zuweisung **kopiert** den Wert). **Referenztypen** (`class`, `string`, Arrays) speichern einen **Verweis** auf ein Objekt im Heap (Zuweisung kopiert den Verweis, beide Variablen zeigen auf dasselbe Objekt, Änderungen sind in beiden sichtbar).', 5],
  ['qa', 'Schreiben Sie eine LINQ-Abfrage, die die Namen aller volljährigen Personen alphabetisch liefert.', 'var namen = personen.Where(p => p.Alter >= 18).OrderBy(p => p.Name).Select(p => p.Name).ToList();', 4],
  ['qa', 'Wozu dient das Schlüsselwort `using` bei Objekten?', 'Es stellt sicher, dass `Dispose()` am Ende des Blocks **immer** aufgerufen wird (auch bei Exceptions), um **Ressourcen** wie Dateien oder Datenbankverbindungen freizugeben. Der Garbage Collector kümmert sich nur um Speicher.', 4],
  ['qa', 'Was ist der Unterschied zwischen `abstract class` und `interface`?', '**Interface:** reiner Vertrag (Member ohne Zustand, seit C# 8 auch Standardimplementierung), eine Klasse kann **mehrere** implementieren. **Abstrakte Klasse:** kann **Zustand (Felder) und gemeinsame Implementierung** enthalten, aber nur **eine** Basisklasse pro Klasse; nicht instanziierbar. Faustregel: "kann etwas tun" ist ein Interface, "ist eine Art von" ist eine Basisklasse.', 5],
  ['qa', 'Wie funktioniert `async/await` und wann ist es sinnvoll?', '`await` wartet auf eine `Task`, **ohne den Thread zu blockieren**; der Rest der Methode läuft danach weiter. Sinnvoll bei **I/O-Operationen** (HTTP, Datei, Datenbank), damit UI und Server **reaktionsfähig** bleiben. Für CPU-Arbeit eignet sich `Task.Run` oder `Parallel`.', 4],
  ['qa', 'Was bewirkt der Operator `??` und `?.`?', '`a ?? b`: Wert von `a`, falls nicht `null`, sonst `b`. `a?.Member`: Zugriff nur wenn `a` nicht `null` ist, sonst Ergebnis `null` (vermeidet `NullReferenceException`).', 3],
  ['quiz', [
    {q: 'Welcher Typ eignet sich für Geldbeträge?', o: ['decimal', 'double', 'float', 'int'], a: 0, e: 'decimal rechnet exakt dezimal.'},
    {q: 'Was ist ein Property?', o: ['Member mit get und set für kontrollierten Zugriff', 'Eine Konstante', 'Ein Delegate', 'Ein Namespace'], a: 0, e: 'Properties kapseln Felder.'},
    {q: 'Welche Eigenschaft hat ein record?', o: ['Wertgleichheit und Unveränderlichkeit', 'Immer Werttyp', 'Keine Properties', 'Nicht vererbbar und nicht vergleichbar'], a: 0, e: 'Records vergleichen Inhalte, nicht Verweise.'},
    {q: 'Was bedeutet Deferred Execution bei LINQ?', o: ['Abfrage läuft erst bei Auswertung (foreach, ToList)', 'Sie läuft nie', 'Sie läuft doppelt', 'Sie läuft im Hintergrund-Thread'], a: 0, e: 'Deshalb ToList() zum Materialisieren.'},
    {q: 'Was sollte man statt Thread.Sleep in async-Code nutzen?', o: ['await Task.Delay', 'Thread.Join', 'Task.Wait', 'Sleep(0)'], a: 0, e: 'Task.Delay blockiert den Thread nicht.'},
    {q: 'Wie viele Basisklassen kann eine C#-Klasse haben?', o: ['Eine', 'Zwei', 'Beliebig viele', 'Keine'], a: 0, e: 'Dafür beliebig viele Interfaces.'},
    {q: 'Welches Schlüsselwort macht eine Methode überschreibbar?', o: ['virtual', 'sealed', 'static', 'readonly'], a: 0, e: 'In der Ableitung mit override.'},
    {q: 'Wofür steht CLR?', o: ['Common Language Runtime', 'Compiled Language Resource', 'Core Library Reference', 'Class Loader Registry'], a: 0, e: 'Sie führt IL-Code aus und verwaltet den Speicher.'},
  ]],
]);
