AP2.add('course-css', [
  ['h', 'Typische Fehler und Lösungen'],
  ['table', ['Problem', 'Ursache', 'Lösung'], [
    ['Element zu breit, Scrollbalken', 'Padding und Border kommen zur Breite hinzu', '`box-sizing: border-box`'],
    ['`margin: auto` zentriert nicht', 'Element ist `inline` oder hat keine Breite', '`display: block` und feste/`max-width`, oder Flex/Grid'],
    ['`z-index` wirkt nicht', 'Element nicht positioniert / anderer Stapelkontext', '`position: relative` setzen; Stapelkontexte prüfen'],
    ['Regel wirkt nicht', 'Spezifität zu niedrig, Tippfehler, späte Regel überschreibt', 'DevTools: durchgestrichene Regel suchen'],
    ['Höhe 100 % funktioniert nicht', 'Elternelement hat keine Höhe', 'Höhe der Eltern setzen, oder `min-height: 100dvh`, Flex/Grid'],
    ['Flex-Kinder schrumpfen', '`flex-shrink: 1` Standard, lange Inhalte', '`min-width: 0`, `flex-shrink: 0` oder `flex-wrap`'],
    ['Bild verzerrt', 'Breite und Höhe unabhängig gesetzt', '`object-fit: cover/contain`, `height: auto`'],
  ]],
  ['h', 'Aufgaben im Prüfungsstil'],
  ['qa', 'Erklären Sie das Box-Modell und die Wirkung von `box-sizing: border-box`.', 'Jedes Element ist eine Box aus **Content, Padding, Border und Margin**. Standardmäßig (`content-box`) bezieht sich `width` nur auf den Content, Padding und Border vergrößern die Box. Mit **`border-box`** gelten Padding und Border **innerhalb** der angegebenen Breite, die Rechnung wird einfacher.', 5],
  ['qa', 'Was ist Spezifität? Welcher Selektor gewinnt: `#nav a` oder `.menu .link`?', 'Spezifität bestimmt, welche Regel bei Konflikten gilt: **ID > Klasse/Attribut/Pseudoklasse > Element**. `#nav a` = (1,0,1), `.menu .link` = (0,2,0): **`#nav a` gewinnt**, weil eine ID mehr zählt als beliebig viele Klassen.', 4],
  ['qa', 'Wie zentrieren Sie ein Element horizontal und vertikal?', 'Container mit `display: flex; justify-content: center; align-items: center;` und eine Höhe (zum Beispiel `min-height: 100vh`). Alternativ `display: grid; place-items: center;`.', 3],
  ['qa', 'Wann Flexbox, wann Grid?', '**Flexbox** für **eindimensionale** Anordnung (Navigationsleiste, Button-Reihe). **Grid** für **zweidimensionale** Layouts (ganze Seite, Galerie). Beide lassen sich kombinieren.', 3],
  ['qa', 'Was bedeutet "Mobile First" und wie setzt man es um?', 'Man schreibt die Basisregeln für **kleine Bildschirme** und ergänzt für größere mit `@media (min-width: ...)`. Das ergibt weniger Code, bessere mobile Performance und zwingt zur Konzentration auf das Wesentliche.', 4],
  ['qa', 'Nennen Sie den Unterschied zwischen `display: none` und `visibility: hidden`.', '`display: none` entfernt das Element aus dem Layout (kein Platz, nicht für Screenreader). `visibility: hidden` blendet es nur aus, der **Platz bleibt** erhalten.', 3],
  ['qa', 'Schreiben Sie CSS für drei gleich breite Spalten, die auf dem Handy untereinander stehen.', ['.raster { display: grid; gap: 16px; grid-template-columns: 1fr; }', '@media (min-width: 768px) { .raster { grid-template-columns: repeat(3, 1fr); } }'], 4],
  ['quiz', [
    {q: 'Welche Reihenfolge hat das Box-Modell von innen nach außen?', o: ['Content, Padding, Border, Margin', 'Margin, Border, Padding, Content', 'Content, Margin, Padding, Border', 'Padding, Content, Border, Margin'], a: 0, e: 'Innen der Inhalt, außen der Außenabstand.'},
    {q: 'Welche Einheit bezieht sich auf die Schriftgröße des Wurzelelements?', o: ['rem', 'em', 'px', '%'], a: 0, e: 'em bezieht sich auf das aktuelle Element.'},
    {q: 'Was bewirkt justify-content in einem Flex-Container (row)?', o: ['Ausrichtung auf der Hauptachse (horizontal)', 'Ausrichtung auf der Querachse', 'Reihenfolge der Elemente', 'Abstände nach außen'], a: 0, e: 'align-items wirkt auf der Querachse.'},
    {q: 'Welcher Selektor hat die höchste Spezifität?', o: ['#id', '.klasse', 'element', '*'], a: 0, e: 'ID vor Klasse vor Element vor Universalselektor.'},
    {q: 'Was macht repeat(auto-fit, minmax(200px, 1fr))?', o: ['Erzeugt so viele Spalten wie passen, mindestens 200px', 'Erzeugt genau 200 Spalten', 'Fixiert Breite auf 200px', 'Löscht das Grid'], a: 0, e: 'Responsives Raster ohne Media Query.'},
    {q: 'Welche Eigenschaften animiert man performant?', o: ['transform und opacity', 'width und height', 'top und left', 'margin und padding'], a: 0, e: 'Sie vermeiden teure Layoutberechnungen.'},
    {q: 'Welche Position bezieht sich auf das Browserfenster?', o: ['fixed', 'relative', 'absolute', 'static'], a: 0, e: 'Fixed scrollt nicht mit.'},
    {q: 'Warum ist @media (min-width) typisch für Mobile First?', o: ['Basis gilt für klein, Regeln erweitern für größere Fenster', 'Es ist schneller zu tippen', 'Es ist veraltet', 'Es funktioniert nur am Handy'], a: 0, e: 'Aufsteigende Breakpoints bauen aufeinander auf.'},
  ]],
]);
