AP2.page('wiso-alv', {
  b: 'wiso', g: 'Sozialversicherung', t: 'Arbeitslosenversicherung',
  d: 'Die **Arbeitslosenversicherung (SGB III)** sichert Arbeitnehmer bei **Arbeitslosigkeit** ab. Träger ist die **Bundesagentur für Arbeit (BA)**. Beitrag: **2,6 %** (je 1,3 % AG und AN). Leistungen: **Arbeitslosengeld I (ALG I)** (60 % des pauschalierten Nettoentgelts, mit Kind 67 %), **Vermittlung und Beratung**, **Weiterbildungsförderung**, **Kurzarbeitergeld**, **Insolvenzgeld**. Wer nach dem ALG I (oder ohne Anspruch) bedürftig bleibt, erhält **Bürgergeld** (SGB II).',
  m: '**ALG I = 60 % (mit Kind 67 %) vom pauschalierten Netto.** **Anwartschaft: 12 Monate Beitragszeit in den letzten 30 Monaten.** Dauer: **6 bis 24 Monate** je nach Beitragszeit und Alter. **Sperrzeit 12 Wochen** bei Eigenkündigung/Aufhebungsvertrag ohne wichtigen Grund. **Frühzeitig melden: 3 Monate vor Ende, spätestens 3 Tage nach Kündigung.**',
  cheat: [
    ['Voraussetzungen ALG I', ['**Arbeitslos** (ohne Beschäftigung, Vermittlung möglich)', '**Arbeitslos gemeldet** bei der Agentur', '**Anwartschaftszeit:** mindestens **12 Monate** versicherungspflichtig in den **letzten 30 Monaten**', '**Verfügbar** für Vermittlung, Eigenbemühungen']],
    ['Höhe und Dauer', ['**60 %** des Leistungsentgelts (pauschaliertes Netto)', '**67 %** mit mindestens einem Kind', 'Dauer: **12 Monate Beitrag = 6 Monate**; 16 = 8; 20 = 10; **24 = 12 Monate**', 'Ab **50 Jahre** (30 Monate) 15 Monate, ab **55** (36 Monate) 18, ab **58** (48 Monate) 24']],
    ['Melden und Sperrzeit', ['**Arbeitssuchend melden:** spätestens **3 Monate vor Ende**, bei kürzerer Frist **innerhalb von 3 Tagen** nach Kenntnis', '**Arbeitslos melden:** am **ersten Tag** der Arbeitslosigkeit', '**Sperrzeit bis zu 12 Wochen** bei Eigenkündigung, Aufhebungsvertrag, Ablehnung zumutbarer Arbeit', 'Meldeversäumnis: Kürzung']],
    ['Weitere Leistungen', ['**Kurzarbeitergeld** (60/67 % bei Arbeitsausfall)', '**Insolvenzgeld** (3 Monate Lohn bei Insolvenz)', '**Bürgergeld** (SGB II) für Bedürftige', 'Förderung der **beruflichen Weiterbildung**, Gründungszuschuss']],
  ],
  blocks: [
    ['h', 'Aufgaben der Bundesagentur für Arbeit'],
    ['table', ['Aufgabe', 'Beschreibung'], [['**Arbeitsvermittlung und Beratung**', 'Stellen vermitteln, Berufsberatung für Schüler und Erwachsene, Ausbildungsvermittlung'], ['**Lohnersatzleistungen**', 'Arbeitslosengeld I, Kurzarbeitergeld, Insolvenzgeld'], ['**Arbeitsmarktförderung**', 'Weiterbildung, Eingliederungszuschüsse, Gründungsförderung, Förderung von Menschen mit Behinderung'], ['**Arbeitsmarktbeobachtung**', 'Statistik, Arbeitslosenquote, Berufsberatungsforschung']]],
    ['h', 'Arbeitslosengeld I (ALG I)'],
    ['steps', ['**Voraussetzungen prüfen:** arbeitslos, arbeitslos gemeldet, **Anwartschaftszeit** erfüllt (12 Monate versicherungspflichtig in den letzten 30 Monaten, sogenannte **Rahmenfrist**).', '**Höhe berechnen:** Aus dem **Bruttoentgelt** der letzten 12 Monate wird ein **pauschaliertes Nettoentgelt** (Leistungsentgelt) gebildet (Abzug von Sozialversicherung, Lohnsteuer, Soli pauschal). **60 %** davon (**67 %** bei **Kind**).', '**Dauer bestimmen:** Nach **Beitragszeit** und **Alter** (siehe Tabelle).', '**Pflichten:** Eigenbemühungen nachweisen, Vermittlungsvorschläge annehmen, Termine wahrnehmen, jede Änderung melden.']],
    ['table', ['Versicherungspflichtige Zeit in den letzten 5 Jahren', 'Lebensalter', 'Anspruchsdauer ALG I'], [['12 Monate', 'jedes', '**6 Monate**'], ['16 Monate', 'jedes', '8 Monate'], ['20 Monate', 'jedes', '10 Monate'], ['24 Monate', 'jedes', '**12 Monate**'], ['30 Monate', 'ab 50 Jahre', '15 Monate'], ['36 Monate', 'ab 55 Jahre', '18 Monate'], ['48 Monate', 'ab 58 Jahre', '**24 Monate**']]],
    ['ex', ['**Beispiel:** Ein 28-jähriger Angestellter ohne Kinder hatte 3.000 Euro Brutto, Leistungsentgelt (pauschal netto) ca. **2.000 Euro**. Er war **30 Monate** versicherungspflichtig beschäftigt. **ALG I** = 60 % von 2.000 = **1.200 Euro monatlich**. Dauer: Bei 24 oder mehr Monaten **12 Monate**. Bei Kind: 67 % = **1.340 Euro**.']],
    ['h', 'Sperrzeit und Meldepflichten'],
    ['kv', [
      ['Sperrzeit (§ 159 SGB III)', 'Bei **versicherungswidrigem Verhalten** ruht der Anspruch auf ALG I: **Sperrzeit von bis zu 12 Wochen** (und der Anspruch wird um mindestens ein Viertel gekürzt), zum Beispiel bei **Eigenkündigung**, **Aufhebungsvertrag** ohne wichtigen Grund, **verhaltensbedingter Kündigung**, Ablehnung **zumutbarer Arbeit**. **Wichtiger Grund** (zum Beispiel Mobbing, Umzug zum Partner) vermeidet die Sperrzeit.'],
      ['Arbeitssuchendmeldung (§ 38)', 'Wer weiß, dass sein Arbeitsverhältnis endet, muss sich **spätestens 3 Monate vorher** bei der Agentur **arbeitssuchend melden** (bei weniger als 3 Monaten Frist: **innerhalb von 3 Tagen** nach Kenntnis). Sonst droht eine **Sperrzeit (1 Woche)**.'],
      ['Arbeitslosmeldung', 'Persönlich oder online **am ersten Tag** der Arbeitslosigkeit, damit der Anspruch beginnt.'],
      ['Zumutbare Arbeit (§ 140)', 'Grundsätzlich ist **jede legale Arbeit** zumutbar. Wegen der **Entlohnung** gilt: In den **ersten 3 Monaten** der Arbeitslosigkeit ist eine Arbeit unzumutbar, wenn das Entgelt **mehr als 20 %** unter dem früheren liegt, in den **folgenden 3 Monaten** mehr als **30 %**; **ab dem 7. Monat** genügt ein Nettoentgelt, das nicht niedriger ist als das ALG.'],
    ]],
  ],
});
