AP2.page('wiso-demografie', {
  b: 'wiso', g: 'Staat und Gesellschaft', t: 'Demografischer Wandel, Fachkräftemangel und Gleichberechtigung',
  d: 'Der **demografische Wandel** bezeichnet die Veränderung von **Größe und Altersstruktur** der Bevölkerung. In Deutschland ist die **Geburtenrate** seit Jahrzehnten niedrig (rund 1,4 Kinder je Frau, für eine stabile Bevölkerung wären 2,1 nötig), während die **Lebenserwartung** steigt und die geburtenstarken Jahrgänge (**Babyboomer**, 1955 bis 1969) in Rente gehen. Folgen: weniger Erwerbstätige, mehr Rentner und Pflegebedürftige, **Fachkräftemangel** und Druck auf die **Sozialversicherungen** (Umlageverfahren, Generationenvertrag). Eine wichtige Antwort ist die bessere Nutzung aller Potenziale, besonders die **Gleichberechtigung** von Frauen im Erwerbsleben.',
  m: '**Ursachen: wenige Geburten + lange Lebenserwartung (+ Migration als Ausgleich).** **Folgen: Rente, Pflege, Fachkräfte, Wahlen (ältere Mehrheit).** **Maßnahmen: Familienpolitik, Zuwanderung von Fachkräften, längeres Arbeiten, Frauen- und Älterenerwerbstätigkeit, Automatisierung/KI.** **Gender Pay Gap: unbereinigt ca. 16 bis 18 %, bereinigt ca. 6 %.**',
  cheat: [
    ['Ursachen', ['niedrige Geburtenrate (ca. 1,4)', 'steigende Lebenserwartung', 'Babyboomer gehen in Rente', 'Abwanderung aus ländlichen Regionen']],
    ['Folgen', ['Rentenversicherung: weniger Beitragszahler', 'Pflege- und Krankenversicherung teurer', 'Fachkräftemangel, Innovationsstau', 'politisches Gewicht der Älteren']],
    ['Maßnahmen', ['Kindergeld, Elterngeld, Kita-Ausbau', 'Fachkräfteeinwanderungsgesetz', 'Rente mit 67, flexible Übergänge', 'Frauen in Vollzeit/MINT, Automatisierung']],
    ['Gleichberechtigung', ['Art. 3 Abs. 2 GG', 'Gender Pay Gap, Entgelttransparenzgesetz', 'Vereinbarkeit Familie und Beruf', 'Girls\' Day, Vorbilder in MINT']],
  ],
  blocks: [
    ['h', 'Was passiert in der Bevölkerung?'],
    ['p', 'Früher hatte die Altersstruktur die Form einer **Pyramide** (viele Junge, wenige Alte). Heute ähnelt sie einer **Urne** oder einem **Pilz**: Die mittleren und älteren Jahrgänge sind stark besetzt, die jungen schwach. Der **Altenquotient** (Menschen ab 65 Jahren je 100 Personen im Alter von 20 bis 64) lag 2021 bei rund 37 und steigt laut Statistischem Bundesamt bis Mitte der 2030er-Jahre auf etwa 50.'],
    ['ex', ['Aussagen aus dem Schaubild der Prüfung (Gemeinschaftskunde Winter 2022/23, Bundeswahlleiter/BiB):', 'Der Anteil der Wahlberechtigten **ab 70 Jahren** hat sich seit 1972 etwa **verdoppelt**, auch der Anteil der 50- bis 69-Jährigen ist gestiegen, der Anteil der unter 50-Jährigen gesunken.', 'Bei der Bundestagswahl 2021 waren rund **58 % der Wahlberechtigten 50 Jahre oder älter**.', 'Die **Wahlbeteiligung** war in allen Jahren zwischen 50 und 70 Jahren am höchsten und **unter 30 Jahren am niedrigsten**.']],
    ['h', 'Warum ist der demografische Wandel ein Problem? (Winter 2022/23, 4 Punkte)'],
    ['table', ['Bereich', 'Problem', 'Folge'], [
      ['**Rentenversicherung**', 'Im **Umlageverfahren** zahlen die heutigen Beschäftigten die Renten der heutigen Rentner (**Generationenvertrag**). Immer weniger Beitragszahler finanzieren immer mehr Rentner immer länger.', 'Höhere Beiträge, höheres Renteneintrittsalter oder niedrigeres Rentenniveau, mehr Steuerzuschüsse'],
      ['**Arbeitsmarkt**', 'Mehr Menschen gehen in Rente, als junge nachkommen.', '**Fachkräftemangel**, unbesetzte Ausbildungsplätze, steigende Arbeitskosten, Aufträge können nicht erledigt werden, Innovationsstau'],
      ['**Pflege und Gesundheit**', 'Mehr alte und pflegebedürftige Menschen, gleichzeitig weniger Pflegekräfte.', 'Steigende Beiträge zur Kranken- und Pflegeversicherung, Pflegenotstand'],
      ['**Politik**', 'Über die Hälfte der Wahlberechtigten ist über 50 und sie wählen häufiger.', 'Interessen Jüngerer werden weniger vertreten (Generationengerechtigkeit)'],
      ['**Regionen**', 'Junge ziehen in Städte, ländliche Räume altern.', 'Schulen, Ärzte, Geschäfte schließen; Infrastruktur unterausgelastet'],
    ]],
    ['h', 'Was kann man tun? (Winter 2022/23, 6 Punkte)'],
    ['list', [
      '**Familienpolitik:** Kindergeld, Elterngeld, mehr und günstigere **Kita-Plätze**, Ganztagsschulen, längere Elternzeit, damit sich Paare leichter für Kinder entscheiden.',
      '**Vereinbarkeit von Familie und Beruf:** Teilzeit, **Homeoffice**, Gleitzeit, Betriebskitas, Rückkehrrecht in Vollzeit.',
      '**Gezielte Zuwanderung** von Fachkräften (Fachkräfteeinwanderungsgesetz, Anerkennung ausländischer Abschlüsse, Sprachkurse, Blaue Karte EU).',
      '**Längere Lebensarbeitszeit**, flexible Übergänge in die Rente, Weiterbeschäftigung Älterer (Aktivrente).',
      '**Höhere Erwerbsbeteiligung von Frauen** (Abbau von Hürden, Ehegattensplitting reformieren, MINT-Förderung).',
      '**Automatisierung und KI**, um mit weniger Arbeitskräften gleich viel zu leisten; **Aus- und Weiterbildung** zur Höherqualifizierung.',
      '**Kapitalgedeckte Altersvorsorge** stärken (betriebliche und private Vorsorge, Generationenkapital), Rentensystem breiter finanzieren.',
    ]],
    ['h', 'Gleichberechtigung in der Arbeitswelt (Sommer 2023)'],
    ['p', '**Art. 3 Abs. 2 GG:** "Männer und Frauen sind gleichberechtigt. Der Staat fördert die tatsächliche Durchsetzung der Gleichberechtigung." Das **Allgemeine Gleichbehandlungsgesetz (AGG)** verbietet Benachteiligung wegen Geschlecht, Herkunft, Religion, Behinderung, Alter oder sexueller Identität, zum Beispiel bei Stellenanzeigen ("m/w/d"), Einstellung und Bezahlung.'],
    ['kv', [
      ['Gender Pay Gap (unbereinigt)', 'Unterschied der durchschnittlichen Bruttostundenlöhne von Frauen und Männern, in Deutschland zuletzt etwa **16 %** (2024). Ursachen: Frauen arbeiten häufiger in schlechter bezahlten Branchen (Pflege, Erziehung), öfter in **Teilzeit** und seltener in Führungspositionen.'],
      ['Gender Pay Gap (bereinigt)', 'Unterschied bei **vergleichbarer** Tätigkeit, Qualifikation und Erwerbsbiografie, etwa **6 %**. Er gilt als Obergrenze für direkte Diskriminierung.'],
      ['Entgelttransparenzgesetz', 'Beschäftigte in Betrieben ab 200 Mitarbeitern können erfahren, was Kollegen des anderen Geschlechts in vergleichbarer Tätigkeit verdienen. Die **EU-Entgelttransparenzrichtlinie** war bis Juni 2026 in nationales Recht umzusetzen.'],
      ['Vereinbarkeit', 'Frauen leisten deutlich mehr unbezahlte **Care-Arbeit** (Haushalt, Kinder, Pflege). Ohne Entlastung führt Erwerbsarbeit zur Doppelbelastung.'],
      ['Frauen in MINT-Berufen', 'In IT-Berufen liegt der Frauenanteil bei unter 20 %. Gründe: Rollenbilder, fehlende **Vorbilder**, Vorurteile im Betrieb. Maßnahmen: Girls\' Day, Mentoring, Social-Media-Kampagnen, Azubis beider Geschlechter auf Messen, flexible Arbeitszeiten, Kultur der Gleichbehandlung.'],
    ]],
    ['h', 'Aufgaben im Prüfungsstil (ganze Sätze!)'],
    ['qa', 'Begründen Sie anhand von zwei Beispielen, warum der demografische Wandel für Deutschland ein Problem darstellt.', ['Durch die niedrige Geburtenrate und die steigende Lebenserwartung gerät die **Rentenversicherung** unter Druck: Im Umlageverfahren müssen immer weniger Beitragszahler die Renten von immer mehr Rentnern finanzieren. Deshalb müssen entweder die Beiträge steigen, das Rentenniveau sinken oder länger gearbeitet werden.', 'Außerdem entsteht ein **Fachkräftemangel**, weil mehr Beschäftigte in Rente gehen, als junge Menschen nachkommen. Unternehmen finden kein Personal, Aufträge bleiben liegen, und die Wirtschaft wächst langsamer.'], 4],
    ['qa', 'Entwickeln Sie zwei Vorschläge, wie die Folgen des demografischen Wandels abgeschwächt werden können.', ['Der Staat sollte die **Familienpolitik** ausbauen, zum Beispiel durch mehr kostenlose Kita-Plätze und Ganztagsbetreuung. So können beide Eltern arbeiten, und die Entscheidung für Kinder fällt leichter.', 'Zudem sollte die **Zuwanderung von Fachkräften** erleichtert werden, etwa durch schnellere Anerkennung ausländischer Berufsabschlüsse und kostenlose Sprachkurse. Dadurch werden offene Stellen besetzt und die Sozialversicherungen erhalten zusätzliche Beitragszahler.'], 6],
    ['qa', 'Verfassen Sie zwei konkrete Vorschläge, wie Ihr Ausbildungsbetrieb den Beruf Fachinformatiker/-in für junge Frauen attraktiver machen kann.', ['Der Betrieb könnte auf **Social Media** mit Videos werben, in denen **Auszubildende beider Geschlechter** ihren Alltag zeigen. Junge Frauen sehen so Vorbilder und erfahren, dass der Beruf auch für sie passt.', 'Außerdem sollte der Betrieb zeigen, dass **Gleichbehandlung gelebt** wird: gleiche Bezahlung, flexible Arbeitszeiten und Homeoffice zur Vereinbarkeit von Familie und Beruf sowie ein klares Vorgehen gegen abwertende Sprüche.'], 6],
    ['quiz', [
      {q: 'Welche Kinderzahl je Frau wäre für eine stabile Bevölkerung ohne Zuwanderung nötig?', o: ['etwa 2,1', 'etwa 1,4', 'etwa 3,0', 'etwa 1,0'], a: 0, e: 'Aktuell rund 1,4.'},
      {q: 'Wie heißt das Finanzierungsprinzip der gesetzlichen Rente?', o: ['Umlageverfahren', 'Kapitaldeckungsverfahren', 'Äquivalenzprinzip', 'Subsidiaritätsprinzip'], a: 0, e: 'Generationenvertrag.'},
      {q: 'Was misst der unbereinigte Gender Pay Gap?', o: ['Den Unterschied der durchschnittlichen Bruttostundenlöhne von Frauen und Männern', 'Den Unterschied bei gleicher Tätigkeit und Qualifikation', 'Die Zahl der Frauen in Führung', 'Den Unterschied der Renten'], a: 0, e: 'Bereinigt = bei vergleichbaren Merkmalen.'},
      {q: 'Welches Gesetz verbietet Benachteiligung wegen des Geschlechts im Arbeitsleben?', o: ['AGG', 'BBiG', 'JArbSchG', 'BetrVG'], a: 0, e: 'Allgemeines Gleichbehandlungsgesetz.'},
    ]],
    ['see', ['wiso-rv', 'wiso-wahlen', 'wiso-ki', 'wiso-methoden']],
  ],
});
