AP2.page('wiso-eu', {
  b: 'wiso', g: 'Staat und Gesellschaft', t: 'Europäische Union: Organe und Gesetzgebung',
  d: 'Die **Europäische Union** ist ein Staatenverbund von **27 Mitgliedstaaten** mit gemeinsamem **Binnenmarkt** (freier Verkehr von Waren, Dienstleistungen, Personen und Kapital) und in 21 Staaten (seit 2026 mit Bulgarien) dem **Euro**. Gesetze entstehen im **ordentlichen Gesetzgebungsverfahren**: Nur die **Europäische Kommission** darf Vorschläge machen, das **Europäische Parlament** (vertritt die Bürger) und der **Rat der EU** (Ministerrat, vertritt die Regierungen) entscheiden **gemeinsam**. EU-Recht gilt als **Verordnung** unmittelbar in allen Staaten oder muss als **Richtlinie** in nationales Recht umgesetzt werden. Beispiele aus der IT: **DSGVO** (Verordnung), **KI-Verordnung (AI Act)**, **NIS-2-Richtlinie**.',
  m: '**Kommission schlägt vor, Parlament und Rat beschließen, EuGH kontrolliert.** **Europäischer Rat (Staats- und Regierungschefs) = Richtung, macht keine Gesetze. Rat der EU (Fachminister) = Gesetzgeber zusammen mit dem Parlament.** **Verordnung gilt sofort überall, Richtlinie muss umgesetzt werden.** Parlament: alle **5 Jahre** direkt gewählt, ab 16 Jahren in Deutschland.',
  cheat: [
    ['Organe', ['**Kommission**: "Regierung", Vorschlagsrecht, Hüterin der Verträge', '**Parlament**: 720 Abgeordnete, gewählt', '**Rat der EU**: Fachminister der Staaten', '**Europäischer Rat**: Staats-/Regierungschefs; **EuGH**: Gericht']],
    ['Rechtsakte', ['**Verordnung**: gilt unmittelbar (DSGVO)', '**Richtlinie**: Ziel verbindlich, Umsetzung national', '**Beschluss**: für einzelne Adressaten', 'Empfehlung/Stellungnahme: unverbindlich']],
    ['Gesetzgebung', ['Kommission legt Vorschlag vor', '1. Lesung Parlament, dann Rat', 'Einigung -> angenommen', 'sonst 2. Lesung, Vermittlungsausschuss, 3. Lesung']],
    ['IT-Bezug', ['DSGVO (2018)', 'KI-Verordnung (2024)', 'NIS-2 (Cybersicherheit)', 'Digital Services Act, Cyber Resilience Act']],
  ],
  blocks: [
    ['h', 'Die wichtigsten Organe (Gemeinschaftskunde Sommer 2024, 6 Punkte)'],
    ['table', ['Organ', 'Zusammensetzung', 'Aufgaben (neben der Gesetzgebung)'], [
      ['**Europäische Kommission** (Brüssel)', 'Je ein Kommissar/eine Kommissarin pro Mitgliedstaat (27), Präsidentin bzw. Präsident vom Europäischen Rat vorgeschlagen und vom Parlament gewählt; Zuständigkeiten (Ressorts) werden ausgehandelt', 'Einziges **Initiativrecht** für Gesetze, **Hüterin der Verträge** (überwacht die Einhaltung des EU-Rechts, kann Vertragsverletzungsverfahren einleiten), führt den Haushalt aus, verhandelt Handelsabkommen'],
      ['**Europäisches Parlament** (Straßburg/Brüssel)', '720 Abgeordnete, alle **5 Jahre direkt** von den EU-Bürgern gewählt (Deutschland: 96 Sitze)', 'Gesetzgeber zusammen mit dem Rat, beschließt mit dem Rat den **Haushalt** und kontrolliert ihn, wählt die Kommissionspräsidentin, kann die Kommission per Misstrauensvotum absetzen'],
      ['**Rat der EU** (Ministerrat)', 'Je ein **Fachminister** pro Mitgliedstaat, je nach Thema (Agrar, Wirtschaft, Inneres ...)', 'Gesetzgeber zusammen mit dem Parlament, vertritt die Interessen der **Regierungen**, sucht Kompromisse zwischen den Staaten, Entscheidung oft mit **qualifizierter Mehrheit** (55 % der Staaten, 65 % der Bevölkerung)'],
      ['**Europäischer Rat**', 'Staats- und Regierungschefs plus Präsidenten von Europäischem Rat und Kommission', 'Legt die **allgemeinen politischen Ziele** fest, macht **keine** Gesetze'],
      ['**Gerichtshof der EU (EuGH)** (Luxemburg)', 'Ein Richter je Mitgliedstaat', 'Sichert die einheitliche Auslegung des EU-Rechts, entscheidet bei Streit (zum Beispiel Urteile zu Datenschutz, "Safe Harbor", "Privacy Shield")'],
    ]],
    ['warn', 'Verwechslungsgefahr: **Rat der EU** (Fachminister, Gesetzgeber), **Europäischer Rat** (Chefs, Richtung) und **Europarat** (keine EU-Institution, 46 Staaten, Europäische Menschenrechtskonvention).'],
    ['h', 'Das ordentliche Gesetzgebungsverfahren'],
    ['diagram', AP2.dg.flow(['Kommission: Gesetzesvorschlag', 'Parlament: 1. Lesung', 'Rat: Standpunkt', 'Einigung? -> Gesetz angenommen', 'sonst: 2. Lesung, Vermittlungsausschuss, 3. Lesung'], {w: 780, h: 120, styles: ['accent', 'soft', 'soft', 'ok', 'plain'], cap: 'Parlament und Rat sind gleichberechtigt. Ohne Einigung scheitert das Gesetz.'})],
    ['steps', [
      'Die **Kommission** erarbeitet einen Gesetzesvorschlag (oft nach Anhörungen) und legt ihn Parlament und Rat vor.',
      '**Erste Lesung:** Das Parlament legt seinen Standpunkt fest (Änderungen). Billigt der Rat diesen Standpunkt, ist das Gesetz angenommen.',
      'Sonst legt der Rat einen eigenen Standpunkt fest; **zweite Lesung** im Parlament. Stimmt das Parlament zu, ist das Gesetz angenommen, lehnt es mit absoluter Mehrheit ab, ist es gescheitert.',
      'Bei Meinungsverschiedenheiten tritt der **Vermittlungsausschuss** (gleich viele Vertreter von Parlament und Rat) zusammen und erarbeitet einen Kompromiss.',
      '**Dritte Lesung:** Parlament und Rat stimmen über den Kompromiss ab. Lehnt eine Seite ab, ist das Gesetz **gescheitert**.',
      'In der Praxis einigen sich Parlament, Rat und Kommission oft vorher informell im **Trilog**.',
    ]],
    ['h', 'Verordnung oder Richtlinie?'],
    ['table', ['', 'Verordnung', 'Richtlinie'], [
      ['Geltung', '**Unmittelbar** in allen Mitgliedstaaten, wie ein nationales Gesetz', 'Gibt ein **Ziel** vor; jeder Staat muss sie innerhalb einer Frist in **nationales Recht umsetzen**'],
      ['Spielraum', 'Keiner (nur Öffnungsklauseln)', 'Staaten wählen Form und Mittel'],
      ['Beispiele', '**DSGVO**, **KI-Verordnung**, Roaming-Verordnung', '**NIS-2** (umgesetzt durch das NIS-2-Umsetzungsgesetz), Barrierefreiheitsrichtlinie (in Deutschland: BFSG), Entgelttransparenzrichtlinie'],
    ]],
    ['h', 'Beispiel: Die KI-Verordnung (AI Act)'],
    ['p', 'Die KI-Verordnung (in Kraft seit August 2024, gestaffelte Geltung bis 2027) ist das erste umfassende KI-Gesetz der Welt. Sie folgt einem **risikobasierten Ansatz**: Je größer das Risiko für Grundrechte, Sicherheit und Gesundheit, desto strenger die Regeln (Details siehe Seite "Künstliche Intelligenz").'],
    ['h', 'Aufgaben im Prüfungsstil (ganze Sätze!)'],
    ['qa', 'Erklären Sie mithilfe des Gesetzgebungsverfahrens zwei mögliche Wege, wie ein EU-Gesetz zustande kommt oder scheitert.', ['Gesetzesvorschläge kann nur die **Europäische Kommission** einbringen. Danach beraten das **Europäische Parlament** und der **Rat der EU**. Sind sich beide einig, zum Beispiel weil der Rat den Standpunkt des Parlaments aus der ersten Lesung übernimmt, ist das Gesetz angenommen.', 'Gibt es Meinungsverschiedenheiten zwischen Parlament und Rat, tritt der **Vermittlungsausschuss** zusammen und erarbeitet einen Kompromiss. Lehnen Parlament oder Rat diesen Kompromiss in der dritten Lesung ab, ist das Gesetz gescheitert.'], 6],
    ['qa', 'Beschreiben Sie Zusammensetzung und eine weitere Aufgabe von EU-Kommission und EU-Parlament.', ['Die **EU-Kommission** besteht aus je einem Kommissar pro Mitgliedsland. Neben dem Vorschlagsrecht für Gesetze wacht sie als "Hüterin der Verträge" darüber, dass die Mitgliedstaaten das EU-Recht einhalten und Beschlüsse in nationales Recht umsetzen.', 'Das **EU-Parlament** besteht aus Abgeordneten, die von den EU-Bürgern alle fünf Jahre direkt gewählt werden. Neben der Gesetzgebung kontrolliert es den EU-Haushalt und die Kommission.'], 6],
    ['quiz', [
      {q: 'Wer hat in der EU das Recht, Gesetze vorzuschlagen?', o: ['Die Europäische Kommission', 'Das Europäische Parlament', 'Der Europäische Rat', 'Der EuGH'], a: 0, e: 'Initiativmonopol der Kommission.'},
      {q: 'Was gilt unmittelbar in allen Mitgliedstaaten?', o: ['Eine Verordnung', 'Eine Richtlinie', 'Eine Empfehlung', 'Eine Stellungnahme'], a: 0, e: 'Beispiel DSGVO.'},
      {q: 'Wer sitzt im Rat der EU?', o: ['Fachminister der Mitgliedstaaten', 'Staats- und Regierungschefs', 'Gewählte Abgeordnete', 'Richter'], a: 0, e: 'Die Chefs bilden den Europäischen Rat.'},
      {q: 'Wie oft wird das Europäische Parlament gewählt?', o: ['Alle 5 Jahre', 'Alle 4 Jahre', 'Alle 6 Jahre', 'Alle 2 Jahre'], a: 0, e: 'Zuletzt 2024.'},
      {q: 'Wer kontrolliert, dass Mitgliedstaaten EU-Recht einhalten, und kann sie verklagen?', o: ['Die Kommission', 'Der Europarat', 'Die EZB', 'Der Europäische Rat'], a: 0, e: 'Klage vor dem EuGH.'},
    ]],
    ['see', ['wiso-ki', 'ps-dsgvo', 'wiso-wahlen', 'wiso-staat']],
  ],
});
