AP2.add('wiso-gewerkschaft', [
  ['h', 'Wichtige Begriffe rund um den Arbeitskampf'],
  ['kv', [
    ['Friedenspflicht', 'Während der **Laufzeit** eines Tarifvertrags dürfen die Parteien **keinen Arbeitskampf** über die geregelten Gegenstände führen. Nach Ablauf (oft zuzüglich einer Frist) endet sie.'],
    ['Warnstreik', 'Kurzer, **befristeter** Streik (wenige Stunden bis Tage) **während der laufenden Verhandlungen** nach Ablauf der Friedenspflicht. Ohne Urabstimmung zulässig. Ziel: **Verhandlungsdruck**.'],
    ['Urabstimmung', 'Die **Gewerkschaftsmitglieder** stimmen **geheim** über einen unbefristeten Streik ab. Meist müssen **mindestens 75 Prozent** zustimmen.'],
    ['Streikposten', 'Beschäftigte, die friedlich andere zur Arbeitsniederlegung aufrufen. Sie dürfen **niemanden gewaltsam** hindern.'],
    ['Notdienstarbeiten', 'Im Streik werden **lebenswichtige Bereiche** (Krankenhaus, Energie) durch Vereinbarung weiter besetzt.'],
    ['Schlichtung', 'Ein **neutraler Schlichter** vermittelt zwischen den Tarifparteien und macht einen **Einigungsvorschlag**. Teilweise ist Schlichtung vertraglich vorgeschrieben (zum Beispiel Metall: vor Streik). Der Vorschlag ist nicht bindend, außer die Parteien vereinbaren das.'],
    ['Sympathiestreik / Solidaritätsstreik', 'Streik zur **Unterstützung** eines anderen Arbeitskampfs. Nur **unter engen Voraussetzungen** zulässig.'],
    ['Wilder Streik', 'Streik **ohne gewerkschaftlichen Aufruf**: **rechtswidrig**, Arbeitgeber darf **abmahnen oder kündigen** und Schadensersatz verlangen.'],
  ]],
  ['table', ['Situation', 'Beurteilung'], [
    ['Die Belegschaft legt spontan die Arbeit nieder, ohne Gewerkschaft, weil das Wetter schlecht ist.', '**Rechtswidrig** (wilder Streik, kein Tarifziel).'],
    ['Die Gewerkschaft ruft mitten in der Laufzeit des Tarifvertrags zum Streik für mehr Lohn auf.', '**Rechtswidrig**: **Friedenspflicht**.'],
    ['Streik gegen ein Gesetz der Bundesregierung (zum Beispiel Rentenreform).', '**Politischer Streik** ist in Deutschland **rechtswidrig** (Demonstrationen sind erlaubt).'],
    ['Warnstreik von 2 Stunden nach Ablauf der Friedenspflicht, die Verhandlungen laufen.', '**Zulässig.**'],
    ['Ein Streikender erhält während des Streiks sein Gehalt.', '**Nein**, das Arbeitsverhältnis ruht. Gewerkschaftsmitglieder erhalten **Streikgeld** (nach Satzung).'],
  ]],
  ['h', 'Mitgliedschaft: Vor- und Nachteile'],
  ['procon', 'Gewerkschaftsmitglied werden', ['**Tarifbindung:** direkter Anspruch auf Tarifleistungen (Mitglieder beider Seiten)', '**Rechtsschutz** und Rechtsberatung (Arbeitsrecht, Sozialrecht)', '**Streikgeld** im Arbeitskampf', 'Stärkere **kollektive Verhandlungsmacht** und Einfluss auf Politik'], ['**Mitgliedsbeitrag** (etwa 1 % des Bruttos, bei Azubis oft ermäßigt)', 'Gebundenheit an **Gewerkschaftsbeschlüsse** (Streikteilnahme)', 'Nicht alle Tarifleistungen **nur** für Mitglieder (viele Betriebe wenden Tarif für alle an)']],
  ['h', 'Sozialpartnerschaft und Tarifflucht'],
  ['p', 'Die Zusammenarbeit von Gewerkschaften und Arbeitgeberverbänden, einschließlich **Mitbestimmung** (Betriebsrat, Aufsichtsrat), prägt die deutsche **soziale Marktwirtschaft**. In den letzten Jahrzehnten sank die **Tarifbindung**: Weniger Betriebe sind Mitglied im Arbeitgeberverband oder wenden Tarifverträge an. Politische Antworten sind **Allgemeinverbindlicherklärungen** und der gesetzliche **Mindestlohn**.'],
  ['h', 'Aufgaben im Prüfungsstil'],
  ['qa', 'Nennen Sie vier Voraussetzungen für einen rechtmäßigen Streik.', ['- Der Streik wird von einer **Gewerkschaft** getragen.', '- Er verfolgt ein **tariflich regelbares Ziel** (kein politischer Streik).', '- Die **Friedenspflicht** ist abgelaufen.', '- Er ist **verhältnismäßig** und das **letzte Mittel** nach gescheiterten Verhandlungen (in der Regel nach Urabstimmung).'], 4],
  ['qa', 'Was ist der Unterschied zwischen Warnstreik und Erzwingungsstreik?', 'Ein **Warnstreik** ist **kurz und befristet**, findet **während der Verhandlungen** statt und soll Druck aufbauen. Ein **Erzwingungsstreik** wird nach **gescheiterten Verhandlungen** und **Urabstimmung** **unbefristet** geführt, bis eine Einigung erreicht ist.', 4],
  ['qa', 'Was passiert mit dem Arbeitsvertrag und dem Lohn während eines rechtmäßigen Streiks?', 'Das **Arbeitsverhältnis ruht**: Der Arbeitnehmer ist von der Arbeitspflicht befreit, der Arbeitgeber von der **Lohnzahlungspflicht**. Das Arbeitsverhältnis besteht weiter, Kündigung wegen der Streikteilnahme ist unzulässig. Gewerkschaftsmitglieder erhalten **Streikgeld**.', 4],
  ['qa', 'Erläutern Sie den Begriff Aussperrung.', 'Die **Aussperrung** ist das Arbeitskampfmittel der **Arbeitgeber**: Sie schließen Arbeitnehmer vorübergehend **von der Beschäftigung aus** und stellen die **Lohnzahlung** ein, meist als **Antwort auf einen Streik**. Sie muss **verhältnismäßig** sein und ist in der Regel **suspendierend** (Arbeitsverhältnis ruht).', 4],
  ['quiz', [
    {q: 'Welcher Verband vertritt die Arbeitgeber auf Bundesebene als Dachverband in Arbeitsmarktfragen?', o: ['BDA', 'DGB', 'IG Metall', 'IHK'], a: 0, e: 'DGB: Gewerkschaften. BDA: Arbeitgeberverbände.'},
    {q: 'Was ist ein wilder Streik?', o: ['Streik ohne Gewerkschaft, rechtswidrig', 'Streik mit Urabstimmung', 'Streik im Ausland', 'Ein kurzer Warnstreik'], a: 0, e: 'Wilde Streiks werden nicht von einer Gewerkschaft getragen.'},
    {q: 'Wann darf nicht gestreikt werden?', o: ['Während der Friedenspflicht (Laufzeit des Tarifvertrags)', 'Nach Ablauf des Tarifvertrags', 'Bei Lohnforderungen', 'Nach der Urabstimmung'], a: 0, e: 'Während der Laufzeit besteht Friedenspflicht.'},
    {q: 'Wer zahlt Streikgeld?', o: ['Die Gewerkschaft an ihre Mitglieder', 'Der Arbeitgeber', 'Der Staat', 'Die Krankenkasse'], a: 0, e: 'Streikgeld ist eine Leistung der Gewerkschaft nach ihrer Satzung.'},
    {q: 'Was bedeutet "suspendierende" Wirkung des Streiks?', o: ['Arbeitsverhältnis ruht, wird aber nicht beendet', 'Das Arbeitsverhältnis endet', 'Der Lohn wird verdoppelt', 'Der Betrieb wird geschlossen'], a: 0, e: 'Suspendieren = ruhen lassen.'},
  ]],
]);
