AP2.add('wiso-jarbschg', [
  ['h', 'Berufsschule und Prüfungen'],
  ['list', ['**Freistellung** für den Berufsschulunterricht (auch für Prüfungen). Die **Unterrichtszeit** (einschließlich Pausen) wird auf die Arbeitszeit **angerechnet**.', 'Vor einem **Unterricht, der vor 9 Uhr beginnt**, darf der Betrieb Jugendliche nicht beschäftigen.', 'An **einem Berufsschultag pro Woche** mit **mehr als 5 Unterrichtsstunden (je mindestens 45 Minuten)**: **keine Beschäftigung mehr** im Betrieb. Dieser Tag zählt dann als **8 Stunden** Arbeitszeit.', '**Berufsschulwoche** mit mindestens 25 Stunden an mindestens fünf Tagen (Blockunterricht): Keine weitere Beschäftigung im Betrieb in dieser Woche, Anrechnung mit 40 Stunden.', 'Ein **Berufsschultag** wird **nicht** auf den Urlaub angerechnet.', 'Am **Tag vor der schriftlichen Abschlussprüfung** ist der Jugendliche **freizustellen**.']],
  ['h', 'Urlaub'],
  ['table', ['Alter zu Beginn des Kalenderjahres', 'Mindesturlaub (Werktage, 6-Tage-Woche)', 'Entspricht (5-Tage-Woche)'], [['unter 16 Jahre', '**30 Werktage**', '25 Arbeitstage'], ['unter 17 Jahre', '**27 Werktage**', 'etwa 22,5 Arbeitstage'], ['unter 18 Jahre', '**25 Werktage**', 'etwa 21 Arbeitstage']]],
  ['p', 'Der Urlaub soll **in den Berufsschulferien** liegen. Wird Urlaub außerhalb der Ferien gewährt, ist für jeden Urlaubstag, an dem Berufsschule ist, **ein weiterer Urlaubstag** zu geben. Für **Volljährige** gilt das BUrlG: **24 Werktage** (20 Arbeitstage bei 5-Tage-Woche) als Mindestanspruch.'],
  ['h', 'Gesundheitsschutz'],
  ['kv', [
    ['Erstuntersuchung (§ 32)', 'Vor Beginn der Beschäftigung muss der Jugendliche **ärztlich untersucht** worden sein (Bescheinigung, nicht älter als 14 Monate). Ohne Bescheinigung **darf er nicht beschäftigt werden**.'],
    ['Nachuntersuchung (§ 33)', '**Ein Jahr nach Beschäftigungsbeginn** muss der Jugendliche erneut untersucht werden. Der Arbeitgeber **fordert dazu auf** (nach 9 Monaten) und beschäftigt ohne Nachweis **nach 14 Monaten** nicht mehr.'],
    ['Verbot gefährlicher Arbeiten (§ 22)', 'Keine Arbeiten, die die **Leistungsfähigkeit übersteigen**, bei denen Jugendliche **sittlichen Gefahren**, **Unfallgefahren** (die sie wegen mangelnder Erfahrung nicht erkennen), **extremer Hitze/Kälte/Nässe**, **gesundheitsschädlichen Stoffen** ausgesetzt sind. Ausnahme für Ausbildungszwecke unter Aufsicht ab 15 möglich.'],
    ['Akkordarbeit (§ 23)', '**Akkord- und Fließbandarbeit** mit **vorgegebenem Tempo** ist für Jugendliche verboten (Ausnahmen in der Ausbildung).'],
    ['Züchtigungsverbot (§ 31)', 'Körperliche **Züchtigung** ist verboten. Alkohol und Tabak dürfen **nicht gegeben** werden.'],
    ['Aushang und Verzeichnis', 'Auslegen des Gesetzes im Betrieb; **Verzeichnis** der beschäftigten Jugendlichen.'],
  ]],
  ['table', ['Frage', 'Antwort'], [
    ['Darf ein 17-Jähriger Samstags arbeiten?', 'In der Regel **nein** (5-Tage-Woche). Ausnahmen gibt es zum Beispiel in Krankenhäusern, Gaststätten, Bäckereien, Landwirtschaft. Dann muss ein anderer Tag in der Woche frei sein.'],
    ['Darf ein 16-Jähriger bis 21 Uhr arbeiten?', '**Nein** (Nachtruhe ab 20 Uhr). Ausnahme: Gaststätten ab 16 Jahren bis 22 Uhr.'],
    ['Wie viel Pause bei 7 Stunden Arbeitszeit?', '**60 Minuten** (mehr als 6 Stunden).'],
    ['Wie viel Pause bei 5 Stunden Arbeitszeit?', '**30 Minuten** (mehr als 4,5 bis 6 Stunden).'],
    ['Arbeitsende 18 Uhr: frühester Beginn am nächsten Tag?', '**6 Uhr** (12 Stunden Ruhezeit; und vor 6 Uhr ohnehin Nachtruhe). Bei Arbeitsende 20 Uhr (Ausnahme Gastro): 8 Uhr.'],
  ]],
  ['h', 'Aufgaben im Prüfungsstil'],
  ['qa', 'Die 17-jährige Auszubildende Mia arbeitet täglich 9 Stunden. Beurteilen Sie das. Wie viel Pause muss sie mindestens haben?', ['Jugendliche dürfen **höchstens 8 Stunden täglich** arbeiten (bis 8,5 Stunden, wenn an anderen Tagen entsprechend weniger). **9 Stunden verstoßen** gegen das JArbSchG.', 'Pause: Bei mehr als 6 Stunden Arbeitszeit mindestens **60 Minuten** (Aufteilung in mindestens 15-Minuten-Abschnitte).'], 5],
  ['qa', 'Nennen Sie vier Schutzvorschriften des Jugendarbeitsschutzgesetzes.', ['- Höchstarbeitszeit 8 Stunden täglich und 40 Stunden pro Woche, 5-Tage-Woche', '- Ruhepausen (30 bzw. 60 Minuten) und 12 Stunden Freizeit nach Arbeitsende', '- Nachtarbeitsverbot (20 bis 6 Uhr), Verbot gefährlicher Arbeiten und von Akkordarbeit', '- Mindesturlaub nach Alter, Freistellung für Berufsschule, ärztliche Erst- und Nachuntersuchung'], 4],
  ['qa', 'Ein Betrieb möchte eine 17-jährige Auszubildende ohne ärztliche Erstuntersuchung beschäftigen. Ist das zulässig?', '**Nein.** Nach § 32 JArbSchG darf ein Jugendlicher nur beschäftigt werden, wenn er innerhalb der letzten 14 Monate ärztlich **untersucht** wurde und die Bescheinigung dem Arbeitgeber vorliegt. Eine Nachuntersuchung ist nach einem Jahr nötig.', 3],
  ['qa', 'Ein Azubi ist zu Beginn des Kalenderjahres 16 Jahre alt. Wie viele Urlaubstage stehen ihm gesetzlich mindestens zu?', 'Maßgeblich ist das **Alter zu Beginn des Kalenderjahres**: Ist er zu Jahresbeginn **16**, also **noch nicht 17**, hat er **mindestens 27 Werktage** (unter 17 Jahren). (Tarif- und Ausbildungsvertrag können mehr vorsehen.)', 4],
  ['quiz', [
    {q: 'Bis zu welchem Alter gilt eine Person als Jugendlicher im Sinne des JArbSchG?', o: ['Unter 18 Jahren (ab 15)', 'Unter 21 Jahren', 'Unter 16 Jahren', 'Unter 25 Jahren'], a: 0, e: 'Jugendlich: 15 bis unter 18 Jahre.'},
    {q: 'Wie lang darf die tägliche Arbeitszeit von Jugendlichen grundsätzlich höchstens sein?', o: ['8 Stunden', '10 Stunden', '6 Stunden', '12 Stunden'], a: 0, e: '8 Stunden täglich, 40 Stunden wöchentlich.'},
    {q: 'Wie viele Minuten Pause stehen Jugendlichen bei 7 Stunden Arbeitszeit mindestens zu?', o: ['60', '30', '45', '15'], a: 0, e: 'Mehr als 6 Stunden: mindestens 60 Minuten.'},
    {q: 'Wie viele Stunden Freizeit muss ein Jugendlicher nach Arbeitsende mindestens haben?', o: ['12', '11', '8', '10'], a: 0, e: 'Jugendliche: 12 Stunden; Erwachsene: 11 Stunden.'},
    {q: 'Wann muss die Nachuntersuchung eines Jugendlichen erfolgen?', o: ['Ein Jahr nach Beschäftigungsbeginn', 'Nach 5 Jahren', 'Nie', 'Nach 3 Monaten'], a: 0, e: 'Die erste Nachuntersuchung ist 12 Monate nach Beginn nötig.'},
  ]],
]);
