AP2.page('wiso-ki', {
  b: 'wiso', g: 'Staat und Gesellschaft', t: 'Künstliche Intelligenz in Arbeitswelt und Gesellschaft',
  d: '**Künstliche Intelligenz (KI)** bezeichnet Computersysteme, die Aufgaben lösen, für die bisher menschliche Intelligenz nötig war: Sprache verstehen, Bilder erkennen, Texte erzeugen, Entscheidungen treffen. Moderne KI beruht meist auf **maschinellem Lernen**: Das System erkennt **Muster in großen Datenmengen** und verbessert sich mit mehr Daten. KI bietet Chancen gegen den **Fachkräftemangel**, birgt aber Risiken (Fehler, **Diskriminierung**, Überwachung, Arbeitsplatzverlust, Desinformation). Die EU regelt KI mit der **KI-Verordnung (AI Act)** nach Risikoklassen; im Betrieb hat der **Betriebsrat** bei der Einführung von KI Mitbestimmungsrechte.',
  m: '**KI = lernt aus Daten, erkennt Muster, trifft (Teil-)Entscheidungen.** **AI Act: unannehmbar (verboten) - hoch (strenge Pflichten) - begrenzt (Transparenz) - minimal (frei).** **Betriebsrat: § 87 Abs. 1 Nr. 6 BetrVG (Überwachung), § 90 (Unterrichtung über neue Technik), § 80 Abs. 3 (Sachverständiger bei KI).** **Stellungnahme: Meinung + 2 Argumente mit Begründung und Beispiel + Fazit.**',
  cheat: [
    ['Begriffe', ['Maschinelles Lernen: lernt aus Daten', 'Deep Learning: neuronale Netze', 'Generative KI: erzeugt Texte, Bilder (ChatGPT, Claude)', 'Schwache KI: Spezialaufgaben']],
    ['AI Act Risikoklassen', ['**unannehmbar**: verboten (Social Scoring)', '**hoch**: Bewerberauswahl, Kredit, Medizin', '**begrenzt**: Chatbots, Deepfakes kennzeichnen', '**minimal**: Spamfilter, Spiele']],
    ['Chancen', ['Entlastung von Routinearbeit', 'gegen Fachkräftemangel', 'schnellere Diagnosen, Übersetzungen', 'neue Berufe und Produkte']],
    ['Risiken', ['Fehler und "Halluzinationen"', 'Diskriminierung durch verzerrte Daten', 'Überwachung, Datenschutz', 'Jobverlust, Abhängigkeit, Desinformation']],
  ],
  blocks: [
    ['h', 'Was ist Künstliche Intelligenz? (Gemeinschaftskunde Sommer 2024, 2 Punkte)'],
    ['p', 'Klassische Programme folgen fest programmierten Regeln ("wenn A, dann B"). Ein KI-System wird stattdessen mit **Beispieldaten trainiert** und lernt daraus selbst Regeln, zum Beispiel aus Millionen Bildern, wie eine Katze aussieht, oder aus riesigen Textmengen, wie Sprache funktioniert. Je mehr und je bessere Daten, desto besser die Ergebnisse. KI-Systeme sind schon heute im Alltag: Sprachassistenten, Navigation, Übersetzung, Empfehlungen in Streamingdiensten, Spamfilter, Chatbots.'],
    ['h', 'Kann KI den Fachkräftemangel verringern? (Sommer 2024, 6 Punkte)'],
    ['table', ['Bereich', 'Einschätzung', 'Begründung'], [
      ['**Informatik, Verwaltung, Buchhaltung**', 'Eher **ja**', 'Viele Aufgaben sind digital und wiederholen sich (Code-Vorschläge, Dokumentation, Belege prüfen, Standardanfragen beantworten). KI kann Fachkräfte entlasten, sodass weniger zusätzliche Stellen nötig sind.'],
      ['**Pflege, Erziehung, Sozialarbeit ("Care-Arbeit")**', 'Eher **nein**', 'Hier zählt der direkte Kontakt von Mensch zu Mensch, Einfühlungsvermögen und individuelles Reagieren. KI kann höchstens bei Dokumentation und Planung helfen, die eigentliche Arbeit am Menschen nicht ersetzen.'],
      ['**Handwerk**', 'Teilweise', 'Planung, Angebote und Materialbestellung lassen sich unterstützen, die körperliche Arbeit vor Ort nicht.'],
    ]],
    ['h', 'Risiken und die KI-Verordnung der EU (Sommer 2024, 4 Punkte)'],
    ['list', [
      '**Kontrollverlust:** Systeme werden immer leistungsfähiger; selbst Experten können nicht genau erklären, wie ein Ergebnis zustande kommt ("Black Box").',
      '**Einschränkung der Freiheit:** KI kann Verhalten analysieren und vorhersagen (Überwachung, Gesichtserkennung im öffentlichen Raum, Social Scoring).',
      '**Diskriminierung:** Lernt eine KI aus verzerrten Daten (zum Beispiel früheren Einstellungsentscheidungen), benachteiligt sie bestimmte Gruppen systematisch.',
      '**Desinformation:** Täuschend echte Fälschungen (Deepfakes) von Bildern, Videos und Stimmen.',
      '**Arbeitsmarkt:** Wegfall von Tätigkeiten, Abhängigkeit von wenigen großen Anbietern.',
    ]],
    ['table', ['Risikoklasse (AI Act)', 'Beispiele', 'Regeln'], [
      ['**Unannehmbares Risiko**', 'Social Scoring durch Behörden, manipulative KI, Emotionserkennung am Arbeitsplatz und in Schulen, biometrische Echtzeit-Fernidentifizierung im öffentlichen Raum (mit engen Ausnahmen)', '**Verboten** (seit Februar 2025)'],
      ['**Hohes Risiko**', 'KI in der **Bewerberauswahl** und Personalführung, Kreditwürdigkeit, Bildung (Prüfungsbewertung), Medizinprodukte, kritische Infrastruktur', 'Risikomanagement, hochwertige Trainingsdaten, Dokumentation, **menschliche Aufsicht**, Registrierung'],
      ['**Begrenztes Risiko**', 'Chatbots, KI-generierte Inhalte, Deepfakes', '**Transparenzpflicht**: Nutzer müssen erkennen, dass sie mit KI sprechen bzw. Inhalte KI-erzeugt sind (Kennzeichnung)'],
      ['**Minimales Risiko**', 'Spamfilter, KI in Videospielen, Rechtschreibprüfung', 'Keine besonderen Pflichten'],
    ]],
    ['p', 'Ziele der Verordnung laut Prüfungstext: KI-Anwendungen **nach ihrem Risiko** für die persönliche Freiheit **klassifizieren**, den Einsatz risikoabhängig **beschränken** (vom Verbot bis zur freien Nutzung), Menschen vor Manipulation schützen und **KI-erzeugte Inhalte kennzeichnen**. Außerdem müssen Unternehmen seit Februar 2025 dafür sorgen, dass Beschäftigte, die mit KI arbeiten, ausreichende **KI-Kompetenz** haben (Art. 4 AI Act).'],
    ['h', 'KI im Betrieb: Rechte des Betriebsrats'],
    ['kv', [
      ['§ 90 BetrVG', 'Der Arbeitgeber muss den Betriebsrat **rechtzeitig unterrichten** und mit ihm beraten, wenn er neue technische Anlagen und Arbeitsverfahren (einschließlich KI) plant.'],
      ['§ 87 Abs. 1 Nr. 6 BetrVG', '**Zwingende Mitbestimmung** bei technischen Einrichtungen, die geeignet sind, **Verhalten oder Leistung** der Beschäftigten zu **überwachen**. Das trifft auf die meisten KI-Systeme zu (zum Beispiel Auswertung von Arbeitszeiten oder Tickets).'],
      ['§ 80 Abs. 3 BetrVG', 'Bei KI darf der Betriebsrat einen **Sachverständigen** hinzuziehen; die Erforderlichkeit wird vermutet.'],
      ['§ 95 BetrVG', 'Auswahlrichtlinien bei Einstellungen, auch wenn KI sie anwendet, brauchen die Zustimmung des Betriebsrats.'],
      ['Betriebsvereinbarung', 'Typischer Weg: Regeln zu erlaubten Einsatzzwecken, Datenschutz, keine Leistungs- und Verhaltenskontrolle, Schulungen, Kontrolle durch Menschen.'],
    ]],
    ['h', 'Musterstellungnahme an den Betriebsrat (Sommer 2024, 6 Punkte)'],
    ['ex', ['Sehr geehrte Betriebsratsmitglieder,', 'für die anstehende Diskussion über den Einsatz von KI in unserem Unternehmen möchte ich meine Meinung darlegen.', '**Erstens** sollte KI nur zur **Unterstützung** eingesetzt werden, etwa beim Vorsortieren von Supportanfragen oder bei der Dokumentation. Endgültige Entscheidungen müssen Menschen treffen. So bleiben Verantwortung und Fachwissen im Unternehmen, und Fehler der KI ("Halluzinationen") werden erkannt.', '**Zweitens** darf KI **nicht zur Auswertung von Personaldaten** wie Fehlzeiten oder Leistungskennzahlen genutzt werden. Personenbezogene Daten sind anfällig für diskriminierende Rückschlüsse: Ältere Beschäftigte oder Eltern kleiner Kinder könnten systematisch benachteiligt werden. Das wäre zudem nach § 87 BetrVG mitbestimmungspflichtig und datenschutzrechtlich problematisch.', '**Fazit:** KI kann uns die Arbeit erleichtern und dem Fachkräftemangel entgegenwirken. Ich befürworte den Einsatz, aber nur mit klaren Regeln in einer Betriebsvereinbarung, Schulungen für alle Beschäftigten und ohne Leistungsüberwachung.', 'Mit freundlichen Grüßen, Vorname Name']],
    ['h', 'Aufgaben im Prüfungsstil (ganze Sätze!)'],
    ['qa', 'Beschreiben Sie den Begriff "Künstliche Intelligenz" in eigenen Worten.', ['Künstliche Intelligenz ist eine computerbasierte Technologie, bei der Programme auf Basis von **Daten selbstständig Entscheidungen treffen** oder Inhalte erzeugen. Statt fester Regeln lernt die KI aus Beispielen Muster und verbessert sich mit zunehmender Nutzung und mehr Daten ständig weiter.'], 2],
    ['qa', 'Arbeiten Sie zwei Risiken von KI und zwei Ziele der EU-KI-Verordnung heraus.', ['Risiken: KI könnte dem Menschen überlegen und dadurch **unkontrollierbar** werden; außerdem kann sie die **persönliche Freiheit** einschränken, wenn sie das Sozialverhalten von Menschen analysiert und vorhersagt.', 'Ziele: KI-Anwendungen sollen nach ihrem **Risiko klassifiziert** und ihr Einsatz entsprechend beschränkt werden (bis zum Verbot). Außerdem sollen **KI-erzeugte Inhalte gekennzeichnet** werden, damit Menschen erkennen, was nicht von Menschen stammt.'], 4],
    ['quiz', [
      {q: 'In welche Risikoklasse des AI Act fällt KI zur Bewerberauswahl?', o: ['Hohes Risiko', 'Minimales Risiko', 'Verboten', 'Begrenztes Risiko'], a: 0, e: 'Beschäftigung ist ein Hochrisikobereich.'},
      {q: 'Was gilt für Chatbots nach dem AI Act?', o: ['Nutzer müssen erkennen können, dass sie mit einer KI kommunizieren', 'Sie sind verboten', 'Es gibt keine Regeln', 'Sie dürfen nur von Behörden betrieben werden'], a: 0, e: 'Transparenzpflicht.'},
      {q: 'Welche Vorschrift gibt dem Betriebsrat ein Mitbestimmungsrecht bei Überwachungstechnik?', o: ['§ 87 Abs. 1 Nr. 6 BetrVG', '§ 622 BGB', 'Art. 38 GG', '§ 9 JArbSchG'], a: 0, e: 'Technische Einrichtungen zur Leistungs- und Verhaltenskontrolle.'},
      {q: 'Was ist Social Scoring nach dem AI Act?', o: ['Verboten', 'Hohes Risiko', 'Erlaubt mit Kennzeichnung', 'Minimales Risiko'], a: 0, e: 'Unannehmbares Risiko.'},
    ]],
    ['see', ['wiso-eu', 'wiso-betriebsrat', 'wiso-demografie', 'ps-dsgvo']],
  ],
});
