AP2.add('wiso-kuendigung', [
  ['ex', ['**Beispiel 1:** Ein Arbeitnehmer (3 Jahre im Betrieb) kündigt am **10. März**. **Frist:** 4 Wochen = 28 Tage, zum **15.** oder **Monatsende**. 28 Tage nach dem 10. März ist der 7. April; der nächste Termin danach ist der **15. April**. Das Arbeitsverhältnis endet am **15. April**.', '**Beispiel 2:** Der Arbeitgeber (8 Jahre Betriebszugehörigkeit) kündigt am **20. Mai**, zugegangen am gleichen Tag. Frist **3 Monate zum Monatsende**: Ende am **31. August** (Frist von 3 Monaten ab 20. Mai ist der 20. August, der nächste Monatsende ist der **31. August**).']],
  ['h', 'Das Kündigungsschutzgesetz (KSchG)'],
  ['p', 'Der **Arbeitgeber** darf **nicht einfach nach Belieben** kündigen. Das **KSchG** schützt Arbeitnehmer, **wenn** (1) das Arbeitsverhältnis **länger als 6 Monate** besteht (**Wartezeit**) und (2) im Betrieb **in der Regel mehr als 10 Arbeitnehmer** beschäftigt sind (Teilzeitkräfte anteilig: bis 20 Stunden 0,5; bis 30 Stunden 0,75; **Auszubildende zählen nicht mit**). Dann ist eine Kündigung nur wirksam, wenn sie **sozial gerechtfertigt** ist:'],
  ['table', ['Kündigungsgrund', 'Bedeutung', 'Voraussetzung', 'Beispiel'], [
    ['**Personenbedingt**', 'Gründe in der **Person**, ohne Schuld', '**Negative Prognose**, keine Weiterbeschäftigungsmöglichkeit, Interessenabwägung', 'Dauerhafte Arbeitsunfähigkeit, Verlust der Fahrerlaubnis beim Berufskraftfahrer, lange Krankheit'],
    ['**Verhaltensbedingt**', '**Schuldhaftes Fehlverhalten** (Pflichtverletzung)', 'Meist vorherige **Abmahnung**; Interessenabwägung', 'Wiederholtes Zuspätkommen, Arbeitsverweigerung, Beleidigung, private Internetnutzung trotz Verbot'],
    ['**Betriebsbedingt**', '**Dringende betriebliche Erfordernisse** (Wegfall des Arbeitsplatzes)', 'Keine Weiterbeschäftigung möglich, **Sozialauswahl**', 'Auftragsrückgang, Betriebsschließung, Umstrukturierung'],
  ]],
  ['kv', [
    ['Abmahnung', 'Rüge einer **konkreten Pflichtverletzung** mit **Warnung**, dass bei Wiederholung die Kündigung droht. Voraussetzung für die **verhaltensbedingte Kündigung** (Ausnahme: schwere Pflichtverletzungen).'],
    ['Sozialauswahl', 'Bei betriebsbedingter Kündigung muss der Arbeitgeber unter **vergleichbaren** Arbeitnehmern die **sozial Stärksten** zuerst kündigen. Kriterien: **Dauer der Betriebszugehörigkeit**, **Lebensalter**, **Unterhaltspflichten**, **Schwerbehinderung**.'],
    ['Klagefrist (§ 4 KSchG)', 'Wer eine Kündigung für unwirksam hält, muss **innerhalb von 3 Wochen** nach Zugang **Kündigungsschutzklage beim Arbeitsgericht** erheben. Danach gilt die Kündigung als **wirksam**, auch wenn sie fehlerhaft war.'],
    ['Abfindung', 'Kein gesetzlicher Anspruch (Ausnahme: § 1a KSchG). Üblich als **Vergleich** vor Gericht: grob **0,5 Bruttomonatsgehälter pro Beschäftigungsjahr** als Faustregel.'],
    ['Anhörung des Betriebsrats (§ 102 BetrVG)', 'Gibt es einen Betriebsrat, muss er **vor jeder Kündigung angehört werden**. Eine Kündigung **ohne Anhörung** ist **unwirksam**.'],
  ]],
  ['h', 'Besonderer Kündigungsschutz'],
  ['table', ['Personengruppe', 'Schutz'], [
    ['**Schwangere** und Mütter bis 4 Monate nach der Entbindung (MuSchG), **Elternzeit**', 'Kündigung **grundsätzlich verboten** (Ausnahme: Zustimmung der Aufsichtsbehörde)'],
    ['**Schwerbehinderte** (Grad der Behinderung ab 50)', 'Kündigung nur mit **Zustimmung des Integrationsamts**'],
    ['**Betriebsratsmitglieder**, Wahlvorstand, JAV', 'Ordentliche Kündigung **ausgeschlossen**, fristlos nur mit **Zustimmung des Betriebsrats** oder gerichtlicher Ersetzung'],
    ['**Auszubildende** (nach der Probezeit)', 'Nur **fristlos aus wichtigem Grund** (siehe Ausbildungsvertrag)'],
    ['Wehr-/Zivildienst, Pflegezeit, Datenschutz- und Immissionsschutzbeauftragte', 'Besonderer Schutz nach Spezialgesetzen'],
  ]],
  ['h', 'Nach der Kündigung: Pflichten und Ansprüche'],
  ['list', ['**Arbeitslosmeldung:** Wer gekündigt wird, muss sich **spätestens 3 Monate vor Ende** (bei kurzfristiger Kündigung **innerhalb von 3 Tagen** nach Kenntnis) bei der **Agentur für Arbeit arbeitssuchend melden**, sonst droht eine **Sperrzeit** beim Arbeitslosengeld.', '**Arbeitszeugnis** (einfach oder qualifiziert) und **Urlaubsabgeltung** für nicht genommenen Urlaub.', '**Freistellung** zur Stellensuche bei Kündigung (angemessene Zeit).', '**Sperrzeit** (bis zu 12 Wochen) droht, wenn der Arbeitnehmer **selbst kündigt** oder einen **Aufhebungsvertrag** ohne wichtigen Grund schließt.']],
  ['h', 'Aufgaben im Prüfungsstil'],
  ['qa', 'Eine Mitarbeiterin (6 Jahre im Betrieb, Betrieb mit 40 Arbeitnehmern) erhält am 5. Juli eine betriebsbedingte schriftliche Kündigung. Welche Frist gilt für den Arbeitgeber, zu welchem Termin endet das Arbeitsverhältnis?', ['5 Jahre Betriebszugehörigkeit erreicht, 8 Jahre nicht: Frist **2 Monate zum Monatsende**.', '2 Monate ab 5. Juli = 5. September; nächster Monatsende: **30. September**. Das Arbeitsverhältnis endet am **30. September**. Das KSchG gilt (mehr als 10 Arbeitnehmer, länger als 6 Monate): Der Arbeitgeber braucht einen sozial gerechtfertigten Grund und muss eine Sozialauswahl durchführen.'], 6],
  ['qa', 'Ein Arbeitnehmer wurde heute (Zugang) gekündigt und hält die Kündigung für ungerecht. Was muss er tun und bis wann?', 'Er muss **innerhalb von drei Wochen** nach Zugang der schriftlichen Kündigung **Kündigungsschutzklage beim Arbeitsgericht** erheben (§ 4 KSchG). Versäumt er die Frist, gilt die Kündigung als wirksam, auch wenn sie sozial nicht gerechtfertigt war. Zusätzlich sollte er sich **arbeitssuchend melden**.', 4],
  ['qa', 'Nennen Sie die drei Arten sozial gerechtfertigter Kündigungsgründe mit je einem Beispiel.', ['- **Personenbedingt:** dauerhafte Krankheit, die die Arbeit unmöglich macht.', '- **Verhaltensbedingt:** wiederholtes unentschuldigtes Fehlen trotz Abmahnung.', '- **Betriebsbedingt:** Stilllegung einer Abteilung, Arbeitsplatz fällt weg.'], 6],
  ['qa', 'Welche Bedeutung hat die Abmahnung?', 'Die Abmahnung rügt eine **konkrete Pflichtverletzung** und **warnt** vor Konsequenzen (Kündigung) bei Wiederholung. Bei **verhaltensbedingten Kündigungen** ist sie in der Regel **Voraussetzung**, damit der Arbeitnehmer sein Verhalten ändern kann. Ausnahme: sehr schwere Pflichtverletzung (zum Beispiel Diebstahl, Gewalt).', 4],
  ['quiz', [
    {q: 'Welche Form muss eine Kündigung haben?', o: ['Schriftlich mit Originalunterschrift', 'Mündlich', 'Per E-Mail', 'Per SMS'], a: 0, e: '§ 623 BGB: Schriftform, E-Mail reicht nicht.'},
    {q: 'Wie lautet die gesetzliche Grundkündigungsfrist?', o: ['4 Wochen zum 15. oder Monatsende', '1 Monat zum Quartal', '3 Monate', '2 Wochen'], a: 0, e: 'Grundfrist für beide Seiten: 4 Wochen zum 15. oder zum Ende des Kalendermonats.'},
    {q: 'Innerhalb welcher Frist muss man Kündigungsschutzklage erheben?', o: ['3 Wochen', '3 Monate', '1 Woche', '1 Jahr'], a: 0, e: 'Drei Wochen nach Zugang der Kündigung.'},
    {q: 'Ab wie vielen Arbeitnehmern gilt das Kündigungsschutzgesetz (Betriebsgröße)?', o: ['Mehr als 10', 'Mehr als 5', 'Mehr als 50', 'Mehr als 100'], a: 0, e: 'Voraussetzung: in der Regel mehr als 10 Arbeitnehmer (ohne Auszubildende).'},
    {q: 'Welche Rolle spielt der Betriebsrat bei einer Kündigung?', o: ['Er muss vorher angehört werden, sonst ist sie unwirksam', 'Er muss kündigen', 'Er hat keine Rolle', 'Er muss unterschreiben, damit der Arbeitnehmer Geld bekommt'], a: 0, e: '§ 102 BetrVG: Anhörung vor jeder Kündigung.'},
    {q: 'Was ist ein Beispiel für eine verhaltensbedingte Kündigung?', o: ['Wiederholtes Zuspätkommen trotz Abmahnung', 'Wegfall des Arbeitsplatzes', 'Dauerhafte Krankheit', 'Betriebsschließung'], a: 0, e: 'Schuldhaftes Fehlverhalten, meist nach Abmahnung.'},
  ]],
]);
