AP2.add('wiso-markt', [
  ['h', 'Was verschiebt die Kurven?'],
  ['p', 'Ändert sich der **Preis**, bewegt man sich **auf** der Kurve. Ändern sich dagegen **andere Faktoren**, **verschiebt sich die ganze Kurve**:'],
  ['table', ['Kurve', 'Verschiebt sich nach rechts (mehr) bei ...', 'Verschiebt sich nach links (weniger) bei ...'], [
    ['**Nachfrage**', 'Steigenden **Einkommen**, **Mode/Trends**, mehr Bevölkerung, höherem Preis eines **Substituts** (Ersatzgut), niedrigerem Preis eines **Komplementärguts** (Ergänzungsgut)', 'Sinkenden Einkommen, geändertem Geschmack, steigendem Preis eines Komplementärguts'],
    ['**Angebot**', 'Sinkenden **Produktionskosten**, **technischem Fortschritt**, Subventionen, mehr Anbietern', 'Steigenden Rohstoff-, Energie- und Lohnkosten, Steuern, Naturkatastrophen'],
  ]],
  ['diagram', AP2.marktDiagrams.shift],
  ['ex', ['**Beispiel:** Im Sommer **steigt die Nachfrage** nach Eis (Wetter). Die Nachfragekurve verschiebt sich nach rechts: **Preis und verkaufte Menge steigen**. Wird ein **Chip-Engpass** gemeldet (**Angebot sinkt**), verschiebt sich die Angebotskurve nach links: **Der Preis steigt, die Menge sinkt** (Beispiel Grafikkarten).']],
  ['h', 'Staatliche Eingriffe in den Preis'],
  ['diagram', AP2.marktDiagrams.caps],
  ['table', ['Maßnahme', 'Wirkung', 'Beispiel'], [['**Höchstpreis** (unter dem Gleichgewicht)', '**Nachfrageüberhang**: Knappheit, Warteschlangen, Schwarzmarkt', 'Mietpreisbremse, Preisdeckel für Energie'], ['**Mindestpreis** (über dem Gleichgewicht)', '**Angebotsüberhang**: Überschuss', 'Gesetzlicher **Mindestlohn** (Arbeitsmarkt), frühere Agrarpreise'], ['**Subvention**', 'Senkt Produktionskosten, Angebot steigt, Preis sinkt', 'Förderung für Elektroautos'], ['**Steuer** (zum Beispiel Tabaksteuer)', 'Verteuert, Angebot sinkt, Preis steigt', 'Energiesteuer']]],
  ['h', 'Marktformen'],
  ['p', 'Nach der **Anzahl der Marktteilnehmer** unterscheidet man (jeweils für Anbieter und Nachfrager) **einen, wenige, viele**:'],
  ['table', ['Nachfrager \\ Anbieter', 'Ein Anbieter', 'Wenige Anbieter', 'Viele Anbieter'], [['**Ein Nachfrager**', 'Zweiseitiges Monopol', 'Beschränktes Nachfragemonopol', '**Monopson** (Nachfragemonopol)'], ['**Wenige Nachfrager**', 'Beschränktes Angebotsmonopol', 'Zweiseitiges Oligopol', 'Nachfrageoligopol'], ['**Viele Nachfrager**', '**Monopol** (Angebotsmonopol)', '**Oligopol** (Angebotsoligopol)', '**Polypol** (vollständige Konkurrenz)']], {first: true}],
  ['table', ['Marktform', 'Anbieter', 'Preisbildung', 'Beispiele', 'Wirkung'], [
    ['**Monopol**', 'Ein einziger', 'Anbieter ist **Preissetzer**, kann hohe Preise und Mengen bestimmen', 'Deutsche Bahn (Schienennetz), lokale Wasserversorgung, Patentinhaber', 'Hohe Preise, wenig Anreiz zur Verbesserung; staatliche Regulierung'],
    ['**Oligopol**', 'Wenige große', 'Gegenseitige Beobachtung, **Preisführerschaft**, **Absprachen (Kartell)** möglich', 'Autohersteller, Mobilfunknetze, Energieversorger, Banken', 'Vorsicht Kartelle; **Kartellverbot** (GWB)'],
    ['**Polypol**', 'Viele kleine', 'Anbieter sind **Preisnehmer** (Marktpreis), starker Wettbewerb', 'Wochenmarkt, Landwirte, Friseure, Online-Händler', 'Günstige Preise für Verbraucher, hoher Druck auf Anbieter'],
  ]],
  ['h', 'Wettbewerb und Kartellrecht'],
  ['list', ['**Wettbewerb** sorgt für niedrige Preise, Qualität und Innovation. Marktmacht kann ihn gefährden.', 'Das **Gesetz gegen Wettbewerbsbeschränkungen (GWB)** verbietet **Kartelle** (Preis-, Mengen-, Gebietsabsprachen), **Missbrauch einer marktbeherrschenden Stellung** und prüft **Fusionen** ab bestimmter Größe.', '**Bundeskartellamt** (Bonn) überwacht und verhängt **Bußgelder**. Europaweit die **EU-Kommission**.', '**Konzentration** durch Fusionen (Zusammenschlüsse), **Konzern** (rechtlich selbstständig, wirtschaftlich unter einer Leitung) und **Kartell** (rechtlich und wirtschaftlich selbstständige Unternehmen mit **Absprache**: verboten).']],
  ['h', 'Wirtschaftsordnungen'],
  ['table', ['', 'Freie Marktwirtschaft', 'Zentralverwaltungswirtschaft (Planwirtschaft)', 'Soziale Marktwirtschaft'], [['Steuerung', 'Über **Preise** (Markt)', 'Staat **plant** Produktion und Preise', '**Markt** plus staatlicher Rahmen und sozialer Ausgleich'], ['Eigentum', 'Privat', 'Staatlich (Volkseigentum)', 'Privat, mit **Sozialbindung** (Art. 14 GG)'], ['Vorteile', 'Effizienz, Innovation, Freiheit', 'Planbarkeit, Gleichheit (Ziel)', 'Wohlstand **und** Absicherung'], ['Nachteile', 'Ungleichheit, Krisen, kein sozialer Schutz', 'Ineffizienz, Mangel, wenig Freiheit', 'Staatsausgaben, Bürokratie'], ['Beispiel', 'Reines Modell (USA näher)', 'DDR, früher Sowjetunion', '**Deutschland** (Ludwig Erhard, Alfred Müller-Armack)']]],
  ['h', 'Aufgaben im Prüfungsstil'],
  ['qa', 'Was passiert mit Preis und Menge, wenn die Nachfrage nach einem Gut steigt, das Angebot aber gleich bleibt?', 'Die Nachfragekurve verschiebt sich nach rechts. Es entsteht bei dem alten Preis ein **Nachfrageüberhang**, der Preis **steigt**, bis ein neues Gleichgewicht erreicht ist. Im neuen Gleichgewicht sind **Preis und Menge höher**.', 4],
  ['qa', 'Erklären Sie, warum ein Mindestpreis über dem Gleichgewichtspreis zu einem Angebotsüberhang führt, und nennen Sie ein Beispiel.', 'Bei einem Preis **über** dem Gleichgewicht wollen die Anbieter mehr verkaufen, als die Nachfrager zu diesem Preis kaufen. Es entsteht ein **Überschuss (Angebotsüberhang)**. Beispiel: Wäre der **Mindestlohn** höher als der Preis, den Arbeitgeber zu zahlen bereit sind, entstünde ein Überangebot an Arbeit (Arbeitslosigkeit); früher Butterberge bei garantierten Agrarpreisen.', 5],
  ['qa', 'Nennen Sie die drei Marktformen auf der Anbieterseite mit je einem Beispiel und einer Eigenschaft.', ['- **Monopol:** ein Anbieter (Schienennetz), Preissetzer.', '- **Oligopol:** wenige Anbieter (Mobilfunk), gegenseitige Abhängigkeit, Kartellgefahr.', '- **Polypol:** viele Anbieter (Wochenmarkt), Preisnehmer, starker Wettbewerb.'], 6],
  ['qa', 'Warum sind Kartelle verboten?', 'Bei einem **Kartell** sprechen rechtlich selbstständige Unternehmen **Preise, Mengen oder Gebiete ab** und schalten damit den **Wettbewerb** aus. Das führt zu **höheren Preisen** und schlechterer Versorgung für Verbraucher. Das **GWB** verbietet Kartelle, das **Bundeskartellamt** verhängt hohe **Bußgelder**.', 4],
  ['quiz', [
    {q: 'Was passiert bei einem Preis über dem Gleichgewichtspreis?', o: ['Angebotsüberhang', 'Nachfrageüberhang', 'Gleichgewicht', 'Nichts'], a: 0, e: 'Es wird mehr angeboten als nachgefragt, der Preis sinkt.'},
    {q: 'Wie nennt man einen Markt mit vielen Anbietern?', o: ['Polypol', 'Monopol', 'Oligopol', 'Monopson'], a: 0, e: 'Poly = viele.'},
    {q: 'Was ist ein Monopson?', o: ['Ein Nachfrager, viele Anbieter', 'Ein Anbieter', 'Wenige Anbieter', 'Viele Nachfrager'], a: 0, e: 'Monopson = Nachfragemonopol.'},
    {q: 'Was bewirkt ein Höchstpreis unter dem Gleichgewichtspreis?', o: ['Nachfrageüberhang (Knappheit)', 'Angebotsüberhang', 'Mehr Angebot', 'Nichts'], a: 0, e: 'Zum niedrigen Preis wird mehr nachgefragt als angeboten.'},
    {q: 'Was verschiebt die Nachfragekurve nach rechts?', o: ['Steigendes Einkommen der Käufer', 'Höherer Preis desselben Guts', 'Steigende Produktionskosten', 'Mindestlohn'], a: 0, e: 'Der eigene Preis bewegt sich auf der Kurve, andere Faktoren verschieben sie.'},
  ]],
]);
