AP2.page('wiso-methoden', {
  b: 'wiso', g: 'Staat und Gesellschaft', t: 'Methoden: Schaubild, Karikatur, Text auswerten und Stellung nehmen',
  d: 'Die Gemeinschaftskunde-Prüfung (60 Minuten, 30 Punkte) besteht aus einer **Handlungssituation** und Materialien: **Zeitungsartikel, Schaubilder, Karikaturen, Gesetzestexte**. Gefragt sind dann wiederkehrende Methoden: **Aussagen herausarbeiten**, **Schaubild auswerten**, **Karikatur beschreiben und interpretieren**, **Aussage überprüfen**, **Stellung nehmen** bzw. einen **Brief/eine E-Mail** mit Vorschlägen schreiben. **Alle Antworten in ganzen Sätzen**, sonst gibt es Punktabzug. Die **Operatoren** (nennen, erklären, beurteilen ...) bestimmen, wie ausführlich geantwortet werden muss.',
  m: '**Operator lesen -> Anforderungsbereich -> Punktzahl beachten (2 Punkte = 1 Argument ausführlich oder 2 kurz).** **Schaubild: Titel, Quelle, Jahr, Einheit -> Hauptaussage -> Einzelheiten -> Entwicklung.** **Karikatur: Beschreiben (was sehe ich?) -> Interpretieren (was meint der Zeichner?) -> Bewerten.** **Stellungnahme: Position, 2 begründete Argumente mit Beispiel, Fazit.**',
  cheat: [
    ['Operatoren AFB I', ['**nennen**: Stichworte/kurze Sätze', '**beschreiben**: Sachverhalt mit eigenen Worten', '**herausarbeiten**: aus dem Material entnehmen', '**darstellen**: geordnet wiedergeben']],
    ['Operatoren AFB II', ['**erklären**: Ursachen, Zusammenhänge', '**erläutern**: erklären + Beispiel', '**begründen**: warum? mit Argumenten', '**vergleichen**, **analysieren**']],
    ['Operatoren AFB III', ['**beurteilen**: Sachurteil mit Kriterien', '**bewerten**/**Stellung nehmen**: eigenes Werturteil', '**überprüfen**: Aussage am Material testen', '**entwickeln**: eigene Lösungsvorschläge']],
    ['Formalia', ['ganze Sätze!', 'Bezug zum Material (Anlage, Zeile)', 'eigene Worte statt Abschreiben', 'Brief: Anrede, Gruß, Name']],
  ],
  blocks: [
    ['h', 'Schaubild (Diagramm, Grafik) auswerten'],
    ['steps', [
      '**Formale Angaben:** Thema/Titel, **Quelle**, **Zeitpunkt/Zeitraum**, **Darstellungsform** (Balken, Linie, Kreis), **Einheiten** (absolute Zahlen, Prozent, Index).',
      '**Hauptaussage** in einem Satz: Was ist die zentrale Entwicklung oder der wichtigste Vergleich?',
      '**Einzelaussagen** mit Zahlen belegen: höchster/niedrigster Wert, Veränderungen, Auffälligkeiten ("Der Anteil der über 70-Jährigen hat sich von 1972 bis 2021 verdoppelt.").',
      '**Erklären und einordnen:** Ursachen der Entwicklung, Bezug zur Fragestellung.',
      '**Kritisch prüfen:** Fehlen Daten? Ist die Achse abgeschnitten? Wer hat das Schaubild veröffentlicht?',
    ]],
    ['tip', 'Formulierungshilfen: "Das Schaubild zeigt ...", "Aus dem Diagramm geht hervor, dass ...", "Der Anteil ist von ... auf ... gestiegen/gesunken.", "Auffällig ist, dass ...", "Im Vergleich zu ... ist ... deutlich höher." Achte auf den Unterschied zwischen **Prozent** und **Prozentpunkten** (von 20 % auf 30 % = +10 Prozentpunkte = +50 %).'],
    ['h', 'Aussage überprüfen (Sommer 2023: "Gleichberechtigung ist in Deutschland erreicht", 6 Punkte)'],
    ['p', 'Bei "Überprüfen Sie die Aussage anhand von zwei Aspekten des Schaubilds" muss man die Aussage **an konkreten Daten testen** und zu einem **differenzierten Fazit** kommen:'],
    ['ex', ['Im Bereich **Gesundheit (Zugang)** stimmt die Aussage: Laut Schaubild ist die Gleichstellung hier fast vollständig erreicht.', 'Bei **Berufs- und Bildungschancen** stimmt sie nicht: Die Gleichstellung ist nicht einmal zur Hälfte erreicht, Deutschland liegt sogar unter dem EU-Durchschnitt.', '**Fazit:** Die Aussage trifft nur teilweise zu, es kommt auf den Bereich an.']],
    ['h', 'Karikatur beschreiben und interpretieren (Sommer 2023, 4 Punkte)'],
    ['steps', [
      '**Beschreiben** (ohne Deutung): Personen, Gegenstände, Mimik, Text/Sprechblasen, Bildunterschrift, Zeichner, Jahr.',
      '**Interpretieren:** Welches Problem greift der Zeichner auf? Welche **Stilmittel** nutzt er (Übertreibung, Gegensatz zwischen Bild und Text, Symbole)? Was ist die **Kernaussage** (Kritik)?',
      '**Bewerten** (wenn verlangt): Ist die Kritik berechtigt? Eigene begründete Meinung.',
    ]],
    ['ex', ['Beschreibung: Eine müde Mutter mit dunklen Augenringen schiebt einen Kinderwagen mit zwei Kindern, eines schreit; sie ist mit Einkaufstüten beladen. Sie sagt zu einer erholt wirkenden Frau: "Nachtarbeit ist ideal für mich. Da kann ich tagsüber prima Haushalt und Kinder versorgen."', 'Interpretation: Der **Gegensatz** zwischen dem erschöpften Aussehen und der Aussage, Nachtarbeit sei "ideal", kritisiert die mangelnde **Vereinbarkeit von Familie und Beruf**. Immer mehr Frauen sind berufstätig, werden aber bei Hausarbeit und Kindererziehung nicht entsprechend entlastet (Doppelbelastung).']],
    ['h', 'Zentrale Aussagen eines Textes herausarbeiten (Sommer 2023, 4 Punkte)'],
    ['list', [
      'Text zweimal lesen, Schlüsselstellen markieren.',
      'Aussagen in **eigenen Worten** formulieren, nicht abschreiben.',
      'So viele Aussagen wie verlangt (bei 4 Punkten meist 4 Aussagen à 1 Punkt), jede in einem vollständigen Satz.',
      'Nur wiedergeben, was im Text steht, keine eigene Meinung (die ist erst bei "Stellung nehmen" gefragt).',
    ]],
    ['h', 'Stellung nehmen / kritisch Stellung nehmen'],
    ['p', 'Eine Stellungnahme ist eine kurze **Argumentation**. Bei "kritisch Stellung nehmen (2 Argumente)" erwarten die Prüfer meist ein **Pro- und ein Contra-Argument** oder zwei Argumente für die eigene Position **und** ein klares **Fazit**.'],
    ['table', ['Baustein', 'Inhalt', 'Beispiel (Wahlalter 16)'], [
      ['**Einleitung/These**', 'Thema und eigene Position', '"Ich befürworte das Wählen ab 16 Jahren bei Bundestagswahlen."'],
      ['**Argument + Begründung + Beispiel**', 'Behauptung, warum, konkretes Beispiel', '"Junge Menschen sind von langfristigen Entscheidungen am längsten betroffen. Zum Beispiel werden sie die Folgen der Klima- und Rentenpolitik noch Jahrzehnte spüren."'],
      ['**Gegenargument + Entkräftung**', 'Gegenposition fair darstellen, abwägen', '"Kritiker meinen, 16-Jährigen fehle die Reife. Dem lässt sich entgegnen, dass sie bei Kommunal- und Europawahlen bereits verantwortungsvoll wählen."'],
      ['**Fazit**', 'Position bekräftigen, eventuell Bedingung/Kompromiss', '"Insgesamt überwiegen für mich die Vorteile, wenn die politische Bildung an Schulen gestärkt wird."'],
    ]],
    ['h', 'Brief oder E-Mail mit Vorschlägen (Sommer 2023, Sommer 2024, 6 Punkte)'],
    ['list', [
      '**Form:** Betreff (bei E-Mail), Anrede ("Sehr geehrter Herr Müller,"), Einleitung (Anlass), Hauptteil, Schluss, Grußformel ("Mit freundlichen Grüßen"), Name.',
      '**Inhalt:** genau so viele **konkrete** Vorschläge wie verlangt, jeweils mit **Begründung** (Warum hilft das?) und Bezug zum Betrieb/Beruf.',
      '**Sprache:** sachlich, höflich, Sie-Form, ganze Sätze.',
    ]],
    ['h', 'Aufgaben zum Üben'],
    ['qa', 'Prüfen Sie die Äußerung "In Deutschland bestimmen die Alten alles" mit zwei Argumenten.', ['Für die Äußerung spricht, dass rund 58 % der Wahlberechtigten 50 Jahre oder älter sind. Dadurch haben ältere Menschen bei Wahlen ein großes Gewicht, und Parteien richten ihre Programme stärker auf deren Interessen aus.', 'Hinzu kommt, dass Jüngere seltener wählen gehen und so ihr Mitspracherecht weniger nutzen. Allerdings "bestimmen" Ältere nicht alles: Junge Menschen können sich über Jugendorganisationen, Demonstrationen (zum Beispiel Fridays for Future) und soziale Medien wirksam Gehör verschaffen. Die Aussage ist daher übertrieben, beschreibt aber ein reales Ungleichgewicht.'], 4],
    ['quiz', [
      {q: 'Welcher Operator verlangt ein eigenes, begründetes Werturteil?', o: ['Stellung nehmen', 'nennen', 'beschreiben', 'herausarbeiten'], a: 0, e: 'Anforderungsbereich III.'},
      {q: 'Was gehört beim Beschreiben einer Karikatur NICHT dazu?', o: ['Die Deutung der Absicht des Zeichners', 'Personen und Gegenstände', 'Texte und Sprechblasen', 'Mimik und Gestik'], a: 0, e: 'Die Deutung kommt bei der Interpretation.'},
      {q: 'Ein Anteil steigt von 20 % auf 25 %. Um wie viel ist er gestiegen?', o: ['Um 5 Prozentpunkte bzw. 25 %', 'Um 5 %', 'Um 25 Prozentpunkte', 'Um 45 %'], a: 0, e: '5/20 = 25 % relativ.'},
      {q: 'Was passiert in der GK-Prüfung bei Antworten in Stichworten?', o: ['Punktabzug, wenn nicht anders angegeben', 'Nichts', 'Doppelte Punkte', 'Die Aufgabe wird nicht gewertet'], a: 0, e: 'Hinweis auf jedem Aufgabenblatt.'},
    ]],
    ['see', ['de-eroerterung', 'de-text', 'wiso-wahlen', 'wiso-demografie']],
  ],
});
