AP2.add('wiso-rv', [
  ['h', 'Die Rentenformel Schritt für Schritt'],
  ['code', 'text', `Monatsrente (brutto) = Entgeltpunkte (EP) mal Zugangsfaktor (ZF) mal aktueller Rentenwert (ARW) mal Rentenartfaktor (RAF)`],
  ['table', ['Faktor', 'Bedeutung', 'Wert / Beispiel'], [
    ['**Entgeltpunkte (EP)**', 'Für jedes Jahr: **Jahresbrutto geteilt durch das Durchschnittsentgelt** aller Versicherten dieses Jahres. Wer genau den Durchschnitt verdient, erhält **1,0 EP** pro Jahr.', '40.000 Euro Jahresbrutto bei Durchschnittsentgelt 50.000 Euro: **0,8 EP**'],
    ['**Zugangsfaktor (ZF)**', 'Berücksichtigt den **Rentenbeginn**: **1,0** bei Regelaltersgrenze, **minus 0,003 je Monat früher** (Abschlag), **plus 0,005 je Monat später** (Zuschlag).', 'Rente 24 Monate früher: 1,0 - 24 mal 0,003 = **0,928**'],
    ['**Aktueller Rentenwert (ARW)**', 'Monatlicher **Euro-Wert eines Entgeltpunktes**. Wird jährlich zum **1. Juli** angepasst (nach Lohnentwicklung).', '**40,79 Euro** (1. Juli 2025; steigt zum 1. Juli 2026)'],
    ['**Rentenartfaktor (RAF)**', 'Gibt die **Art der Rente** an: **1,0** für Altersrente und volle Erwerbsminderungsrente, **0,55** für große Witwenrente, **0,25** für kleine Witwenrente, 0,1 für Halbwaisenrente.', 'Altersrente: **1,0**'],
  ]],
  ['ex', ['**Beispiel 1:** Eine Versicherte hat **40 Entgeltpunkte** gesammelt, geht zur **Regelaltersgrenze** (ZF 1,0) in Altersrente (RAF 1,0), ARW 40,79 Euro. **Monatsrente = 40 mal 1,0 mal 40,79 mal 1,0 = 1.631,60 Euro brutto.** (Davon gehen noch **Beiträge zur Kranken- und Pflegeversicherung** und gegebenenfalls **Steuern** ab.)', '**Beispiel 2:** Gleiche Versicherte geht **12 Monate früher** in Rente (Abschlag 12 mal 0,3 % = 3,6 %, ZF 0,964): 40 mal 0,964 mal 40,79 = **1.572,86 Euro** monatlich, **dauerhaft** weniger.', '**Beispiel 3:** Jemand verdient **jedes Jahr genau das Durchschnittsentgelt**, 45 Jahre lang: **45 EP**. Das ergibt (ARW 40,79) **1.835,55 Euro** (**Standardrente** ohne Abschläge).']],
  ['table', ['Voraussetzung', 'Regelaltersrente', 'Altersrente für langjährig Versicherte', 'Altersrente für besonders langjährig Versicherte'], [['Wartezeit (Versicherungsjahre)', '**5 Jahre**', '**35 Jahre**', '**45 Jahre**'], ['Frühester Beginn', 'Regelaltersgrenze (67)', 'Ab **63** (mit Abschlägen, 0,3 % je Monat)', 'Ab 64 bis 65 (je nach Jahrgang), **ohne Abschläge**'], ['Abschläge', 'keine', '**ja**', '**keine**']]],
  ['h', 'Weitere Renten'],
  ['kv', [
    ['Erwerbsminderungsrente', 'Wenn man **wegen Krankheit** nicht mehr arbeiten kann. **Volle**: weniger als **3 Stunden** täglich erwerbsfähig. **Teilweise**: **3 bis unter 6 Stunden**. Voraussetzung: **5 Jahre Wartezeit**, **3 Jahre Pflichtbeiträge** in den letzten 5 Jahren.'],
    ['Hinterbliebenenrente', 'Nach dem Tod eines Versicherten: **Witwen-/Witwerrente** (große: **55 %** der Rente des Verstorbenen, bei Erziehung, Alter ab 47 oder Erwerbsminderung; kleine: **25 %** für höchstens 24 Monate) und **Waisenrente** (bis 18, in Ausbildung bis 27).'],
    ['Rehabilitation', '**Reha vor Rente**: Zuerst wird versucht, die Erwerbsfähigkeit durch medizinische oder berufliche Reha zu erhalten.'],
    ['Rentenanpassung', 'Jeden **1. Juli** wird der aktuelle Rentenwert angepasst (Lohnentwicklung). Rente ist **steuerpflichtig** (nachgelagerte Besteuerung, mit steigendem Besteuerungsanteil).'],
  ]],
  ['h', 'Altersvorsorge: Drei Säulen'],
  ['table', ['Säule', 'Inhalt', 'Beispiele'], [['**1. Säule: gesetzliche Vorsorge**', 'Pflichtversicherung, Umlage', 'Gesetzliche Rentenversicherung, Beamtenpension, Versorgungswerke'], ['**2. Säule: betriebliche Altersvorsorge (bAV)**', 'Über den **Arbeitgeber**, oft **Entgeltumwandlung** (Bruttogehalt wird in Beitrag umgewandelt, steuer- und beitragsvorteilhaft). Arbeitnehmer haben **Anspruch** auf Entgeltumwandlung; Arbeitgeber zahlt **15 % Zuschuss** zu eingesparten Sozialbeiträgen', 'Direktversicherung, Pensionskasse, Pensionsfonds'], ['**3. Säule: private Vorsorge**', 'Freiwillig, individuell', 'Riester-Rente (staatlich gefördert), Basisrente (Rürup), private Rentenversicherung, ETF-Sparplan, Immobilie']]],
  ['p', 'Die gesetzliche Rente allein reicht oft **nicht**, um den gewohnten Lebensstandard zu halten (**Versorgungslücke**). Deshalb sind **Betriebsrente und private Vorsorge** wichtig. Je früher man beginnt, desto stärker wirkt der **Zinseszinseffekt**.'],
  ['h', 'Aufgaben im Prüfungsstil'],
  ['qa', 'Erklären Sie das Umlageverfahren und nennen Sie ein Problem.', 'Beim **Umlageverfahren** werden die **laufenden Beiträge** der Erwerbstätigen **sofort zur Auszahlung der Renten** verwendet (**Generationenvertrag**). Es wird kein Kapital angespart. **Problem:** der **demografische Wandel**: Immer weniger Beitragszahler müssen immer mehr Rentner finanzieren.', 4],
  ['qa', 'Berechnen Sie die Monatsrente: 35 Entgeltpunkte, Rentenbeginn zur Regelaltersgrenze, aktueller Rentenwert 40,79 Euro, Altersrente.', ['Rente = 35 mal 1,0 mal 40,79 mal 1,0 = **1.427,65 Euro** brutto pro Monat.'], 3],
  ['qa', 'Eine Arbeitnehmerin verdient 36.000 Euro im Jahr, das Durchschnittsentgelt beträgt 50.000 Euro. Wie viele Entgeltpunkte erwirbt sie in diesem Jahr?', ['EP = 36.000 / 50.000 = **0,72 Entgeltpunkte**.'], 3],
  ['qa', 'Nennen Sie die drei Säulen der Altersvorsorge mit je einem Beispiel.', ['- 1. Säule (gesetzlich): gesetzliche Rentenversicherung', '- 2. Säule (betrieblich): Direktversicherung per Entgeltumwandlung', '- 3. Säule (privat): Riester-Rente oder private Rentenversicherung'], 3],
  ['quiz', [
    {q: 'Wie wird die gesetzliche Rentenversicherung finanziert?', o: ['Im Umlageverfahren', 'Im Kapitaldeckungsverfahren', 'Durch Aktien', 'Durch Spenden'], a: 0, e: 'Beiträge der Beschäftigten finanzieren die laufenden Renten.'},
    {q: 'Was ergibt 1 Entgeltpunkt?', o: ['Ein Jahr mit Durchschnittsverdienst', 'Einen Euro Rente', 'Ein Jahr Wartezeit', 'Einen Monat Beitrag'], a: 0, e: 'EP = Jahresentgelt geteilt durch Durchschnittsentgelt.'},
    {q: 'Wie hoch ist die Wartezeit für die Regelaltersrente?', o: ['5 Jahre', '35 Jahre', '10 Jahre', '45 Jahre'], a: 0, e: 'Mindestens 5 Beitragsjahre (Wartezeit).'},
    {q: 'Was bewirkt ein früherer Rentenbeginn vor der Regelaltersgrenze?', o: ['Dauerhafter Abschlag (0,3 % je Monat)', 'Höhere Rente', 'Keine Änderung', 'Steuerfreiheit'], a: 0, e: 'Der Zugangsfaktor sinkt pro Monat um 0,003.'},
    {q: 'Welche Rentenart zahlt die Rentenversicherung bei Tod des Ehepartners?', o: ['Hinterbliebenenrente (Witwen-/Witwerrente)', 'Altersrente', 'Erwerbsminderungsrente', 'Riester-Rente'], a: 0, e: 'Hinterbliebenenrenten sichern Witwen, Witwer und Waisen.'},
  ]],
]);
