AP2.page('wiso-steuern', {
  b: 'wiso', g: 'Unternehmen und Steuern', t: 'Steuerarten: Einkommensteuer, Umsatzsteuer, Gewerbesteuer',
  d: '**Steuern** sind **Zwangsabgaben ohne direkte Gegenleistung** an den Staat (§ 3 AO). Man unterscheidet **direkte Steuern** (Steuerzahler = Steuerträger, zum Beispiel **Einkommensteuer**, **Körperschaftsteuer**, **Gewerbesteuer**) und **indirekte Steuern** (werden auf Preise aufgeschlagen, zum Beispiel **Umsatzsteuer**). Die **Einkommensteuer** ist **progressiv** (mit steigendem Einkommen steigt der Satz), die **Umsatzsteuer** beträgt **19 %** (ermäßigt **7 %**).',
  m: '**Einkommensteuer progressiv (wer mehr verdient, zahlt anteilig mehr). Umsatzsteuer 19 % / 7 %, Endverbraucher trägt sie (indirekt).** Brutto = Netto mal 1,19. Nettopreis = Brutto geteilt durch 1,19. **Zahllast = Umsatzsteuer - Vorsteuer.** Gewerbesteuer geht an die **Gemeinde**.',
  cheat: [
    ['Einkommensteuer (ESt)', ['**Progressiver** Tarif (Eingangssteuersatz **14 %**, Spitzensteuersatz **42 %**, Reichensteuer **45 %**)', '**Grundfreibetrag** (2026: **12.348 Euro**, steuerfrei)', 'Lohnsteuer = Vorauszahlung auf ESt (Steuerklassen I bis VI)', '**Soli** und **Kirchensteuer** (8 % in BW) als Zuschlag']],
    ['Umsatzsteuer (USt, MwSt)', ['**19 %** Regelsatz, **7 %** ermäßigt (Lebensmittel, Bücher, ÖPNV)', '**Indirekte Steuer**: Endverbraucher trägt sie', 'Unternehmen: **Vorsteuerabzug**, zahlt **Zahllast** ans Finanzamt', '**Kleinunternehmer** (bis 25.000 Euro Vorjahresumsatz): keine USt']],
    ['Gewerbesteuer', ['Steuer der **Gemeinde** auf den **Gewerbeertrag**', 'Steuermesszahl **3,5 %** mal **Hebesatz** der Gemeinde', '**Freibetrag 24.500 Euro** (Einzelunternehmen, Personengesellschaften)', 'Anrechnung auf die Einkommensteuer']],
    ['Weitere Steuern', ['**Körperschaftsteuer** 15 % (GmbH, AG)', '**Grundsteuer**, **Grunderwerbsteuer**, **Kfz-Steuer**', '**Erbschafts- und Schenkungsteuer**', 'Energie-, Tabak-, Alkoholsteuer (Verbrauchsteuern)']],
  ],
  blocks: [
    ['h', 'Wozu Steuern?'],
    ['p', 'Der Staat braucht Geld für **Schulen, Straßen, Polizei, Sozialleistungen**. Er finanziert sich hauptsächlich durch **Steuern**. Anders als Gebühren (Gegenleistung, zum Beispiel Passgebühr) und Beiträge (Sozialversicherung) gibt es bei Steuern **keinen direkten Gegenanspruch**. Ihre Höhe richtet sich nach der **wirtschaftlichen Leistungsfähigkeit**.'],
    ['table', ['Einteilung', 'Arten', 'Beispiele'], [['**Direkte Steuern**', 'Steuerschuldner und -träger sind **dieselbe Person**', 'Einkommensteuer, Lohnsteuer, Körperschaftsteuer, Gewerbesteuer, Erbschaftsteuer'], ['**Indirekte Steuern**', 'Steuerschuldner (Unternehmen) **wälzt** die Steuer auf den Preis ab, der **Verbraucher trägt** sie', 'Umsatzsteuer, Tabaksteuer, Energiesteuer, Biersteuer'], ['**Besitzsteuern**', 'Auf Einkommen und Vermögen', 'ESt, KSt, Grundsteuer, Erbschaftsteuer'], ['**Verkehrsteuern**', 'Auf Rechtsvorgänge', 'Umsatzsteuer, Grunderwerbsteuer, Kfz-Steuer'], ['**Verbrauchsteuern**', 'Auf den Verbrauch bestimmter Güter', 'Energie-, Tabak-, Alkoholsteuer']]],
    ['kv', [
      ['Steuerhoheit', 'Wer bekommt die Einnahmen? **Gemeinschaftsteuern** (ESt, KSt, USt) werden zwischen **Bund, Ländern und Gemeinden** aufgeteilt. **Bundessteuern** (Energiesteuer), **Ländersteuern** (Erbschaft-, Kfz-Steuer), **Gemeindesteuern** (**Gewerbesteuer**, Grundsteuer).'],
      ['Finanzamt', 'Zuständige Behörde der Länder. Jeder Bürger hat eine lebenslange **Steuer-Identifikationsnummer (Steuer-ID)**. **Steuererklärung** jährlich (bei Arbeitnehmern meist freiwillig, **Pflicht** zum Beispiel bei Nebeneinkünften oder Steuerklassen III/V).'],
    ]],
    ['h', 'Einkommensteuer (ESt)'],
    ['p', 'Die **Einkommensteuer** erfasst das **Einkommen natürlicher Personen**. Es gibt **sieben Einkunftsarten**: **Land- und Forstwirtschaft, Gewerbebetrieb, selbstständige Arbeit, nichtselbstständige Arbeit** (Gehalt), **Kapitalvermögen**, **Vermietung und Verpachtung**, **sonstige Einkünfte** (zum Beispiel Renten). Vom Einkommen werden **Werbungskosten** und **Sonderausgaben** abgezogen. Übrig bleibt das **zu versteuernde Einkommen (zvE)**.'],
    ['diagram', {w: 760, h: 300, keep: 560, cap: 'Verlauf des Einkommensteuertarifs (vereinfacht, Prinzip): Der durchschnittliche Steuersatz steigt stetig, der Grenzsteuersatz in Stufen bis 42 beziehungsweise 45 Prozent.', nodes: [
      {id: 'g', k: 'text', x: 110, y: 250, t: 'Grundfreibetrag: 0 %', fs: 12, tc: 'text2', b: true}, {id: 'e', k: 'text', x: 240, y: 160, t: 'Eingangssteuersatz 14 %', fs: 12, tc: 'accent', b: true}, {id: 's', k: 'text', x: 450, y: 70, t: 'Spitzensteuersatz 42 %', fs: 12, tc: 'accent', b: true}, {id: 'r', k: 'text', x: 640, y: 42, t: 'Reichensteuer 45 %', fs: 12, tc: 'bad', b: true}, {id: 'x', k: 'text', x: 720, y: 285, t: 'zu versteuerndes Einkommen', fs: 11, tc: 'text2'}, {id: 'y', k: 'text', x: 50, y: 12, t: 'Grenzsteuersatz', fs: 11, tc: 'text2'},
    ], edges: [{a: [50, 270], b: [750, 270], ea: 'arrow', s: 'text'}, {a: [50, 270], b: [50, 24], ea: 'arrow', s: 'text'}, {a: [50, 262], b: [170, 262], ea: 'none', s: 'ok', w: 3}, {a: [170, 262], b: [420, 100], ea: 'none', s: 'accent', w: 3, sm: false}, {a: [420, 100], b: [660, 100], ea: 'none', s: 'accent', w: 3}, {a: [660, 100], b: [660, 70], ea: 'none', s: 'bad', w: 3}, {a: [660, 70], b: [740, 70], ea: 'none', s: 'bad', w: 3}]}],
    ['kv', [
      ['Progression', 'Steigt das Einkommen, steigt der **Steuersatz** (nicht nur der Betrag). Das entspricht der **Leistungsfähigkeit**: Wer mehr hat, trägt anteilig mehr.'],
      ['Grenzsteuersatz und Durchschnittssteuersatz', '**Grenzsteuersatz:** Steuer auf den **nächsten** verdienten Euro. **Durchschnittssteuersatz:** Gesamtsteuer geteilt durch das gesamte zu versteuernde Einkommen. **Immer niedriger** als der Grenzsteuersatz.'],
      ['Tarif (Stand 2026, Details prüfen)', '**Grundfreibetrag 12.348 Euro**; danach Zone mit steigendem Satz von **14 %** bis **42 %**; Spitzensteuersatz **42 %** ab etwa 70.000 Euro zvE; **Reichensteuer 45 %** ab etwa 278.000 Euro zvE.'],
      ['Zuschläge', '**Solidaritätszuschlag 5,5 %** der Einkommensteuer (seit 2021 nur noch für Besserverdiener); **Kirchensteuer** 8 % (Baden-Württemberg, Bayern) oder 9 % (übrige Länder) der Einkommensteuer.'],
      ['Steuerklassen (Arbeitnehmer)', '**I:** Ledige. **II:** Alleinerziehende. **III/V:** Verheiratete (III: höheres Einkommen, V: niedrigeres). **IV:** Verheiratete mit ähnlichem Einkommen. **VI:** zweites Arbeitsverhältnis. Die Klasse bestimmt die **monatliche Lohnsteuer**; die tatsächliche Steuer ergibt sich in der **Steuererklärung**.'],
    ]],
  ],
});
