AP2.add('wiso-sv', [
  ['h', 'Beispielrechnung: Sozialabgaben eines Angestellten'],
  ['ex', ['**Gegeben:** Monatsbrutto **3.200 Euro**, Arbeitnehmer **mit Kind** (Pflegeversicherung AN 1,8 %), Zusatzbeitrag der Krankenkasse 2,9 %.', '**Rentenversicherung (AN):** 3.200 mal 9,3 % = **297,60 Euro**', '**Arbeitslosenversicherung (AN):** 3.200 mal 1,3 % = **41,60 Euro**', '**Krankenversicherung (AN):** 3.200 mal (7,3 % + 1,45 %) = 3.200 mal 8,75 % = **280,00 Euro**', '**Pflegeversicherung (AN):** 3.200 mal 1,8 % = **57,60 Euro**', '**Summe Arbeitnehmeranteil** = 297,60 + 41,60 + 280,00 + 57,60 = **676,80 Euro** (das sind **21,15 Prozent** des Bruttos).', '**Arbeitgeberanteil** ist ebenso hoch, **676,80 Euro** (bei gleichem Satz), dazu **Unfallversicherung** und Umlagen. Die **Gesamtkosten** des Arbeitgebers betragen daher etwa 3.200 + 676,80 + UV = **über 3.876,80 Euro**.']],
  ['kv', [
    ['Beitragsbemessungsgrenze', 'Nur das Einkommen **bis zu dieser Grenze** wird verbeitragt. Wer mehr verdient, zahlt für den **übersteigenden Teil** keine Beiträge. Daher steigen die Abgaben nicht endlos. (RV/ALV 2026: 8.450 Euro pro Monat; KV/PV: 5.812,50 Euro pro Monat.)'],
    ['Versicherungspflichtgrenze (Jahresarbeitsentgeltgrenze)', 'Wer **mehr als 77.400 Euro** (2026) im Jahr verdient, ist in der **gesetzlichen KV nicht mehr versicherungspflichtig** und kann in die **private KV** wechseln (oder freiwillig gesetzlich bleiben).'],
    ['Minijob (geringfügige Beschäftigung)', 'Verdienst bis **603 Euro monatlich** (2026, 13,90 Euro Mindestlohn mal 130 geteilt durch 3). Pauschalabgaben des **Arbeitgebers** (ca. 28-31 %), der Arbeitnehmer zahlt nur **Rentenversicherung** (3,6 %, befreiungsfähig), **keine** Lohnsteuer in der Regel (Pauschalsteuer 2 %).'],
    ['Midijob (Übergangsbereich)', 'Verdienst von **603,01 bis 2.000 Euro**: Der Arbeitnehmer zahlt **gleitend** steigende Sozialbeiträge, Rentenansprüche aus dem vollen Entgelt.'],
    ['Azubis', 'Auch Azubis sind **sozialversicherungspflichtig**. Bei Vergütung **bis 325 Euro** monatlich zahlt der Arbeitgeber **allein** die Beiträge. Höhere Vergütung: wie üblich je Hälfte.'],
    ['Einzug der Beiträge', 'Der **Arbeitgeber** berechnet und überweist den **Gesamtsozialversicherungsbeitrag** an die **Krankenkasse** (Einzugsstelle), die ihn verteilt. Der Arbeitnehmeranteil wird vom Lohn **einbehalten**.'],
  ]],
  ['h', 'Wichtige Prinzipien'],
  ['table', ['Prinzip', 'Bedeutung', 'Beispiel'], [
    ['**Solidarprinzip**', 'Beitrag nach **Leistungsfähigkeit** (Einkommen), Leistung nach **Bedarf**. Starke helfen Schwachen, Gesunde helfen Kranken.', 'Alle zahlen 14,6 % des Einkommens, jeder bekommt dieselbe Behandlung'],
    ['**Äquivalenzprinzip**', 'Leistung **nach Beitrag**. Gilt vor allem in der **Rentenversicherung** (höhere Beiträge, höhere Rente) und beim Arbeitslosengeld.', 'Wer länger und mehr einzahlt, bekommt mehr Rente'],
    ['**Umlageverfahren**', 'Aktuelle Beiträge **finanzieren sofort die laufenden Leistungen**, es wird (fast) nichts angespart. **Generationenvertrag.**', 'Rentenversicherung'],
    ['**Kapitaldeckungsverfahren**', 'Beiträge werden **angespart und verzinst**, später daraus Leistungen. Gilt bei **Riester** und der **privaten KV** (Altersrückstellungen).', 'Private Altersvorsorge'],
    ['**Sachleistungsprinzip**', 'Der Versicherte erhält die **Behandlung direkt**, die Kasse rechnet mit dem Arzt ab (GKV).', 'Krankenversichertenkarte beim Arzt'],
    ['**Selbstverwaltung**', 'Versicherte und Arbeitgeber verwalten die Träger **selbst** (Verwaltungsrat, Sozialwahlen).', 'Wahl der Vertreterversammlung'],
    ['**Subsidiarität**', 'Der Staat hilft, wenn Eigenhilfe nicht reicht.', 'Bürgergeld/Sozialhilfe als letztes Netz'],
  ]],
  ['h', 'Das soziale Netz im Überblick'],
  ['table', ['Ebene', 'Beispiele'], [['**Versicherung** (Beitrag, Anspruch)', 'Sozialversicherung (die fünf Zweige)'], ['**Versorgung** (Steuerfinanziert, besondere Leistung)', 'Beamtenversorgung, Kriegsopferversorgung, Elterngeld, Kindergeld, BAföG'], ['**Fürsorge** (Bedürftigkeit)', 'Bürgergeld, Sozialhilfe, Wohngeld, Grundsicherung im Alter']]],
  ['h', 'Aufgaben im Prüfungsstil'],
  ['qa', 'Nennen Sie die fünf Zweige der Sozialversicherung und deren Träger.', ['- Krankenversicherung: Krankenkassen', '- Rentenversicherung: Deutsche Rentenversicherung', '- Arbeitslosenversicherung: Bundesagentur für Arbeit', '- Pflegeversicherung: Pflegekassen (bei den Krankenkassen)', '- Unfallversicherung: Berufsgenossenschaften / Unfallkassen'], 5],
  ['qa', 'Berechnen Sie den Arbeitnehmeranteil zur Sozialversicherung bei 2.500 Euro Brutto mit folgenden Sätzen: RV 9,3 %, ALV 1,3 %, KV 8,75 %, PV 1,8 %.', ['RV: 2.500 mal 0,093 = **232,50 Euro**; ALV: 2.500 mal 0,013 = **32,50 Euro**; KV: 2.500 mal 0,0875 = **218,75 Euro**; PV: 2.500 mal 0,018 = **45,00 Euro**.', 'Summe: **528,75 Euro** (21,15 %).'], 6],
  ['qa', 'Welche Sozialversicherung wird allein vom Arbeitgeber finanziert und warum?', 'Die **gesetzliche Unfallversicherung**. Der Arbeitgeber trägt das **Risiko von Arbeitsunfällen** (Haftungsprivileg: Er haftet dafür im Gegenzug nicht persönlich gegenüber dem Beschäftigten), und die Beiträge richten sich nach seiner Lohnsumme und der **Gefahrklasse** seiner Branche.', 4],
  ['qa', 'Erklären Sie das Solidarprinzip an einem Beispiel.', 'Beim Solidarprinzip zahlt jeder einen **einkommensabhängigen Beitrag**, die Leistung hängt vom **Bedarf** ab. Beispiel Krankenversicherung: Ein gut verdienender Versicherter zahlt mehr Beitrag als eine Geringverdienerin, beide erhalten bei Krankheit dieselbe Behandlung; Familienmitglieder ohne Einkommen sind beitragsfrei mitversichert.', 4],
  ['quiz', [
    {q: 'Welche Versicherung zahlt allein der Arbeitgeber?', o: ['Unfallversicherung', 'Rentenversicherung', 'Krankenversicherung', 'Arbeitslosenversicherung'], a: 0, e: 'Die Beiträge zur gesetzlichen Unfallversicherung zahlt nur der Arbeitgeber.'},
    {q: 'Wie wird die Rentenversicherung finanziert?', o: ['Im Umlageverfahren', 'Im Kapitaldeckungsverfahren', 'Durch Spenden', 'Durch Kredite'], a: 0, e: 'Aktuelle Beiträge finanzieren aktuelle Renten (Generationenvertrag).'},
    {q: 'Was ist die Beitragsbemessungsgrenze?', o: ['Einkommensgrenze, bis zu der Beiträge erhoben werden', 'Mindestlohn', 'Höchstalter für Beiträge', 'Steuerfreibetrag'], a: 0, e: 'Einkommen über der Grenze bleibt beitragsfrei.'},
    {q: 'Welches Prinzip beschreibt "Beitrag nach Einkommen, Leistung nach Bedarf"?', o: ['Solidarprinzip', 'Äquivalenzprinzip', 'Kapitaldeckung', 'Selbstverschuldensprinzip'], a: 0, e: 'Solidarität zwischen Gesunden und Kranken, Jungen und Alten, Gut- und Geringverdienern.'},
    {q: 'Wer zieht die Sozialversicherungsbeiträge ein?', o: ['Die Krankenkasse als Einzugsstelle (Arbeitgeber führt ab)', 'Das Finanzamt', 'Die IHK', 'Der Betriebsrat'], a: 0, e: 'Der Gesamtsozialversicherungsbeitrag geht an die Einzugsstelle (Krankenkasse).'},
  ]],
]);
