AP2.add('wiso-unternehmen', [
  ['h', 'Weitere Formen'],
  ['kv', [
    ['GmbH & Co. KG', 'Eine **KG**, deren **Komplementär eine GmbH** ist. So haftet **niemand persönlich unbeschränkt**, aber es gelten **steuerliche Vorteile** der Personengesellschaft. Häufig bei Familienunternehmen.'],
    ['eG (eingetragene Genossenschaft)', 'Zusammenschluss von **Mitgliedern** zur **Förderung der Mitglieder** (Raiffeisenbank, Volksbank, Wohnungsbaugenossenschaft). **Jedes Mitglied hat eine Stimme**, unabhängig vom Anteil (**Kopfprinzip**). Haftung auf Geschäftsanteil.'],
    ['KGaA / SE', '**KGaA:** Kommanditgesellschaft auf Aktien (Mischform). **SE:** **Societas Europaea**, europäische Aktiengesellschaft.'],
    ['Eingetragener Verein (e. V.)', 'Für **nichtwirtschaftliche** Zwecke (Sport, Kultur). Mitglieder, Vorstand.'],
    ['Stille Gesellschaft, Partnergesellschaft (PartG)', 'Beteiligung ohne Außenauftreten, Zusammenschluss **Freiberufler** (Anwälte, Ärzte, Architekten).'],
  ]],
  ['h', 'Vergleich der wichtigsten Formen'],
  ['table', ['Kriterium', 'Einzelunternehmen', 'GbR / OHG', 'GmbH', 'AG'], [
    ['**Haftung**', 'unbeschränkt', 'unbeschränkt, solidarisch', '**beschränkt** auf Gesellschaftsvermögen', '**beschränkt**'],
    ['**Mindestkapital**', 'keines', 'keines', '25.000 Euro', '50.000 Euro'],
    ['**Gründungsaufwand**', 'gering', 'gering (GbR), mittel (OHG)', 'mittel: notariell, Handelsregister', 'hoch: Satzung, Gründungsprüfung'],
    ['**Leitung**', 'Inhaber', 'Gesellschafter', 'Geschäftsführer', 'Vorstand (vom Aufsichtsrat überwacht)'],
    ['**Steuern**', 'Einkommensteuer (+ Gewerbesteuer)', 'Einkommensteuer der Gesellschafter (+ Gewerbesteuer)', '**Körperschaftsteuer** 15 % + Soli + Gewerbesteuer (zusammen ca. 30 %)', 'Körperschaftsteuer wie GmbH'],
    ['**Kapitalbeschaffung**', 'Eigenkapital des Inhabers, Kredit', 'Einlagen der Gesellschafter, Kredit', 'Einlagen, Kredit, Gesellschafterdarlehen', '**Aktien über die Börse**'],
    ['**Publizität**', 'gering', 'gering', 'Jahresabschluss veröffentlichen', 'hoch'],
    ['**Beispiele**', 'Friseur, Freelancer, Einzelhändler', 'Praxisgemeinschaft, Handwerksbetrieb (OHG)', 'Softwarehaus, Mittelständler', 'SAP SE, Siemens AG'],
  ]],
  ['h', 'Von der Idee zum Unternehmen'],
  ['steps', ['**Geschäftsidee und Businessplan** (Markt, Finanzierung, Risiken).', '**Rechtsform wählen** (Haftung, Kapital, Steuern, Mitbestimmung).', '**Gesellschaftsvertrag** (bei Gesellschaften), **Notar** (GmbH, AG), **Handelsregister** (Pflicht für Kaufleute und Kapitalgesellschaften).', '**Gewerbeanmeldung** beim Ordnungsamt/Gewerbeamt der Gemeinde (Kosten ca. 20 bis 60 Euro). Freiberufler (zum Beispiel Software-Freelancer, wenn Katalogberuf/ähnlich) melden sich beim **Finanzamt**.', '**Anmeldung beim Finanzamt** (Fragebogen zur steuerlichen Erfassung), **IHK-Mitgliedschaft**, **Berufsgenossenschaft**, ggf. Krankenkasse/Sozialversicherung für Mitarbeiter.']],
  ['h', 'Kaufmann, Handelsregister und Firma'],
  ['kv', [
    ['Kaufmann (HGB)', 'Wer ein **Handelsgewerbe** betreibt, also ein Gewerbe, das nach Art und Umfang einen **in kaufmännischer Weise eingerichteten Geschäftsbetrieb** erfordert (**Istkaufmann**). **Kannkaufmann** durch freiwillige Eintragung. **Formkaufmann** sind GmbH, AG (kraft Rechtsform).'],
    ['Handelsregister', '**Öffentliches Verzeichnis** beim Amtsgericht (Abteilung A: Einzelunternehmen/Personengesellschaften, **Abteilung B**: Kapitalgesellschaften). Enthält Firma, Sitz, Inhaber/Geschäftsführer, Vertretungsbefugnis. Jeder kann einsehen. **Öffentlicher Glaube.**'],
    ['Firma', 'Der **Name**, unter dem ein Kaufmann sein Geschäft betreibt, mit **Rechtsformzusatz** (e. K., OHG, GmbH, AG).'],
    ['Prokura', 'Umfassende **Vollmacht** für alle gewöhnlichen Geschäfte (nicht Grundstücksverkauf), ins Handelsregister eingetragen. **Handlungsvollmacht** ist enger.'],
  ]],
  ['h', 'Aufgaben im Prüfungsstil'],
  ['qa', 'Erklären Sie den Unterschied zwischen einer Personengesellschaft und einer Kapitalgesellschaft bezüglich der Haftung.', 'Bei **Personengesellschaften** (GbR, OHG, Einzelunternehmen) haften die Gesellschafter **persönlich und unbeschränkt** mit ihrem gesamten Privatvermögen (Ausnahme: Kommanditist nur bis zur Einlage). Bei **Kapitalgesellschaften** (GmbH, AG) haftet **nur das Gesellschaftsvermögen**, die Gesellschafter riskieren nur ihre **Einlage**.', 4],
  ['qa', 'Drei Informatiker wollen ein Softwareunternehmen gründen und ihr Privatvermögen schützen. Welche Rechtsform empfehlen Sie? Nennen Sie das Mindestkapital.', 'Eine **GmbH** (alternativ eine **UG (haftungsbeschränkt)** bei wenig Startkapital). Die **Haftung ist auf das Gesellschaftsvermögen beschränkt**. Das **Stammkapital** der GmbH beträgt mindestens **25.000 Euro** (bei Gründung mindestens 12.500 Euro einzuzahlen), bei der UG ab **1 Euro**. Für die Gründung ist ein **notarieller Gesellschaftsvertrag** und die Eintragung ins Handelsregister nötig.', 5],
  ['qa', 'Nennen Sie die Organe einer Aktiengesellschaft und deren Aufgabe.', ['- **Vorstand:** leitet die Gesellschaft in eigener Verantwortung, vertritt sie nach außen.', '- **Aufsichtsrat:** überwacht den Vorstand, bestellt und beruft ihn ab.', '- **Hauptversammlung:** Versammlung der Aktionäre, beschließt zum Beispiel über Gewinnverwendung, Satzungsänderungen, wählt Aufsichtsratsmitglieder.'], 6],
  ['qa', 'Was unterscheidet Komplementär und Kommanditist bei der KG?', 'Der **Komplementär** haftet **unbeschränkt persönlich** und **führt die Geschäfte**. Der **Kommanditist** haftet nur **bis zur Höhe seiner Einlage**, ist von der **Geschäftsführung ausgeschlossen** und hat Kontrollrechte.', 4],
  ['quiz', [
    {q: 'Wie hoch ist das gesetzliche Mindest-Stammkapital einer GmbH?', o: ['25.000 Euro', '50.000 Euro', '1 Euro', '10.000 Euro'], a: 0, e: 'GmbH: 25.000 Euro. AG: 50.000 Euro. UG: ab 1 Euro.'},
    {q: 'Welche Rechtsform haftet nur mit dem Gesellschaftsvermögen?', o: ['GmbH', 'OHG', 'GbR', 'Einzelunternehmen'], a: 0, e: 'Kapitalgesellschaften haften beschränkt.'},
    {q: 'Wer leitet eine Aktiengesellschaft?', o: ['Der Vorstand', 'Der Aufsichtsrat', 'Die Hauptversammlung', 'Der Betriebsrat'], a: 0, e: 'Der Aufsichtsrat überwacht den Vorstand.'},
    {q: 'Wie haften die Gesellschafter einer OHG?', o: ['Unbeschränkt und solidarisch', 'Nur mit der Einlage', 'Gar nicht', 'Nur mit 25.000 Euro'], a: 0, e: 'Alle Gesellschafter haften persönlich mit dem gesamten Vermögen.'},
    {q: 'Wo werden Kapitalgesellschaften eingetragen?', o: ['Handelsregister (Abteilung B)', 'Melderegister', 'Vereinsregister', 'Gewerbezentralregister'], a: 0, e: 'Handelsregister beim Amtsgericht.'},
  ]],
]);
