AP2.page('wiso-wahlen', {
  b: 'wiso', g: 'Staat und Gesellschaft', t: 'Demokratie, Wahlen und politische Beteiligung',
  d: 'In der Demokratie geht **alle Staatsgewalt vom Volke aus** (Art. 20 GG). Das Volk übt sie vor allem durch **Wahlen** aus. Damit Wahlen demokratisch sind, müssen sie nach **Art. 38 Abs. 1 GG** **allgemein, unmittelbar, frei, gleich und geheim** sein. Der Bundestag wird alle vier Jahre nach einer **personalisierten Verhältniswahl** mit **Erst- und Zweitstimme** gewählt. Neben Wahlen gibt es viele weitere Formen der **politischen Beteiligung**: Parteien, Bürgerinitiativen, Petitionen, Demonstrationen, Bürger- und Volksbegehren, Jugendgemeinderäte und soziale Medien.',
  m: '**Wahlrechtsgrundsätze "a-u-f-g-g": allgemein, unmittelbar, frei, gleich, geheim.** **Aktives Wahlrecht = wählen dürfen, passives = gewählt werden dürfen.** **Erststimme = Person im Wahlkreis, Zweitstimme = Partei (entscheidet über die Sitzverteilung).** **5-%-Hürde** (oder Grundmandatsklausel).',
  cheat: [
    ['Wahlrechtsgrundsätze', ['**allgemein**: alle Staatsbürger ab Mindestalter', '**unmittelbar**: direkt, ohne Wahlmänner', '**frei**: ohne Zwang und Druck', '**gleich**: jede Stimme zählt gleich; **geheim**: niemand sieht die Wahl']],
    ['Wahlalter', ['Bundestag: 18 (aktiv und passiv)', 'Europawahl: 16 (seit 2024)', 'Kommunalwahl BW: 16', 'Landtagswahl BW: 16 (seit 2026)']],
    ['Beteiligung', ['Partei, Jugendorganisation', 'Bürgerinitiative, Verband', 'Petition, Demonstration', 'Bürger-/Volksbegehren, Jugendgemeinderat']],
    ['Bundestagswahl', ['Erststimme: Wahlkreiskandidat', 'Zweitstimme: Landesliste', '5-%-Hürde', 'alle 4 Jahre']],
  ],
  blocks: [
    ['h', 'Die fünf Wahlrechtsgrundsätze (Gemeinschaftskunde Winter 2022/23)'],
    ['table', ['Grundsatz', 'Bedeutung', 'Verstoß wäre zum Beispiel'], [
      ['**allgemein**', 'Grundsätzlich alle Staatsbürgerinnen und -bürger dürfen wählen und gewählt werden, unabhängig von Geschlecht, Einkommen, Bildung, Religion. Ein **Mindestalter** ist zulässig.', 'Wahlrecht nur für Steuerzahler oder Männer'],
      ['**unmittelbar**', 'Die Wähler entscheiden **direkt** über die Abgeordneten, ohne dass Wahlmänner oder -frauen dazwischengeschaltet sind.', 'Wahlmännergremium wie bei der US-Präsidentenwahl'],
      ['**frei**', 'Die Entscheidung wird **ohne Zwang** oder unzulässige Beeinflussung getroffen; es gibt keine Wahlpflicht.', 'Arbeitgeber droht mit Kündigung, wenn man Partei X wählt'],
      ['**gleich**', 'Jeder hat **gleich viele Stimmen**, jede Stimme hat **gleiches Gewicht** und gleichen Einfluss auf die Sitzverteilung.', 'Stimmen von Reichen zählen doppelt (Dreiklassenwahlrecht)'],
      ['**geheim**', 'Niemand kann nachvollziehen, **wie** jemand gewählt hat (Wahlkabine, Urne).', 'Offene Stimmabgabe per Handzeichen'],
    ]],
    ['h', 'Wie wird der Bundestag gewählt?'],
    ['list', [
      '**Erststimme:** Wahl einer Kandidatin oder eines Kandidaten im **Wahlkreis** (299 Wahlkreise). Seit der Wahlrechtsreform 2023 erhält ein Wahlkreissieger das Mandat nur, wenn es durch das Zweitstimmenergebnis seiner Partei **gedeckt** ist.',
      '**Zweitstimme:** Wahl einer **Partei** (Landesliste). Sie entscheidet über die **Sitzverteilung** im Bundestag (630 Sitze) und ist damit die wichtigere Stimme.',
      '**Sperrklausel:** Parteien brauchen mindestens **5 %** der Zweitstimmen (oder drei Direktmandate, Grundmandatsklausel), um in den Bundestag einzuziehen. Ziel: Zersplitterung des Parlaments verhindern.',
    ]],
    ['h', 'Beteiligung jenseits der Wahl (Winter 2022/23, Sommer 2023)'],
    ['table', ['Form', 'Beschreibung', 'Ab welchem Alter?'], [
      ['**Partei / Jugendorganisation**', 'Mitglied werden, Programme mitgestalten, Kandidaten aufstellen (Junge Union, Jusos, Grüne Jugend, Junge Liberale, ...)', 'Meist ab 14 bis 16'],
      ['**Bürgerinitiative**', 'Zusammenschluss von Bürgern zu einem **konkreten Anliegen** (Spielplatz, gegen Mülldeponie, Radweg), Protestaktionen, Unterschriften', 'Jedes Alter'],
      ['**Petition**', 'Bitte oder Beschwerde an Parlament oder Behörde (Art. 17 GG), auch als Online-Petition beim Bundestag', 'Jedes Alter'],
      ['**Demonstration**', 'Öffentliche Versammlung für ein Anliegen (Art. 8 GG Versammlungsfreiheit), Anmeldung bei der Behörde', 'Jedes Alter'],
      ['**Bürgerbegehren / Bürgerentscheid** (Gemeinde), **Volksbegehren / Volksentscheid** (Land)', 'Bürger beantragen mit Unterschriften eine Abstimmung über eine Sachfrage und entscheiden direkt (direkte Demokratie)', 'In BW auf kommunaler Ebene ab 16'],
      ['**Jugendgemeinderat**', 'Gewählte Vertretung der Jugendlichen in der Gemeinde mit Antrags- und Rederecht im Gemeinderat (§ 41a GemO BW)', 'Meist 14 bis 21'],
      ['**Kontakt zu Abgeordneten, soziale Medien, Interessenverbände**', 'Briefe, Bürgersprechstunden, Kampagnen, Gewerkschaftsjugend', 'Jedes Alter'],
    ]],
    ['h', 'Wählen ab 16? Pro und Contra (Winter 2022/23, 6 Punkte)'],
    ['procon', 'Wahlalter 16 bei Bundestagswahlen', ['Junge Menschen sind von langfristigen Entscheidungen (Klima, Rente, Bildung, Schulden) am längsten betroffen', 'Früh ernst genommen werden steigert das politische Interesse und die spätere Wahlbeteiligung', 'Gleicht das Übergewicht älterer Wähler durch den demografischen Wandel etwas aus', 'Mit 16 trägt man schon Verantwortung (Ausbildung, Steuern auf Ausbildungsvergütung); bei Europa- und Kommunalwahlen klappt es bereits'], ['Fehlende Reife und Lebenserfahrung, Entscheidungen leichter beeinflussbar', 'Widerspruch zur Volljährigkeit (Vertragsfähigkeit, Strafmündigkeit nach Erwachsenenrecht)', 'Gefahr, dass populistische oder extreme Parteien profitieren (durch Studien nicht eindeutig belegt)', 'Für die Änderung von Art. 38 GG ist eine Zweidrittelmehrheit nötig']],
    ['h', 'Wahlpflicht? Pro und Contra (Sommer 2023, 6 Punkte)'],
    ['procon', 'Einführung einer Wahlpflicht', ['Hohe Wahlbeteiligung macht das Ergebnis repräsentativer ("Herrschaft des Volkes")', 'Zwingt zur Auseinandersetzung mit Politik, kann Interesse wecken', 'Gibt es in Belgien, Luxemburg, Australien'], ['Verstoß gegen den Grundsatz der **freien** Wahl (auch Nicht-Wählen ist eine Entscheidung)', 'Uninformierte wählen eventuell beliebig oder populistisch', 'Kontrolle und Sanktionen sind aufwendig und teuer', 'Bekämpft nicht die Ursachen der Politikverdrossenheit']],
    ['h', 'Aufgaben im Prüfungsstil (ganze Sätze!)'],
    ['qa', 'Erklären Sie zwei Voraussetzungen für demokratische Wahlen.', ['Demokratische Wahlen müssen die Wahlrechtsgrundsätze aus Art. 38 Abs. 1 GG einhalten. Zum Beispiel muss die Wahl **geheim** sein: Jeder wählt in der Wahlkabine, sodass niemand nachvollziehen kann, wie er gewählt hat. Dadurch muss niemand Nachteile durch seine Wahlentscheidung fürchten.', 'Außerdem muss die Wahl **gleich** sein: Jede Wählerin und jeder Wähler hat gleich viele Stimmen, und jede Stimme hat das gleiche Gewicht für die Sitzverteilung im Parlament.'], 4],
    ['qa', 'Stellen Sie zwei Möglichkeiten dar, wie man auch unter 18 Jahren Einfluss auf die Politik nehmen kann.', ['Man kann sich in der **Jugendorganisation einer Partei** engagieren und dort an Programmen und Kampagnen mitarbeiten.', 'Man kann sich einer **Bürgerinitiative** anschließen oder eine **(Online-)Petition** starten bzw. unterschreiben, um Politiker auf ein Problem aufmerksam zu machen, zum Beispiel fehlende Freizeitangebote für Jugendliche. In Baden-Württemberg darf man außerdem ab 16 an Kommunal- und Europawahlen teilnehmen.'], 4],
    ['quiz', [
      {q: 'Welcher Wahlrechtsgrundsatz verbietet Wahlmänner zwischen Wähler und Abgeordnetem?', o: ['unmittelbar', 'allgemein', 'frei', 'geheim'], a: 0, e: 'Direkte Wahl.'},
      {q: 'Welche Stimme entscheidet über die Sitzverteilung im Bundestag?', o: ['Zweitstimme', 'Erststimme', 'Beide gleich', 'Keine'], a: 0, e: 'Sie wird für die Landesliste der Partei abgegeben.'},
      {q: 'In welchem Artikel des Grundgesetzes stehen die Wahlrechtsgrundsätze?', o: ['Art. 38', 'Art. 1', 'Art. 20', 'Art. 9'], a: 0, e: 'Art. 20: Staatsprinzipien, Art. 9: Koalitionsfreiheit.'},
      {q: 'Was ist das passive Wahlrecht?', o: ['Das Recht, gewählt zu werden', 'Das Recht zu wählen', 'Briefwahl', 'Nichtwählen'], a: 0, e: 'Aktiv = wählen.'},
      {q: 'Welche Hürde muss eine Partei für den Bundestag in der Regel überspringen?', o: ['5 % der Zweitstimmen', '10 % der Erststimmen', '3 %', '50 %'], a: 0, e: 'Oder drei Direktmandate.'},
    ]],
    ['see', ['wiso-staat', 'wiso-demografie', 'wiso-eu', 'wiso-methoden']],
  ],
});
