AP2.add('infra-cia', [
  ['h', 'Risiko und Risikobehandlung'],
  ['p', 'Absolute Sicherheit gibt es nicht. Man bewertet **Risiken** und entscheidet, wie viel Aufwand sich lohnt. Das Risiko berechnet sich als **Risiko = Eintrittswahrscheinlichkeit mal Schadenshöhe**.'],
  ['table', ['Behandlungsart', 'Bedeutung', 'Beispiel'], [
    ['**Vermeiden**', 'Die riskante Tätigkeit nicht ausführen', 'Keine Kundendaten in der Cloud speichern'],
    ['**Vermindern**', 'Maßnahmen senken Wahrscheinlichkeit oder Schaden', 'Verschlüsselung, Patchen, Firewall, Schulung'],
    ['**Übertragen**', 'Risiko auf Dritte verlagern', 'Cyber-Versicherung, Outsourcing mit Vertrag'],
    ['**Akzeptieren**', 'Risiko bewusst tragen (Restrisiko)', 'Seltener Ausfall eines unwichtigen Systems wird hingenommen'],
  ]],
  ['table', ['Eintrittswahrscheinlichkeit / Schaden', 'gering', 'mittel', 'hoch'], [['hoch', 'mittel', 'hoch', 'sehr hoch'], ['mittel', 'gering', 'mittel', 'hoch'], ['gering', 'gering', 'gering', 'mittel']], {first: true}],
  ['h', 'Wichtige Prinzipien'],
  ['kv', [
    ['Least Privilege (minimale Rechte)', 'Jeder bekommt nur die Rechte, die er für seine Aufgabe **unbedingt braucht**.'],
    ['Need-to-know', 'Informationen nur an Personen, die sie **für die Aufgabe benötigen**.'],
    ['Defense in Depth (gestaffelte Verteidigung)', 'Mehrere Schutzschichten hintereinander (Firewall, Segmentierung, Virenschutz, Zugriffskontrolle, Verschlüsselung). Fällt eine, hält die nächste.'],
    ['Vier-Augen-Prinzip / Funktionstrennung', 'Kritische Aktionen brauchen zwei Personen; Entwicklung und Betrieb sind getrennt.'],
    ['Security by Design', 'Sicherheit von Anfang an in die Software einplanen, nicht nachträglich anflicken.'],
  ]],
  ['h', 'Authentifizierung und Passwörter'],
  ['p', 'Man kann sich mit drei Arten von Faktoren ausweisen: **Wissen** (Passwort, PIN), **Besitz** (Smartphone, Token, Chipkarte) und **Sein** (Fingerabdruck, Gesicht). **Mehr-Faktor-Authentifizierung (MFA)** kombiniert **mindestens zwei verschiedene** Arten und erhöht die Sicherheit stark: Ein gestohlenes Passwort allein reicht dann nicht.'],
  ['list', ['Passwörter niemals im **Klartext** speichern. Speichern als **gesalzener Hash** (bcrypt, Argon2): Das **Salt** ist ein zufälliger Zusatz pro Benutzer und verhindert **Rainbow-Table-Angriffe**.', 'Lange Passwörter oder **Passphrasen** sind besser als kurze komplexe. Einen **Passwortmanager** nutzen.', '**Standardpasswörter** von Geräten ändern. Passwörter nie mehrfach verwenden.']],
  ['h', 'Aufgaben im Prüfungsstil'],
  ['qa', 'Ordnen Sie zu, welches Schutzziel verletzt wird: a) Ein Hacker liest die Kundendatenbank. b) Ein Mitarbeiter ändert versehentlich Preise. c) Der Webserver ist durch einen DDoS-Angriff nicht erreichbar.', ['- a) **Vertraulichkeit**', '- b) **Integrität**', '- c) **Verfügbarkeit**'], 3],
  ['qa', 'Nennen Sie je eine technische Maßnahme zum Schutz der drei Schutzziele.', ['- Vertraulichkeit: **Verschlüsselung** der Daten (TLS, Festplattenverschlüsselung) und Zugriffsrechte.', '- Integrität: **Hashwerte oder digitale Signaturen**, Berechtigungsvergabe, Protokollierung.', '- Verfügbarkeit: **Redundanz** (RAID, Cluster), regelmäßige **Backups**, USV.'], 6],
  ['qa', 'Was ist Mehr-Faktor-Authentifizierung? Nennen Sie ein Beispiel.', 'Bei der MFA muss sich der Benutzer mit **mindestens zwei Faktoren unterschiedlicher Kategorien** (Wissen, Besitz, Sein) ausweisen. Beispiel: Passwort (Wissen) plus Einmalcode in einer Authenticator-App auf dem Smartphone (Besitz). Auch bei gestohlenem Passwort bleibt der Zugang geschützt.', 4],
  ['qa', 'Wie berechnet man das Risiko? Ein Ausfall eines Servers kostet 20.000 Euro und tritt mit einer Wahrscheinlichkeit von 5 Prozent pro Jahr auf. Berechnen Sie das erwartete jährliche Risiko.', 'Risiko = Eintrittswahrscheinlichkeit mal Schadenshöhe = 0,05 mal 20.000 Euro = **1.000 Euro pro Jahr**. Maßnahmen, die weniger als 1.000 Euro im Jahr kosten und den Schaden verhindern, sind wirtschaftlich sinnvoll.', 4],
  ['quiz', [
    {q: 'Welches Schutzziel wird durch Verschlüsselung in erster Linie geschützt?', o: ['Vertraulichkeit', 'Verfügbarkeit', 'Zurechenbarkeit', 'Performance'], a: 0, e: 'Verschlüsselte Daten kann nur lesen, wer den Schlüssel besitzt.'},
    {q: 'Ein Angreifer ändert unbemerkt eine Bankverbindung in einer Rechnung. Welches Ziel ist verletzt?', o: ['Integrität', 'Vertraulichkeit', 'Verfügbarkeit', 'Keines'], a: 0, e: 'Die Daten wurden verfälscht: Integrität.'},
    {q: 'Was bedeutet das Prinzip der minimalen Rechte (Least Privilege)?', o: ['Jeder erhält nur die für seine Aufgabe nötigen Rechte', 'Alle haben Administratorrechte', 'Niemand darf etwas', 'Rechte werden zufällig vergeben'], a: 0, e: 'Je weniger Rechte, desto kleiner der mögliche Schaden bei Missbrauch.'},
    {q: 'Wie bezeichnet man die Kombination aus Passwort und Smartphone-Code?', o: ['Mehr-Faktor-Authentifizierung', 'Verschlüsselung', 'Hashing', 'Backup'], a: 0, e: 'Wissen plus Besitz sind zwei unterschiedliche Faktoren.'},
    {q: 'Wofür dient ein Salt beim Passwort-Hashing?', o: ['Gegen Rainbow-Table-Angriffe und gleiche Hashes bei gleichen Passwörtern', 'Zum Verschlüsseln der Datenbank', 'Zum Komprimieren', 'Zum Sortieren'], a: 0, e: 'Ein zufälliger Zusatz pro Passwort macht vorgerechnete Tabellen nutzlos.'},
  ]],
]);
