AP2.page('infra-grundschutz', {
  b: 'infra', g: 'IT-Sicherheit', t: 'BSI IT-Grundschutz: Schutzbedarfsfeststellung, Gefährdungen und Maßnahmen',
  d: 'Der **IT-Grundschutz** des **BSI** (Bundesamt für Sicherheit in der Informationstechnik) ist eine Methode, um mit Standardmaßnahmen ein angemessenes Sicherheitsniveau zu erreichen (BSI-Standards 200-1 bis 200-4, **IT-Grundschutz-Kompendium**). Ein zentraler Schritt ist die **Schutzbedarfsfeststellung**: Für jedes Objekt (Anwendung, Server, Raum) wird für die Grundwerte **Vertraulichkeit, Integrität und Verfügbarkeit** bewertet, wie groß der Schaden bei einer Verletzung wäre. Die Kategorien sind **normal**, **hoch** und **sehr hoch**. Danach richten sich die Maßnahmen.',
  m: '**normal = begrenzter, überschaubarer Schaden. hoch = beträchtlicher Schaden. sehr hoch = existenzbedrohend, katastrophal.** **Maximumprinzip: Ein Server erbt den höchsten Schutzbedarf der Anwendungen, die darauf laufen.** **Personenbezogene Daten -> Vertraulichkeit mindestens hoch; Gesundheitsdaten, Passwörter -> sehr hoch.** **Begründung immer mit Schadensszenario** (Gesetzesverstoß, Image, Finanzen, Aufgabenerfüllung).',
  cheat: [
    ['Schutzbedarf', ['**normal**: Schaden begrenzt', '**hoch**: beträchtlich', '**sehr hoch**: existenzbedrohend', 'je Grundwert C, I, A einzeln']],
    ['Schadensszenarien', ['Verstoß gegen Gesetze/Verträge', 'Beeinträchtigung informationeller Selbstbestimmung', 'Gefahr für Leib und Leben', 'Aufgabenerfüllung, Außenwirkung, Finanzen']],
    ['Vererbung', ['**Maximumprinzip**', '**Kumulationseffekt**: viele kleine -> hoch', '**Verteilungseffekt**: Redundanz -> niedriger', 'Anwendung -> System -> Raum -> Netz']],
    ['Vorgehen BSI 200-2', ['Strukturanalyse', 'Schutzbedarfsfeststellung', 'Modellierung (Bausteine)', 'IT-Grundschutz-Check, Risikoanalyse, Umsetzung']],
  ],
  blocks: [
    ['h', 'Die Schutzbedarfskategorien'],
    ['table', ['Kategorie', 'Bedeutung', 'Beispiel Verfügbarkeit', 'Beispiel Vertraulichkeit'], [
      ['**normal**', 'Die Schadensauswirkungen sind **begrenzt und überschaubar**', 'Ausfall von einem Tag ist tolerierbar', 'Interne Telefonliste'],
      ['**hoch**', 'Die Schadensauswirkungen können **beträchtlich** sein', 'Ausfall über einige Stunden führt zu deutlichen Verlusten', 'Personaldaten, Kundendaten, Angebotskalkulationen'],
      ['**sehr hoch**', 'Die Schadensauswirkungen können ein **existenziell bedrohliches, katastrophales** Ausmaß erreichen', 'Produktionssteuerung, Notrufsystem, Medizingeräte', 'Gesundheitsdaten, Zugangsdaten/Passwörter der Kunden, Geschäftsgeheimnisse'],
    ]],
    ['h', 'Prüfungsbeispiel: Ticketsystem-Server (AP1 Winter 2025/26, 6 Punkte)'],
    ['p', 'Auf dem Server laufen Ticketsystem und Support-Wiki. Zugriff haben alle Supportmitarbeiter und der Vertrieb (für Abrechnungen). In der Datenbank liegen **personenbezogene Daten** von Kunden und Beschäftigten sowie Informationen über die IT der Kunden, darunter **dokumentierte Passwörter**.'],
    ['table', ['Grundwert', 'Schutzbedarf', 'Begründung'], [
      ['**Vertraulichkeit**', '**sehr hoch**', 'Personenbezogene Daten (DSGVO-Verstoß mit Bußgeld, Meldepflicht) und **Kundenpasswörter**: Bei Offenlegung könnten Angreifer in die Netze der Kunden eindringen; Haftung und Imageschaden können existenzbedrohend sein.'],
      ['**Integrität**', '**hoch**', 'Manipulierte Tickets, Abrechnungsdaten oder falsche Anleitungen im Wiki führen zu Fehlern beim Kunden, falschen Rechnungen und Vertrauensverlust.'],
      ['**Verfügbarkeit**', '**normal** bis **hoch**', 'Fällt das System kurz aus, kann der Support vorübergehend telefonisch und manuell arbeiten (normal). Bei vertraglich zugesicherten Reaktionszeiten (SLA) wäre ein längerer Ausfall beträchtlich (hoch).'],
    ]],
    ['tip', 'Es gibt selten nur **eine** richtige Einstufung. Punkte gibt es für eine **schlüssige Begründung** mit einem konkreten Schadensszenario. Formuliere: "Schutzbedarf hoch, weil bei Verlust/Manipulation/Ausfall ... passieren würde."'],
    ['h', 'Vererbung des Schutzbedarfs'],
    ['list', [
      '**Maximumprinzip:** Ein IT-System erhält den **höchsten** Schutzbedarf aller Anwendungen, die es nutzen. Läuft eine "sehr hohe" Anwendung auf einem Server, ist der Server "sehr hoch".',
      '**Kumulationseffekt:** Viele Anwendungen mit "normal" auf einem System können zusammen einen **höheren** Schutzbedarf ergeben (Ausfall trifft alle gleichzeitig).',
      '**Verteilungseffekt:** Ist eine Anwendung auf **redundante** Systeme verteilt (Cluster), kann der Verfügbarkeitsbedarf des einzelnen Systems **niedriger** sein.',
    ]],
    ['h', 'Personenbezogene Daten (AP1 Winter 2025/26 und Winter 2023/24)'],
    ['def', '**Personenbezogene Daten** sind nach **Art. 4 Nr. 1 DSGVO** alle Informationen, die sich auf eine **identifizierte oder identifizierbare natürliche Person** beziehen, also direkt (Name) oder indirekt über Kennungen (Kundennummer, IP-Adresse, Standortdaten, Kfz-Kennzeichen).'],
    ['table', ['Kategorie', 'Beispiele'], [
      ['**Personenbezogene Daten**', 'Name, Anschrift, E-Mail, Telefonnummer, Geburtsdatum, Kundennummer, IP-Adresse, Kontonummer, Foto, Personalnummer'],
      ['**Besondere Kategorien** (Art. 9 DSGVO, besonders schützenswert)', 'Gesundheitsdaten, genetische und biometrische Daten, ethnische Herkunft, politische Meinung, religiöse Überzeugung, Gewerkschaftszugehörigkeit, Sexualleben'],
      ['**Keine personenbezogenen Daten**', 'Anonymisierte Statistiken, Firmendaten einer GmbH (juristische Person), technische Daten wie Drohnengewicht oder Seriennummer ohne Personenbezug'],
    ]],
    ['h', 'Daten im Ticketsystem vor unberechtigtem Zugriff schützen (6 Punkte)'],
    ['list', [
      '**Rollen- und Rechtekonzept** (Need-to-know, Least Privilege): Der Vertrieb sieht nur Abrechnungsdaten, nicht die Kundenpasswörter; Support nur die eigenen Kunden.',
      '**Starke Authentifizierung:** individuelle Konten, sichere Passwörter, **Zwei-Faktor-Authentifizierung**, Anbindung an zentrale Benutzerverwaltung (LDAP/AD).',
      '**Verschlüsselung:** Datenbank bzw. Festplatten verschlüsseln (Encryption at Rest), Zugriff nur per HTTPS/TLS.',
      '**Passwörter nicht im Klartext** dokumentieren, sondern in einem **Passwort-Tresor** (verschlüsselt, mit Zugriffsprotokoll).',
      '**Protokollierung** der Zugriffe (wer hat wann welches Ticket geöffnet) und regelmäßige Kontrolle.',
      '**Netzsegmentierung und Firewall:** Server in eigenem Servernetz, nur aus Support- und Vertriebs-VLAN erreichbar; Updates und Härtung.',
    ]],
    ['h', 'Gefährdungen der Verfügbarkeit und Gegenmaßnahmen (AP1 Sommer 2022)'],
    ['table', ['Gefährdung (BSI-Elementargefährdung)', 'Maßnahme'], [
      ['**Ausfall der Stromversorgung**', 'USV, Notstromaggregat, redundante Netzteile'],
      ['**Ausfall/Defekt von Hardware** (Festplatte, Netzteil)', 'RAID, Ersatzteile, Wartungsvertrag, Cluster'],
      ['**Feuer, Wasser, Überhitzung**', 'Brandmelder, Löschanlage, Klimatisierung, Serverraum nicht im Keller, Backup an anderem Ort'],
      ['**Schadsoftware/Ransomware**', 'Virenschutz, Updates, Offline-Backups, Schulung, E-Mail-Filter'],
      ['**DDoS-Angriff**', 'DDoS-Schutz beim Provider, Firewall, Lastverteilung'],
      ['**Fehlbedienung, versehentliches Löschen**', 'Rechtekonzept, Backups mit Versionierung, Schulung'],
      ['**Ausfall der Internetanbindung**', 'Zweite Leitung eines anderen Providers (LTE/5G-Backup)'],
      ['**Diebstahl, unbefugter Zutritt**', 'Abgeschlossener Serverraum, Zutrittskontrolle, Videoüberwachung'],
    ]],
    ['h', 'Ransomware: Auswirkungen auf die Schutzziele (AP1 Winter 2022/23)'],
    ['table', ['Schutzziel', 'Auswirkung eines Ransomware-Angriffs auf den Dateiserver'], [
      ['**Verfügbarkeit**', 'Dateien sind **verschlüsselt** und nicht mehr nutzbar; Arbeit steht still, bis aus Backup wiederhergestellt ist.'],
      ['**Integrität**', 'Daten wurden **unbefugt verändert** (verschlüsselt); man kann nicht sicher sein, dass wiederhergestellte oder entschlüsselte Daten unverändert sind.'],
      ['**Vertraulichkeit**', 'Moderne Erpresser **kopieren Daten vorher** (Double Extortion) und drohen mit Veröffentlichung; Datenschutzverletzung nach Art. 33 DSGVO meldepflichtig (72 Stunden).'],
    ]],
    ['h', 'Erweiterte Schutzziele'],
    ['kv', [
      ['Vertraulichkeit', 'Nur Berechtigte können Informationen lesen.'],
      ['Integrität', 'Daten sind vollständig und unverändert; Änderungen werden erkannt.'],
      ['Verfügbarkeit', 'Systeme und Daten stehen zur Verfügung, wenn sie gebraucht werden.'],
      ['Authentizität', 'Echtheit: Ein Kommunikationspartner oder eine Nachricht stammt wirklich vom angegebenen Absender.'],
      ['Verbindlichkeit (Nichtabstreitbarkeit)', 'Eine Handlung kann dem Urheber eindeutig zugeordnet werden und ist nicht abstreitbar (digitale Signatur).'],
    ]],
    ['h', 'Aufgaben im Prüfungsstil'],
    ['qa', 'Erläutern Sie den Begriff "personenbezogene Daten" und geben Sie zwei Beispiele an.', ['Personenbezogene Daten sind alle Informationen, die sich auf eine **identifizierte oder identifizierbare natürliche Person** beziehen (Art. 4 DSGVO). Die Person kann direkt oder über Zusatzinformationen erkannt werden.', 'Beispiele: Name und Anschrift, E-Mail-Adresse, Telefonnummer, Kundennummer, IP-Adresse.'], 4],
    ['qa', 'Ein Webshop-Server enthält Kundenkonten mit Zahlungsdaten. Ermitteln Sie den Schutzbedarf für Vertraulichkeit und Verfügbarkeit und begründen Sie.', ['**Vertraulichkeit: hoch bis sehr hoch.** Zahlungsdaten und Kundenkonten sind personenbezogen; ein Datenleck verstößt gegen DSGVO (Bußgeld) und PCI-DSS, verursacht Betrugsschäden und massiven Imageschaden.', '**Verfügbarkeit: hoch.** Jede Stunde Ausfall bedeutet entgangenen Umsatz und verärgerte Kunden; bei einem kleinen Shop eventuell normal.'], 4],
    ['quiz', [
      {q: 'Welche Schutzbedarfskategorie beschreibt existenzbedrohende Schäden?', o: ['sehr hoch', 'hoch', 'normal', 'kritisch'], a: 0, e: 'Drei Stufen: normal, hoch, sehr hoch.'},
      {q: 'Was besagt das Maximumprinzip?', o: ['Ein System erbt den höchsten Schutzbedarf seiner Anwendungen', 'Der Schutzbedarf wird gemittelt', 'Nur die wichtigste Anwendung zählt nicht', 'Es gilt immer sehr hoch'], a: 0, e: 'Kumulation kann ihn sogar erhöhen.'},
      {q: 'Welche Daten gehören zu den besonderen Kategorien nach Art. 9 DSGVO?', o: ['Gesundheitsdaten', 'E-Mail-Adresse', 'Kundennummer', 'Postleitzahl'], a: 0, e: 'Auch Religion, Gewerkschaft, Biometrie.'},
      {q: 'Welches Schutzziel verletzt Ransomware unmittelbar am deutlichsten?', o: ['Verfügbarkeit', 'Authentizität', 'Verbindlichkeit', 'Anonymität'], a: 0, e: 'Die Daten sind verschlüsselt und unbrauchbar.'},
      {q: 'Welche Institution veröffentlicht den IT-Grundschutz?', o: ['BSI', 'IHK', 'ISO', 'BNetzA'], a: 0, e: 'Bundesamt für Sicherheit in der Informationstechnik.'},
    ]],
    ['see', ['infra-cia', 'infra-isms', 'ps-dsgvo', 'infra-angriffe', 'infra-backup']],
  ],
});
