AP2.page('infra-ipconfig', {
  b: 'infra', g: 'Netzwerke', t: 'IP-Konfiguration, DHCP-Vergabearten, NAT und Fehlersuche',
  d: 'Damit ein Gerät im Netz und im Internet arbeiten kann, braucht es vier Angaben: **IP-Adresse**, **Subnetzmaske** (bzw. Präfix), **Standardgateway** (Router ins andere Netz) und **DNS-Server**. Diese vergibt meist ein **DHCP-Server** im vierstufigen Ablauf **DORA** (Discover, Offer, Request, Acknowledge), entweder **manuell** (fest per MAC-Adresse), **automatisch** (dauerhaft dieselbe Adresse) oder **dynamisch** (für eine Lease-Zeit). Private Adressen (10/8, 172.16/12, 192.168/16) werden am Router per **NAT** in eine öffentliche Adresse übersetzt. Viele Prüfungsaufgaben drehen sich um **Fehlersuche**: falsches Subnetz, fehlendes Gateway, doppelte Adressen.',
  m: '**IP + Maske + Gateway + DNS.** **DORA: Discover (Broadcast) - Offer - Request (Broadcast) - Acknowledge.** **Gleiche Netz-ID = direkt erreichbar, sonst über das Gateway.** **Gateway muss im eigenen Subnetz liegen.** **Private IPs sind im Internet nicht routbar -> NAT/Portweiterleitung/VPN.** **169.254.x.x = kein DHCP-Server gefunden (APIPA).**',
  cheat: [
    ['Pflichtangaben', ['IP-Adresse', 'Subnetzmaske / Präfix', 'Standardgateway', 'DNS-Server (+ Lease-Zeit)']],
    ['DHCP-Vergabearten', ['**manuell/statisch**: Liste MAC -> IP', '**automatisch**: erste Vergabe, dann immer dieselbe', '**dynamisch**: Lease, danach evtl. andere', 'Reservierung = manuell im DHCP']],
    ['Private Bereiche', ['10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16', '169.254.0.0/16 APIPA, 127.0.0.0/8 Loopback']],
    ['Werkzeuge', ['`ipconfig /all`, `ip addr`', '`ping`, `tracert`/`traceroute`', '`nslookup`, `arp -a`', '`ipconfig /release` / `/renew`']],
  ],
  blocks: [
    ['h', 'Wozu dienen die vier Einträge? (AP1 Sommer 2023)'],
    ['table', ['Eintrag', 'Zweck', 'Beispiel'], [
      ['**IP-Adresse**', 'Eindeutige logische Adresse des Geräts im Netz (Schicht 3)', '192.168.1.25'],
      ['**Subnetzmaske**', 'Trennt Netz- und Hostanteil; legt fest, welche Ziele im **eigenen** Netz liegen', '255.255.255.0 = /24'],
      ['**Standardgateway**', 'Router, an den alle Pakete in **fremde** Netze (auch ins Internet) geschickt werden', '192.168.1.254'],
      ['**DNS-Server**', 'Übersetzt Namen (www.ihk.de) in IP-Adressen', '192.168.1.1 oder 9.9.9.9'],
    ]],
    ['h', 'DHCP: Ablauf DORA (Winter 2025/26, Winter 2022/23)'],
    ['steps', [
      '**DHCP Discover:** Der Client hat noch keine IP und ruft per **Broadcast** (Ziel 255.255.255.255, UDP-Port 67) ins Netz: "Ich brauche eine IP-Konfiguration."',
      '**DHCP Offer:** Jeder DHCP-Server, der den Broadcast hört, **bietet** eine Konfiguration an (IP, Maske, Gateway, DNS, Lease-Zeit). Es kann mehrere Angebote geben.',
      '**DHCP Request:** Der Client wählt ein Angebot und **fordert** es an, wieder per **Broadcast**, damit alle Server erfahren, welches Angebot gewählt wurde (die anderen geben ihre Adresse wieder frei).',
      '**DHCP Acknowledge (ACK):** Der gewählte Server **bestätigt**; der Client verwendet die Konfiguration ab jetzt für die Lease-Zeit.',
    ]],
    ['p', 'Nach der Hälfte der Lease-Zeit versucht der Client zu **verlängern** (Request direkt an seinen Server). Über Router hinweg funktioniert DHCP nur mit einem **DHCP-Relay-Agent** (IP-Helper), weil Router Broadcasts nicht weiterleiten.'],
    ['h', 'Die drei Vergabearten (Winter 2025/26, 4 Punkte)'],
    ['table', ['Art', 'Funktionsweise', 'Geeignet für'], [
      ['**Manuell (statisch)**', 'Der Administrator legt eine Tabelle an: Welche **MAC-Adresse** bekommt welche IP-Adresse (Reservierung).', 'Drucker, Server, Access Points, Kameras: Geräte, die immer unter derselben Adresse erreichbar sein müssen'],
      ['**Automatisch**', 'Der Server vergibt beim ersten Kontakt eine freie Adresse und merkt sich die Zuordnung zur MAC dauerhaft (unbegrenzte Lease). Das Gerät erhält immer dieselbe IP.', 'Feste Arbeitsplatz-PCs'],
      ['**Dynamisch**', 'Die Adresse wird nur für eine **Lease-Zeit** verliehen, kann verlängert werden und fällt danach an den Pool zurück. Beim nächsten Mal gibt es eventuell eine andere.', 'Wechselnde Geräte: **Gäste-WLAN**, Wartezimmer, Notebooks'],
    ]],
    ['ex', ['Prüfungsantwort Winter 2025/26: "Da die Patienten nicht lange in der Praxis sind und häufig wechseln, bietet sich die **dynamische** Vergabe mit kurzer Lease-Zeit an. So werden Adressen schnell wieder frei und der Pool reicht aus."']],
    ['p', '**Immer dieselbe IP per DHCP (Winter 2022/23, 2 Punkte):** Auf dem DHCP-Server wird für die **MAC-Adresse** des Geräts eine **Reservierung** angelegt (manuelle Vergabe).'],
    ['h', 'Fehlersuche: typische Prüfungsfälle'],
    ['h3', 'Fall 1: Drucker umgezogen (AP1 Winter 2025/26)'],
    ['p', 'Der Drucker stand früher in Gebäude A (Netz 192.168.1.0/24) und wurde nach Gebäude B (Netz 192.168.2.0/24) gebracht. Seine **manuell** eingetragene Konfiguration lautet weiterhin IP 192.168.1.x, Gateway 192.168.1.254. Die PCs in Gebäude B können nicht drucken.'],
    ['list', [
      '**Ursache:** Die IP-Adresse des Druckers liegt im **falschen Subnetz**. Die PCs in Gebäude B halten 192.168.1.x für ein fremdes Netz und schicken die Pakete ans Gateway; der Router leitet sie nach Gebäude A, wo der Drucker nicht mehr ist.',
      '**Lösung:** Dem Drucker eine freie Adresse aus **192.168.2.0/24** mit passendem Gateway (192.168.2.254) geben, oder auf DHCP mit **Reservierung** umstellen. Danach die Druckerwarteschlangen der PCs anpassen.',
    ]],
    ['h3', 'Fall 2: Geräte erreichen sich, aber nicht das Internet (AP1 Winter 2023/24)'],
    ['list', [
      '**Kein oder falsches Standardgateway** eingetragen (zum Beispiel Adresse eines PCs statt des Routers, oder ein Gateway aus einem anderen Subnetz).',
      '**DNS-Server fehlt:** `ping 9.9.9.9` funktioniert, `ping www.ihk.de` nicht.',
      'Router hat keine Verbindung zum Provider oder **NAT** ist nicht konfiguriert.',
    ]],
    ['h3', 'Fall 3: Ein Client mit manueller Konfiguration (AP1 Sommer 2024)'],
    ['list', [
      '**Falsche Subnetzmaske** (zum Beispiel /16 statt /24): Der Client hält fremde Adressen für lokal und schickt keine Pakete ans Gateway.',
      '**IP-Adresse doppelt vergeben** (Konflikt mit einem anderen Gerät oder dem DHCP-Pool).',
      '**Netz- oder Broadcastadresse** als Host-IP eingetragen (zum Beispiel 192.168.1.0 oder .255).',
    ]],
    ['h3', 'Braucht ein Netzwerkdrucker ein Gateway? (AP1 Winter 2023/24)'],
    ['p', 'Nur, wenn er mit Geräten **außerhalb seines Subnetzes** kommunizieren soll: Clients aus anderen VLANs/Subnetzen, ein zentraler Druckserver in einem anderen Netz, E-Mail-Versand von Scans, Firmware-Updates oder Cloud-Druck. Stehen alle Clients im selben Subnetz, ist kein Gateway nötig; es ohne Bedarf wegzulassen, verringert sogar die Angriffsfläche.'],
    ['h', 'Öffentliche und private IPv4-Adressen, NAT'],
    ['table', ['', 'Private Adresse', 'Öffentliche Adresse'], [
      ['Bereich', '10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16 (RFC 1918)', 'Alle anderen (außer Sonderbereiche), weltweit eindeutig, vom Provider zugeteilt'],
      ['Routbar im Internet?', '**Nein**, Router im Internet verwerfen sie', 'Ja'],
      ['Einsatz', 'Lokale Netze, mehrfach weltweit verwendet', 'Router-WAN-Schnittstelle, öffentliche Server'],
    ]],
    ['p', '**NAT** (Network Address Translation, genauer PAT/NAT-Overload) ersetzt am Router die private Absenderadresse durch die öffentliche und merkt sich in einer Tabelle, welche Antwort zu welchem internen Gerät gehört. Dadurch können viele Geräte eine öffentliche IP teilen. Verbindungen **von außen nach innen** sind ohne Weiteres nicht möglich.'],
    ['ex', ['AP1 Sommer 2024: Warum kann man aus dem Homeoffice nicht auf das Videoüberwachungssystem (192.168.10.20) zugreifen?', 'Die Kamera hat eine **private** IP-Adresse, die im Internet nicht geroutet wird; der Router lässt eingehende Verbindungen wegen NAT und Firewall nicht durch. Lösung: **VPN** ins Firmennetz (sicher) oder Portweiterleitung (unsicher, nicht empfohlen).']],
    ['h', 'Was ändert sich auf dem Weg durch einen Router? (AP1 Sommer 2022)'],
    ['p', 'Ein PC (192.168.1.10) sendet an einen Webserver im Internet. Zwischen Switch und Router wird mitgeschnitten.'],
    ['table', ['Feld', 'Wert im Mitschnitt (PC -> Router)', 'Erklärung'], [
      ['Quell-MAC', 'MAC des **PCs**', 'MAC-Adressen gelten nur im lokalen Segment (Schicht 2)'],
      ['Ziel-MAC', 'MAC des **Routers** (Gateway)', 'Nicht die MAC des Webservers! Der PC kennt sie nicht und braucht sie nicht'],
      ['Quell-IP', '192.168.1.10 (PC)', 'Bleibt im LAN gleich; erst der Router ersetzt sie per NAT'],
      ['Ziel-IP', 'IP des **Webservers**', 'IP-Adressen bleiben Ende-zu-Ende gleich (bis auf NAT)'],
    ]],
    ['note', 'Merke: **MAC-Adressen ändern sich bei jedem Hop** (Router schreibt neue Quell- und Ziel-MAC), **IP-Adressen bleiben** (außer NAT). Die MAC-Adresse ist **48 Bit** lang (6 Byte, hexadezimal) und gehört zur **Schicht 2** (Sicherungsschicht), die IP-Adresse zur **Schicht 3** (Vermittlungsschicht). ARP ermittelt zu einer IP die MAC im lokalen Netz.'],
    ['h', 'Aufgaben im Prüfungsstil'],
    ['qa', 'Geben Sie für das Netz 192.168.1.0/24 den nutzbaren Adressbereich, die Maske in Dotted-Decimal, die Anzahl Hosts, die Broadcastadresse und das Gateway (höchste Hostadresse) an.', ['Maske: **255.255.255.0**; Hosts: 2^8 - 2 = **254**.', 'Bereich: **192.168.1.1 bis 192.168.1.254**; Broadcast: **192.168.1.255**; Gateway: **192.168.1.254**.'], 5],
    ['qa', 'Nennen Sie vier Konfigurationseinstellungen, die ein Host vom DHCP-Server beziehen muss, um Webseiten aus dem Internet abzurufen.', ['- IP-Adresse', '- Subnetzmaske', '- Standardgateway', '- DNS-Server (zusätzlich: Lease-Zeit)'], 4],
    ['qa', 'Ein PC zeigt die Adresse 169.254.17.3. Was ist passiert und wie gehen Sie vor?', ['Der PC hat **keinen DHCP-Server erreicht** und sich selbst eine **APIPA**-Adresse gegeben. Vorgehen: Kabel/WLAN prüfen, `ipconfig /renew`, Erreichbarkeit und Status des DHCP-Servers prüfen (Pool erschöpft? Dienst gestoppt? Relay im richtigen VLAN?).'], 3],
    ['quiz', [
      {q: 'Welcher DHCP-Schritt wird vom Client als Broadcast gesendet, nachdem er ein Angebot gewählt hat?', o: ['Request', 'Offer', 'Acknowledge', 'Release'], a: 0, e: 'Damit alle Server die Wahl mitbekommen.'},
      {q: 'Welche Vergabeart eignet sich für Gäste im Wartezimmer?', o: ['Dynamisch', 'Manuell', 'Automatisch', 'Gar keine'], a: 0, e: 'Kurze Leases, Adressen werden schnell frei.'},
      {q: 'Welche Adresse ist privat?', o: ['172.20.5.1', '172.32.5.1', '11.0.0.1', '193.168.1.1'], a: 0, e: '172.16.0.0 bis 172.31.255.255.'},
      {q: 'Welche Ziel-MAC hat ein Paket vom PC an einen Server im Internet im LAN-Segment?', o: ['Die MAC des Standardgateways', 'Die MAC des Servers', 'FF:FF:FF:FF:FF:FF', 'Die eigene MAC'], a: 0, e: 'Die nächste Station ist der Router.'},
      {q: 'Wie viele Bit hat eine MAC-Adresse?', o: ['48', '32', '64', '128'], a: 0, e: '6 Byte.'},
    ]],
    ['see', ['infra-ports', 'infra-subnetting', 'infra-vlan', 'infra-vpn', 'infra-ipv6']],
  ],
});
