AP2.add('infra-ipv6', [
  ['h', 'Adressvergabe und Neuerungen'],
  ['kv', [
    ['Präfix und Interface-ID', 'Die ersten **64 Bit** sind das Subnetz-Präfix (vom Provider und eigenen Subnetzen), die letzten **64 Bit** die **Interface-ID** des Geräts. Ein Heimanschluss bekommt vom Provider meist ein **/56** oder **/48**, daraus lassen sich viele /64-Subnetze bilden.'],
    ['SLAAC', 'Stateless Address Autoconfiguration: Ein Gerät bildet seine Adresse **selbst**, aus dem Präfix, das der Router in einer **Router Advertisement**-Nachricht bekannt gibt, und einer Interface-ID (zufällig oder aus der MAC-Adresse).'],
    ['DHCPv6', 'Zustandsbehafteter Server wie bei IPv4, vergibt Adressen und Zusatzinformationen (zum Beispiel DNS-Server).'],
    ['NDP', 'Neighbor Discovery Protocol: Ersetzt **ARP**. Findet MAC-Adressen von Nachbarn, Router und prüft Adressduplikate (über ICMPv6).'],
    ['Privacy Extensions', 'Zufällige, wechselnde Interface-IDs, damit ein Gerät nicht über seine MAC-Adresse dauerhaft verfolgt werden kann.'],
  ]],
  ['h', 'IPv4 und IPv6 im Vergleich'],
  ['table', ['Merkmal', 'IPv4', 'IPv6'], [
    ['Adresslänge', '32 Bit', '128 Bit'],
    ['Schreibweise', 'Dezimal mit Punkten (192.168.1.1)', 'Hexadezimal mit Doppelpunkten'],
    ['Anzahl Adressen', 'ca. 4,3 Milliarden', 'ca. 3,4 mal 10^38'],
    ['Broadcast', 'Ja', '**Nein** (Multicast)'],
    ['NAT', 'Meist nötig (Adressmangel)', 'Nicht nötig, Ende-zu-Ende-Verbindungen'],
    ['Adresskonfiguration', 'Manuell oder DHCP', 'SLAAC, DHCPv6 oder manuell'],
    ['Adressauflösung', 'ARP', 'NDP (ICMPv6)'],
    ['Header', 'Variabel (20 bis 60 Byte), Prüfsumme', 'Feste Länge 40 Byte, einfacher, ohne Prüfsumme'],
    ['Sicherheit', 'IPsec optional', 'IPsec unterstützt (nicht mehr zwingend)'],
    ['Fragmentierung', 'Router und Sender', 'Nur der Sender'],
  ]],
  ['h', 'Übergang von IPv4 zu IPv6'],
  ['list', ['**Dual Stack:** Geräte sprechen **beide** Protokolle gleichzeitig. Der häufigste Weg.', '**Tunneling:** IPv6-Pakete werden in IPv4-Pakete verpackt (zum Beispiel 6in4), um IPv4-Netze zu überbrücken.', '**Übersetzung (NAT64/DNS64):** Ein Gateway übersetzt zwischen IPv6 und IPv4.']],
  ['procon', 'Umstieg auf IPv6', ['Riesiger Adressraum, keine Adressknappheit', 'Einfachere Konfiguration (SLAAC), einfacher Header', 'Direkte Erreichbarkeit ohne NAT, bessere Unterstützung für IoT', 'Von Providern und Inhalten zunehmend bevorzugt'], ['Neue Adressformate sind schwerer zu merken', 'Alte Geräte und Software müssen angepasst werden', 'Firewall-Regeln müssen auch für IPv6 gepflegt werden (sonst Sicherheitslücke)', 'Parallelbetrieb (Dual Stack) bedeutet doppelten Aufwand']],
  ['h', 'Aufgaben im Prüfungsstil'],
  ['qa', 'Kürzen Sie die IPv6-Adresse 2001:0db8:0000:0000:0000:0000:0000:0001.', ['Führende Nullen weglassen: 2001:db8:0:0:0:0:0:1.', 'Die längste Folge von Null-Gruppen durch :: ersetzen: **2001:db8::1**.'], 3],
  ['qa', 'Schreiben Sie die Adresse fe80::1 vollständig aus. Um welchen Adresstyp handelt es sich?', ['Vollständig: **fe80:0000:0000:0000:0000:0000:0000:0001**.', 'Typ: **Link-Local-Adresse** (nur im lokalen Segment gültig, wird nicht geroutet).'], 3],
  ['qa', 'Nennen Sie drei Vorteile von IPv6 gegenüber IPv4.', ['- Wesentlich größerer Adressraum (128 Bit), NAT nicht mehr nötig', '- Automatische Adresskonfiguration (SLAAC)', '- Einfacherer, fester Header (40 Byte), effizienteres Routing', '- Kein Broadcast, dafür Multicast (weniger Netzlast)'], 3],
  ['qa', 'Ein Provider vergibt ein /48-Präfix. Wie viele /64-Subnetze lassen sich daraus bilden?', '/64 minus /48 = 16 Bit für Subnetze. 2^16 = **65.536 Subnetze**.', 3],
  ['quiz', [
    {q: 'Wie viele Bit hat eine IPv6-Adresse?', o: ['128', '32', '64', '256'], a: 0, e: 'IPv6 verwendet 128 Bit.'},
    {q: 'Wie oft darf "::" in einer IPv6-Adresse vorkommen?', o: ['Höchstens einmal', 'Beliebig oft', 'Genau zweimal', 'Gar nicht'], a: 0, e: 'Sonst wäre die Adresse nicht eindeutig rekonstruierbar.'},
    {q: 'Welches Protokoll ersetzt ARP in IPv6?', o: ['NDP', 'DHCP', 'ICMPv4', 'DNS'], a: 0, e: 'Neighbor Discovery Protocol (über ICMPv6).'},
    {q: 'Welche Adressen sind Link-Local-Adressen?', o: ['fe80::/10', '2001::/16', 'ff00::/8', '::1'], a: 0, e: 'Link-Local beginnt mit fe80.'},
    {q: 'Gibt es in IPv6 Broadcast?', o: ['Nein, stattdessen Multicast', 'Ja, wie in IPv4', 'Nur im WLAN', 'Nur für Router'], a: 0, e: 'IPv6 kennt keinen Broadcast, Multicast übernimmt diese Aufgaben.'},
  ]],
]);
