AP2.add('infra-krypto', [
  ['table', ['Merkmal', 'Symmetrisch', 'Asymmetrisch'], [
    ['Schlüssel', 'Ein gemeinsamer geheimer Schlüssel', 'Schlüsselpaar (öffentlich und privat)'],
    ['Geschwindigkeit', '**Sehr schnell** (100- bis 1000-mal schneller)', 'Langsam, rechenintensiv'],
    ['Schlüssellänge (sicher)', '128 bis 256 Bit (AES)', 'RSA mindestens 2048 Bit (besser 3072), ECC 256 Bit'],
    ['Schlüsselaustausch', '**Problem**: Schlüssel muss sicher übermittelt werden', 'Kein Problem: öffentlicher Schlüssel darf offen sein'],
    ['Schlüsselanzahl bei n Teilnehmern', 'n(n-1)/2', 'n Schlüsselpaare'],
    ['Typische Verfahren', 'AES, ChaCha20', 'RSA, ECC (ECDSA, ECDH), Diffie-Hellman'],
    ['Einsatz', 'Verschlüsselung großer Datenmengen', 'Schlüsselaustausch, Signaturen, Zertifikate'],
  ]],
  ['h', 'Hybride Verschlüsselung: das Beste aus beiden'],
  ['p', 'In der Praxis (HTTPS, E-Mail-Verschlüsselung, VPN) nutzt man **beide Verfahren**: Die **asymmetrische** Methode tauscht sicher einen zufälligen **Sitzungsschlüssel** aus. Mit diesem wird die eigentliche Kommunikation **symmetrisch** (schnell) verschlüsselt.'],
  ['steps', ['Alice erzeugt einen zufälligen **Sitzungsschlüssel** (zum Beispiel 256-Bit-AES-Schlüssel).', 'Sie verschlüsselt **diesen Sitzungsschlüssel** mit **Bobs öffentlichem Schlüssel** (asymmetrisch) und sendet ihn.', 'Bob entschlüsselt ihn mit seinem **privaten Schlüssel**.', 'Beide verschlüsseln die eigentlichen Daten **symmetrisch** mit dem Sitzungsschlüssel.']],
  ['h', 'Hash-Funktionen'],
  ['p', 'Eine **Hashfunktion** berechnet aus beliebig langen Daten einen **Hashwert fester Länge** (SHA-256: 256 Bit, 64 Hexzeichen). Eigenschaften: **Einwegfunktion** (aus dem Hash lassen sich die Daten nicht zurückrechnen), **Determinismus** (gleiche Eingabe ergibt gleichen Hash), **Lawineneffekt** (kleinste Änderung ergibt völlig anderen Hash) und **Kollisionsresistenz** (praktisch nicht möglich, zwei verschiedene Eingaben mit gleichem Hash zu finden).'],
  ['code', 'text', `SHA-256("Hallo")  = 753692ec36adb4c794c973945eb2a99c1649703ea6f76bf259abb4fb838e013e
SHA-256("hallo")  = d3751d33f9cd5049c4af2b462735457e4d3baf130bcbb87f389e349fbaeb20b9
                    (ein einziger Buchstabe anders: komplett anderer Hash)`],
  ['tool', 'hash'],
  ['table', ['Anwendung des Hashes', 'Wie?'], [['**Integritätsprüfung**', 'Download und Hash vergleichen: Stimmt der Hash, ist die Datei unverändert.'], ['**Passwörter speichern**', 'Nur der **Hash** (mit Salt) wird gespeichert, nie das Passwort. Beim Login wird der Hash der Eingabe verglichen.'], ['**Digitale Signatur**', 'Nicht die ganze Datei, nur ihr Hash wird signiert (schneller).'], ['**HMAC**', 'Hash mit geheimem Schlüssel: prüft Integrität **und** Authentizität einer Nachricht.']]],
  ['warn', 'Hash ist **keine Verschlüsselung**: Er ist nicht umkehrbar und es gibt keinen Schlüssel. **MD5 und SHA-1 sind unsicher** (Kollisionen möglich). Für Passwörter nimmt man spezielle **langsame** Verfahren mit Salt: **bcrypt, scrypt, Argon2**.'],
  ['h', 'Digitale Signatur'],
  ['diagram', AP2.dg.flow(['Dokument', 'Hash berechnen', 'Hash mit privatem Schlüssel signieren', 'Signatur + Dokument senden', 'Empfänger: Signatur mit öffentlichem Schlüssel prüfen, Hash vergleichen'], {w: 780, h: 130, nh: 70, styles: ['soft', 'accent', 'accent', 'soft', 'ok'], cap: 'Prinzip der digitalen Signatur: Stimmen beide Hashwerte überein, stammt das Dokument vom Absender und ist unverändert.'})],
  ['h', 'BitLocker und TPM'],
  ['kv', [
    ['BitLocker', 'Funktion von Windows zur **Festplattenverschlüsselung (Full Disk Encryption)**. Das gesamte Laufwerk wird mit **AES** (128 oder 256 Bit) verschlüsselt. Wird die Platte oder der Laptop gestohlen, sind die Daten ohne Schlüssel **nicht lesbar** (Schutz der Vertraulichkeit **at rest**). Der **Wiederherstellungsschlüssel (Recovery Key)** muss sicher getrennt aufbewahrt werden (zum Beispiel im Active Directory).'],
    ['TPM (Trusted Platform Module)', 'Ein **Sicherheitschip** im Rechner (Mainboard oder Prozessor). Er erzeugt und **speichert Schlüssel** geschützt in Hardware, kann nicht ausgelesen werden und **misst den Systemzustand** beim Start (Bootloader, Firmware). Nur wenn das System **unverändert** ist, gibt das TPM den BitLocker-Schlüssel frei. Windows 11 verlangt TPM 2.0.'],
    ['Authentifizierung beim Start', '**Nur TPM** (komfortabel, Schutz bei Diebstahl der Platte), **TPM + PIN** (zusätzlicher Faktor gegen Angriffe auf den laufenden Rechner), USB-Startschlüssel.'],
    ['Secure Boot', 'Das UEFI-Firmware lässt nur **signierte** Bootloader und Treiber starten (Schutz vor Rootkits).'],
  ]],
  ['procon', 'Festplattenverschlüsselung (BitLocker)', ['Schutz der Daten bei Diebstahl oder Verlust des Geräts', 'Nahezu transparent für den Benutzer, geringe Leistungseinbußen (Hardware-Beschleunigung)', 'DSGVO: technische Maßnahme zum Schutz personenbezogener Daten'], ['Bei **Verlust des Schlüssels** sind die Daten unwiederbringlich verloren', 'Schützt nicht vor Schadsoftware auf dem laufenden, entsperrten System', 'Verwaltung der Recovery-Keys nötig']],
  ['h', 'Aufgaben im Prüfungsstil'],
  ['qa', 'Erklären Sie, wie Alice eine vertrauliche Nachricht an Bob mit asymmetrischer Verschlüsselung senden kann.', ['Alice verschlüsselt die Nachricht mit **Bobs öffentlichem Schlüssel**. Bob entschlüsselt sie mit seinem **privaten Schlüssel**, den nur er besitzt. Selbst Alice kann die Nachricht danach nicht mehr entschlüsseln.'], 4],
  ['qa', 'Warum nutzt HTTPS ein hybrides Verfahren?', 'Asymmetrische Verfahren lösen das Schlüsselaustausch-Problem, sind aber **langsam**. Symmetrische Verfahren sind **schnell**, brauchen aber einen gemeinsamen Schlüssel. Deshalb wird per asymmetrischem Verfahren (zum Beispiel ECDHE, RSA) ein **Sitzungsschlüssel** ausgetauscht und die Daten danach symmetrisch (AES) verschlüsselt.', 4],
  ['qa', 'Wie stellt man mit einem Hashwert sicher, dass eine heruntergeladene Datei unverändert ist?', 'Der Anbieter veröffentlicht den **Hashwert** (zum Beispiel SHA-256) der Datei. Man berechnet nach dem Download den Hash der eigenen Datei und **vergleicht**. Sind beide gleich, wurde die Datei nicht verändert. Weicht schon ein Bit ab, ergibt sich ein komplett anderer Hash.', 4],
  ['qa', 'Was ist der Unterschied zwischen Hash und Verschlüsselung?', 'Verschlüsselung ist **umkehrbar** (mit dem Schlüssel erhält man den Klartext zurück). Ein Hash ist eine **Einwegfunktion** mit fester Länge, der Klartext lässt sich nicht daraus gewinnen. Hash dient der Integritätsprüfung, Verschlüsselung der Vertraulichkeit.', 4],
  ['qa', 'Welche Aufgabe hat das TPM beim Einsatz von BitLocker?', 'Das TPM speichert den Verschlüsselungsschlüssel **hardwaregeschützt** und gibt ihn nur frei, wenn die gemessenen Startkomponenten (Firmware, Bootloader) unverändert sind. So lässt sich die Festplatte nicht einfach in einen anderen Rechner einbauen und auslesen.', 4],
  ['quiz', [
    {q: 'Welches Verfahren ist symmetrisch?', o: ['AES', 'RSA', 'ECDSA', 'Diffie-Hellman'], a: 0, e: 'AES nutzt einen gemeinsamen Schlüssel. RSA und ECC sind asymmetrisch.'},
    {q: 'Womit verschlüsselt Alice eine Nachricht an Bob?', o: ['Mit Bobs öffentlichem Schlüssel', 'Mit Bobs privatem Schlüssel', 'Mit ihrem privaten Schlüssel', 'Mit dem Hash'], a: 0, e: 'Nur Bobs privater Schlüssel kann den mit seinem öffentlichen Schlüssel erzeugten Geheimtext entschlüsseln.'},
    {q: 'Womit signiert Alice ein Dokument?', o: ['Mit ihrem privaten Schlüssel', 'Mit dem öffentlichen Schlüssel von Bob', 'Mit AES', 'Gar nicht'], a: 0, e: 'Signiert wird mit dem eigenen privaten Schlüssel, geprüft wird mit dem öffentlichen.'},
    {q: 'Welche Hashfunktion gilt als unsicher?', o: ['MD5', 'SHA-256', 'SHA-3', 'Argon2'], a: 0, e: 'MD5 (und SHA-1) sind durch Kollisionen gebrochen.'},
    {q: 'Wie viele Schlüssel braucht man symmetrisch für 6 Teilnehmer, damit jeder mit jedem geheim kommunizieren kann?', o: ['15', '6', '12', '30'], a: 0, e: 'n(n-1)/2 = 6 mal 5 / 2 = 15.'},
    {q: 'Was macht ein TPM?', o: ['Speichert Schlüssel hardwaregeschützt und prüft den Systemzustand', 'Beschleunigt die Grafik', 'Sichert Daten in die Cloud', 'Verwaltet IP-Adressen'], a: 0, e: 'Das Trusted Platform Module ist ein Sicherheitschip.'},
  ]],
]);
