AP2.add('infra-osi', [
  ['h', 'Kapselung (Encapsulation)'],
  ['p', 'Wenn ein Programm Daten sendet, wandern sie von **oben nach unten** durch die Schichten. Jede Schicht **packt die Daten in einen Umschlag**: Sie setzt einen **Header** davor (Schicht 2 auch einen **Trailer** dahinter). Das nennt man **Kapselung**. Beim Empfänger geht es **von unten nach oben**, und jede Schicht öffnet ihren Umschlag (**Entkapselung**).'],
  ['diagram', {w: 860, h: 280, keep: 700, cap: 'Kapselung: Von oben nach unten kommen immer mehr Header dazu.', nodes: [
    {id: 'l7', k: 'text', x: 180, y: 40, t: 'Schicht 7: Daten', anchorEnd: true, fs: 13, b: true}, {id: 'l4', k: 'text', x: 180, y: 100, t: 'Schicht 4: Segment', anchorEnd: true, fs: 13, b: true},
    {id: 'l3', k: 'text', x: 180, y: 160, t: 'Schicht 3: Paket', anchorEnd: true, fs: 13, b: true}, {id: 'l2', k: 'text', x: 180, y: 220, t: 'Schicht 2: Frame', anchorEnd: true, fs: 13, b: true},
    {id: 'd1', k: 'box', x: 600, y: 40, w: 300, h: 44, t: 'Nutzdaten (zum Beispiel HTTP-Anfrage)', s: 'ok'},
    {id: 'h4', k: 'box', x: 410, y: 100, w: 80, h: 44, t: 'TCP', s: 'accent'}, {id: 'd2', k: 'box', x: 600, y: 100, w: 300, h: 44, t: 'Nutzdaten', s: 'ok'},
    {id: 'h3', k: 'box', x: 330, y: 160, w: 80, h: 44, t: 'IP', s: 'accent'}, {id: 'h42', k: 'box', x: 410, y: 160, w: 80, h: 44, t: 'TCP', s: 'accent'}, {id: 'd3', k: 'box', x: 600, y: 160, w: 300, h: 44, t: 'Nutzdaten', s: 'ok'},
    {id: 'h2', k: 'box', x: 250, y: 220, w: 80, h: 44, t: 'Ethernet', s: 'solid'}, {id: 'h32', k: 'box', x: 330, y: 220, w: 80, h: 44, t: 'IP', s: 'accent'}, {id: 'h43', k: 'box', x: 410, y: 220, w: 80, h: 44, t: 'TCP', s: 'accent'}, {id: 'd4', k: 'box', x: 600, y: 220, w: 300, h: 44, t: 'Nutzdaten', s: 'ok'}, {id: 'tr', k: 'box', x: 780, y: 220, w: 60, h: 44, t: 'FCS', s: 'solid'},
  ], edges: []}],
  ['note', 'Entscheidend ist die Reihenfolge: Ganz außen sitzt der Header der **untersten** Schicht. Der Trailer **FCS** (Frame Check Sequence) ist die Prüfsumme zur Fehlererkennung.'],
  ['h', 'Beispiel: Aufruf einer Webseite'],
  ['steps', ['**Schicht 7:** Der Browser erzeugt eine **HTTP-Anfrage** ("GET /index.html").', '**Schicht 6/5:** Die Daten werden ggf. verschlüsselt (TLS) und die Sitzung verwaltet.', '**Schicht 4:** TCP teilt die Daten in **Segmente**, setzt **Quellport** (zum Beispiel 51234) und **Zielport** (443) davor.', '**Schicht 3:** IP verpackt jedes Segment in ein **Paket** mit **Quell-IP** und **Ziel-IP**. Der Router entscheidet anhand der Ziel-IP über den Weg.', '**Schicht 2:** Ethernet verpackt das Paket in einen **Frame** mit **MAC-Adresse** des nächsten Geräts (zum Beispiel Router) und der Prüfsumme.', '**Schicht 1:** Der Frame wird als **Bits** über Kabel oder Funk übertragen. Der Empfänger entkapselt in umgekehrter Reihenfolge.']],
  ['h', 'Fehlersuche mit dem Schichtenmodell'],
  ['p', 'Bei einer Störung geht man **Schicht für Schicht** vor (Bottom-up, von unten nach oben) und grenzt das Problem ein:'],
  ['table', ['Symptom', 'Wahrscheinliche Schicht', 'Prüfung'], [
    ['Kein Link-Licht an der Netzwerkkarte, Kabel defekt', '**1** Bitübertragung', 'Kabel, Stecker, Strom'],
    ['Gerät bekommt keine MAC-Zuordnung, VLAN falsch, Switch-Port deaktiviert', '**2** Sicherung', 'Switch-Port, VLAN, ARP-Tabelle'],
    ['IP-Adresse falsch, Gateway fehlt, Ping zu einer anderen Subnetz-Adresse scheitert', '**3** Vermittlung', '`ipconfig`, `ping`, `traceroute`'],
    ['Ping geht, aber Dienst erreichbar nicht: Port blockiert (Firewall)', '**4** Transport', '`telnet host port`, Firewall-Regeln'],
    ['Webseite nicht erreichbar, IP geht, Name nicht: DNS-Fehler', '**7** Anwendung', '`nslookup`, Anwendungsprotokoll'],
  ]],
  ['h', 'Aufgaben im Prüfungsstil'],
  ['qa', 'Ordnen Sie den OSI-Schichten zu: a) Router, b) Switch, c) Hub, d) TCP, e) MAC-Adresse, f) HTTP.', ['- a) Router: **Schicht 3** (Vermittlung)', '- b) Switch: **Schicht 2** (Sicherung)', '- c) Hub: **Schicht 1** (Bitübertragung)', '- d) TCP: **Schicht 4** (Transport)', '- e) MAC-Adresse: **Schicht 2**', '- f) HTTP: **Schicht 7** (Anwendung)'], 6],
  ['qa', 'Erklären Sie den Begriff Kapselung im OSI-Modell.', 'Beim Senden fügt jede Schicht den Daten der darüberliegenden Schicht ihre **eigenen Steuerinformationen** (Header, auf Schicht 2 auch Trailer) hinzu. Dadurch entstehen aus Daten Segmente, Pakete und Frames. Der Empfänger entfernt die Header schichtweise wieder (Entkapselung).', 4],
  ['qa', 'Wie nennt man die Dateneinheit auf Schicht 2, 3 und 4?', ['- Schicht 2: **Frame**', '- Schicht 3: **Paket**', '- Schicht 4: **Segment** (TCP) bzw. **Datagramm** (UDP)'], 3],
  ['quiz', [
    {q: 'Auf welcher Schicht arbeitet ein Router?', o: ['Schicht 3 (Vermittlung)', 'Schicht 2 (Sicherung)', 'Schicht 1 (Bitübertragung)', 'Schicht 7 (Anwendung)'], a: 0, e: 'Router arbeiten mit IP-Adressen und damit auf Schicht 3.'},
    {q: 'Wie heißt die Dateneinheit auf Schicht 2?', o: ['Frame', 'Paket', 'Segment', 'Bit'], a: 0, e: 'Schicht 2: Frame, Schicht 3: Paket, Schicht 4: Segment.'},
    {q: 'Welche Schicht ist für Ports und die Zuverlässigkeit der Ende-zu-Ende-Verbindung zuständig?', o: ['Transportschicht (4)', 'Sicherungsschicht (2)', 'Darstellungsschicht (6)', 'Bitübertragungsschicht (1)'], a: 0, e: 'TCP und UDP arbeiten auf der Transportschicht mit Portnummern.'},
    {q: 'Was passiert bei der Kapselung?', o: ['Jede Schicht fügt einen Header hinzu', 'Daten werden gelöscht', 'Nur Schicht 7 fügt Daten hinzu', 'Der Router verschlüsselt alles'], a: 0, e: 'Kapselung bedeutet: Daten werden mit Steuerinformationen jeder Schicht "verpackt".'},
    {q: 'Welches Gerät arbeitet mit MAC-Adressen?', o: ['Switch', 'Hub', 'Repeater', 'Kabel'], a: 0, e: 'Ein Switch leitet Frames anhand der MAC-Adresse (Schicht 2).'},
    {q: 'Wo wird DNS im OSI-Modell eingeordnet?', o: ['Schicht 7 (Anwendung)', 'Schicht 3', 'Schicht 1', 'Schicht 2'], a: 0, e: 'DNS ist ein Anwendungsprotokoll.'},
  ]],
]);
