AP2.add('infra-ports', [
  ['h', 'DHCP: Automatische IP-Konfiguration'],
  ['p', 'Ohne DHCP müsste man für jedes Gerät IP-Adresse, Subnetzmaske, Gateway und DNS-Server von Hand eintragen. Der **DHCP-Server** vergibt diese Werte automatisch für eine bestimmte Zeit (**Lease**). Weil der Client anfangs keine IP-Adresse hat, läuft der Ablauf mit **Broadcasts** ab: **DORA**.'],
  ['seq', {w: 700, actors: ['Client (ohne IP)', 'DHCP-Server'], cap: 'DHCP-Ablauf DORA (UDP Port 68 Client, 67 Server)', steps: [
    [0, 1, 'DHCP Discover (Broadcast: Wer ist DHCP-Server?)', 's'], [1, 0, 'DHCP Offer (Angebot: 192.168.1.50 /24, GW .1, DNS .1)', 'r'], [0, 1, 'DHCP Request (Ich nehme 192.168.1.50)', 's'], [1, 0, 'DHCP Acknowledge (bestätigt, Lease 24 h)', 'r'],
  ]}],
  ['list', ['**Lease-Zeit:** Die Adresse wird nur geliehen und muss rechtzeitig **erneuert** werden.', '**Reservierung:** Der Server gibt einem Gerät anhand der **MAC-Adresse** immer dieselbe IP (zum Beispiel für Drucker).', '**Scope (Bereich):** Der Adresspool des Servers, zum Beispiel 192.168.1.100 bis 192.168.1.200.', '**DHCP-Relay:** Leitet DHCP-Anfragen über Router in andere Subnetze, damit ein Server mehrere Netze versorgen kann.', '**Ausfall:** Antwortet kein DHCP-Server, vergibt sich das Gerät eine **169.254.x.x** (APIPA).']],
  ['h', 'HTTP und HTTPS'],
  ['p', '**HTTP** (Hypertext Transfer Protocol) ist ein **Anfrage-Antwort-Protokoll**: Der Client schickt eine **Anfrage** (Request) mit einer Methode, der Server antwortet mit einem **Statuscode**. **HTTPS** ist HTTP **über TLS**: Die Verbindung ist **verschlüsselt** und der Server wird per **Zertifikat** authentifiziert.'],
  ['table', ['Methode', 'Bedeutung', 'Typischer Einsatz (REST)'], [['GET', 'Ressource lesen', 'Artikel anzeigen'], ['POST', 'Neue Ressource anlegen / Daten senden', 'Bestellung aufgeben'], ['PUT', 'Ressource vollständig ersetzen', 'Kundendaten komplett aktualisieren'], ['PATCH', 'Teil einer Ressource ändern', 'Nur E-Mail-Adresse ändern'], ['DELETE', 'Ressource löschen', 'Konto löschen']]],
  ['table', ['Statuscode', 'Bedeutung'], [['**200 OK**', 'Erfolg'], ['**201 Created**', 'Ressource wurde angelegt'], ['**301 / 302**', 'Weiterleitung (dauerhaft / temporär)'], ['**400 Bad Request**', 'Fehlerhafte Anfrage'], ['**401 Unauthorized**', 'Anmeldung nötig'], ['**403 Forbidden**', 'Zugriff verboten (angemeldet, aber nicht berechtigt)'], ['**404 Not Found**', 'Ressource nicht gefunden'], ['**500 Internal Server Error**', 'Fehler im Server']]],
  ['tip', 'Merke die Gruppen: **2xx** = Erfolg, **3xx** = Weiterleitung, **4xx** = Fehler des **Clients**, **5xx** = Fehler des **Servers**.'],
  ['h', 'E-Mail-Protokolle'],
  ['diagram', {w: 760, h: 180, keep: 620, cap: 'Weg einer E-Mail: Senden mit SMTP, Abholen mit IMAP oder POP3.', nodes: [
    {id: 'a', k: 'round', x: 80, y: 90, t: ['Absender', 'Mail-Programm'], w: 130, h: 56}, {id: 'b', k: 'round', x: 270, y: 90, t: ['Mailserver', 'des Absenders'], w: 130, h: 56, s: 'accent'}, {id: 'c', k: 'round', x: 460, y: 90, t: ['Mailserver', 'des Empfängers'], w: 130, h: 56, s: 'accent'}, {id: 'd', k: 'round', x: 670, y: 90, t: ['Empfänger', 'Mail-Programm'], w: 130, h: 56},
  ], edges: [{a: 'a', b: 'b', t: 'SMTP'}, {a: 'b', b: 'c', t: 'SMTP'}, {a: 'd', b: 'c', t: 'IMAP / POP3', lo: [0, 12]}]}],
  ['table', ['Protokoll', 'Aufgabe', 'Merkmal'], [['**SMTP**', 'E-Mail senden und zwischen Servern weiterleiten', 'Nur Senden'], ['**POP3**', 'E-Mails vom Server abholen', 'Meist vom Server löschen, nur ein Gerät'], ['**IMAP**', 'E-Mails auf dem Server verwalten', 'Mails bleiben auf dem Server, mehrere Geräte synchron']]],
  ['h', 'FTP: Dateiübertragung'],
  ['p', '**FTP** nutzt **zwei Verbindungen**: Port **21** für Befehle (Steuerung) und Port **20** oder einen dynamischen Port für die Daten. Es gibt **aktiven** Modus (Server baut Datenverbindung zum Client auf, Probleme mit Firewalls) und **passiven** Modus (Client baut beide Verbindungen auf). FTP überträgt **Passwörter im Klartext**. Sicher sind **SFTP** (über SSH, Port 22) und **FTPS** (FTP über TLS).'],
  ['h', 'ODBC: Zugriff auf Datenbanken'],
  ['p', '**ODBC** (Open Database Connectivity) ist eine **standardisierte Programmierschnittstelle** (API) für den Zugriff auf Datenbanken. Eine Anwendung spricht nur ODBC. Ein **ODBC-Treiber** übersetzt die Aufrufe in die Sprache der jeweiligen Datenbank (MySQL, Oracle, SQL Server). Dadurch bleibt die Anwendung **unabhängig vom Datenbankhersteller**. Die Verbindung wird über einen **Data Source Name (DSN)** konfiguriert. ODBC ist **kein Netzwerkprotokoll** und hat keinen eigenen Port; es nutzt den **Port der Datenbank** (zum Beispiel 3306 bei MySQL). Das Java-Gegenstück ist **JDBC**.'],
  ['diagram', AP2.dg.flow(['Anwendung', 'ODBC-Treiber-Manager', 'ODBC-Treiber', 'Datenbank (SQL Server, MySQL ...)'], {w: 760, h: 100, styles: ['accent', 'soft', 'soft', 'ok'], cap: 'ODBC: Die Anwendung ist von der konkreten Datenbank entkoppelt.'})],
]);
