AP2.add('infra-raid', [
  ['h3', 'RAID 5: Striping mit verteilter Parität'],
  ['p', 'Die Daten werden verteilt und zusätzlich wird ein **Paritätsblock** berechnet. Die Parität liegt **abwechselnd auf allen Platten**. **Eine** Platte darf ausfallen. Mindestens **3 Platten**. Nutzkapazität: **(n - 1)** Platten. Lesen schnell, **Schreiben langsamer** (Parität muss berechnet werden, "Write Penalty").'],
  ['diagram', AP2.raidDiagrams.r5],
  ['h3', 'RAID 6: doppelte Parität'],
  ['p', 'Wie RAID 5, aber mit **zwei unabhängigen Paritätsblöcken (P und Q)**. **Zwei** Platten dürfen gleichzeitig ausfallen. Mindestens **4 Platten**. Nutzkapazität: **(n - 2)** Platten. Sinnvoll bei **großen Platten**, weil der Rebuild lange dauert und in dieser Zeit eine zweite Platte ausfallen könnte.'],
  ['diagram', AP2.raidDiagrams.r6],
  ['h3', 'RAID 10 (1+0): Spiegel plus Striping'],
  ['p', 'Zuerst werden Plattenpaare **gespiegelt** (RAID 1), dann werden die Paare **zusammengefasst** (RAID 0). Mindestens **4 Platten**, Nutzkapazität **50 Prozent**. **Schnell** beim Lesen und Schreiben und **sehr sicher**: Pro Spiegelpaar darf eine Platte ausfallen. Fällt aber **beide Platten eines Paares** aus, sind die Daten verloren. Gut für Datenbanken.'],
  ['diagram', AP2.raidDiagrams.r10],
  ['table', ['Level', 'Min. Platten', 'Nutzkapazität', 'Ausfalltoleranz', 'Lesen', 'Schreiben', 'Typischer Einsatz'], [
    ['**RAID 0**', '2', 'n mal c (100 %)', 'keine', 'sehr gut', 'sehr gut', 'Temporäre Daten, Tempo'],
    ['**RAID 1**', '2', 'c (50 %)', '1 Platte', 'gut', 'normal', 'Betriebssystem, kleine Server'],
    ['**RAID 5**', '3', '(n-1) mal c', '1 Platte', 'gut', 'mittel (Parität)', 'Dateiserver, allgemeine Server'],
    ['**RAID 6**', '4', '(n-2) mal c', '2 Platten', 'gut', 'langsamer', 'Große Arrays, Archive'],
    ['**RAID 10**', '4', 'n/2 mal c (50 %)', '1 je Spiegelpaar', 'sehr gut', 'sehr gut', 'Datenbanken, hohe Last'],
  ]],
  ['note', 'Es gibt weitere Kombinationen: **RAID 01** (zuerst Striping, dann Spiegel), **RAID 50** und **RAID 60** (RAID 5/6 Gruppen, die gestriped werden) sowie **JBOD** ("Just a Bunch Of Disks": einfach zusammengefasst, ohne Redundanz). **RAID 2, 3 und 4** sind veraltet.'],
  ['h', 'Kapazität berechnen: Schema'],
  ['steps', ['**Level, Anzahl n und Größe c** der Platten ablesen.', 'Formel des Levels anwenden (siehe Tabelle).', 'Einheit angeben (TB, GB). Bei Dezimal-Angaben des Herstellers rechnen (1 TB = 1000 GB), das Betriebssystem zeigt oft weniger an.']],
  ['ex', ['**6 Platten mit je 4 TB:**', 'RAID 0: 6 mal 4 = **24 TB**', 'RAID 5: (6 - 1) mal 4 = **20 TB**', 'RAID 6: (6 - 2) mal 4 = **16 TB**', 'RAID 10: (6 / 2) mal 4 = **12 TB**', 'RAID 1: nur 2 Platten möglich, 4 TB (bei 6 Platten: Mehrfachspiegel).']],
  ['tool', 'raid'],
  ['h', 'Hot Spare, Rebuild und Grenzen'],
  ['list', ['**Hot Spare:** Eine zusätzliche Platte, die im Normalbetrieb ungenutzt ist und beim Ausfall automatisch einspringt (**Rebuild** beginnt sofort).', '**Rebuild:** Wiederherstellung der Daten auf der Ersatzplatte. Dauert bei großen Platten **Stunden bis Tage**, in dieser Zeit sinkt Leistung und Redundanz.', '**Hot Swap:** Platte kann im laufenden Betrieb getauscht werden.', '**Hardware- und Software-RAID:** Ein **RAID-Controller** (mit Cache und Batterie) übernimmt die Arbeit, oder das Betriebssystem (Windows Storage Spaces, Linux mdadm, ZFS).']],
  ['warn', ['**RAID ist kein Backup!** RAID schützt nur vor dem **Ausfall einer Platte**. Es schützt **nicht** vor versehentlichem Löschen, Viren und Ransomware, Softwarefehlern, Brand, Diebstahl oder einem Controller-Defekt. Auch ein gespiegeltes Löschen ist ein Löschen.']],
  ['h', 'Aufgaben im Prüfungsstil'],
  ['qa', 'Ein Server soll mit 5 Festplatten zu je 2 TB als RAID 5 betrieben werden. Berechnen Sie die Nutzkapazität und nennen Sie die Ausfalltoleranz.', ['Nutzkapazität = (n - 1) mal c = (5 - 1) mal 2 TB = **8 TB**.', 'Ausfalltoleranz: **eine** Platte darf ausfallen (die Kapazität einer Platte, 2 TB, wird für die Parität verwendet).'], 4],
  ['qa', 'Vergleichen Sie RAID 5 und RAID 10 für einen Datenbankserver. Wofür entscheiden Sie sich?', 'RAID 10 ist beim **Schreiben deutlich schneller**, weil keine Parität berechnet werden muss, und beim Rebuild nur eine Platte kopiert wird. Nachteil: Nutzkapazität nur 50 Prozent. RAID 5 bietet mehr Kapazität, schreibt aber langsamer (Write Penalty). Für **schreibintensive Datenbanken** ist **RAID 10** die bessere Wahl.', 5],
  ['qa', 'Warum ersetzt ein RAID-System keine Datensicherung?', 'RAID schützt nur vor dem Ausfall von Festplatten. Datenverlust durch Bedienfehler, Schadsoftware (Ransomware), Softwarefehler, Controller-Defekt, Brand oder Diebstahl wird auf alle Platten repliziert bzw. betrifft das ganze System. Nur ein getrenntes Backup (Kopie an anderem Ort) ermöglicht die Wiederherstellung früherer Stände.', 4],
  ['qa', 'Wie viele Platten dürfen bei RAID 6 ausfallen und warum setzt man RAID 6 bei sehr großen Platten ein?', '**Zwei** Platten. Bei großen Platten dauert der Rebuild lange; in dieser Zeit könnte eine zweite Platte ausfallen (oder ein Lesefehler auftreten). RAID 6 verkraftet das, RAID 5 nicht.', 3],
  ['quiz', [
    {q: 'Welches RAID-Level bietet KEINE Ausfallsicherheit?', o: ['RAID 0', 'RAID 1', 'RAID 5', 'RAID 6'], a: 0, e: 'RAID 0 (Striping) hat keine Redundanz. Eine ausgefallene Platte zerstört alle Daten.'},
    {q: '4 Platten mit je 1 TB im RAID 5: Wie groß ist die Nutzkapazität?', o: ['3 TB', '4 TB', '2 TB', '1 TB'], a: 0, e: '(4 - 1) mal 1 TB = 3 TB.'},
    {q: 'Wie viele Platten braucht RAID 10 mindestens?', o: ['4', '2', '3', '6'], a: 0, e: 'Zwei Spiegelpaare, die gestriped werden: mindestens 4 Platten.'},
    {q: 'Wie viele Platten dürfen bei RAID 6 gleichzeitig ausfallen?', o: ['2', '1', '3', '0'], a: 0, e: 'RAID 6 hat doppelte Parität.'},
    {q: '8 Platten je 3 TB als RAID 10: Nutzkapazität?', o: ['12 TB', '24 TB', '21 TB', '18 TB'], a: 0, e: '(8 / 2) mal 3 TB = 12 TB.'},
    {q: 'Wofür dient ein Hot Spare?', o: ['Er springt bei Plattenausfall automatisch ein', 'Er beschleunigt das Lesen', 'Er ersetzt das Backup', 'Er kühlt den Server'], a: 0, e: 'Eine Reserveplatte startet nach dem Ausfall automatisch den Rebuild.'},
  ]],
]);
