AP2.add('infra-tls', [
  ['h', 'TLS 1.3: schneller und sicherer'],
  ['table', ['Merkmal', 'TLS 1.2', 'TLS 1.3'], [['Handshake', '2 Round-Trips', '**1 Round-Trip** (Client schickt Schlüsselanteil schon im ClientHello), optional 0-RTT'], ['Cipher Suites', 'Viele, auch veraltete möglich', 'Nur wenige, **moderne** (AEAD wie AES-GCM, ChaCha20)'], ['Schlüsselaustausch', 'RSA oder (EC)DHE', '**Nur (EC)DHE** (immer Forward Secrecy)'], ['Zertifikat', 'Im Klartext übertragen', 'Verschlüsselt'], ['Veraltete Verfahren', 'Teils unterstützt (RC4, 3DES, SHA-1)', 'Entfernt']]],
  ['kv', [
    ['Perfect Forward Secrecy (PFS)', 'Für **jede Sitzung** wird ein **neuer, temporärer Schlüssel** ausgehandelt. Wird der private Schlüssel des Servers später gestohlen, lassen sich **aufgezeichnete alte Verbindungen nicht entschlüsseln**.'],
    ['Cipher Suite', 'Kombination der Verfahren, zum Beispiel `TLS_AES_256_GCM_SHA384` (TLS 1.3: AES-256 im GCM-Modus, Hash SHA-384). Bei TLS 1.2 stehen auch Schlüsselaustausch und Signatur im Namen (zum Beispiel ECDHE-RSA-AES256-GCM-SHA384).'],
    ['SNI (Server Name Indication)', 'Der Client nennt im ClientHello den gewünschten Hostnamen. So kann ein Server mit **mehreren Domains** das passende Zertifikat wählen.'],
    ['HSTS', 'HTTP Strict Transport Security: Der Server weist den Browser an, die Domain **nur noch per HTTPS** zu verwenden. Schützt vor Downgrade-Angriffen.'],
  ]],
  ['h', 'mTLS: Beide Seiten weisen sich aus'],
  ['p', 'Bei normalem TLS beweist nur der **Server** seine Identität. Der Client bleibt anonym (er meldet sich später mit Benutzername/Passwort an). Bei **mTLS** (mutual TLS) sendet der Server zusätzlich eine **CertificateRequest**, und der **Client** schickt sein **Client-Zertifikat** samt Signatur. Beide prüfen die Zertifikate des anderen anhand einer vertrauenswürdigen CA.'],
  ['seq', {w: 780, actors: ['Client (Dienst A)', 'Server (Dienst B)'], cap: 'mTLS: Zusätzlich zum Serverzertifikat fordert der Server ein Clientzertifikat an.', steps: [
    [0, 1, 'ClientHello', 's'], [1, 0, 'ServerHello, Serverzertifikat', 'r'], [1, 0, 'CertificateRequest (bitte Clientzertifikat)', 'r'], [0, 0, 'Serverzertifikat prüfen', 's'], [0, 1, 'Clientzertifikat + Signatur (Besitz des privaten Schlüssels)', 's'], [1, 1, 'Clientzertifikat prüfen (CA, Gültigkeit, Sperrung)', 's'], [0, 1, 'Finished', 's'], [1, 0, 'Finished', 'r'], ['sep', 'Beide Seiten sind authentifiziert, Verbindung verschlüsselt'],
  ]}],
  ['procon', 'mTLS', ['**Starke gegenseitige Authentifizierung**: Nur Geräte und Dienste mit gültigem Zertifikat kommen durch', 'Kein Passwort nötig, kaum Phishing-anfällig', 'Passt zu **Zero Trust**, Microservices, APIs, IoT-Geräten, B2B-Schnittstellen'], ['**Verwaltungsaufwand**: Zertifikate für alle Clients ausstellen, verteilen, erneuern, sperren (PKI nötig)', 'Fehlersuche komplexer (abgelaufene Zertifikate)', 'Für öffentliche Webseiten mit anonymen Besuchern ungeeignet']],
  ['table', ['Einsatzbereich', 'Normales TLS', 'mTLS'], [['Öffentlicher Webshop (Kunden anonym)', 'Ja', 'Nein'], ['Service-zu-Service-Kommunikation (Microservices)', 'Unzureichend', 'Ja'], ['VPN und Netzwerkzugang (802.1X mit Zertifikaten)', '-', 'Ja'], ['Bank-API (B2B)', 'Als Basis', 'Ja (zusätzliche Client-Authentifizierung)']]],
  ['h', 'Aufgaben im Prüfungsstil'],
  ['qa', 'Beschreiben Sie in fünf Schritten den Ablauf eines TLS-Handshakes.', ['1. **ClientHello**: Client sendet unterstützte Versionen, Cipher Suites, Zufallswert.', '2. **ServerHello**: Server wählt Verfahren, sendet sein **Zertifikat**.', '3. Client **prüft das Zertifikat** (Kette, Hostname, Gültigkeit, Sperrung).', '4. **Schlüsselaustausch** (ECDHE): Beide berechnen einen gemeinsamen Sitzungsschlüssel.', '5. **Finished**-Nachrichten bestätigen den Handshake, danach werden Daten **symmetrisch verschlüsselt**.'], 5],
  ['qa', 'Warum verwendet TLS zuerst asymmetrische und dann symmetrische Verschlüsselung?', 'Asymmetrische Verfahren lösen das **Schlüsselaustausch- und Authentifizierungsproblem**, sind aber **rechenintensiv**. Symmetrische Verfahren sind **sehr schnell**. TLS nutzt deshalb asymmetrische Verfahren nur im Handshake, um einen **gemeinsamen Sitzungsschlüssel** zu vereinbaren, und verschlüsselt die Nutzdaten danach symmetrisch.', 4],
  ['qa', 'Worin unterscheidet sich mTLS von TLS und wann setzt man es ein?', 'Bei TLS authentifiziert sich nur der **Server** per Zertifikat. Bei **mTLS** muss sich zusätzlich der **Client** mit einem Zertifikat ausweisen, beide Seiten prüfen sich gegenseitig. Einsatz: Kommunikation zwischen Diensten/Microservices, API-Zugriffe, Geräteauthentifizierung, Zero-Trust-Umgebungen.', 4],
  ['qa', 'Eine HTTPS-Seite zeigt "Zertifikat abgelaufen". Nennen Sie mögliche Folgen und die Lösung.', 'Browser warnen und blockieren den Zugriff oder Nutzer verlieren das Vertrauen. API-Clients können Verbindungen verweigern (Ausfall). **Lösung:** Neues Zertifikat beantragen und installieren, künftig **automatische Erneuerung** (ACME) und Ablaufüberwachung einrichten.', 4],
  ['quiz', [
    {q: 'Welcher Port wird für HTTPS verwendet?', o: ['443', '80', '22', '8080'], a: 0, e: 'HTTPS nutzt TCP-Port 443.'},
    {q: 'Welche Verschlüsselung schützt die Nutzdaten nach dem TLS-Handshake?', o: ['Symmetrische Verschlüsselung', 'Asymmetrische Verschlüsselung', 'Gar keine', 'Hashing'], a: 0, e: 'Nach dem Handshake wird mit dem Sitzungsschlüssel symmetrisch verschlüsselt (zum Beispiel AES).'},
    {q: 'Was bedeutet mTLS?', o: ['Beide Seiten authentifizieren sich mit Zertifikaten', 'Mobile TLS', 'Multi-Thread TLS', 'Minimal TLS'], a: 0, e: 'Mutual TLS: gegenseitige Authentifizierung.'},
    {q: 'Was bewirkt Perfect Forward Secrecy?', o: ['Alte aufgezeichnete Sitzungen bleiben auch nach Schlüsseldiebstahl geschützt', 'Die Verbindung wird schneller', 'Der Server braucht kein Zertifikat', 'Es gibt keine Cipher Suites'], a: 0, e: 'Jede Sitzung hat einen eigenen temporären Schlüssel.'},
    {q: 'Welche Version gilt als aktuell und besonders sicher?', o: ['TLS 1.3', 'SSL 3.0', 'TLS 1.0', 'SSL 2.0'], a: 0, e: 'SSL und frühe TLS-Versionen sind veraltet.'},
  ]],
]);
