AP2.page('infra-usv', {
  b: 'infra', g: 'Storage und Verfügbarkeit', t: 'USV, Stromversorgung und Serverausstattung für hohe Verfügbarkeit',
  d: 'Eine **USV** (unterbrechungsfreie Stromversorgung) überbrückt **Stromausfälle** und schützt vor **Spannungsschwankungen**, Spitzen und Störungen, bis der Strom zurückkommt oder die Server **geordnet heruntergefahren** sind. Man unterscheidet nach **IEC 62040-3** drei Klassen: **VFD** (Offline/Standby), **VI** (Line-Interactive) und **VFI** (Online/Doppelwandler, Dauerwandler). Für die **Dimensionierung** addiert man die Leistung aller angeschlossenen Geräte, plant eine **Reserve** ein und rechnet bei Bedarf mit dem **Leistungsfaktor** von Wirkleistung (W) in Scheinleistung (VA) um.',
  m: '**USV-Größe = Summe Wirkleistung · (1 + Reserve), dann nächstgrößeres Modell.** **Scheinleistung S (VA) = Wirkleistung P (W) / cos φ.** **VFI (Online) = beste Qualität, ständig über Wechselrichter, keine Umschaltzeit.** **Überbrückungszeit hängt von der Auslastung ab: Last in % = Verbrauch / Nennleistung.** **Server für hohe Verfügbarkeit: RAID, redundante Netzteile, ECC-RAM, Hot-Swap, USV.**',
  cheat: [
    ['USV-Klassen', ['**VFD** Offline: schaltet erst bei Ausfall um (ms)', '**VI** Line-Interactive: regelt Spannung', '**VFI** Online/Doppelwandler: immer über Akku-Wechselrichter', 'Server/Rechenzentrum: VFI']],
    ['Formeln', ['P = U · I (W)', 'S = P / cos φ (VA)', 'Gesamt = Summe der Geräte', 'mit 30 % Reserve: · 1,3']],
    ['Energie', ['E = P · t (kWh)', 'Kosten = kWh · Preis', '24/7: 8760 h pro Jahr', 'Einsparung % = (alt - neu) / alt · 100']],
    ['Server-Hardware', ['RAID 1/5/6/10, Hot-Spare', 'redundante Netzteile (2 Stromkreise)', 'ECC-RAM, SSD/NVMe, viele Kerne', 'Remote-Management (iLO/iDRAC)']],
  ],
  blocks: [
    ['h', 'Wovor schützt eine USV?'],
    ['list', [
      '**Stromausfall** (Blackout): Akku übernimmt die Versorgung.',
      '**Unter- und Überspannung**, **Spannungsspitzen** (Blitz, Schalthandlungen), **Frequenzschwankungen**, Oberschwingungen.',
      'Dadurch: kein **Datenverlust** durch abrupten Ausfall, keine **beschädigten Dateisysteme oder Datenbanken**, keine Hardwareschäden.',
      'Über die USV-Software (USB/Netzwerk) werden Server bei längerem Ausfall **automatisch geordnet heruntergefahren**.',
    ]],
    ['p', '**Schutzziele (AP1 Winter 2024/25):** Die USV erhöht vor allem die **Verfügbarkeit** (Systeme laufen weiter) und die **Integrität** (Daten werden nicht durch abrupte Abschaltung beschädigt, Schreibvorgänge werden abgeschlossen).'],
    ['h', 'Die drei USV-Klassen'],
    ['table', ['Klasse', 'Funktionsweise', 'Umschaltzeit', 'Einsatz'], [
      ['**VFD** (Voltage and Frequency Dependent), Offline/Standby', 'Geräte hängen direkt am Netz; erst bei Ausfall schaltet die USV auf den Akku-Wechselrichter um', '2 bis 10 ms', 'Einzelne PCs, günstig'],
      ['**VI** (Voltage Independent), Line-Interactive', 'Wie Offline, aber ein Spannungsregler gleicht Unter- und Überspannung ohne Akku aus', 'ca. 2 bis 4 ms', 'Kleine Server, Netzwerktechnik'],
      ['**VFI** (Voltage and Frequency Independent), Online/Doppelwandler (Dauerwandler)', 'Netzstrom wird **ständig** gleichgerichtet und über den Wechselrichter neu erzeugt; der Verbraucher ist völlig vom Netz entkoppelt', '**0 ms**, reine Sinuswelle', 'Server, Rechenzentren, Medizintechnik'],
    ]],
    ['h', 'USV dimensionieren (AP1 Winter 2025/26)'],
    ['p', 'Abzusichern: Server 1000 W, Firewall 30 W, Router 50 W, Switch (PoE) 33 W, zwei WLAN-Access-Points je 18 W. Überbrückung mindestens 5 Minuten, **30 % Reserve** für Erweiterungen. Angebotene Modelle (Online-USV): P1000 = 900 W, P1500 = 1350 W, P2200 = 1980 W, P3000 = 2700 W; je 6 Minuten bei 100 % Last.'],
    ['steps', [
      'Summe der Leistungen: 1000 + 30 + 50 + 33 + 2 · 18 = **1149 W**.',
      'Mit 30 % Reserve: 1149 W · 1,3 = **1493,7 W**.',
      'Nächstgrößeres Modell wählen: P1500 (1350 W) reicht **nicht**, also **P2200 (1980 W)**.',
      'Überbrückungszeit: Bei 100 % Last hält jedes Modell 6 Minuten, also auch die geforderten 5 Minuten. Bei geringerer Last länger.',
      'Tatsächliche Auslastung: 1149 W / 1980 W = **58 %**. Im Diagramm "Überbrückungszeit über Last" bei 58 % ablesen (bei etwa halber Last oft das Doppelte bis Dreifache der Volllastzeit).',
    ]],
    ['h3', 'Mit Scheinleistung rechnen (AP1 Winter 2024/25)'],
    ['p', 'Netzteile nehmen neben der **Wirkleistung P** (Watt, wird tatsächlich in Arbeit und Wärme umgesetzt) auch **Blindleistung** auf. Die **Scheinleistung S** in **Voltampere (VA)** ist das, was die USV liefern muss. Zusammenhang über den **Leistungsfaktor cos φ** (0 bis 1, bei modernen Netzteilen mit PFC 0,9 bis 0,99):'],
    ['ex', ['**S = P / cos φ**. Ein Server mit 450 W und cos φ = 0,9: S = 450 W / 0,9 = **500 VA**.', 'Geräte: Server 450 W (cos φ 0,9), Switch 60 W (0,8), Firewall 40 W (0,8). S = 500 + 75 + 50 = **625 VA**. Mit 25 % Reserve: 625 VA · 1,25 = **781 VA** -> USV mit mindestens 800 VA (und genug Watt!).']],
    ['warn', 'USVs haben **zwei** Grenzen: VA **und** Watt (zum Beispiel "1500 VA / 900 W"). Beide müssen eingehalten werden. Viele Fehler entstehen, weil nur die VA-Angabe verglichen wird.'],
    ['h', 'Welche Geräte gehören an die USV?'],
    ['list', [
      '**Ja:** Server, Speichersysteme (NAS/SAN), Firewall, Router, Core- und wichtige Access-Switches, WLAN-APs für kritische Dienste, Telefonanlage.',
      '**Nein (meist):** Laserdrucker (hoher Anlaufstrom, nicht kritisch), Arbeitsplatz-PCs (außer kritische), Kaffeemaschine, Heizlüfter.',
    ]],
    ['h', 'Stromkosten berechnen (AP1 Winter 2023/24)'],
    ['ex', ['Ein Netzwerk verbraucht dauerhaft 420 W, Strompreis 0,30 €/kWh. Jahreskosten?', 'Energie: 0,42 kW · 24 h · 365 = 0,42 kW · 8760 h = **3679,2 kWh**.', 'Kosten: 3679,2 kWh · 0,30 €/kWh = **1103,76 €**.', 'Neue Geräte verbrauchen nur 300 W: Einsparung = (420 - 300) / 420 · 100 = **28,6 %**.']],
    ['h', 'Serveranforderungen für kurze Zugriffszeiten und hohe Verfügbarkeit (AP1 Winter 2025/26, 8 Punkte)'],
    ['table', ['Anforderung', 'Begründung'], [
      ['**SSD/NVMe-Speicher**', 'Sehr kurze Zugriffszeiten und hohe IOPS auch bei vielen gleichzeitigen Zugriffen'],
      ['**Leistungsstarke Mehrkern-CPU** (bzw. 2 Sockel)', 'Viele parallele Anfragen ohne Wartezeit'],
      ['**Viel Arbeitsspeicher**, **ECC-RAM**', 'Cache für Daten, weniger Plattenzugriffe; ECC erkennt und korrigiert Bitfehler (Integrität, Stabilität)'],
      ['**RAID** (1, 5, 6 oder 10) mit **Hot-Swap** und Hot-Spare', 'Ausfall einer Platte führt nicht zum Datenverlust oder Stillstand, Tausch im laufenden Betrieb'],
      ['**Redundante, hot-swap-fähige Netzteile** an getrennten Stromkreisen', 'Ausfall eines Netzteils oder Stromkreises legt den Server nicht lahm'],
      ['**Redundante Netzwerkkarten** (Teaming/Bonding), schnelle Anbindung (10 GbE)', 'Kein Ausfall bei Defekt eines Ports/Kabels, hoher Durchsatz'],
      ['**Remote-Management** (iLO, iDRAC, IPMI), Herstellersupport mit kurzer Reaktionszeit', 'Fehlerbehebung auch nachts und am Wochenende'],
    ]],
    ['h3', 'Maßnahmen für hohe Verfügbarkeit rund um die Uhr (Winter 2025/26, 3 Punkte)'],
    ['list', ['**RAID 1, 5 oder 10**', '**redundantes Netzteil** im Server', '**redundanter Server** (Cluster, Failover, Virtualisierung mit Hochverfügbarkeit)', '**USV** (und eventuell Netzersatzanlage/Generator)', 'Monitoring mit Alarmierung, Wartungsvertrag, Klimatisierung des Serverraums']],
    ['h', 'Aufgaben im Prüfungsstil'],
    ['qa', 'Geräte: Server 600 W, NAS 80 W, Firewall 25 W, Switch 45 W. Es sollen 20 % Reserve eingeplant werden. Welche USV wählen Sie aus 600 W, 900 W und 1350 W?', ['Summe: 600 + 80 + 25 + 45 = 750 W.', 'Mit Reserve: 750 W · 1,2 = **900 W**.', '900 W genügt genau; zur Sicherheit (Alterung des Akkus, Anlaufströme) besser das **1350-W-Modell**. Die Begründung muss den Rechenweg enthalten.'], 5],
    ['qa', 'Erläutern Sie den Unterschied zwischen einer Offline-USV (VFD) und einer Online-USV (VFI).', ['**Offline (VFD):** Die Verbraucher werden im Normalbetrieb direkt aus dem Netz versorgt. Erst bei Ausfall schaltet die USV auf den Wechselrichter um; dabei entsteht eine kurze **Umschaltzeit** (einige ms), Spannungsschwankungen werden nicht ausgeglichen.', '**Online (VFI, Doppelwandler):** Der Strom fließt **immer** über Gleichrichter, Akku und Wechselrichter. Die Verbraucher sind vollständig vom Netz entkoppelt, es gibt **keine Umschaltzeit**, die Ausgangsspannung ist eine saubere Sinuswelle. Teurer und mit etwas höheren Verlusten.'], 4],
    ['quiz', [
      {q: 'Welche USV-Klasse arbeitet ohne Umschaltzeit?', o: ['VFI (Online)', 'VFD (Offline)', 'VI (Line-Interactive)', 'Alle gleich'], a: 0, e: 'Doppelwandler.'},
      {q: 'Wie berechnet man die Scheinleistung?', o: ['S = P / cos φ', 'S = P · cos φ', 'S = U / I', 'S = P + cos φ'], a: 0, e: 'cos φ < 1, also S > P.'},
      {q: 'Ein Gerät mit 0,5 kW läuft 24/7. Wie viele kWh pro Jahr?', o: ['4380', '8760', '12', '438'], a: 0, e: '0,5 · 8760.'},
      {q: 'Welches Schutzziel verbessert eine USV vor allem?', o: ['Verfügbarkeit', 'Vertraulichkeit', 'Authentizität', 'Anonymität'], a: 0, e: 'Zusätzlich Integrität.'},
      {q: 'Was bewirkt ECC-RAM?', o: ['Erkennt und korrigiert Speicherfehler', 'Verdoppelt die Taktrate', 'Verschlüsselt den Speicher', 'Spart Strom'], a: 0, e: 'Error Correcting Code.'},
    ]],
    ['see', ['infra-verfuegbarkeit', 'infra-raid', 'infra-backup', 'eua-bits']],
  ],
});
