AP2.page('infra-vlan', {
  b: 'infra', g: 'Netzwerke', t: 'VLAN, Inter-VLAN-Routing, DMZ und Netzplanung mit VLSM',
  d: 'Ein **VLAN** (Virtual LAN) teilt ein physisches Switch-Netz in mehrere **logisch getrennte** Netze (eigene **Broadcastdomäne**, eigenes IP-Subnetz). Geräte in verschiedenen VLANs können nur über einen **Router** oder **Layer-3-Switch** miteinander sprechen (**Inter-VLAN-Routing**), wo Firewall-Regeln greifen. Über eine Leitung zwischen Switches laufen mehrere VLANs als **Trunk**; die Frames tragen dabei ein **Tag nach IEEE 802.1Q** mit der VLAN-ID. Eine **DMZ** ist ein eigenes Netzsegment für Server, die aus dem Internet erreichbar sein müssen, abgeschottet vom internen LAN. Die passenden Subnetze plant man mit **VLSM** (Subnetze unterschiedlicher Größe).',
  m: '**VLAN = eigenes Subnetz + eigene Broadcastdomäne.** **Access-Port: ein VLAN, untagged (Endgerät). Trunk-Port: mehrere VLANs, getaggt (802.1Q).** **VLAN-ID 12 Bit -> 1 bis 4094.** **Zwischen VLANs nur über Router/L3-Switch.** **VLSM: größtes Netz zuerst, Größe = nächste Zweierpotenz ≥ Hosts + 2.** **DMZ: Server, die von außen erreichbar sein müssen, zwischen zwei Firewalls (oder an eigener Firewall-Schnittstelle).**',
  cheat: [
    ['VLAN-Begriffe', ['**Access-Port**: Endgerät, untagged', '**Trunk**: mehrere VLANs, 802.1Q-Tag', '**Native VLAN**: untagged auf dem Trunk', 'Tag = 4 Byte, 12 Bit VLAN-ID']],
    ['Vorteile', ['Sicherheit: Trennung, Firewall dazwischen', 'Weniger Broadcasts, mehr Leistung', 'Flexibel: Abteilung ohne Umverkabeln', 'Weniger Hardware']],
    ['Subnetzgrößen', ['/30 = 2 Hosts', '/29 = 6, /28 = 14', '/27 = 30, /26 = 62', '/25 = 126, /24 = 254']],
    ['DMZ', ['einstufig: eine Firewall mit 3 Zonen', 'zweistufig: zwei Firewalls (verschiedene Hersteller)', 'Webserver, Mailgateway, VPN in die DMZ', 'Datenbanken bleiben intern']],
  ],
  blocks: [
    ['h', 'Warum VLANs?'],
    ['p', 'Ohne VLAN sieht jedes Gerät am Switch die Broadcasts aller anderen und kann sie direkt erreichen. Mit VLANs trennt man zum Beispiel **Verwaltung**, **Produktion**, **Server**, **WLAN** und **Gäste** logisch, obwohl sie dieselben Switches nutzen. Verkehr zwischen den Gruppen muss über einen Router mit **Firewall-Regeln**; so erreicht ein infizierter Gast-PC die Patientendaten nicht.'],
    ['table', ['Art', 'Funktionsweise'], [
      ['**Portbasiertes VLAN**', 'Jeder Switch-Port wird fest einem VLAN zugeordnet (Access-Port). Einfach, Standard für Endgeräte.'],
      ['**Tagged VLAN (802.1Q)**', 'Der Switch fügt in den Ethernet-Frame ein **4-Byte-Tag** mit der **VLAN-ID** ein. So können über **eine** Leitung (Trunk) Frames vieler VLANs laufen, zum Beispiel zwischen Switches, zum Router oder zu einem Access Point mit mehreren SSIDs.'],
      ['**Dynamisches VLAN**', 'Die Zuordnung erfolgt nach Anmeldung, zum Beispiel per **802.1X und RADIUS** (Benutzer der Buchhaltung landet automatisch in VLAN 20).'],
    ]],
    ['h', 'Inter-VLAN-Routing'],
    ['list', [
      '**Router-on-a-Stick:** Ein Router ist über **einen** Trunk-Port angebunden und hat für jedes VLAN eine **virtuelle Unterschnittstelle** mit der Gateway-Adresse des Subnetzes.',
      '**Layer-3-Switch:** Der Switch routet selbst zwischen den VLAN-Schnittstellen (SVIs), sehr schnell, typisch im **Core**.',
      '**Firewall als Router:** Jedes VLAN endet an der Firewall, die den Verkehr zwischen den Zonen filtert (beste Kontrolle).',
    ]],
    ['h', 'Prüfungsbeispiel Winter 2022/23: Subnetze für VLANs (20 Punkte)'],
    ['p', 'Netz 192.168.10.0/24, Subnetze lückenlos und so klein wie möglich, Gateway = höchste Hostadresse. Bedarf: WLAN1 50 Hosts, WLAN2 50, LAN1 25, LAN2 25, Servernetz 10, Netzwerkmanagement 10, VPN-Transfernetz 2.'],
    ['steps', [
      'Für jedes Netz die nötige Größe bestimmen: Hosts + Netzadresse + Broadcast -> nächste **Zweierpotenz**. 50 + 2 = 52 -> 64 (/26). 25 + 2 = 27 -> 32 (/27). 10 + 2 -> 16 (/28). 2 + 2 -> 4 (/30).',
      'Nach Größe **absteigend sortieren** und von vorne lückenlos vergeben (so bleiben die Grenzen sauber ausgerichtet).',
      'Für jedes Subnetz Netz-ID, Maske, Hostbereich, Broadcast und Gateway (höchste Hostadresse) notieren.',
    ]],
    ['table', ['Netz', 'Hosts', 'Netz-ID', 'CIDR', 'Hostbereich', 'Gateway', 'Broadcast'], [
      ['WLAN1', '50', '192.168.10.0', '/26', '.1 bis .62', '.62', '.63'],
      ['WLAN2', '50', '192.168.10.64', '/26', '.65 bis .126', '.126', '.127'],
      ['LAN1', '25', '192.168.10.128', '/27', '.129 bis .158', '.158', '.159'],
      ['LAN2', '25', '192.168.10.160', '/27', '.161 bis .190', '.190', '.191'],
      ['Servernetz', '10', '192.168.10.192', '/28', '.193 bis .206', '.206', '.207'],
      ['Netzwerkmanagement', '10', '192.168.10.208', '/28', '.209 bis .222', '.222', '.223'],
      ['VPN-Transfernetz', '2', '192.168.10.224', '/30', '.225 bis .226', '.226', '.227'],
    ]],
    ['h', 'Prüfungsbeispiel Winter 2023/24: Schulnetz (16 Punkte)'],
    ['p', 'Netz 192.168.0.0/24. Lehrernetz 52 PCs + 10 Drucker, Anmelde-PCs 10 + 2 Drucker, Sekretariat 6 PCs + 3 Drucker, Serverraum/DMZ 3 Server. **Jedes Subnetz braucht zusätzlich eine Adresse für den Router** (letzte freie Adresse).'],
    ['table', ['Subnetz', 'Bedarf (inkl. Router)', 'Größe', 'Netz-ID', 'Maske', 'Router', 'Broadcast'], [
      ['Lehrernetz', '52 + 10 + 1 = 63', '128 (/25)', '192.168.0.0', '255.255.255.128', '.126', '.127'],
      ['Anmelde-PCs', '10 + 2 + 1 = 13', '16 (/28)', '192.168.0.128', '255.255.255.240', '.142', '.143'],
      ['Sekretariat', '6 + 3 + 1 = 10', '16 (/28)', '192.168.0.144', '255.255.255.240', '.158', '.159'],
      ['Serverraum/DMZ', '3 + 1 = 4', '8 (/29)', '192.168.0.160', '255.255.255.248', '.166', '.167'],
    ]],
    ['warn', '63 Adressen plus Netz- und Broadcastadresse sind 65, das passt **nicht** in ein /26 (64 Adressen, 62 nutzbar). Deshalb wird das Lehrernetz ein /25. Genau an solchen Grenzfällen werden Punkte verloren: immer **Hosts + 2 ≤ Blockgröße** prüfen.'],
    ['tool', 'subnet'],
    ['h', 'DMZ: einstufig oder zweistufig (Winter 2023/24, Winter 2024/25)'],
    ['def', 'Eine **DMZ** (demilitarisierte Zone) ist ein Netzwerkbereich, der **sowohl vom Internet als auch vom internen LAN durch Firewall-Regeln getrennt** ist. Dort stehen Server, die von außen erreichbar sein müssen (Webserver, Mail-Gateway, VPN-Gateway). Wird ein solcher Server kompromittiert, verhindert die Firewall zum LAN den direkten Durchgriff auf interne Systeme.'],
    ['table', ['Variante', 'Aufbau', 'Bewertung'], [
      ['**Einstufig** (Three-legged)', 'Eine Firewall mit drei Schnittstellen: Internet (WAN), DMZ, LAN', 'Günstig und einfach; die Firewall ist Single Point of Failure: Wird sie überwunden, sind DMZ und LAN offen'],
      ['**Zweistufig**', 'Äußere Firewall zwischen Internet und DMZ, innere Firewall zwischen DMZ und LAN (idealerweise verschiedene Hersteller)', 'Höhere Sicherheit (zwei Hürden), teurer und aufwendiger'],
    ]],
    ['h3', 'Netzskizze mit einstufiger DMZ (Winter 2024/25, 6 Punkte)'],
    ['diagram', {w: 760, h: 330, keep: 560, cap: 'Internet - Firewall (drei Zonen) - DMZ mit Webserver und Core-Switch mit zwei Access-Switches für Arbeitsplätze und Drucker.', nodes: [
      {id: 'i', k: 'oval', x: 380, y: 30, w: 140, h: 44, t: 'Internet', s: 'soft'},
      {id: 'fw', k: 'round', x: 380, y: 110, w: 150, h: 46, t: 'Firewall', s: 'bad'},
      {id: 'w', k: 'round', x: 650, y: 110, w: 160, h: 46, t: ['DMZ:', 'Webserver'], s: 'accent'},
      {id: 'c', k: 'round', x: 380, y: 190, w: 160, h: 46, t: 'Core-Switch', s: 'solid'},
      {id: 'a1', k: 'round', x: 200, y: 260, w: 150, h: 44, t: 'Access-Switch 1', s: 'plain'},
      {id: 'a2', k: 'round', x: 560, y: 260, w: 150, h: 44, t: 'Access-Switch 2', s: 'plain'},
      {id: 'p1', k: 'box', x: 70, y: 310, w: 110, h: 30, t: 'PCs', s: 'plain'},
      {id: 'd1', k: 'box', x: 200, y: 310, w: 110, h: 30, t: 'Drucker 1', s: 'plain'},
      {id: 'p2', k: 'box', x: 690, y: 310, w: 110, h: 30, t: 'PCs', s: 'plain'},
      {id: 'd2', k: 'box', x: 560, y: 310, w: 110, h: 30, t: 'Drucker 2', s: 'plain'},
    ], edges: [{a: 'i', b: 'fw', ea: 'none'}, {a: 'fw', b: 'w', ea: 'none', t: 'DMZ'}, {a: 'fw', b: 'c', ea: 'none', t: 'LAN'}, {a: 'c', b: 'a1', ea: 'none'}, {a: 'c', b: 'a2', ea: 'none'}, {a: 'a1', b: 'p1', ea: 'none'}, {a: 'a1', b: 'd1', ea: 'none'}, {a: 'a2', b: 'p2', ea: 'none'}, {a: 'a2', b: 'd2', ea: 'none'}]}],
    ['p', '**Hierarchisches Netzdesign:** Der **Core-Switch** (Kern, schnell, oft Layer 3) verbindet die **Access-Switches** (Zugangsebene, an denen PCs und Drucker hängen); in größeren Netzen liegt dazwischen eine **Distribution**-Ebene.'],
    ['h', 'Physische und logische Struktur (AP1 Sommer 2023)'],
    ['table', ['', 'Physische Struktur (Topologie)', 'Logische Struktur'], [
      ['Beschreibt', 'Wie Geräte **tatsächlich verkabelt** und aufgestellt sind (Räume, Kabelwege, Switches, Patchfelder)', 'Wie die Daten **fließen** und wie das Netz **organisiert** ist: VLANs, IP-Subnetze, Routing, Zugriffsrechte'],
      ['Beispiel', 'Alle PCs hängen sternförmig am selben Switch', 'Die PCs am selben Switch gehören zu zwei VLANs und zwei Subnetzen'],
      ['Änderung', 'Umverkabeln, Hardware kaufen', 'Konfiguration ändern'],
    ]],
    ['h', 'Aufgaben im Prüfungsstil'],
    ['qa', 'Erklären Sie dem Schulleiter den Begriff DMZ und nennen Sie Vorteile, den Datenbankserver dort zu betreiben.', ['Eine DMZ ist ein eigenes Netzsegment, das sowohl vom Internet als auch vom internen LAN durch Firewalls getrennt ist. Server, die von mehreren Netzen erreichbar sein sollen, werden dort platziert.', 'Vorteile: Zugriffe werden durch Firewall-Regeln genau kontrolliert; wird ein Server in der DMZ kompromittiert, ist kein direkter Durchgriff ins interne Netz möglich; klare Trennung der Sicherheitszonen.', 'Hinweis: Ein reiner Datenbankserver ohne Zugriff von außen gehört eher in ein internes **Servernetz**; in die DMZ kommt die von außen erreichbare Anwendung.'], 4],
    ['qa', 'Nennen Sie drei Vorteile von VLANs.', ['- **Sicherheit:** logische Trennung, Verkehr zwischen VLANs nur über Router/Firewall', '- **Leistung:** kleinere Broadcastdomänen, weniger Broadcastverkehr', '- **Flexibilität und Kosten:** Geräte können per Konfiguration einem anderen Netz zugeordnet werden, ohne Umverkabelung oder zusätzliche Switches'], 3],
    ['quiz', [
      {q: 'Welcher Standard beschreibt VLAN-Tagging?', o: ['IEEE 802.1Q', 'IEEE 802.3af', 'IEEE 802.11ax', 'IEEE 802.1X'], a: 0, e: '802.1X ist die portbasierte Authentifizierung.'},
      {q: 'Wie viele Hosts passen in ein /27?', o: ['30', '32', '62', '14'], a: 0, e: '32 Adressen minus Netz und Broadcast.'},
      {q: 'Was verbindet ein Trunk-Port?', o: ['Mehrere VLANs über eine Leitung', 'Genau ein Endgerät', 'WLAN und LAN', 'Zwei Internetanschlüsse'], a: 0, e: 'Frames werden getaggt.'},
      {q: 'Wie kommunizieren Geräte in verschiedenen VLANs?', o: ['Über einen Router oder Layer-3-Switch', 'Direkt über den Switch', 'Gar nicht', 'Nur per WLAN'], a: 0, e: 'Inter-VLAN-Routing.'},
      {q: 'Was gehört in eine DMZ?', o: ['Öffentlich erreichbarer Webserver', 'Buchhaltungs-PCs', 'Domain-Controller', 'Drucker der Geschäftsführung'], a: 0, e: 'Interne Systeme bleiben im LAN.'},
    ]],
    ['see', ['infra-subnetting', 'infra-komponenten', 'infra-firewall', 'infra-topologien', 'infra-wlan']],
  ],
});
