AP2.page('infra-vpn', {
  b: 'infra', g: 'Netzwerke', t: 'VPN: Site-to-Site, End-to-Site und sicherer Fernzugriff',
  d: 'Ein **VPN** (Virtual Private Network) baut über ein unsicheres Netz (Internet) einen **verschlüsselten Tunnel** auf, sodass entfernte Geräte oder Standorte so arbeiten können, als wären sie im internen Netz. **Site-to-Site** verbindet **zwei Netze** (Standorte) dauerhaft über zwei VPN-Gateways. **End-to-Site** (Client-to-Site, Remote Access) verbindet **ein einzelnes Gerät** (Notebook im Homeoffice, Arzt beim Hausbesuch) mit einem Netz über eine **VPN-Client-Software**. **End-to-End** verbindet zwei einzelne Geräte. Gängige Protokolle: **IPsec**, **SSL/TLS-VPN** (OpenVPN), **WireGuard**.',
  m: '**Site-to-Site = Netz mit Netz (zwei Gateways, Nutzer merken nichts). End-to-Site = Gerät mit Netz (Client-Software). End-to-End = Gerät mit Gerät.** **Tunnel = Pakete werden verschlüsselt in andere Pakete verpackt (Kapselung).** **VPN sichert Vertraulichkeit, Integrität, Authentizität auf dem Transportweg.**',
  cheat: [
    ['Typen', ['**Site-to-Site**: Standortvernetzung', '**End-to-Site**: Homeoffice, Außendienst', '**End-to-End**: zwei Hosts direkt', 'Endpunkt im Netz: VPN-Gateway/Konzentrator']],
    ['Protokolle', ['**IPsec** (Schicht 3, ESP/AH, IKE)', '**SSL/TLS-VPN** (OpenVPN, Port 443)', '**WireGuard** (modern, schlank, UDP)', 'veraltet: PPTP']],
    ['Authentifizierung', ['Pre-Shared Key', 'Zertifikate (PKI)', 'Benutzername + Passwort + 2FA', 'RADIUS/LDAP-Anbindung']],
    ['Varianten', ['Full Tunnel: aller Verkehr durchs VPN', 'Split Tunnel: nur Firmenverkehr', 'Always-on-VPN', 'Alternativen: ZTNA, Remote Desktop Gateway']],
  ],
  blocks: [
    ['h', 'Wie funktioniert ein Tunnel?'],
    ['p', 'Das Notebook im Homeoffice will auf den Praxisserver 192.168.10.5 zugreifen. Diese private Adresse ist im Internet nicht erreichbar. Der VPN-Client **verschlüsselt** das ursprüngliche Paket komplett und **verpackt** es in ein neues Paket an die **öffentliche Adresse des VPN-Gateways**. Das Gateway entpackt und entschlüsselt es und leitet das ursprüngliche Paket ins interne Netz weiter. Unterwegs sieht ein Angreifer nur verschlüsselte Daten zwischen Notebook und Gateway.'],
    ['diagram', AP2.dg.flow(['Notebook mit VPN-Client', 'Internet (verschlüsselter Tunnel)', 'VPN-Gateway / Firewall', 'Praxisnetz: Server 192.168.10.5'], {w: 760, h: 110, styles: ['soft', 'bad', 'accent', 'ok'], cap: 'End-to-Site-VPN: Nur zwischen Client und Gateway läuft der Tunnel durch das unsichere Internet.'})],
    ['h', 'Die VPN-Typen im Vergleich'],
    ['table', ['Typ', 'Verbindet', 'Endpunkte', 'Typischer Einsatz'], [
      ['**Site-to-Site**', 'Netz mit Netz', 'Je ein VPN-Gateway (Router/Firewall) pro Standort; für die Nutzer unsichtbar', 'Filialen, neuer Standort, Rechenzentrum mit Büro (Winter 2022/23)'],
      ['**End-to-Site** (Client-to-Site, Remote Access)', 'Einzelgerät mit Netz', 'VPN-Client auf dem Gerät, VPN-Server/Gateway im Firmennetz', 'Homeoffice, Außendienst, Arzt beim Hausbesuch (Winter 2025/26)'],
      ['**End-to-End**', 'Gerät mit Gerät', 'Beide Hosts', 'Fernwartung eines einzelnen Servers'],
    ]],
    ['ex', ['Winter 2022/23: "Die Verbindung der Standorte erfolgt über VPN. Begründen Sie, um welche Art es sich handelt."', 'Es ist ein **Site-to-Site-VPN**, weil **zwei Netze** (alter und neuer Standort) dauerhaft über VPN-Konzentratoren miteinander verbunden werden und alle Geräte die Ressourcen des jeweils anderen Netzes nutzen können.']],
    ['ex', ['Winter 2025/26: "Ärzte brauchen bei Hausbesuchen Zugriff auf die Patientendaten. Beschreiben Sie eine Möglichkeit des sicheren Zugriffs." (4 Punkte)', 'Über ein **End-to-Site-VPN**: Auf dem Laptop wird eine VPN-Client-Software installiert, im Praxisnetz ein VPN-Server (zum Beispiel auf der Firewall) betrieben. Der Arzt authentifiziert sich (Zertifikat und Passwort, besser mit zweitem Faktor). Alle Pakete werden **verschlüsselt durch das Internet getunnelt**, sodass Patientendaten (besondere Kategorie nach Art. 9 DSGVO) nicht mitgelesen werden können.']],
    ['h', 'Protokolle'],
    ['table', ['Protokoll', 'Schicht', 'Merkmale'], [
      ['**IPsec**', '3 (Vermittlung)', 'Standard für Site-to-Site. **IKE** handelt Schlüssel aus, **ESP** verschlüsselt und sichert Integrität, **AH** nur Integrität. **Tunnelmodus** (ganzes Paket gekapselt) oder **Transportmodus** (nur Nutzdaten).'],
      ['**SSL/TLS-VPN** (zum Beispiel OpenVPN)', '4 bis 7', 'Nutzt TLS wie HTTPS; über Port 443 kommt man durch fast jede Firewall. Beliebt für Remote Access.'],
      ['**WireGuard**', '3', 'Sehr schlanker, moderner Code, schnell, feste moderne Kryptografie, UDP.'],
      ['**PPTP**', '2', '**Unsicher**, nicht mehr verwenden.'],
    ]],
    ['h', 'Vorteile und Grenzen'],
    ['procon', 'VPN für den Fernzugriff', ['Vertraulichkeit und Integrität der Daten auf dem Weg durchs Internet', 'Zugriff auf interne Dienste, ohne sie ins Internet zu stellen (keine Portweiterleitungen)', 'Starke Authentifizierung der Gegenstelle (Zertifikate)', 'Kostengünstig gegenüber Standleitungen'], ['Gerät im Homeoffice wird Teil des Netzes; ist es infiziert, gelangt Schadsoftware ins Firmennetz', 'Engpass und Single Point of Failure am VPN-Gateway', 'Etwas Geschwindigkeitsverlust durch Verschlüsselung und Umweg', 'Schutz nur auf dem Transportweg, nicht auf den Endgeräten']],
    ['note', '**Zero Trust Network Access (ZTNA)** gilt als Weiterentwicklung: Statt Zugang zum ganzen Netz gibt es nur Zugriff auf einzelne Anwendungen, nach Prüfung von Identität und Gerätezustand bei jeder Anfrage.'],
    ['h', 'Aufgaben im Prüfungsstil'],
    ['qa', 'Unterscheiden Sie Site-to-Site- und End-to-Site-VPN und nennen Sie je einen Einsatzfall.', ['**Site-to-Site:** verbindet zwei (oder mehr) **Netze** über VPN-Gateways an jedem Standort; die Endgeräte brauchen keine VPN-Software. Einsatz: Filiale mit Zentrale verbinden.', '**End-to-Site:** verbindet ein **einzelnes Endgerät** mit VPN-Client mit einem entfernten Netz über ein VPN-Gateway. Einsatz: Mitarbeiter im Homeoffice.'], 4],
    ['qa', 'Nennen Sie drei Maßnahmen, um einen VPN-Zugang für Homeoffice-Mitarbeiter abzusichern.', ['- **Zwei-Faktor-Authentifizierung** (Passwort plus App/Token) oder Client-Zertifikate statt nur Passwort', '- aktuelle, sichere Protokolle (IPsec/IKEv2, OpenVPN, WireGuard), regelmäßige Updates des Gateways', '- nur verwaltete, gepatchte Firmengeräte mit Virenschutz zulassen; Zugriffsrechte nach dem **Minimalprinzip**, Protokollierung der Verbindungen'], 3],
    ['quiz', [
      {q: 'Welche VPN-Art verbindet zwei Standortnetze?', o: ['Site-to-Site', 'End-to-Site', 'End-to-End', 'Split DNS'], a: 0, e: 'Gateways an beiden Standorten.'},
      {q: 'Was braucht ein Mitarbeiter für End-to-Site-VPN?', o: ['Eine VPN-Client-Software und Zugangsdaten', 'Einen zweiten Router', 'Eine Standleitung', 'Eine öffentliche IP auf dem Notebook'], a: 0, e: 'Gegenstelle ist das VPN-Gateway der Firma.'},
      {q: 'Welches VPN-Protokoll gilt als unsicher?', o: ['PPTP', 'IPsec', 'WireGuard', 'OpenVPN'], a: 0, e: 'Veraltete Verschlüsselung.'},
      {q: 'Welcher IPsec-Teil verschlüsselt die Nutzdaten?', o: ['ESP', 'AH', 'IKE', 'DNS'], a: 0, e: 'AH sichert nur die Integrität.'},
    ]],
    ['see', ['infra-firewall', 'infra-ipconfig', 'infra-tls', 'infra-krypto']],
  ],
});
