AP2.page('infra-wlan', {
  b: 'infra', g: 'Netzwerke', t: 'WLAN: Standards, Frequenzen, WPA2/WPA3 und Gäste-WLAN',
  d: '**WLAN** nach **IEEE 802.11** überträgt Daten per Funk im **2,4-GHz**-, **5-GHz**- und (ab Wi-Fi 6E) **6-GHz**-Band. Weil jeder in Reichweite mithören kann, ist **Verschlüsselung** Pflicht: heute **WPA2** oder besser **WPA3**. Beide gibt es als **Personal** (ein gemeinsamer **Pre-Shared Key**, PSK/SAE) und **Enterprise** (jeder Benutzer meldet sich einzeln über **802.1X/EAP** an einem **RADIUS-Server** an). Ein **Gäste-WLAN** wird über eine eigene **SSID** in einem eigenen **VLAN** vom internen Netz getrennt.',
  m: '**2,4 GHz: weiter, durch Wände, aber langsamer und überfüllt. 5 GHz: schneller, mehr Kanäle, kürzere Reichweite.** **Personal = ein Passwort für alle, Enterprise = jeder Benutzer eigene Anmeldung (RADIUS).** **WEP und WPA (TKIP) sind gebrochen.** **Gäste: eigene SSID + VLAN + Client-Isolation + nur Internet.**',
  cheat: [
    ['Standards', ['802.11n = Wi-Fi 4 (2,4/5 GHz)', '802.11ac = Wi-Fi 5 (5 GHz)', '802.11ax = Wi-Fi 6/6E (2,4/5/6 GHz)', '802.11be = Wi-Fi 7']],
    ['Sicherheit', ['WEP: unsicher', 'WPA (TKIP): veraltet', 'WPA2 (AES-CCMP): Mindeststandard', 'WPA3 (SAE, 192 Bit Enterprise): aktuell']],
    ['Personal vs Enterprise', ['PSK: ein Schlüssel für alle Geräte', 'Enterprise: 802.1X, EAP, RADIUS', 'Benutzer/Zertifikat einzeln sperrbar', 'Protokollierung, wer wann online war']],
    ['Konfiguration', ['Starkes Passwort, WPA3/WPA2', 'WPS aus, Admin-Passwort ändern', 'Firmware aktuell', 'Gastnetz getrennt, Client-Isolation']],
  ],
  blocks: [
    ['h', 'Frequenzbänder (AP1 Winter 2022/23)'],
    ['table', ['Eigenschaft', '2,4 GHz', '5 GHz', '6 GHz (Wi-Fi 6E)'], [
      ['Reichweite, Wanddurchdringung', '**Hoch**', 'Mittel', 'Gering'],
      ['Datenrate', 'Niedriger', '**Hoch**', 'Sehr hoch'],
      ['Überschneidungsfreie Kanäle', 'Nur **3** (1, 6, 11)', 'Viele (19 und mehr)', 'Sehr viele'],
      ['Störungen', 'Viele (Nachbar-WLANs, Bluetooth, Mikrowelle)', 'Weniger', 'Kaum'],
      ['Einsatz', 'IoT-Geräte, große Entfernungen', 'Büro, Video, viele Clients', 'Hohe Dichte, neueste Geräte'],
    ]],
    ['h', 'Wi-Fi 6 (802.11ax): Neuerungen (AP1 Sommer 2023)'],
    ['list', [
      '**OFDMA:** Ein Kanal wird in Teilkanäle aufgeteilt, mehrere Geräte werden **gleichzeitig** bedient. Viel besser bei vielen Clients (Schule, Messe, Wartezimmer).',
      '**MU-MIMO** in Up- und Downlink: mehrere Datenströme parallel an mehrere Geräte.',
      '**Target Wake Time:** Geräte schlafen bis zum vereinbarten Zeitpunkt, spart Akku (IoT).',
      '**1024-QAM:** höhere Datenrate; **WPA3** ist für die Wi-Fi-6-Zertifizierung Pflicht.',
      '**Wi-Fi 6E:** zusätzlich das **6-GHz-Band** mit vielen freien Kanälen.',
    ]],
    ['h', 'Verschlüsselung und Authentifizierung'],
    ['table', ['Verfahren', 'Verschlüsselung', 'Bewertung'], [
      ['WEP', 'RC4', '**Unsicher**, in Minuten zu knacken'],
      ['WPA', 'TKIP', '**Veraltet**, nicht mehr verwenden'],
      ['WPA2-Personal', 'AES-CCMP, PSK', 'Noch verbreitet; mit schwachem Passwort per Wörterbuchangriff knackbar (Handshake mitschneiden, offline raten)'],
      ['WPA3-Personal', 'AES, **SAE** (Dragonfly-Handshake)', 'Schützt gegen Offline-Wörterbuchangriffe, **Forward Secrecy**'],
      ['WPA2/WPA3-Enterprise', 'AES, **802.1X/EAP** mit **RADIUS**', 'Jeder Benutzer authentifiziert sich einzeln; empfohlen für Unternehmen'],
    ]],
    ['h3', 'Personal (Pre-Shared Key) vs. Enterprise (RADIUS) (Winter 2025/26, 4 Punkte)'],
    ['table', ['', 'Personal (PSK)', 'Enterprise (RADIUS)'], [
      ['Anmeldung', 'Ein **gemeinsamer Schlüssel** für alle, zum Beispiel per Aushang im Wartezimmer', 'Jeder Benutzer hat **eigene Zugangsdaten** (Benutzername/Passwort) oder ein Zertifikat, die ein **RADIUS-Server** prüft'],
      ['Wer authentifiziert sich?', 'Nur das **Gerät** (wer das Passwort kennt)', 'Der **Benutzer**'],
      ['Einzelnen Zugang sperren', 'Nicht möglich, Schlüssel muss überall geändert werden', 'Ja, Konto deaktivieren'],
      ['Nachvollziehbarkeit', 'Keine', 'Protokollierung, wer wann verbunden war (Accounting)'],
      ['Aufwand', 'Gering', 'RADIUS-Server, Benutzerverwaltung, ggf. Zertifikate'],
    ]],
    ['h', 'Gäste-WLAN sicher vom internen Netz trennen'],
    ['p', 'Aufgabe Winter 2025/26: Patienten sollen im Wartezimmer ins Internet, das WLAN soll vom internen Praxisnetz (Server mit Patientendaten) getrennt sein.'],
    ['steps', [
      'Eigene **SSID** für Gäste am Access Point ("Praxis-Gast").',
      'Diese SSID einem eigenen **VLAN** (zum Beispiel VLAN 30) zuordnen; Uplink als **Trunk (802.1Q)** zur Firewall.',
      'Eigenes **IP-Subnetz** mit **DHCP (dynamisch, kurze Lease)** für das Gäste-VLAN.',
      '**Firewall-Regel:** Gäste-VLAN darf nur ins **Internet** (HTTP/HTTPS, DNS), **kein** Zugriff auf interne Netze.',
      '**Client-Isolation** aktivieren, damit Gästegeräte sich nicht gegenseitig angreifen können; Bandbreite begrenzen.',
      'Zugang per **PSK mit regelmäßigem Wechsel** oder **Captive Portal** mit Nutzungsbedingungen (Haftung, Störerhaftung).',
    ]],
    ['h', 'Sicherheitsaspekte bei der WLAN-Konfiguration (AP1 Winter 2022/23)'],
    ['list', [
      '**WPA3** (mindestens WPA2-AES) statt WEP/WPA/TKIP.',
      '**Langes, zufälliges Passwort** (mindestens 12 bis 20 Zeichen) bzw. Enterprise-Anmeldung.',
      '**Standard-Admin-Passwort** des Access Points ändern, Verwaltung nur aus dem internen Netz und per HTTPS.',
      '**WPS deaktivieren** (PIN-Verfahren angreifbar).',
      '**Firmware** aktuell halten.',
      '**Gastnetz** getrennt, Sendeleistung an Gebäude anpassen, nicht benötigte Dienste abschalten.',
    ]],
    ['note', 'Das Verstecken der SSID oder ein MAC-Filter erhöhen die Sicherheit **kaum**: Die SSID ist trotzdem im Funkverkehr sichtbar, MAC-Adressen lassen sich fälschen. In der Prüfung gelten sie höchstens als ergänzende Maßnahmen.'],
    ['h', 'Aufgaben im Prüfungsstil'],
    ['qa', 'Der Router bietet für WPA2/WPA3 die Alternativen Preshared Key (Personal) und RADIUS (Enterprise). Erläutern Sie beide Möglichkeiten.', ['**Preshared Key:** Alle Nutzer erhalten denselben Schlüssel (zum Beispiel per Aushang) und geben ihn einmal im Gerät ein. Danach erhalten sie beliebig oft Zugang. Es authentifiziert sich nur das Gerät, nicht der Benutzer; ein Sperren einzelner Nutzer ist nicht möglich.', '**RADIUS:** Benutzer werden auf einem Anmeldeserver angelegt und erhalten Benutzername und Passwort (oder ein Zertifikat). Damit authentifizieren sie sich einzeln am WLAN (802.1X). Konten können einzeln gesperrt werden, Anmeldungen werden protokolliert.'], 4],
    ['qa', 'Nennen Sie jeweils zwei Eigenschaften des 2,4-GHz- und des 5-GHz-Bandes.', ['**2,4 GHz:** größere Reichweite und bessere Durchdringung von Wänden; nur drei überlappungsfreie Kanäle, störanfällig, geringere Datenrate.', '**5 GHz:** höhere Datenraten, mehr Kanäle und weniger Störungen; geringere Reichweite, schlechtere Wanddurchdringung.'], 4],
    ['quiz', [
      {q: 'Welcher Standard heißt Wi-Fi 6?', o: ['802.11ax', '802.11ac', '802.11n', '802.11g'], a: 0, e: 'ac = Wi-Fi 5.'},
      {q: 'Was ist der Hauptunterschied zwischen WPA2-Personal und -Enterprise?', o: ['Enterprise authentifiziert jeden Benutzer einzeln über RADIUS', 'Enterprise nutzt kein AES', 'Personal ist schneller verschlüsselt', 'Enterprise funktioniert nur mit 5 GHz'], a: 0, e: 'Personal = ein gemeinsamer Schlüssel.'},
      {q: 'Welches Verfahren schützt WPA3-Personal gegen Offline-Wörterbuchangriffe?', o: ['SAE', 'TKIP', 'WPS', 'RC4'], a: 0, e: 'Simultaneous Authentication of Equals.'},
      {q: 'Wie viele überlappungsfreie Kanäle gibt es im 2,4-GHz-Band (Europa, 20 MHz)?', o: ['3', '13', '1', '24'], a: 0, e: 'Kanäle 1, 6, 11 (bzw. 1, 5, 9, 13).'},
      {q: 'Welche Maßnahme trennt ein Gäste-WLAN wirksam vom internen Netz?', o: ['Eigene SSID in eigenem VLAN mit Firewall-Regeln', 'SSID verstecken', 'Kürzeres Passwort', 'Kanal 6 verwenden'], a: 0, e: 'Logische Trennung plus Filterung.'},
    ]],
    ['see', ['infra-medien', 'infra-radius', 'infra-vlan', 'infra-ipconfig']],
  ],
});
