AP2.page('ref-altpruefungen', {
  b: 'ref', g: 'Referenz', t: 'Alte Abschlussprüfungen 2022 bis 2026: alle Aufgaben und wo sie erklärt werden',
  d: 'Diese Übersicht listet **jede Aufgabe** der vorliegenden baden-württembergischen Abschlussprüfungen (Berufsschule und IHK, FA 234 Fachinformatiker/-in Anwendungsentwicklung) mit Punkten und Thema, dazu die Seiten, auf denen das Thema erklärt wird. **Teil 2** besteht aus "Planen eines Softwareproduktes" (PS, 90 Minuten) und "Entwicklung und Umsetzung von Algorithmen" (EuA, 90 Minuten). Dazu kommen Gemeinschaftskunde (60 Minuten), Deutsch (120 Minuten) und Teil 1 (AP1). Die Projekte sind fiktive Unternehmen; die Themen wiederholen sich aber sehr zuverlässig.',
  m: '**Kommt fast immer:** UML-Klassendiagramm lesen/erweitern + eine Klasse implementieren, ER-Modell/Relationenschema, 4 bis 6 SQL-Statements, ein HTML/CSS-Formular, eine kaufmännische Rechnung (Angebotsvergleich, Break-even, BAB, TCO), Netzwerk/IT-Sicherheit (Subnetting, DHCP, VPN, Verschlüsselung, Backup).',
  cheat: [
    ['PS (Teil 2)', ['UML + Implementierung (30 bis 50 P.)', 'Datenbank + SQL (20 bis 40 P.)', 'Netzwerk/Sicherheit (18 bis 23 P.)', 'BWL/Projekt (20 bis 30 P.)']],
    ['EuA (Teil 2)', ['HTML/CSS/JS (20 bis 35 P.)', 'Algorithmus/Struktogramm/Code (30 bis 55 P.)', 'SQL/JSON/REST', 'Kostenrechnung (25 bis 30 P.)']],
    ['Gemeinschaftskunde', ['Wahlen, Beteiligung', 'demografischer Wandel', 'Gleichberechtigung, KI, EU', 'ganze Sätze!']],
    ['AP1', ['Angebotsvergleich, Wareneingang', 'IP-Konfiguration, USV', 'ERM, SQL, XML/JSON', 'Pseudocode, Schutzbedarf']],
  ],
  blocks: [
    ['h', 'Häufigkeit der Themen in Teil 2 (2022 bis 2026, 10 Prüfungen)'],
    ['table', ['Thema', 'Vorkommen', 'Seiten'], [
      ['SQL (CREATE, ALTER, INSERT, UPDATE, DELETE, JOIN, GROUP BY/HAVING)', '**10 von 10**', 'SQL-Aufgaben aus den Prüfungen, SQL-Seiten'],
      ['UML-Klassendiagramm lesen, erweitern, Klassen implementieren', '**9 von 10**', 'Klassen aus UML implementieren, Klassendiagramm'],
      ['ER-Modell, Relationenschreibweise, Normalisierung, Anomalien', '**9 von 10**', 'ER-Modell, Relationales Modell, Normalisierung'],
      ['HTML-Formular / CSS-Layout / Media Queries / JavaScript', '**8 von 10**', 'HTML-Formulare, CSS, JavaScript'],
      ['Kaufmännische Rechnung (Break-even, Deckungsbeitrag, BAB, Angebotsvergleich, TCO)', '**8 von 10**', 'Kostenarten, Kalkulation, Angebotsvergleich, TCO'],
      ['Netzwerk (Subnetting/VLSM, DHCP, VLAN, VPN, DMZ, WLAN)', '**6 von 10**', 'Subnetting, IP-Konfiguration, VLAN, VPN, WLAN'],
      ['IT-Sicherheit (Verschlüsselung, Signatur, Zertifikate, HTTPS, SQL-Injection)', '**6 von 10**', 'Kryptografie, PKI, TLS, Angriffe'],
      ['Algorithmus als Struktogramm/PAP oder Code', '**6 von 10**', 'Typische Prüfungsalgorithmen, Struktogramm'],
      ['JSON/XML/CSV, REST-API', '**6 von 10**', 'Datenaustauschformate, Web-APIs'],
      ['Entwurfsmuster (Observer, Singleton, Factory)', '**3 von 10**', 'Entwurfsmuster'],
      ['IoT/MQTT, Schnittstellen, Bits', '**3 von 10**', 'IoT und MQTT, Zahlensysteme und Schnittstellen'],
    ]],
    ['h', 'Winter 2025/26: Medical Systems GmbH, Gemeinschaftspraxis SmartDocs'],
    ['table', ['Teil', 'Aufgabe', 'Punkte'], [
      ['PS 1', 'Observer erläutern (10), Push/Push-Update/Pull begründen (5), Singleton Vor-/Nachteil (4), Klasse SarsCov2Analyse implementieren (13)', '32'],
      ['PS 2', 'ERM aus MySQL-Skript (6), JOIN mit WHERE/ORDER (6), GROUP BY/HAVING > 300 (10), ALTER TABLE ADD (3), UPDATE zwei Spalten (4), drei Anomalien (6)', '35'],
      ['PS 3', 'WPA2/3 Personal vs. RADIUS (4), DHCP DORA (4), Vergabearten (4), sicherer Fernzugriff VPN (4), inkrementell vs. differenziell (4), Verfügbarkeit (3)', '23'],
      ['EuA 1', 'CSS Grid nach Ausrichtung (8), Media Queries Schriftgrößen (5), JavaScript Button aktivieren (4), SOAP/GraphQL/WebSockets (4), JSON-Struktur (8), Bootstrap-CDN-Probleme (4)', '33'],
      ['EuA 2', 'IoT/MQTT: lokal vs. Cloud (3), Sensoren/Aktoren (6), Publisher/Subscriber/Broker (6), Topics (3), JSON-Paket (6), Schutzziele (2), Verbindungssicherung (6)', '32'],
      ['EuA 3', 'Angebotsvergleich 10 Notebooks (8), weitere Kriterien (2), Pflichten aus Kaufvertrag (4), Zustandekommen bei geänderter Bestellung (5), Mängelrechte (3 + 3)', '25'],
    ]],
    ['see', ['eua-patterns', 'eua-sqlexam', 'ps-normalisierung', 'infra-wlan', 'infra-ipconfig', 'infra-vpn', 'infra-backup', 'infra-usv', 'eua-css', 'eua-js', 'eua-webapi', 'eua-formate', 'eua-iot', 'ps-angebot', 'ps-kaufvertrag'], 'Erklärt auf'],
    ['h', 'Sommer 2025: Carsharing TeilFahr e.V. / Mensa-Bestellsystem'],
    ['table', ['Teil', 'Aufgabe', 'Punkte'], [
      ['PS 1', 'Assoziation/Aggregation, Kardinalitäten, Rollen erläutern (6), abstrakte Klassen und Polymorphie (6), Klassendiagramm um E-Fahrzeuge erweitern (s. Lösung), Vertrag/Fahrzeug/EFahrzeug/EScooter implementieren (14)', '46'],
      ['PS 2', 'n:m-Beziehung auflösen, Relationen (6), CREATE TABLE mit AUTO_INCREMENT (6), SUM km im Dezember (6), COUNT HAVING > 10 ORDER DESC (6), DELETE (2)', '26'],
      ['PS 3', 'Symmetrisch: Vertraulichkeit/Integrität, aber keine Authentizität (5), asymmetrische Signatur (5), Vorteil symmetrisch (2), Zertifikatsinhalte (3), Echtheit prüfen (3)', '18'],
      ['EuA 1', 'Umfrage auswerten (s. Lösung), funktional/nicht-funktional (s. Lösung), HTML-Formular (s. Lösung), CSS-Menü (10), Inline/Block, Kaskade (Inline-Style gewinnt), Barrierefreiheit', '35'],
      ['EuA 2', 'SELECT DISTINCT BETWEEN (8), UPDATE +10 % (3), Datenmodell um Bewertung erweitern (1), Struktogramm Gruppenwechsel und Bestwert (15)', '30'],
      ['EuA 3', 'fixe/variable Kosten (2 + 2), Gewinn bei 63 % (3), Break-even-Tabelle (6), Diagramm (8), Inhouse vs. extern (4)', '25'],
    ]],
    ['see', ['eua-umlcode', 'ps-klassen', 'ps-er', 'eua-sqlexam', 'infra-krypto', 'infra-pki', 'eua-html', 'eua-css', 'ps-lastenheft', 'eua-dateien', 'ps-kostenarten', 'ps-itsm'], 'Erklärt auf'],
    ['h', 'Winter 2024/25: Kapazitätsmessung von Akkus'],
    ['table', ['Teil', 'Aufgabe', 'Punkte'], [
      ['PS 1', 'abstract-Einschränkung (3), Strom/Spannung ergänzen (4), pruefeWert überschreiben (4), Assoziationen mit Multiplizität (6), aus Struktogramm ins Klassendiagramm (10), bereinigeMesswertliste implementieren (10), Aufruf private Methode (3)', '40'],
      ['PS 2', 'ERM (5), Stromwerte per JOIN (7), AVG prozentuale Abweichung je Hersteller (8), UPDATE (5)', '25'],
      ['PS 3', 'agil vs. klassisch (5), Empfehlung (2), fix/variabel (2 + 2), Stückdeckungsbeitrag (2), kritische Menge (4), Diagramm (6), Verlängerung auf 6 Wochen (2)', '25'],
      ['EuA 1', 'HTML-Formular mit Tabelle, required, select (19), CSS-Einbindung Vor-/Nachteile (6)', '25'],
      ['EuA 2', 'pruefeWert Strom (5), Struktogramm berechneKapazitaet (10), Messwert/Strom/Messreihe implementieren (27)', '42'],
      ['EuA 3', 'Baudrate 9600 (3), Schnittstellen Bluetooth/Ethernet/WLAN (6), Ohm U = R·I (2), Leistung (2), HTTPS Vor- und Nachteile (4), Netzskizze einstufige DMZ (6)', '23'],
    ]],
    ['see', ['eua-umlcode', 'ps-relational', 'eua-sqlexam', 'ps-vorgehen', 'ps-kostenarten', 'eua-html', 'eua-css', 'eua-bits', 'eua-webapi', 'infra-vlan'], 'Erklärt auf'],
    ['h', 'Sommer 2024: Skiclub-Mitgliederverwaltung / Flowers2You'],
    ['table', ['Teil', 'Aufgabe', 'Punkte'], [
      ['PS 1', 'Datenmodell um Skilehrer erweitern (10), Redundanz Kurstitel und Lösung (10)', '20'],
      ['PS 2', 'COUNT LIKE YEAR (4), SUM HAVING (4), ALTER ADD/MODIFY NOT NULL (4), INSERT (4), UPDATE (4)', '20'],
      ['PS 3', 'Select ergänzen (s. Lösung), CSS-Klasse (s. Lösung), action/method (3), GET vs. POST (4), HTTPS (4), JSON der Formulardaten (4), Schritte INSERT (6)', '30'],
      ['PS 4', 'TCO eigener Server (10), Miete vs. eigener Server + weitere Kriterien (10)', '20'],
      ['EuA 1', 'Klasse Bestellposition in Python (10), Aggregation (4), Liste vs. Menge (6)', '20'],
      ['EuA 2', 'CSV einlesen + Preis suchen (18), Rechnung erzeugen (18)', '36'],
      ['EuA 3', 'XML in JSON (12), Vorteile JSON (6)', '18'],
      ['EuA 4', 'ERM in 3NF mit historischem Preis (8), Relationenmodell (8)', '16'],
    ]],
    ['see', ['ps-er', 'ps-normalisierung', 'eua-sqlexam', 'eua-html', 'eua-webapi', 'ps-tco', 'ps-itsm', 'eua-umlcode', 'eua-dateien', 'eua-formate', 'ps-relational'], 'Erklärt auf'],
    ['h', 'Winter 2023/24: Schulverwaltung / Kita-Software'],
    ['table', ['Teil', 'Aufgabe', 'Punkte'], [
      ['PS 1', 'Klassendiagramm erweitern: Teilzeit/Vollzeit, Ausbilder, Klasse, Betrieb, Zeugnis (16), Klasse Lehrer : Person implementieren (11)', '27'],
      ['PS 2', 'ERM in Relationen (12), CREATE TABLE (6), Fremdschlüssel AG (6), AGs mit < 5 Teilnehmern (8), INSERT (4), UPDATE IN (4)', '40'],
      ['PS 3', 'IPv6-Adresstypen (3), VLSM mit Router-Adressen (16), DMZ (4)', '23'],
      ['EuA 1', 'Anmeldeformular mit mailto, size, textarea, radio, checkbox (24)', '24'],
      ['EuA 2', 'Struktogramm Menüsteuerung, Polymorphie erklären, Person/Kind/Erzieherin + Testprogramm (36)', '36'],
      ['EuA 3', 'BAB: Kosten verteilen (7), Zuschlagssätze (13), Selbstkosten (10)', '30'],
    ]],
    ['see', ['ps-klassen', 'eua-umlcode', 'ps-relational', 'eua-sqlexam', 'infra-ipv6', 'infra-vlan', 'eua-html', 'eua-algoexam', 'ps-kalkulation'], 'Erklärt auf'],
    ['h', 'Sommer 2023: TrainYourBrain AG / SmartHome'],
    ['table', ['Teil', 'Aufgabe', 'Punkte'], [
      ['PS 1', 'Klassendiagramm für Online-Fortbildungen umbauen (9), Methode Link versenden (8), Entwurfsmuster für Warteliste (3), Observer-Klassendiagramm (8)', '28'],
      ['PS 2', 'Umbuchungsproblem (3), Transaktion (3), Relationenschreibweise (9), ALTER TABLE (3), Teilnehmerliste über 4 Tabellen (8), LEFT JOIN Anmeldungen (6)', '32'],
      ['PS 3', 'Gewinn Präsenz (6), Deckungsbeitrag (3), Gewinnschwelle (6), DB online (6), Vergleich (3), neuer Preis (3), Marketing-Mix (3)', '30'],
      ['EuA 1', 'HTML mit Radiobuttons (8), Temperatur aktualisieren (4), Uhrzeit 2 Wege (2), Media Query ab 600 px (4), Logo positionieren (2)', '20'],
      ['EuA 2', 'JSON-Auswertung als Code (20), Hauptprogramm (9), Whitebox-Test (8), Struktogramm mit Bitflags je Sensor (10), REST-Befehle (8)', '55'],
      ['EuA 3', 'I²C-Adressen binär/hex (6), Auflösung 8 Bit (3), WPA2-PSK beurteilen (3), MQTT absichern (3)', '15'],
    ]],
    ['see', ['eua-umlcode', 'eua-patterns', 'eua-sqlexam', 'ps-kostenarten', 'ps-marketing', 'eua-html', 'eua-js', 'eua-css', 'eua-dateien', 'eua-algoexam', 'eua-bits', 'eua-webapi', 'eua-iot'], 'Erklärt auf'],
    ['h', 'Winter 2022/23: kVpersonal GmbH (Photovoltaik) / CarLos Gebrauchtwagen'],
    ['table', ['Teil', 'Aufgabe', 'Punkte'], [
      ['PS 1', 'Alternative zu CSV/XML (JSON), XML wohlgeformt?, Klassendiagramm um CSV und Hybridwechselrichter erweitern, CsvAnfrage implementieren (20), Polymorphie (3), Komposition (3), Connection-String (4)', '47'],
      ['PS 2', 'VLSM für 7 Subnetze (20 inkl. Teil 2.2), DHCP DORA, Optionen, Reservierung, Site-to-Site-VPN', '20'],
      ['PS 3', 'Angebotsvergleich 8 Access Points (12), Nutzwertanalyse (9), Entscheidung (2)', '23'],
      ['EuA 1', 'CSS-Orte und Wartbarkeit (6), Kontaktformular (22), SQL-Injection (4), Vorteile CMS (3)', '35'],
      ['EuA 2', 'Vorteile Franchise (3), fix/variabel (4), Break-even-Tabelle (14), Diagramm (8)', '29'],
      ['EuA 3', 'CREATE mit AUTO_INCREMENT, ALTER ADD 2 Spalten, INSERT, UPDATE, COUNT HAVING >= 10, Unterabfrage MAX', '26'],
    ]],
    ['see', ['eua-formate', 'eua-umlcode', 'eua-dateien', 'infra-vlan', 'infra-ipconfig', 'infra-vpn', 'ps-angebot', 'ps-kosten', 'eua-css', 'eua-html', 'infra-angriffe', 'ps-marketing', 'ps-kostenarten', 'eua-sqlexam'], 'Erklärt auf'],
    ['h', 'Sommer 2022: Packmeister GmbH (IAV-DriveApp) / Kurierdienst Flinke Pedale'],
    ['table', ['Teil', 'Aufgabe', 'Punkte'], [
      ['PS 1', 'CSV/XML erkennen (4), Factory begründen (5), Interface ImportService ergänzen, detectManufacturer (7), ImportData (6), Vorteile und Anpassungen (3 + 5)', '50'],
      ['PS 2', 'Relationenmodell (7), CREATE trace_data, COUNT verbauter Motoren (6), REST: HTTP(S) und JSON (2 + 3)', '23'],
      ['PS 3', 'Vorteile Predictive Maintenance (4), eEPK ausfüllen (13)', '17'],
      ['EuA 1', 'Layout-Möglichkeiten (3), CSS Grid für 5 Container (8), Media Query Ausrichtung (2), Labels und Barrierefreiheit (3), Radiobuttons (4)', '20'],
      ['EuA 2', 'Struktogramm Sexagesimal -> Dezimal (10), calcPreis mit Unterfunktion (25), Testvektor (5)', '40'],
      ['EuA 3', 'Nachteile nicht normalisierter Daten (6), 3NF schrittweise (12), längste Fahrt, Fahrten je Tarif, Ergebnis einer Abfrage (12)', '30'],
    ]],
    ['see', ['eua-formate', 'eua-patterns', 'eua-interface', 'ps-relational', 'eua-sqlexam', 'eua-webapi', 'ps-epk', 'ps-marketing', 'eua-css', 'eua-html', 'eua-algoexam', 'eua-testfaelle', 'ps-normalisierung'], 'Erklärt auf'],
    ['h', 'Gemeinschaftskunde (60 Minuten, 30 Punkte)'],
    ['table', ['Prüfung', 'Handlungssituation und Aufgaben'], [
      ['Winter 2022/23', 'Azubi durfte mit 17 nicht wählen: Wahlrechtsgrundsätze (4), Beteiligung unter 18 (2), Schaubild Wahlberechtigte/Wahlbeteiligung (4 + 4), Wahlalter 16 kritisch (6), demografischer Wandel als Problem (4), Gegenmaßnahmen (6)'],
      ['Sommer 2023', 'Girls\' Day und Frauen in Männerberufen: Textaussagen (4), Karikatur Nachtarbeit (4), Bürgerinitiative/Petition (4), Wahlpflicht (6), Schaubild Gleichstellungsindex (6), Brief mit Vorschlägen an den Chef (6)'],
      ['Sommer 2024', 'Künstliche Intelligenz: Begriff (2), Fachkräftemangel nach Berufsgruppen (6), Risiken und Ziele der EU-KI-Verordnung (4), EU-Gesetzgebung (6), EU-Organe (6), Stellungnahme an den Betriebsrat (6)'],
    ]],
    ['see', ['wiso-wahlen', 'wiso-demografie', 'wiso-ki', 'wiso-eu', 'wiso-methoden', 'wiso-betriebsrat'], 'Erklärt auf'],
    ['h', 'Deutsch (120 Minuten, Typ I oder Typ II)'],
    ['p', 'Teil 1 Textverständnis und Sprachgebrauch (25 Punkte), Teil 2 Schreibaufgabe (25 Punkte). Alle Aufgaben 2022 bis 2024 mit Mustern auf der Seite "Die Deutschprüfung".'],
    ['see', ['de-pruefung', 'de-text', 'de-eroerterung', 'de-brief', 'de-sprache'], 'Erklärt auf'],
    ['h', 'Abschlussprüfung Teil 1 (AP1, 2022 bis 2026)'],
    ['table', ['Bereich', 'Typische Aufgaben'], [
      ['Beschaffung', 'Kundenanforderungen herausarbeiten, Nutzwertanalyse, quantitativer Angebotsvergleich, Handelskalkulation, Bezugsquellen, Gründe für bisherigen Lieferanten, Checkliste Wareneingang, Kaufvertrag und Angebot (Bestandteile)'],
      ['Netzwerk', 'IP-Bereich, Broadcast, Gateway, DHCP, Drucker im falschen Subnetz, LWL-Patchkabel (OM4/OS2, LC/SC), MAC vs. IP (OSI), Paketanalyse, Wi-Fi 6, IPv6-Adresstypen, öffentliche vs. private IPs, Firewall-Funktionen'],
      ['IT-Sicherheit', 'Schutzbedarfsfeststellung, personenbezogene Daten (DSGVO-Kategorien), USV-Dimensionierung (Watt, VA, Reserve, Überbrückungszeit), Gefährdungen der Verfügbarkeit, Ransomware, SLA prüfen'],
      ['Daten und Software', 'ERM mit Kardinalitäten, Relationenschema, CREATE/UPDATE/INSERT-Fehler, SUM/COUNT, Export als CSV/XML/JSON, Pseudocode-Fehler finden, Prüfziffer, Suchlogik, deleteOldFiles'],
      ['Betrieb', 'Organigramm (Einlinien-/Stabliniensystem), Rechtsformen (GmbH, OHG, e. K.), Firmierung, Stromkosten, ITIL (Event, Incident, Service Request), Syslog-Stufen'],
    ]],
    ['see', ['ps-angebot', 'ps-beschaffung', 'ps-kaufvertrag', 'infra-ipconfig', 'infra-medien', 'infra-wlan', 'infra-ipv6', 'infra-firewall', 'infra-grundschutz', 'infra-usv', 'ps-itsm', 'ps-er', 'eua-sqlexam', 'eua-formate', 'eua-algoexam', 'wiso-unternehmen', 'wiso-organisation'], 'Erklärt auf'],
  ],
});
