AP2.page('ref-glossar', {
  b: 'ref', g: 'Referenz', t: 'Glossar',
  d: 'Kurze **Definitionen** wichtiger Fachbegriffe, alphabetisch sortiert. Englische Begriffe stehen in Klammern.',
  m: 'Begriff, Definition, Beispiel. **Eigene Worte** üben.',
  cheat: [['Hinweis', ['Begriffe aus dem ganzen Stoff', 'Ausführliche Erklärung auf der Themenseite']]],
  blocks: [
    ['kv', [
      ['ACID', 'Atomarität, Konsistenz, Isolation, Dauerhaftigkeit: Eigenschaften einer Datenbanktransaktion.'],
      ['Algorithmus', 'Endliche, eindeutige Handlungsvorschrift zur Lösung eines Problems.'],
      ['API', 'Schnittstelle, über die Programme miteinander kommunizieren.'],
      ['Backup', 'Datensicherung; Voll, differenziell, inkrementell.'],
      ['Betriebsrat', 'Gewählte Vertretung der Arbeitnehmer im Betrieb (BetrVG).'],
      ['CIA-Triade', 'Vertraulichkeit, Integrität, Verfügbarkeit.'],
      ['DSGVO', 'EU-Datenschutz-Grundverordnung zum Schutz personenbezogener Daten.'],
      ['Firewall', 'Filtert Netzwerkverkehr nach Regeln.'],
      ['Gantt-Diagramm', 'Balkenplan, der Vorgänge über die Zeit darstellt.'],
      ['GmbH', 'Kapitalgesellschaft mit beschränkter Haftung, 25.000 Euro Stammkapital.'],
      ['Hash', 'Ergebnis einer Einwegfunktion fester Länge.'],
      ['Integrität', 'Daten sind vollständig und unverändert.'],
      ['Kritischer Pfad', 'Weg im Netzplan ohne Puffer; bestimmt die Projektdauer.'],
      ['Lastenheft', 'Anforderungen des Auftraggebers: Was und Wofür.'],
      ['Pflichtenheft', 'Umsetzung des Auftragnehmers: Wie und Womit.'],
      ['MTBF', 'Mean Time Between Failures: mittlere Betriebszeit zwischen Ausfällen.'],
      ['Normalisierung', 'Beseitigung von Redundanzen in Tabellen (1NF bis 3NF).'],
      ['OSI-Modell', 'Referenzmodell mit 7 Schichten für Netzkommunikation.'],
      ['PKI', 'Infrastruktur für digitale Zertifikate und Schlüssel.'],
      ['RAID', 'Zusammenschluss von Festplatten für Leistung oder Redundanz.'],
      ['Scrum', 'Agiles Rahmenwerk mit Sprints, Product Owner, Scrum Master, Team.'],
      ['Subnetting', 'Aufteilen eines Netzes in kleinere Netze mit Subnetzmaske.'],
      ['TLS', 'Verschlüsselungsprotokoll für sichere Verbindungen (HTTPS).'],
      ['UML', 'Standardnotation für Modelle von Software.'],
      ['Verfügbarkeit', 'Anteil der Zeit, in der ein System funktioniert.'],
    ]],
    ['quiz', [{q: 'Wofür steht CIA in der IT-Sicherheit?', o: ['Confidentiality, Integrity, Availability', 'Computer, Internet, Access', 'Control, Inspect, Audit', 'Cloud, Intranet, API'], a: 0, e: 'Vertraulichkeit, Integrität, Verfügbarkeit.'}]],
  ],
});
