AP2.page('ps-angebot', {
  b: 'ps', g: 'Kaufmännische Rechnungen', t: 'Angebotsvergleich: quantitativ (Bezugskalkulation) und qualitativ (Nutzwertanalyse)',
  d: 'Beim **quantitativen (rechnerischen) Angebotsvergleich** berechnet man für jedes Angebot den **Bezugspreis (Einstandspreis)**: Listenpreis - Rabatt = Zieleinkaufspreis - Skonto = Bareinkaufspreis + Bezugskosten = Bezugspreis. Beim **qualitativen Angebotsvergleich (Nutzwertanalyse)** bewertet man auch **nicht-preisliche Kriterien** (Qualität, Garantie, Lieferzeit, Nachhaltigkeit): Jedes Kriterium bekommt eine **Gewichtung** (Summe 100 %), jedes Angebot **Punkte**; **gewichtete Punkte = Gewichtung · Punkte**, das Angebot mit der höchsten Summe gewinnt.',
  m: '**"Listen - Rabatt - Skonto + Bezug"** (LRSB). **Rabatt** gibt es für Menge/Treue sofort, **Skonto** für schnelle Zahlung, **Bezugskosten** sind Fracht/Verpackung. Skonto wird vom **Zieleinkaufspreis** (nach Rabatt) berechnet. "**frei Haus**" = keine Bezugskosten. Preise immer **netto** vergleichen.',
  cheat: [
    ['Bezugskalkulation', ['Listeneinkaufspreis (netto)', '**- Liefererrabatt** (%)', '**= Zieleinkaufspreis**', '**- Liefererskonto** (%)', '**= Bareinkaufspreis**', '**+ Bezugskosten** (Fracht, Verpackung)', '**= Bezugspreis / Einstandspreis**']],
    ['Nutzwertanalyse', ['Kriterien festlegen', 'Gewichtung (Summe 100 %)', 'Punkte je Angebot (z. B. 1 bis 10)', 'gewichtete Punkte = G · P', 'Summe bilden, höchste gewinnt']],
    ['Weitere Kriterien', ['Qualität, Garantie, Service', 'Lieferzeit, Liefertreue', 'Zuverlässigkeit, Image', 'Umwelt/Nachhaltigkeit', 'Zahlungsbedingungen, Erfahrungen']],
    ['Begriffe', ['**netto** = ohne USt (19 %)', '**brutto** = mit USt', '**frei Haus**: Lieferant zahlt Versand', '**30 Tage Ziel**: Zahlungsfrist', '**2 % Skonto in 10 Tagen**']],
  ],
  blocks: [
    ['h', 'Warum zwei Arten von Vergleich?'],
    ['p', 'Das billigste Angebot ist nicht automatisch das beste. Ein Access Point für 178 € mit 7 Jahren Garantie kann besser sein als einer für 170 € mit nur 2 Jahren. Deshalb vergleicht man zuerst **rechnerisch** (Was kostet mich die Ware wirklich, bis sie bei mir im Lager liegt?) und dann **qualitativ** (Wie gut erfüllt das Angebot meine sonstigen Anforderungen?).'],
    ['h', 'Quantitativer Vergleich: die Bezugskalkulation'],
    ['table', ['Begriff', 'Bedeutung', 'Typische Formulierung im Angebot'], [
      ['**Listeneinkaufspreis**', 'Preis laut Preisliste/Angebot, netto', '"Listenpreis 1.149,00 € zzgl. MwSt."'],
      ['**Rabatt**', 'Preisnachlass, z. B. für Menge oder Treue', '"ab 5 Geräten 5 % Rabatt"'],
      ['**Zieleinkaufspreis**', 'Preis, wenn man das Zahlungsziel ausnutzt', ''],
      ['**Skonto**', 'Nachlass für Zahlung innerhalb kurzer Frist', '"2 % Skonto bei Zahlung innerhalb 8 Tagen"'],
      ['**Bareinkaufspreis**', 'Preis bei sofortiger Zahlung', ''],
      ['**Bezugskosten**', 'Fracht, Verpackung, Versicherung, Zoll', '"Versand 5,00 € pro Stück", "Bezugskosten 7,99 €"'],
      ['**Bezugspreis** (= Einstandspreis)', 'Was die Ware wirklich kostet', ''],
    ]],
    ['warn', 'Häufige Fehler: (1) Skonto vom **Listenpreis** statt vom Zieleinkaufspreis berechnen. (2) Bezugskosten **je Stück** und **pauschal** verwechseln ("5 € pro Stück" bei 10 Stück = 50 €; "100 € pro Lieferung" = einmal 100 €). (3) Rabatt geben, obwohl die **Mindestmenge** nicht erreicht ist ("ab 10 Stück" bei 8 Stück: kein Rabatt). (4) Brutto- und Nettopreise mischen.'],
    ['h', 'Prüfungsbeispiel: 10 Notebooks (Winter 2025/26)'],
    ['p', '**Schneider KG:** Listenpreis 1.149 €, ab 5 Geräten 5 % Rabatt, 2 % Skonto, Verpackung/Transport 5 € pro Stück. **Hardware Solutions GmbH:** Listenpreis 1.199 €, 7 % Rabatt ab 10 Stück, 3 % Skonto, frei Haus.'],
    ['table', ['Kalkulation (je Stück)', 'Schneider KG', 'Hardware Solutions'], [
      ['Listeneinkaufspreis', '1.149,00 €', '1.199,00 €'],
      ['- Rabatt', '5 % = 57,45 €', '7 % = 83,93 €'],
      ['= Zieleinkaufspreis', '1.091,55 €', '1.115,07 €'],
      ['- Skonto', '2 % = 21,83 €', '3 % = 33,45 €'],
      ['= Bareinkaufspreis', '1.069,72 €', '1.081,62 €'],
      ['+ Bezugskosten', '5,00 €', '0,00 € (frei Haus)'],
      ['= Bezugspreis je Stück', '**1.074,72 €**', '1.081,62 €'],
      ['Bezugspreis für 10 Stück', '**10.747,19 €**', '10.816,18 €'],
    ]],
    ['p', 'Rechnerisch ist **Schneider KG** günstiger. Trotzdem kann die Wahl auf Hardware Solutions fallen, wenn z. B. die schnellere Lieferzeit (7 statt 10 Tage) oder das längere Zahlungsziel wichtiger sind. Dafür gibt es den qualitativen Vergleich.'],
    ['tool', 'bezug'],
    ['h', 'Qualitativer Vergleich: die Nutzwertanalyse'],
    ['steps', [
      '**Kriterien** festlegen, die für die Entscheidung wichtig sind (z. B. Preis, Übertragungsrate, Sicherheit, Garantie, Energieverbrauch).',
      '**Gewichtung** je Kriterium vergeben (in %, Summe = 100 %). Wichtige Kriterien bekommen mehr Gewicht.',
      'Jedes Angebot je Kriterium mit **Punkten** bewerten (z. B. 1 = schlecht bis 10 = sehr gut).',
      '**Gewichtete Punkte** = Gewichtung · Punkte (z. B. 30 % · 8 = 2,4 oder 30 · 8 = 240).',
      'Gewichtete Punkte je Angebot **addieren**. Das Angebot mit der **höchsten Summe** ist das beste.',
      'Entscheidung **begründen** (in einem Satz mit Bezug auf die Summe und die wichtigsten Kriterien).',
    ]],
    ['table', ['Kriterium', 'Gewichtung', 'AZOS AP-42', 'Getnear AP-08', 'ELink AP-15'], [
      ['Preis', '30 %', '9 → 2,7', '7 → 2,1', '6 → 1,8'],
      ['Übertragungsrate', '20 %', '9 → 1,8', '7 → 1,4', '4 → 0,8'],
      ['Sicherheit (WPA3)', '20 %', '10 → 2,0', '6 → 1,2', '10 → 2,0'],
      ['Leistungsaufnahme', '10 %', '9 → 0,9', '6 → 0,6', '8 → 0,8'],
      ['MTBF / Garantie', '20 %', '10 → 2,0', '6 → 1,2', '5 → 1,0'],
      ['**Summe**', '**100 %**', '**9,4**', '6,5', '6,4'],
    ]],
    ['note', 'Beispiel in Anlehnung an Winter 2022/23 (Access Points): AZOS hat 1200 Mbit/s im 5-GHz-Band, WPA3, 7 Jahre Garantie und die höchste MTBF. Ergebnis: **AZOS** schneidet in beiden Vergleichen am besten ab. Punkte sind teilweise subjektiv; in der Prüfung zählt eine **nachvollziehbare Begründung**.'],
    ['procon', 'Nutzwertanalyse', ['Bezieht **nicht messbare** Kriterien (Qualität, Image, Nachhaltigkeit) ein', 'Entscheidung wird **transparent** und **nachvollziehbar**', 'Gewichtung bildet die **Prioritäten** des Unternehmens ab'], ['**Subjektiv**: Gewichtung und Punkte hängen von der Person ab', 'Scheingenauigkeit durch Zahlen', 'Aufwendig bei vielen Kriterien']],
    ['h', 'Nettopreise und Umsatzsteuer'],
    ['p', 'Unternehmen kalkulieren mit **Nettopreisen**, weil sie die gezahlte Umsatzsteuer als **Vorsteuer** vom Finanzamt zurückbekommen (Vorsteuerabzug). Die Umsatzsteuer ist für Unternehmen ein **durchlaufender Posten**; nur der Endverbraucher trägt sie wirklich. Brutto = Netto · 1,19; Netto = Brutto / 1,19.'],
    ['h', 'Übungen'],
    ['qa', 'Lieferant A: 5,50 € je T-Shirt, 10 % Rabatt ab 500 Stück, 2 % Skonto, 100 € Bearbeitung pauschal. Lieferant B: 5,15 € je Stück, 5 % Rabatt, netto Kasse, frei Haus. Berechnen Sie den Bezugspreis für 1.000 T-Shirts (Sommer 2022).', [['table', ['', 'A: Shirts & more', 'B: Weber Print'], [['Listenpreis', '5.500,00 €', '5.150,00 €'], ['- Rabatt', '550,00 € (10 %)', '257,50 € (5 %)'], ['= Zieleinkaufspreis', '4.950,00 €', '4.892,50 €'], ['- Skonto', '99,00 € (2 %)', '0,00 €'], ['= Bareinkaufspreis', '4.851,00 €', '4.892,50 €'], ['+ Bezugskosten', '100,00 €', '0,00 €'], ['= Bezugspreis', '4.951,00 €', '**4.892,50 €**']]], 'Rechnerisch ist **Weber Print** günstiger.'], 9],
    ['qa', 'Nennen Sie vier Kriterien außer dem Preis, die für die Wahl eines Lieferanten wichtig sein können.', ['- Qualität der Ware und Garantie', '- Lieferzeit und Liefertreue (Termintreue)', '- Service, Kulanz, Verhalten bei Reklamationen', '- Zuverlässigkeit und Erfahrungen aus früheren Geschäften', '- Ökologische und soziale Nachhaltigkeit, Standort (regional)'], 2],
    ['qa', 'Erläutern Sie, wie die Nutzwertanalyse funktioniert und warum sie bei der Auswahl eines Angebots sinnvoll ist.', 'Man legt Kriterien fest, gewichtet sie nach Wichtigkeit (Summe 100 %), vergibt für jedes Angebot Punkte je Kriterium, multipliziert Punkte mit Gewichtung und addiert. Das Angebot mit dem höchsten Nutzwert wird gewählt. Sinnvoll, weil auch **qualitative** Kriterien (Service, Garantie, Nachhaltigkeit) objektiviert und nachvollziehbar in die Entscheidung einfließen, nicht nur der Preis.', 5],
    ['quiz', [
      {q: 'Wovon wird der Skonto berechnet?', o: ['Vom Zieleinkaufspreis', 'Vom Listenpreis', 'Vom Bezugspreis', 'Vom Bruttopreis'], a: 0, e: 'Erst Rabatt abziehen, dann Skonto vom Ergebnis.'},
      {q: 'Was bedeutet "Lieferung frei Haus"?', o: ['Keine Bezugskosten für den Käufer', 'Kein Rabatt', 'Zahlung sofort', 'Keine Umsatzsteuer'], a: 0, e: 'Der Lieferant trägt die Versandkosten.'},
      {q: 'Welche Reihenfolge ist richtig?', o: ['Listenpreis, Rabatt, Skonto, Bezugskosten', 'Listenpreis, Skonto, Rabatt, Bezugskosten', 'Bezugskosten, Rabatt, Skonto', 'Rabatt, Listenpreis, Skonto'], a: 0, e: 'LRSB.'},
      {q: 'Gewichtung 25 %, Punkte 8. Gewichtete Punkte?', o: ['2', '33', '8,25', '0,32'], a: 0, e: '0,25 · 8 = 2.'},
      {q: 'Warum vergleichen Unternehmen Nettopreise?', o: ['Die Umsatzsteuer erhalten sie als Vorsteuer zurück', 'Brutto ist verboten', 'Netto ist immer höher', 'Wegen Skonto'], a: 0, e: 'Für Unternehmen ist die USt ein durchlaufender Posten.'},
    ]],
    ['see', ['ps-kostenarten', 'ps-kalkulation', 'ps-kaufvertrag', 'ps-beschaffung']],
  ],
});
