AP2.page('ps-beschaffung', {
  b: 'ps', g: 'Kaufmännische Rechnungen', t: 'Beschaffung: optimale Bestellmenge, Bestellverfahren und Wareneingang',
  d: 'Die **optimale Bestellmenge** ist die Menge, bei der die **Summe aus Bestellkosten und Lagerkosten** pro Jahr am **kleinsten** ist. Viele kleine Bestellungen verursachen hohe **Bestellkosten**, wenige große Bestellungen hohe **Lagerkosten**. Beim **Bestellpunktverfahren** wird bestellt, sobald der **Meldebestand** erreicht ist; beim **Bestellrhythmusverfahren** in **festen Zeitabständen**.',
  m: '**Im Optimum sind Bestellkosten = Lagerkosten.** Lagerkosten = **durchschnittlicher Lagerbestand (Menge / 2) · Einstandspreis · Lagerkostensatz**. Bestellkosten = **Anzahl Bestellungen · Kosten je Bestellung**. **Meldebestand = Tagesverbrauch · Lieferzeit + Mindestbestand.**',
  cheat: [
    ['Formeln', ['Bestellungen/Jahr = Jahresbedarf / Bestellmenge', 'Ø Lagerbestand = Bestellmenge / 2', 'Lagerkosten = Ø Bestand · Preis · Lagerkostensatz', 'Andler: x = √(200 · M · K_B / (P · L%))']],
    ['Bestellverfahren', ['**Bestellpunkt**: bei Meldebestand, Termine unregelmäßig', '**Bestellrhythmus**: feste Intervalle (alle 14 Tage)', 'Meldebestand = Verbrauch/Tag · Lieferzeit + Mindestbestand']],
    ['Bezugsquellen', ['**Intern**: Lieferantendatei, frühere Bestellungen, Kollegen', '**Extern**: Internet/Plattformen, Messen, Kataloge, Branchenbücher, Vertreter']],
    ['Wareneingang', ['Lieferschein mit Bestellung vergleichen', 'Verpackung auf Schäden prüfen (im Beisein des Boten)', 'Menge und Art prüfen', 'Ware auf Mängel prüfen, Mängel sofort rügen']],
  ],
  blocks: [
    ['h', 'Das Grundproblem'],
    ['p', 'Ein Unternehmen braucht im Jahr **1.200 Rauchmelder**. Es kann einmal 1.200 Stück bestellen (wenige Bestellkosten, aber das Lager ist voll und bindet Kapital) oder jede Woche 23 Stück (leeres Lager, aber 52 Bestellungen mit Porto, Bearbeitung, Prüfung). Irgendwo dazwischen liegt das **Kostenminimum**.'],
    ['table', ['Kostenart', 'Was gehört dazu?', 'Verhalten bei größerer Bestellmenge'], [
      ['**Bestellkosten** (fix je Bestellung)', 'Angebote einholen, Bestellung schreiben, Wareneingang prüfen, Rechnung buchen', '**sinken** (weniger Bestellungen)'],
      ['**Lagerkosten**', 'Kapitalbindung (Zinsen), Miete, Versicherung, Schwund, Veralterung', '**steigen** (mehr Ware im Lager)'],
    ]],
    ['h', 'Tabellarische Lösung (wie mit Excel in der Prüfung)'],
    ['p', 'Daten (in Anlehnung an Sommer 2022): Jahresbedarf 1.200 Stück, Einstandspreis 19,50 €, Kosten je Bestellung 25,00 €, Lagerkostensatz 20 %.'],
    ['table', ['Bestellmenge', 'Bestellungen pro Jahr', 'Ø Lagerbestand', 'Bestellkosten', 'Lagerkosten', 'Gesamtkosten'], [
      ['50', '24', '25', '600,00 €', '97,50 €', '697,50 €'],
      ['100', '12', '50', '300,00 €', '195,00 €', '495,00 €'],
      ['**120**', '**10**', '**60**', '**250,00 €**', '**234,00 €**', '**484,00 €**'],
      ['150', '8', '75', '200,00 €', '292,50 €', '492,50 €'],
      ['200', '6', '100', '150,00 €', '390,00 €', '540,00 €'],
      ['300', '4', '150', '100,00 €', '585,00 €', '685,00 €'],
    ]],
    ['chart', {kind: 'line', w: 720, h: 320, labels: ['50', '100', '120', '150', '200', '300'], series: [
      {n: 'Bestellkosten', d: [600, 300, 250, 200, 150, 100], k: 'text3'},
      {n: 'Lagerkosten', d: [97.5, 195, 234, 292.5, 390, 585], k: 'text'},
      {n: 'Gesamtkosten', d: [697.5, 495, 484, 492.5, 540, 685], k: 'accent'},
    ], ymax: 750, yl: 'Kosten pro Jahr in €', cap: 'Die Gesamtkostenkurve hat ihr Minimum dort, wo sich Bestell- und Lagerkosten schneiden (rechnerisch bei etwa 124 Stück).'}],
    ['p', 'Mit der **Andler-Formel** genau: x = √(200 · 1.200 · 25 / (19,50 · 20)) = √15.385 ≈ **124 Stück**. In Excel nutzt man "kopierfähige Formeln", z. B. `=$B$3/A8` für die Anzahl Bestellungen (Jahresbedarf absolut adressiert) und `=A8/2*$B$4*$D$4` für die Lagerkosten.'],
    ['tool', 'andler'],
    ['h', 'Warum weicht man trotzdem ab?'],
    ['list', ['**Unregelmäßiger Verbrauch** (Saisonartikel, Weihnachten)', '**Fehlender Lagerplatz** oder fehlendes **Kapital**', 'Drohender **Preisverfall** oder **technische Veralterung** (gerade bei IT-Hardware!)', 'Drohende **Lieferengpässe** oder Preiserhöhungen (dann mehr bestellen)', '**Mengenrabatte** ab bestimmten Mengen', 'Mindestabnahmemengen des Lieferanten']],
    ['h', 'Bestellpunkt- und Bestellrhythmusverfahren'],
    ['table', ['', 'Bestellpunktverfahren', 'Bestellrhythmusverfahren'], [
      ['Auslöser', 'Lagerbestand erreicht den **Meldebestand**', 'Fester **Termin** (z. B. alle 14 Tage)'],
      ['Bestelltermine', 'unregelmäßig', 'regelmäßig'],
      ['Bestellmenge', 'meist fest (z. B. optimale Menge)', 'oft variabel (auffüllen auf Höchstbestand)'],
      ['Geeignet für', 'schwankenden Verbrauch, wichtige Teile', 'gleichmäßigen Verbrauch, einfache Planung'],
    ]],
    ['ex', ['Tagesverbrauch 5 Stück, Lieferzeit 6 Tage, Mindestbestand (eiserne Reserve) 20 Stück.', 'Meldebestand = 5 · 6 + 20 = **50 Stück**. Sinkt der Bestand auf 50, wird bestellt; bis die Ware kommt, werden 30 verbraucht, die Reserve von 20 bleibt.']],
    ['h', 'Bezugsquellen und Wareneingangsprüfung'],
    ['table', ['Interne Bezugsquellen', 'Externe Bezugsquellen'], [['Lieferantendatei / ERP-System', 'Internet, Suchmaschinen, B2B-Plattformen'], ['Frühere Angebote und Bestellungen', 'Fachmessen, Ausstellungen'], ['Erfahrungen von Kollegen', 'Kataloge, Fachzeitschriften, Branchenverzeichnisse'], ['Artikeldatei', 'Vertreterbesuche, Kammern (IHK)']]],
    ['steps', [
      '**Sofort bei Anlieferung (im Beisein des Boten):** Anschrift, Anzahl der Packstücke, äußere Beschädigung prüfen. Schäden auf dem Lieferschein vermerken lassen.',
      '**Lieferschein mit Bestellung vergleichen:** Art, Menge, Ausführung.',
      '**Unverzüglich danach:** Ware auspacken und auf **Mängel** prüfen (Funktion, Kratzer, falsche Teile).',
      '**Mängel unverzüglich rügen** (beim zweiseitigen Handelskauf Pflicht nach § 377 HGB, sonst verliert man die Rechte).',
      'Ware einlagern, Bestand buchen, Rechnung prüfen.',
    ]],
    ['h', 'Übungen'],
    ['qa', 'Erklären Sie den Unterschied zwischen Bestellpunkt- und Bestellrhythmusverfahren.', 'Beim **Bestellpunktverfahren** wird bestellt, sobald der Lagerbestand den **Meldebestand** erreicht; die Bestelltermine sind daher unregelmäßig. Beim **Bestellrhythmusverfahren** wird in **festen Zeitabständen** bestellt (z. B. alle 14 Tage), unabhängig vom genauen Bestand.', 4],
    ['qa', 'Nennen Sie zwei Argumente, von der optimalen Bestellmenge abzuweichen.', ['- Fehlender Lagerplatz oder zu wenig Kapital', '- Drohender Preisverfall/Veralterung (IT-Hardware) oder drohende Lieferengpässe'], 4],
    ['qa', 'Erläutern Sie vier Arbeitsschritte bei der Wareneingangsprüfung eines gelieferten Videoüberwachungssystems.', ['- Packstücke zählen und Verpackung auf äußere Schäden prüfen (im Beisein des Zustellers, Schäden quittieren lassen)', '- Lieferschein mit der Bestellung vergleichen (Art, Menge)', '- Geräte auspacken, auf Vollständigkeit (Zubehör, Kabel) und sichtbare Mängel prüfen', '- Funktionstest durchführen; Mängel unverzüglich schriftlich beim Lieferanten rügen'], 8],
    ['quiz', [
      {q: 'Was gilt im Optimum der Bestellmenge?', o: ['Bestellkosten = Lagerkosten', 'Lagerkosten = 0', 'Bestellkosten maximal', 'Nur eine Bestellung pro Jahr'], a: 0, e: 'Die Gesamtkosten sind dort minimal.'},
      {q: 'Wie berechnet man den durchschnittlichen Lagerbestand (ohne Mindestbestand)?', o: ['Bestellmenge / 2', 'Jahresbedarf / 2', 'Bestellmenge · 2', 'Jahresbedarf / Bestellmenge'], a: 0, e: 'Der Bestand sinkt gleichmäßig von voll auf null.'},
      {q: 'Tagesverbrauch 10, Lieferzeit 5 Tage, Mindestbestand 30. Meldebestand?', o: ['80', '50', '30', '35'], a: 0, e: '10 · 5 + 30 = 80.'},
      {q: 'Was steigt, wenn man größere Mengen bestellt?', o: ['Lagerkosten', 'Bestellkosten', 'Anzahl der Bestellungen', 'Bestellhäufigkeit'], a: 0, e: 'Mehr Ware liegt im Lager und bindet Kapital.'},
    ]],
    ['see', ['ps-angebot', 'ps-kaufvertrag', 'ps-kostenarten']],
  ],
});
