AP2.page('ps-dsgvo', {
  b: 'ps', g: 'Recht und Datenschutz', t: 'DSGVO: Grundsätze und Betroffenenrechte',
  d: 'Die **Datenschutz-Grundverordnung (DSGVO)** schützt die **personenbezogenen Daten** natürlicher Personen in der EU. Verarbeitung ist nur erlaubt, wenn sie den **Grundsätzen** des Art. 5 entspricht und eine **Rechtsgrundlage** (Art. 6) hat. Betroffene haben **Rechte** (Auskunft, Berichtigung, Löschung usw.).',
  m: 'Grundsätze (Art. 5): **R-Z-D-R-S-I-R** = **R**echtmäßigkeit/Transparenz, **Z**weckbindung, **D**atenminimierung, **R**ichtigkeit, **S**peicherbegrenzung, **I**ntegrität und Vertraulichkeit, **R**echenschaftspflicht. Verbot mit Erlaubnisvorbehalt: **Alles verboten, außer es gibt eine Rechtsgrundlage.**',
  cheat: [
    ['Personenbezogene Daten', ['Alle Infos über **identifizierte oder identifizierbare** Person', 'Name, E-Mail, Adresse, **IP-Adresse**, Kundennummer, Foto', '**Besondere Kategorien (Art. 9):** Gesundheit, Religion, Biometrie, Gewerkschaft']],
    ['Grundsätze (Art. 5)', ['Rechtmäßigkeit, Treu und Glauben, Transparenz', 'Zweckbindung', 'Datenminimierung', 'Richtigkeit', 'Speicherbegrenzung', 'Integrität und Vertraulichkeit', 'Rechenschaftspflicht']],
    ['Rechtsgrundlagen (Art. 6)', ['**Einwilligung**', '**Vertrag** erfüllen', 'Rechtliche **Verpflichtung**', 'Lebenswichtige Interessen', 'Öffentliche Aufgabe', '**Berechtigtes Interesse**']],
    ['Betroffenenrechte', ['**Auskunft** (15), **Berichtigung** (16)', '**Löschung** (17), **Einschränkung** (18)', '**Datenübertragbarkeit** (20)', '**Widerspruch** (21), Widerruf der Einwilligung', 'Beschwerde bei Aufsichtsbehörde']],
  ],
  blocks: [
    ['h', 'Worum geht es?'],
    ['p', 'Seit dem **25. Mai 2018** gilt in der ganzen EU die DSGVO (englisch: GDPR). Sie gilt für **jede** Verarbeitung personenbezogener Daten, also auch für Software, die du entwickelst. In Deutschland ergänzt das **Bundesdatenschutzgesetz (BDSG)** die Verordnung. Wer sich nicht daran hält, riskiert **Bußgelder bis 20 Millionen Euro oder 4 Prozent des weltweiten Jahresumsatzes** (je nachdem, was höher ist).'],
    ['h', 'Wichtige Begriffe'],
    ['kv', [
      ['Personenbezogene Daten', 'Alle Informationen, die sich auf eine **identifizierte oder identifizierbare natürliche Person** beziehen. Auch eine IP-Adresse oder eine Kundennummer, wenn man damit auf die Person schließen kann.'],
      ['Betroffene Person', 'Die Person, deren Daten verarbeitet werden (zum Beispiel der Kunde).'],
      ['Verantwortlicher', 'Wer über **Zweck und Mittel** der Verarbeitung entscheidet (meist das Unternehmen).'],
      ['Auftragsverarbeiter', 'Wer im Auftrag des Verantwortlichen Daten verarbeitet (zum Beispiel ein Cloud-Anbieter). Braucht einen **Auftragsverarbeitungsvertrag (AVV)**.'],
      ['Verarbeitung', 'Jeder Vorgang mit Daten: erheben, speichern, ändern, übermitteln, löschen.'],
      ['Besondere Kategorien', 'Besonders sensible Daten (Gesundheit, Religion, politische Meinung, Biometrie). Strengere Regeln.'],
    ]],
    ['h', 'Die Grundsätze der Verarbeitung (Art. 5)'],
    ['table', ['Grundsatz', 'Bedeutung', 'Beispiel aus der Praxis'], [
      ['Rechtmäßigkeit, Treu und Glauben, Transparenz', 'Es muss eine Rechtsgrundlage geben, die Verarbeitung ist fair, die Person wird informiert.', 'Datenschutzerklärung erklärt, wofür E-Mail-Adressen genutzt werden.'],
      ['Zweckbindung', 'Daten dürfen nur für den **festgelegten** Zweck genutzt werden.', 'Die Adresse aus der Bestellung darf nicht ohne Weiteres für Werbung genutzt werden.'],
      ['Datenminimierung', 'Nur so viele Daten erheben, wie **notwendig**.', 'Für einen Newsletter reicht die E-Mail-Adresse, das Geburtsdatum ist nicht nötig.'],
      ['Richtigkeit', 'Daten müssen sachlich **richtig** und aktuell sein.', 'Falsche Adresse wird auf Antrag korrigiert.'],
      ['Speicherbegrenzung', 'Daten nur so lange speichern, wie es der Zweck verlangt.', 'Bewerberdaten nach Abschluss des Verfahrens löschen (üblich nach wenigen Monaten).'],
      ['Integrität und Vertraulichkeit', 'Angemessene **Sicherheit** (Schutz vor Verlust und unbefugtem Zugriff).', 'Verschlüsselung, Zugriffsrechte, Backups.'],
      ['Rechenschaftspflicht', 'Der Verantwortliche muss die Einhaltung **nachweisen** können.', 'Dokumentation, Verzeichnis der Verarbeitungstätigkeiten.'],
    ]],
    ['h', 'Rechtsgrundlagen (Art. 6)'],
    ['p', 'Die DSGVO ist ein **Verbot mit Erlaubnisvorbehalt**: Jede Datenverarbeitung ist verboten, außer es gibt eine Rechtsgrundlage. Mindestens eine muss zutreffen:'],
    ['table', ['Rechtsgrundlage', 'Beispiel'], [
      ['Einwilligung der Person (freiwillig, informiert, widerrufbar)', 'Newsletter-Anmeldung per Opt-in'],
      ['Erfüllung eines **Vertrags**', 'Lieferadresse speichern, um Ware zu versenden'],
      ['Erfüllung einer **rechtlichen Verpflichtung**', 'Aufbewahrung von Rechnungen (steuerrechtlich)'],
      ['Schutz lebenswichtiger Interessen', 'Notfall'],
      ['Wahrnehmung einer Aufgabe im **öffentlichen Interesse**', 'Behördliche Verarbeitung'],
      ['**Berechtigtes Interesse** des Verantwortlichen (nach Abwägung)', 'Betrugsprävention, IT-Sicherheit (Logdateien)'],
    ]],
  ],
});
