AP2.add('ps-dsgvo', [
  ['h', 'Betroffenenrechte'],
  ['p', 'Jede Person kann von dem Verantwortlichen verlangen, dass er ihre Rechte erfüllt. In der Regel muss er **innerhalb eines Monats** antworten. Als Entwickler musst du diese Rechte **technisch ermöglichen** (zum Beispiel Export und Löschen von Nutzerdaten).'],
  ['table', ['Recht', 'Artikel', 'Inhalt'], [
    ['Informationspflicht', 'Art. 13, 14', 'Person wird bei Erhebung informiert: wer, welche Daten, wofür, wie lange, an wen (Datenschutzerklärung).'],
    ['Auskunftsrecht', 'Art. 15', 'Person kann erfahren, **ob und welche** Daten gespeichert sind, und eine Kopie verlangen.'],
    ['Berichtigung', 'Art. 16', 'Falsche Daten müssen korrigiert werden.'],
    ['Löschung ("Recht auf Vergessenwerden")', 'Art. 17', 'Löschung, wenn Zweck entfallen, Einwilligung widerrufen oder unrechtmäßig verarbeitet. **Ausnahme:** Aufbewahrungspflichten.'],
    ['Einschränkung der Verarbeitung', 'Art. 18', 'Daten werden gesperrt, aber nicht gelöscht (zum Beispiel während der Prüfung der Richtigkeit).'],
    ['Datenübertragbarkeit', 'Art. 20', 'Person kann Daten in einem **gängigen, maschinenlesbaren Format** (zum Beispiel CSV, JSON) bekommen und zu einem anderen Anbieter mitnehmen.'],
    ['Widerspruch', 'Art. 21', 'Person kann der Verarbeitung (zum Beispiel für Werbung) widersprechen.'],
    ['Widerruf der Einwilligung', 'Art. 7', 'Jederzeit möglich, so einfach wie die Erteilung.'],
    ['Keine automatisierte Einzelentscheidung', 'Art. 22', 'Entscheidungen mit rechtlicher Wirkung dürfen nicht allein einem Algorithmus überlassen werden.'],
    ['Beschwerderecht', 'Art. 77', 'Beschwerde bei der Datenschutz-Aufsichtsbehörde.'],
  ]],
  ['h', 'Pflichten für Unternehmen und Entwickler'],
  ['kv', [
    ['Privacy by Design / by Default (Art. 25)', 'Datenschutz von Anfang an in die Software einbauen. **By Default:** Die datenschutzfreundlichsten Einstellungen sind voreingestellt.'],
    ['Technische und organisatorische Maßnahmen (TOM, Art. 32)', 'Verschlüsselung, Pseudonymisierung, Zugriffskontrolle, Backup, Schulung. Angemessen zum Risiko.'],
    ['Verzeichnis von Verarbeitungstätigkeiten (Art. 30)', 'Dokumentation: Welche Daten werden zu welchem Zweck verarbeitet?'],
    ['Auftragsverarbeitung (Art. 28)', 'Vertrag mit Dienstleistern, die Daten für uns verarbeiten (Hosting, Cloud).'],
    ['Datenschutz-Folgenabschätzung (Art. 35)', 'Bei **hohem Risiko** für die Betroffenen (zum Beispiel umfangreiche Überwachung) vorab durchführen.'],
    ['Datenschutzbeauftragter (Art. 37, BDSG § 38)', 'In Deutschland Pflicht, wenn in der Regel **mindestens 20 Personen** ständig mit automatisierter Verarbeitung personenbezogener Daten beschäftigt sind (oder bei besonders riskanter Verarbeitung).'],
    ['Meldepflicht bei Datenpannen (Art. 33, 34)', 'Meldung an die Aufsichtsbehörde **innerhalb von 72 Stunden**, bei hohem Risiko auch Information der Betroffenen.'],
    ['Übermittlung in Drittländer (Art. 44 ff.)', 'Daten dürfen nur in Länder außerhalb der EU, wenn dort ein angemessenes Schutzniveau besteht oder geeignete Garantien (zum Beispiel Standardvertragsklauseln) vorliegen.'],
  ]],
  ['h', 'Was bedeutet das für die Softwareentwicklung?'],
  ['list', ['**Datenminimierung:** Nur notwendige Felder abfragen, optionale Felder als optional kennzeichnen.', '**Sicherheit:** Passwörter nur als **gesalzener Hash** speichern (nie im Klartext), Verbindungen über HTTPS, Zugriffsrechte nach Rollen.', '**Löschkonzept:** Daten nach Ablauf der Frist automatisch löschen oder anonymisieren.', '**Einwilligung:** Opt-in (aktive Zustimmung, kein vorangekreuztes Kästchen), dokumentieren, Widerruf einfach machen.', '**Pseudonymisierung/Anonymisierung:** Wo möglich Namen durch IDs ersetzen. Anonyme Daten fallen nicht mehr unter die DSGVO.', '**Export- und Löschfunktion:** Auskunft und Datenübertragbarkeit technisch ermöglichen.', '**Logging:** Keine Passwörter oder unnötige personenbezogene Daten in Logdateien.']],
  ['table', ['Begriff', 'Bedeutung', 'Beispiel'], [
    ['Pseudonymisierung', 'Direkte Identifikation wird durch ein Kennzeichen ersetzt, Zuordnung ist mit Zusatzinformation möglich.', 'Statt "Anna Meier" die Nummer 4711; Zuordnungstabelle getrennt aufbewahrt.'],
    ['Anonymisierung', 'Kein Personenbezug mehr herstellbar, auch nicht mit Zusatzwissen.', 'Statistik: "35 Prozent der Nutzer sind 30 bis 39 Jahre alt".'],
    ['Verschlüsselung', 'Daten sind ohne Schlüssel nicht lesbar.', 'AES-256 für gespeicherte Daten, TLS bei der Übertragung.'],
  ]],
  ['h', 'Aufgaben im Prüfungsstil'],
  ['qa', 'Nennen Sie fünf Grundsätze der Datenverarbeitung nach Art. 5 DSGVO und erklären Sie zwei davon kurz.', ['Rechtmäßigkeit/Transparenz, Zweckbindung, Datenminimierung, Richtigkeit, Speicherbegrenzung, Integrität und Vertraulichkeit, Rechenschaftspflicht.', '**Zweckbindung:** Daten dürfen nur für den bei der Erhebung festgelegten Zweck verwendet werden. **Datenminimierung:** Es dürfen nur die Daten erhoben werden, die für den Zweck erforderlich sind.'], 5],
  ['qa', 'Ein Kunde verlangt die Löschung seiner Daten. Unter welchen Bedingungen muss der Betrieb dem nachkommen und was kann dem entgegenstehen?', 'Der Betrieb muss löschen, wenn der Zweck der Speicherung entfallen ist, die Einwilligung widerrufen wurde oder die Verarbeitung unrechtmäßig war (Art. 17). Entgegenstehen können **gesetzliche Aufbewahrungspflichten** (zum Beispiel Buchhaltungsunterlagen für mehrere Jahre). Dann werden die Daten gesperrt und erst nach Ablauf der Frist gelöscht.', 4],
  ['qa', 'Bei einem Hackerangriff wurden Kundendaten entwendet. Was muss das Unternehmen tun?', 'Die Datenpanne ist **innerhalb von 72 Stunden** der Datenschutzaufsichtsbehörde zu melden (Art. 33). Besteht ein hohes Risiko für die Betroffenen, müssen auch diese unverzüglich informiert werden (Art. 34). Die Panne und die Maßnahmen sind zu dokumentieren.', 4],
  ['quiz', [
    {q: 'Welcher Grundsatz fordert, nur notwendige Daten zu erheben?', o: ['Datenminimierung', 'Zweckbindung', 'Richtigkeit', 'Speicherbegrenzung'], a: 0, e: 'Datenminimierung: so wenig Daten wie nötig.'},
    {q: 'Wie schnell muss eine Datenpanne in der Regel der Aufsichtsbehörde gemeldet werden?', o: ['Innerhalb von 72 Stunden', 'Innerhalb von 7 Tagen', 'Nach einem Jahr', 'Gar nicht'], a: 0, e: 'Art. 33 DSGVO verlangt die Meldung in der Regel binnen 72 Stunden.'},
    {q: 'Welches Recht erlaubt, die eigenen Daten in einem maschinenlesbaren Format zu erhalten?', o: ['Recht auf Datenübertragbarkeit', 'Recht auf Löschung', 'Recht auf Widerspruch', 'Recht auf Schweigen'], a: 0, e: 'Art. 20: Datenübertragbarkeit in strukturiertem, gängigem, maschinenlesbarem Format.'},
    {q: 'Was bedeutet "Verbot mit Erlaubnisvorbehalt"?', o: ['Datenverarbeitung ist verboten, außer es gibt eine Rechtsgrundlage', 'Alles ist erlaubt', 'Nur Behörden dürfen Daten verarbeiten', 'Daten dürfen nur gelöscht werden'], a: 0, e: 'Ohne Rechtsgrundlage (Art. 6) ist die Verarbeitung unzulässig.'},
    {q: 'Ist eine IP-Adresse ein personenbezogenes Datum?', o: ['Ja, wenn die Person damit identifizierbar ist', 'Nie', 'Nur bei Behörden', 'Nur in Deutschland'], a: 0, e: 'Auch IP-Adressen können personenbezogen sein, wenn eine Identifizierung möglich ist.'},
  ]],
]);
