AP2.page('ps-epk', {
  b: 'ps', g: 'Anforderungsanalyse', t: 'Geschäftsprozesse modellieren: EPK und eEPK',
  d: 'Eine **ereignisgesteuerte Prozesskette (EPK)** stellt einen **Geschäftsprozess** als Abfolge von **Ereignissen** (Zustände, Sechseck) und **Funktionen** (Tätigkeiten, abgerundetes Rechteck) dar, die abwechselnd folgen und über **Konnektoren** (UND, ODER, XOR) verzweigen und zusammenlaufen. Die **erweiterte EPK (eEPK)** ergänzt **Organisationseinheiten** (wer führt aus?), **Informationsobjekte** (welche Daten, Dokumente, Tabellen werden gelesen oder geschrieben?) und **Anwendungssysteme**. EPKs stammen aus dem ARIS-Konzept und dienen der Analyse und Optimierung von Abläufen, bevor Software sie unterstützt.',
  m: '**Ereignis - Funktion - Ereignis - ...: immer abwechselnd.** **Start und Ende sind Ereignisse.** **Nach einem Ereignis darf kein XOR/ODER verzweigen** (Ereignisse entscheiden nicht), nach einer Funktion schon. **Konnektor, der aufteilt, muss mit demselben Typ wieder zusammengeführt werden.** **eEPK: Organisationseinheit (Oval mit Strich), Informationsobjekt (Rechteck), Pfeilrichtung = Daten lesen oder schreiben.**',
  cheat: [
    ['Grundsymbole', ['**Ereignis**: Sechseck, passiv ("Auftrag eingegangen")', '**Funktion**: abgerundetes Rechteck, aktiv ("Auftrag prüfen")', '**Kontrollfluss**: Pfeil']],
    ['Konnektoren', ['**UND (∧)**: alle Pfade', '**ODER (∨)**: mindestens einer', '**XOR (×)**: genau einer', 'Kreis mit Symbol']],
    ['eEPK-Zusätze', ['Organisationseinheit (Oval)', 'Informationsobjekt (Rechteck)', 'Anwendungssystem', 'Prozesswegweiser (Verweis auf andere EPK)']],
    ['Formulierung', ['Ereignis: Substantiv + Partizip ("Ware geliefert")', 'Funktion: Substantiv + Verb ("Ware prüfen")', 'keine Wertungen, kurz']],
  ],
  blocks: [
    ['h', 'Warum Geschäftsprozesse modellieren?'],
    ['p', 'Bevor eine Software einen Ablauf unterstützt (zum Beispiel ein Wartungsportal), muss man den Ablauf **verstehen**: Wer macht was, wann, mit welchen Informationen, und welche Entscheidungen fallen? Die EPK macht das sichtbar, deckt Medienbrüche und doppelte Arbeit auf und dient als Grundlage für das **Pflichtenheft**. In der Prüfung muss man meist eine **Vorlage vervollständigen** oder aus einem Text eine (e)EPK zeichnen.'],
    ['h', 'Die Symbole'],
    ['diagram', {w: 760, h: 200, keep: 600, cap: 'Grundsymbole der eEPK', nodes: [
      {id: 'e', k: 'diamond', x: 90, y: 60, w: 130, h: 56, t: ['Ereignis', '(Zustand)'], s: 'bad'},
      {id: 'f', k: 'round', x: 260, y: 60, w: 130, h: 56, t: ['Funktion', '(Tätigkeit)'], s: 'ok'},
      {id: 'c', k: 'circle', x: 400, y: 60, w: 50, h: 50, t: 'XOR', s: 'plain'},
      {id: 'o', k: 'oval', x: 540, y: 60, w: 140, h: 50, t: ['Organisations-', 'einheit'], s: 'soft'},
      {id: 'i', k: 'box', x: 690, y: 60, w: 120, h: 50, t: ['Informations-', 'objekt'], s: 'plain'},
      {id: 'l1', k: 'text', x: 90, y: 140, t: ['Sechseck, passiv', '"Rechnung erhalten"'], w: 10, h: 10},
      {id: 'l2', k: 'text', x: 260, y: 140, t: ['aktiv, Verb', '"Rechnung prüfen"'], w: 10, h: 10},
      {id: 'l3', k: 'text', x: 400, y: 140, t: ['UND / ODER /', 'XOR'], w: 10, h: 10},
      {id: 'l4', k: 'text', x: 540, y: 140, t: ['wer?', '"Service-Abteilung"'], w: 10, h: 10},
      {id: 'l5', k: 'text', x: 690, y: 140, t: ['welche Daten?', '"tb_Sensordaten"'], w: 10, h: 10},
    ], edges: []}],
    ['note', 'In der Norm ist das Ereignis ein **Sechseck**; das Diagramm hier zeigt es vereinfacht als Raute-Form. Auf Papier zeichnest du ein flaches Sechseck (Rechteck mit spitzen Seiten).'],
    ['h', 'Regeln für korrekte EPKs'],
    ['steps', [
      'Eine EPK **beginnt** und **endet** mit einem **Ereignis**.',
      '**Ereignisse und Funktionen wechseln sich ab.** Zwei Funktionen oder zwei Ereignisse direkt hintereinander sind falsch (außer über Konnektoren).',
      'Jedes Ereignis und jede Funktion hat **genau einen** ein- und **einen** ausgehenden Kontrollfluss; Verzweigungen nur über **Konnektoren**.',
      '**Entscheidungen trifft eine Funktion**: Nach einem **Ereignis** darf **nicht** mit XOR oder ODER verzweigt werden (ein Ereignis kann nicht entscheiden). Nach einer Funktion folgt bei einer Entscheidung ein XOR und dann die möglichen Ergebnis-Ereignisse.',
      'Ein aufteilender Konnektor wird mit einem Konnektor **desselben Typs** wieder zusammengeführt.',
    ]],
    ['h', 'Prüfungsbeispiel Sommer 2022: Predictive Maintenance (13 Punkte)'],
    ['p', 'Ablauf laut Aufgabentext: Die Service-Abteilung überwacht automatisch die Sensordaten. Wird ein Schwellenwert überschritten, prüft ein Mitarbeiter anhand der Tabelle `tb_Sensordaten` und des Datenblatts, ob ein Wartungsfall vorliegt. Wenn nicht, ist der Prozess beendet und der Kunde wird informiert. Wenn ja, wird die Dringlichkeit (hoch, mittel, niedrig) mit Wartungsvorlage, Datenblatt und Sensordaten eingeordnet. Danach terminiert der Mitarbeiter die Wartung (mit `tb_Techniker` und Datenblatt, Eintrag im Wartungskalender) und bestellt **gleichzeitig** Ersatzteile, falls nötig. Sind beide Schritte erledigt, werden Kunde und Techniker informiert.'],
    ['diagram', {w: 760, h: 760, keep: 560, cap: 'Lösungsskizze als eEPK (vereinfacht). Links Organisationseinheiten, rechts Informationsobjekte.', nodes: [
      {id: 'e1', k: 'diamond', x: 380, y: 30, w: 220, h: 44, t: 'Sensor überschreitet Schwellenwert', s: 'bad'},
      {id: 'f1', k: 'round', x: 380, y: 100, w: 220, h: 44, t: 'Prüfen, ob Wartungsfall vorliegt', s: 'ok'},
      {id: 'x1', k: 'circle', x: 380, y: 165, w: 40, h: 40, t: 'XOR'},
      {id: 'e2', k: 'diamond', x: 200, y: 230, w: 190, h: 44, t: 'Kein Wartungsfall', s: 'bad'},
      {id: 'f2', k: 'round', x: 200, y: 300, w: 190, h: 44, t: 'Kunde informieren', s: 'ok'},
      {id: 'e3', k: 'diamond', x: 200, y: 370, w: 190, h: 44, t: 'Kunde informiert', s: 'bad'},
      {id: 'e4', k: 'diamond', x: 560, y: 230, w: 190, h: 44, t: 'Wartungsfall liegt vor', s: 'bad'},
      {id: 'f4', k: 'round', x: 560, y: 300, w: 210, h: 44, t: 'Dringlichkeit einordnen', s: 'ok'},
      {id: 'x2', k: 'circle', x: 560, y: 360, w: 40, h: 40, t: 'XOR'},
      {id: 'e5', k: 'diamond', x: 560, y: 420, w: 260, h: 40, t: 'Dringlichkeit hoch / mittel / niedrig', s: 'bad'},
      {id: 'a1', k: 'circle', x: 560, y: 480, w: 40, h: 40, t: '∧'},
      {id: 'f6', k: 'round', x: 440, y: 545, w: 200, h: 44, t: 'Wartung terminieren', s: 'ok'},
      {id: 'f7', k: 'round', x: 680, y: 545, w: 170, h: 44, t: 'Ersatzteile bestellen', s: 'ok'},
      {id: 'a2', k: 'circle', x: 560, y: 610, w: 40, h: 40, t: '∧'},
      {id: 'f8', k: 'round', x: 560, y: 668, w: 240, h: 44, t: 'Kunde und Techniker informieren', s: 'ok'},
      {id: 'e8', k: 'diamond', x: 560, y: 730, w: 240, h: 40, t: 'Beteiligte sind informiert', s: 'bad'},
      {id: 'o1', k: 'oval', x: 110, y: 100, w: 120, h: 40, t: 'Service', s: 'soft'},
      {id: 'i1', k: 'box', x: 640, y: 100, w: 150, h: 40, t: 'tb_Sensordaten, Datenblatt'},
      {id: 'i2', k: 'box', x: 120, y: 545, w: 150, h: 40, t: 'tb_Techniker, Kalender'},
    ], edges: [
      {a: 'e1', b: 'f1'}, {a: 'f1', b: 'x1'}, {a: 'x1', b: 'e2'}, {a: 'x1', b: 'e4'}, {a: 'e2', b: 'f2'}, {a: 'f2', b: 'e3'},
      {a: 'e4', b: 'f4'}, {a: 'f4', b: 'x2'}, {a: 'x2', b: 'e5'}, {a: 'e5', b: 'a1'}, {a: 'a1', b: 'f6'}, {a: 'a1', b: 'f7'},
      {a: 'f6', b: 'a2'}, {a: 'f7', b: 'a2'}, {a: 'a2', b: 'f8'}, {a: 'f8', b: 'e8'},
      {a: 'o1', b: 'f1', ea: 'none'}, {a: 'i1', b: 'f1'}, {a: 'i2', b: 'f6'},
    ]}],
    ['p', 'Hinweise zur Lösung: Die drei Dringlichkeiten sind im Original drei getrennte Ereignisse nach dem XOR, die vor "Wartung terminieren" mit einem XOR wieder zusammenlaufen. "Material bestellen" läuft **parallel** (UND), weil es "gleichzeitig" heißt; da Ersatzteile nur "falls nötig" bestellt werden, wäre auch ein **ODER** vertretbar. Informationsobjekte zeigen mit dem Pfeil **zur** Funktion, wenn gelesen wird, und **von** der Funktion weg, wenn geschrieben wird (Wartungskalender).'],
    ['h', 'Industrie 4.0 und Predictive Maintenance'],
    ['p', '**Predictive Maintenance** (vorausschauende Wartung) wertet Sensordaten von Maschinen laufend aus und erkennt Verschleiß, **bevor** ein Ausfall passiert. Gewartet wird nicht nach festem Intervall (präventiv) oder erst nach dem Defekt (reaktiv), sondern **zustandsabhängig**.'],
    ['table', ['Vorteile für den Hersteller (Anbieter des Service)', 'Vorteile für den Kunden'], [
      ['**Kundenbindung** durch Servicevertrag, regelmäßige Einnahmen', 'Weniger **ungeplante Stillstände**, Kostenersparnis'],
      ['**Kundenzufriedenheit** und Image', 'Höhere **Planbarkeit** der Produktion, Wartung in ruhigen Zeiten'],
      ['Daten über das Verhalten der eigenen Maschinen -> bessere Produkte', 'Längere Lebensdauer, Ersatzteile rechtzeitig verfügbar'],
    ]],
    ['h', 'EPK, Aktivitätsdiagramm oder BPMN?'],
    ['table', ['Notation', 'Herkunft', 'Stärke'], [
      ['**EPK / eEPK**', 'ARIS (Scheer), betriebswirtschaftlich, im deutschsprachigen Raum verbreitet', 'Fachabteilungen verstehen sie gut; zeigt Organisation und Daten'],
      ['**UML-Aktivitätsdiagramm**', 'Softwaretechnik', 'Nah an der Implementierung, Swimlanes, Objektflüsse'],
      ['**BPMN 2.0**', 'Internationaler Standard (OMG)', 'Sehr ausdrucksstark (Pools, Lanes, Nachrichten, Ereignistypen), ausführbar in Workflow-Engines'],
    ]],
    ['h', 'Aufgaben im Prüfungsstil'],
    ['qa', 'Nennen Sie je zwei Vorteile der Einführung von Predictive Maintenance für den Maschinenhersteller und dessen Kunden.', ['Hersteller: Kundenbindung, Kundenzufriedenheit (zusätzlich: neue Erlösquelle durch Serviceverträge, Erkenntnisse für die Produktentwicklung).', 'Kunde: Kostenersparnis durch weniger Ausfallzeiten, bessere Planbarkeit der Produktionskapazität.'], 4],
    ['qa', 'Finden Sie die Fehler in folgender EPK: "Bestellung eingegangen" -> XOR -> "Bestellung annehmen" / "Bestellung ablehnen" -> "Bestellung bearbeitet".', ['- Nach dem **Ereignis** "Bestellung eingegangen" wird mit XOR verzweigt. Ein Ereignis kann nicht entscheiden; es fehlt eine **Funktion** wie "Bestellung prüfen", danach XOR mit den Ereignissen "Bestellung ist in Ordnung" / "Bestellung ist fehlerhaft".', '- Die Zweige müssen mit einem **XOR wieder zusammengeführt** werden, bevor ein gemeinsames Endereignis folgt.', '- Nach den Funktionen "annehmen" bzw. "ablehnen" fehlt jeweils ein Ereignis (Wechsel Funktion/Ereignis).'], 4],
    ['quiz', [
      {q: 'Womit beginnt und endet eine EPK?', o: ['Mit Ereignissen', 'Mit Funktionen', 'Mit Konnektoren', 'Mit Organisationseinheiten'], a: 0, e: 'Start- und Endereignis.'},
      {q: 'Welcher Konnektor bedeutet "genau ein Pfad"?', o: ['XOR', 'UND', 'ODER', 'NAND'], a: 0, e: 'Exklusives Oder.'},
      {q: 'Was ergänzt die eEPK gegenüber der EPK?', o: ['Organisationseinheiten und Informationsobjekte', 'Klassen und Methoden', 'Primärschlüssel', 'Zeitdauern'], a: 0, e: 'Wer? Welche Daten?'},
      {q: 'Was ist nach einem Ereignis NICHT erlaubt?', o: ['Eine Verzweigung mit XOR', 'Eine Funktion', 'Ein UND-Konnektor', 'Ein Pfeil'], a: 0, e: 'Ereignisse treffen keine Entscheidungen.'},
      {q: 'Wie wird eine Funktion formuliert?', o: ['Substantiv + Verb, zum Beispiel "Rechnung prüfen"', 'Partizip, zum Beispiel "Rechnung geprüft"', 'Frage, zum Beispiel "Rechnung ok?"', 'Nur ein Substantiv'], a: 0, e: '"Rechnung geprüft" wäre ein Ereignis.'},
    ]],
    ['see', ['ps-aktivitaet', 'ps-usecase', 'ps-marketing']],
  ],
});
