AP2.page('ps-itsm', {
  b: 'ps', g: 'IT-Service und Betrieb', t: 'IT-Service-Management, SLA, Make or Buy und Cloud-Modelle',
  d: '**IT-Service-Management (ITSM)** organisiert den Betrieb von IT als **Dienstleistung** für Kunden und Fachabteilungen. Das bekannteste Rahmenwerk ist **ITIL**. Es unterscheidet unter anderem **Events** (Zustandsmeldungen), **Incidents** (Störungen), **Service Requests** (Standardanfragen), **Problems** (Ursachen wiederkehrender Störungen) und **Changes** (geplante Änderungen). Leistungen und Qualität werden in einem **Service Level Agreement (SLA)** vereinbart. Vor einer Eigenentwicklung steht die **Make-or-Buy-Entscheidung**, beim Betrieb die Wahl zwischen eigenem Rechenzentrum (**On-Premises**), **Managed Hosting** und **Cloud** (IaaS, PaaS, SaaS).',
  m: '**Incident = etwas ist kaputt. Service Request = Standardwunsch (neues Passwort, neue Maus). Event = Meldung über einen Zustand (nicht unbedingt schlimm). Problem = Ursache hinter Incidents.** **SLA = was, wie gut, wie schnell, was passiert bei Verstoß.** **IaaS: Server mieten, PaaS: Plattform mieten, SaaS: fertige Software nutzen.**',
  cheat: [
    ['ITIL-Begriffe', ['**Event**: Zustandsänderung', '**Incident**: ungeplante Störung', '**Service Request**: Standardanfrage', '**Problem**, **Change**, **Known Error**']],
    ['SLA-Inhalte', ['Leistungsbeschreibung, Servicezeiten', 'Verfügbarkeit in %', 'Reaktions- und Wiederherstellungszeit', 'Eskalation, Vertragsstrafen, Berichte']],
    ['Cloud-Modelle', ['**IaaS**: VM, Speicher, Netz', '**PaaS**: Laufzeitumgebung, Datenbank', '**SaaS**: fertige Anwendung', 'Public, Private, Hybrid Cloud']],
    ['Make or Buy', ['Kosten (TCO)', 'Know-how, Kapazität', 'Abhängigkeit, Kontrolle', 'Zeit bis zur Nutzung']],
  ],
  blocks: [
    ['h', 'Events, Incidents, Service Requests (AP1 Sommer 2023)'],
    ['table', ['Begriff', 'Definition', 'Beispiel'], [
      ['**Event** (Ereignis)', 'Jede erkennbare **Zustandsänderung** eines IT-Systems, die für das Management relevant ist. Kann informativ, eine Warnung oder ein Ausnahmefall sein.', 'Backup erfolgreich abgeschlossen; Festplatte zu 85 % voll; Benutzer meldet sich an'],
      ['**Incident** (Störung)', 'Eine **ungeplante Unterbrechung** oder **Qualitätsminderung** eines IT-Service. Ziel: Service **so schnell wie möglich** wiederherstellen.', 'Drucker druckt nicht; E-Mail-Server nicht erreichbar; Anwendung stürzt ab'],
      ['**Service Request** (Serviceanfrage)', 'Eine **Standardanfrage** eines Benutzers, die nicht durch eine Störung ausgelöst wird und nach einem festen Ablauf erledigt wird.', 'Passwort zurücksetzen; neuen Monitor bestellen; Zugriff auf einen Ordner'],
      ['**Problem**', 'Die **unbekannte Ursache** eines oder mehrerer Incidents. Ziel: Ursache finden und dauerhaft beseitigen.', 'Warum fällt der Server jeden Montag aus?'],
      ['**Change**', 'Eine **geplante Änderung** an der IT, die bewertet und genehmigt wird.', 'Update des Betriebssystems, neue Firewall-Regel'],
    ]],
    ['p', 'Ein **Service Desk** ist die zentrale Anlaufstelle (Single Point of Contact). Tickets werden nach **Priorität** bearbeitet; Priorität = **Auswirkung (Impact) x Dringlichkeit (Urgency)**. Kann der First-Level-Support nicht helfen, wird an den Second Level (Spezialisten) oder Third Level (Hersteller) **eskaliert**.'],
    ['h', 'Statusmeldungen und Dringlichkeitsstufen (Syslog)'],
    ['p', 'Server, Router und Firewalls schreiben Meldungen in ein Protokoll (zum Beispiel per **Syslog**, RFC 5424). Jede Meldung hat einen **Schweregrad** von 0 (am dringendsten) bis 7. In AP1-Aufgaben sind Meldungen den Stufen zuzuordnen.'],
    ['table', ['Stufe', 'Name', 'Bedeutung', 'Beispielmeldung'], [
      ['0', 'Emergency', 'System unbenutzbar', 'Kernel panic, Server startet nicht'],
      ['1', 'Alert', 'Sofort handeln', 'RAID: zweite Platte ausgefallen, Daten in Gefahr'],
      ['2', 'Critical', 'Kritischer Zustand', 'Festplattenfehler, Dienst abgestürzt'],
      ['3', 'Error', 'Fehler', 'Anmeldung an Datenbank fehlgeschlagen'],
      ['4', 'Warning', 'Warnung', 'Festplatte zu 90 % voll, Zertifikat läuft in 7 Tagen ab'],
      ['5', 'Notice', 'Normal, aber bemerkenswert', 'Konfiguration geändert'],
      ['6', 'Informational', 'Information', 'Backup erfolgreich, Benutzer angemeldet'],
      ['7', 'Debug', 'Fehlersuche', 'Detaillierte Programmausgaben'],
    ]],
    ['h', 'Service Level Agreement (SLA)'],
    ['def', 'Ein **SLA** ist eine Vereinbarung zwischen **Dienstleister und Kunde** über Art, Umfang und **messbare Qualität** einer IT-Dienstleistung. Interne Vereinbarungen zwischen Abteilungen heißen **OLA** (Operational Level Agreement), Verträge mit Zulieferern **Underpinning Contract**.'],
    ['list', [
      '**Leistungsbeschreibung:** Welche Services (Hosting, Support, Backup)?',
      '**Servicezeiten:** zum Beispiel Mo bis Fr 8 bis 18 Uhr oder 24/7.',
      '**Verfügbarkeit:** zum Beispiel 99,9 % pro Jahr (= höchstens 8,76 Stunden Ausfall).',
      '**Reaktionszeit:** Zeit bis zur ersten Rückmeldung; **Wiederherstellungszeit** (Entstördauer, MTTR): Zeit bis der Service wieder läuft, gestaffelt nach Priorität.',
      '**Datensicherung:** RPO/RTO, Aufbewahrung.',
      '**Eskalationswege, Ansprechpartner, Berichte** (Reporting).',
      '**Vertragsstrafen/Gutschriften** (Pönale) bei Unterschreitung, Laufzeit, Kündigung.',
    ]],
    ['ex', ['AP1 Sommer 2022: Im SLA sind 99,5 % Verfügbarkeit pro Monat (30 Tage) und eine Entstördauer von höchstens 4 Stunden vereinbart. Im Monat gab es zwei Ausfälle: 2,5 h und 3 h.', 'Erlaubte Ausfallzeit: 30 · 24 h · 0,5 % = 720 h · 0,005 = **3,6 h**.', 'Tatsächlich: 5,5 h > 3,6 h -> **Verfügbarkeit nicht eingehalten** (99,24 %). Entstördauer: beide Ausfälle unter 4 h -> **eingehalten**.']],
    ['tool', 'avail'],
    ['h', 'Make or Buy: selbst entwickeln oder einkaufen? (Sommer 2025, 4 Punkte)'],
    ['table', ['Für Eigenentwicklung / Inhouse-Betreuung', 'Für Fremdvergabe / Kauf / Outsourcing'], [
      ['**Know-how-Aufbau** im eigenen Haus, langfristig nutzbar', 'Schneller verfügbar (Standardsoftware sofort einsetzbar)'],
      ['**Volle Kontrolle**, passgenau auf eigene Anforderungen', 'Spezialisierter Anbieter, oft höhere Qualität und Erfahrung'],
      ['**Unabhängigkeit** von externen Dienstleistern (keine Preiserhöhungen, kein Ausfall des Anbieters)', 'Planbare Kosten, kein eigenes Personal nötig'],
      ['Bessere **Kompatibilität** zur eigenen Software', 'Eigene Kapazitäten bleiben für das Kerngeschäft frei'],
      ['Schlechte Leistung eines Externen fällt nicht auf das eigene Unternehmen zurück; **Auslastung und Sicherung eigener Arbeitsplätze**', 'Wartung, Updates und Support inklusive'],
      ['Langfristig oft **kostengünstiger** bei vorhandenem Personal', 'Bei geringer Nutzung meist günstiger als Eigenentwicklung'],
    ]],
    ['h', 'Eigener Server, Managed Server oder Cloud? (Sommer 2024, 10 Punkte)'],
    ['p', 'Rein rechnerisch vergleicht man die **TCO** (Total Cost of Ownership) über die Nutzungsdauer: eigener Server 3.661 € (Kauf, Zubehör, Strom, Internet über 4 Jahre) gegenüber Miete 29 € · 48 Monate + 39 € Einrichtung = 1.431 €. Zusätzlich zu den Kosten sind zu bedenken:'],
    ['list', [
      '**Verfügbarkeit und Ausfallsicherheit:** Rechenzentrum mit USV, Klimatisierung, redundanter Anbindung und automatischem Hardwaretausch.',
      '**Know-how und Personal:** Wer administriert, patcht und sichert den eigenen Server?',
      '**Datenschutz:** Wo stehen die Daten (EU, Deutschland)? Auftragsverarbeitungsvertrag (AVV) nach Art. 28 DSGVO nötig.',
      '**Sicherheit:** professionelles Monitoring, aktuelle Verschlüsselung (inklusive SSL-Zertifikat), Versicherung gegen Schäden.',
      '**Kontrolle und Abhängigkeit:** Beim eigenen Server volle Kontrolle; beim Anbieter Abhängigkeit (Vendor Lock-in), Kündigungsfristen.',
      '**Skalierbarkeit:** Mietlösungen lassen sich schnell vergrößern.',
    ]],
    ['h', 'Cloud-Servicemodelle'],
    ['table', ['Modell', 'Anbieter verwaltet', 'Kunde verwaltet', 'Beispiele'], [
      ['**On-Premises**', 'nichts', 'alles: Gebäude, Hardware, Netz, Betriebssystem, Anwendung, Daten', 'Eigener Serverraum'],
      ['**IaaS** (Infrastructure as a Service)', 'Rechenzentrum, Hardware, Virtualisierung, Netz', 'Betriebssystem, Middleware, Anwendung, Daten', 'Virtuelle Maschinen bei AWS EC2, Azure VM, Hetzner Cloud'],
      ['**PaaS** (Platform as a Service)', 'zusätzlich Betriebssystem, Laufzeitumgebung, Datenbank', 'Anwendung und Daten', 'Azure App Service, Google App Engine, Heroku'],
      ['**SaaS** (Software as a Service)', 'alles bis zur fertigen Anwendung', 'nur Nutzung, Konfiguration, eigene Daten', 'Microsoft 365, Salesforce, Online-Buchhaltung'],
    ]],
    ['p', '**Bereitstellungsmodelle:** **Public Cloud** (geteilte Infrastruktur eines Anbieters), **Private Cloud** (exklusiv für eine Organisation), **Hybrid Cloud** (Kombination), **Community Cloud** (für eine Gruppe mit gleichen Anforderungen, zum Beispiel Behörden).'],
    ['h', 'Aufgaben im Prüfungsstil'],
    ['qa', 'Ordnen Sie zu und begründen Sie: (a) Ein Mitarbeiter benötigt einen zweiten Monitor. (b) Die Warenwirtschaft ist seit 9 Uhr nicht erreichbar. (c) Die Überwachung meldet: Speicherplatz auf dem Fileserver bei 80 %. (d) Ein Benutzer hat sein Passwort vergessen.', ['(a) **Service Request:** Standardanfrage ohne Störung.', '(b) **Incident:** ungeplante Unterbrechung eines Service, schnell wiederherstellen.', '(c) **Event** (Warnung): Zustandsmeldung, noch keine Störung; kann einen Change (Speicher erweitern) auslösen.', '(d) **Service Request:** standardisierter Ablauf (Passwort zurücksetzen).'], 4],
    ['qa', 'Nennen Sie vier mögliche Inhalte eines SLAs.', ['- Beschreibung der Leistung und Servicezeiten', '- zugesicherte Verfügbarkeit in Prozent', '- Reaktionszeit und maximale Wiederherstellungszeit je Priorität', '- Vertragsstrafen, Eskalationswege, Berichtswesen, Laufzeit'], 4],
    ['qa', 'Überzeugen Sie die Geschäftsleitung anhand von zwei Kriterien, dass die Inhouse-Programmierung und -Betreuung eines Softwaremoduls die bessere Alternative ist.', ['- **Know-how bleibt im Unternehmen** und kann langfristig für Weiterentwicklungen genutzt werden; eigene Mitarbeiter sind ausgelastet.', '- **Unabhängigkeit** von einem externen Dienstleister, der Preise erhöhen oder ausfallen könnte; bessere Kompatibilität zur bestehenden Software; schlechte Fremdleistung würde auf das eigene Unternehmen zurückfallen.'], 4],
    ['quiz', [
      {q: 'Was ist ein Incident nach ITIL?', o: ['Eine ungeplante Unterbrechung oder Qualitätsminderung eines Service', 'Eine Standardanfrage', 'Eine geplante Änderung', 'Ein Hardwarekauf'], a: 0, e: 'Ziel: schnelle Wiederherstellung.'},
      {q: 'Welcher Syslog-Schweregrad ist am dringendsten?', o: ['0 Emergency', '7 Debug', '4 Warning', '3 Error'], a: 0, e: 'Je kleiner die Zahl, desto dringender.'},
      {q: 'Bei welchem Cloud-Modell verwaltet der Kunde noch das Betriebssystem?', o: ['IaaS', 'PaaS', 'SaaS', 'Bei keinem'], a: 0, e: 'Bei PaaS übernimmt der Anbieter das Betriebssystem.'},
      {q: '99,9 % Verfügbarkeit pro Jahr erlauben etwa wie viel Ausfall?', o: ['8,76 Stunden', '87,6 Stunden', '52 Minuten', '3,65 Tage'], a: 0, e: '8760 h · 0,001.'},
      {q: 'Wie berechnet man die Priorität eines Tickets?', o: ['Auswirkung x Dringlichkeit', 'Kosten x Zeit', 'Anzahl Anrufe', 'Nach Eingangsdatum'], a: 0, e: 'Impact x Urgency.'},
    ]],
    ['see', ['infra-verfuegbarkeit', 'ps-tco', 'ps-vertraege', 'ps-dsgvo']],
  ],
});
