AP2.page('ps-kalkulation', {
  b: 'ps', g: 'Kaufmännische Rechnungen', t: 'Kalkulation: BAB, Zuschlagskalkulation und Handelskalkulation',
  d: '**Einzelkosten** lassen sich einem Produkt direkt zurechnen (Fertigungsmaterial, Fertigungslöhne). **Gemeinkosten** entstehen für viele Produkte gemeinsam (Miete, Verwaltung, Abschreibungen). Der **Betriebsabrechnungsbogen (BAB)** verteilt die Gemeinkosten auf **Kostenstellen** (Material, Fertigung, Verwaltung, Vertrieb) und berechnet **Gemeinkostenzuschlagssätze**. Mit diesen Sätzen rechnet die **Zuschlagskalkulation** vom Material bis zu den **Selbstkosten** eines Auftrags.',
  m: '**Zuschlagsbasis merken:** MGK auf **Fertigungsmaterial**, FGK auf **Fertigungslöhne**, VwGK und VtGK auf **Herstellkosten**. **Zuschlagssatz = Gemeinkosten der Stelle / Zuschlagsbasis · 100 %.** Schema: **FM + MGK + FL + FGK = HK; HK + VwGK + VtGK = SK.**',
  cheat: [
    ['Zuschlagskalkulation', ['Fertigungsmaterial (FM)', '+ Materialgemeinkosten (MGK)', '+ Fertigungslöhne (FL)', '+ Fertigungsgemeinkosten (FGK)', '**= Herstellkosten (HK)**', '+ Verwaltungsgemeinkosten', '+ Vertriebsgemeinkosten', '**= Selbstkosten (SK)**']],
    ['Zuschlagssätze', ['MGK % = MGK / FM', 'FGK % = FGK / FL', 'VwGK % = VwGK / HK', 'VtGK % = VtGK / HK', 'HK = FM + MGK + FL + FGK']],
    ['Verkaufskalkulation', ['Selbstkosten', '+ Gewinn (vom Hundert)', '= Barverkaufspreis', '+ Kundenskonto (im Hundert)', '= Zielverkaufspreis', '+ Kundenrabatt (im Hundert)', '= Listenverkaufspreis netto', '+ 19 % USt = brutto']],
    ['Kostenverteilung', ['Nach **Schlüssel** (z. B. Mitarbeiter, m², Verhältnis 4:25:4:3)', 'Anteil = Betrag / Summe der Teile · Teile', 'Summe je Kostenstelle bilden']],
  ],
  blocks: [
    ['h', 'Einzelkosten und Gemeinkosten'],
    ['table', ['', 'Einzelkosten', 'Gemeinkosten'], [
      ['Definition', 'Direkt einem Produkt/Auftrag zurechenbar', 'Fallen für mehrere Produkte gemeinsam an'],
      ['Beispiele', 'Fertigungsmaterial (Bauteile), Fertigungslöhne (Montagestunden)', 'Gehälter Verwaltung, Miete, Strom, Abschreibungen, Versicherung'],
      ['Verrechnung', 'Direkt in die Kalkulation', 'Über **Zuschlagssätze** aus dem BAB'],
    ]],
    ['note', 'Nicht verwechseln: **Einzel-/Gemeinkosten** fragt "Kann ich die Kosten einem Produkt direkt zuordnen?". **Fix/variabel** fragt "Ändern sich die Kosten mit der Menge?". Fertigungsmaterial ist Einzelkosten **und** variabel; Miete ist Gemeinkosten **und** fix.'],
    ['h', 'Der Betriebsabrechnungsbogen (BAB)'],
    ['p', 'Der BAB ist eine Tabelle: Zeilen = **Gemeinkostenarten**, Spalten = **Kostenstellen**. Man verteilt jede Kostenart nach einem passenden **Verteilungsschlüssel** auf die Stellen, bildet die Spaltensummen und teilt jede Summe durch ihre Zuschlagsbasis.'],
    ['ex', ['Aufgabe (Winter 2023/24, Zahlen vereinfacht): Personalkosten 120.000 €; Mitarbeiter: Material 4, Verwaltung 1, Vertrieb 1 (gleich hohe Personalkosten).', 'Abschreibungen 360.000 € im Verhältnis **4 : 25 : 4 : 3** (Material : Fertigung : Verwaltung : Vertrieb).', 'Fertigungsmaterial 500.000 €, Fertigungslöhne 350.000 € (nicht im BAB, sie sind Einzelkosten).']],
    ['steps', [
      'Personal: 6 Mitarbeiter, also 120.000 / 6 = 20.000 € je Mitarbeiter. Material 4 · 20.000 = **80.000 €**, Verwaltung **20.000 €**, Vertrieb **20.000 €**, Fertigung 0 €.',
      'Abschreibungen: 4 + 25 + 4 + 3 = 36 Teile; 360.000 / 36 = 10.000 € je Teil. Material **40.000 €**, Fertigung **250.000 €**, Verwaltung **40.000 €**, Vertrieb **30.000 €**.',
      'Sonstige Kosten laut Aufgabe eintragen, Spaltensummen bilden.',
      'Zuschlagsbasen bestimmen und Zuschlagssätze berechnen.',
    ]],
    ['table', ['Kostenart', 'Material', 'Fertigung', 'Verwaltung', 'Vertrieb'], [
      ['Personalkosten', '80.000', '0', '20.000', '20.000'],
      ['Abschreibungen', '40.000', '250.000', '40.000', '30.000'],
      ['Sonstige Kosten', '30.000', '310.000', '18.000', '28.000'],
      ['**Summe Gemeinkosten**', '**150.000**', '**560.000**', '**78.000**', '**78.000**'],
      ['Zuschlagsbasis', 'FM 500.000', 'FL 350.000', 'HK 1.560.000', 'HK 1.560.000'],
      ['**Zuschlagssatz**', '**30 %**', '**160 %**', '**5 %**', '**5 %**'],
    ]],
    ['p', 'Herstellkosten als Basis für Verwaltung und Vertrieb: **HK = FM + MGK + FL + FGK = 500.000 + 150.000 + 350.000 + 560.000 = 1.560.000 €**. Dann 78.000 / 1.560.000 = 5 %.'],
    ['h', 'Zuschlagskalkulation eines Auftrags'],
    ['p', 'Auftrag: Fertigungsmaterial 467 €, Fertigungszeit 10 h zu 25 €/h. Zuschlagssätze aus dem BAB: MGK 30 %, FGK 160 %, VwGK 5 %, VtGK 5 %.'],
    ['table', ['Position', 'Rechnung', 'Betrag'], [
      ['Fertigungsmaterial', '', '467,00 €'],
      ['+ MGK 30 %', '467 · 0,30', '140,10 €'],
      ['= Materialkosten', '', '607,10 €'],
      ['Fertigungslöhne', '10 h · 25 €', '250,00 €'],
      ['+ FGK 160 %', '250 · 1,60', '400,00 €'],
      ['= Fertigungskosten', '', '650,00 €'],
      ['**= Herstellkosten**', '607,10 + 650,00', '**1.257,10 €**'],
      ['+ VwGK 5 %', '1.257,10 · 0,05', '62,86 €'],
      ['+ VtGK 5 %', '1.257,10 · 0,05', '62,86 €'],
      ['**= Selbstkosten**', '', '**1.382,82 €**'],
    ]],
    ['h', 'Handelskalkulation (Verkaufspreis berechnen)'],
    ['p', 'Ein Händler (oder ein IT-Systemhaus, das Hardware weiterverkauft) rechnet vom **Bezugspreis** zum **Listenverkaufspreis**. Neu: **Kundenskonto und Kundenrabatt** werden **"im Hundert"** gerechnet, weil sie später vom Endpreis abgezogen werden.'],
    ['table', ['Schritt', 'Prozentrechnung', 'Beispiel'], [
      ['Bezugspreis', 'aus der Bezugskalkulation', '1.000,00 €'],
      ['+ Handlungskosten 20 %', 'vom Hundert (Basis = 100 %)', '200,00 €'],
      ['= Selbstkosten', '', '1.200,00 €'],
      ['+ Gewinn 10 %', 'vom Hundert', '120,00 €'],
      ['= Barverkaufspreis', '= 98 % des Zielverkaufspreises', '1.320,00 €'],
      ['+ Kundenskonto 2 %', '**im Hundert**: 1.320 / 98 · 2', '26,94 €'],
      ['= Zielverkaufspreis', '= 90 % des Listenpreises', '1.346,94 €'],
      ['+ Kundenrabatt 10 %', '**im Hundert**: 1.346,94 / 90 · 10', '149,66 €'],
      ['= Listenverkaufspreis netto', '', '**1.496,60 €**'],
      ['+ 19 % Umsatzsteuer', '', '284,35 €'],
      ['= Listenverkaufspreis brutto', '', '1.780,95 €'],
    ]],
    ['warn', '**"Im Hundert"** heißt: Der bekannte Betrag ist **nicht** 100 %, sondern 100 % minus Prozentsatz. Prüfe dein Ergebnis rückwärts: 1.346,94 € - 2 % = 1.320,00 €. Würdest du einfach 2 % von 1.320 € addieren, käme nach Abzug des Skontos zu wenig heraus.'],
    ['p', '**Vorwärtskalkulation:** vom Bezugspreis zum Verkaufspreis (wie oben). **Rückwärtskalkulation:** vom Marktpreis (Konkurrenz) zurück zum maximal möglichen Einkaufspreis (Aufgabe "Welchen Einkaufspreis dürfen wir höchstens zahlen?"). **Differenzkalkulation:** Einkaufs- und Verkaufspreis stehen fest, man berechnet den verbleibenden **Gewinn**.'],
    ['h', 'Übungen'],
    ['qa', 'Berechnen Sie den MGK-Zuschlagssatz: MGK laut BAB 96.000 €, Fertigungsmaterial 320.000 €.', 'MGK-Zuschlag = 96.000 / 320.000 · 100 % = **30 %**.', 2],
    ['qa', 'Erläutern Sie den Unterschied zwischen Einzel- und Gemeinkosten und nennen Sie je ein Beispiel aus einem Softwarehaus.', '**Einzelkosten** können einem Auftrag direkt zugerechnet werden, z. B. die für einen Kunden geleisteten Programmierstunden oder eine für dieses Projekt gekaufte Lizenz. **Gemeinkosten** entstehen für alle Aufträge gemeinsam und werden über Zuschläge verteilt, z. B. Büromiete, Gehalt der Buchhaltung, Serverbetrieb.', 4],
    ['qa', 'Ein Händler verkauft einen Monitor für 300 € netto (Listenverkaufspreis). Er gewährt 10 % Rabatt und 2 % Skonto. Berechnen Sie den Barverkaufspreis.', ['Listenverkaufspreis 300,00 €', '- 10 % Rabatt = 30,00 € → Zielverkaufspreis 270,00 €', '- 2 % Skonto = 5,40 € → **Barverkaufspreis 264,60 €**'], 3],
    ['quiz', [
      {q: 'Was ist die Zuschlagsbasis für die Fertigungsgemeinkosten?', o: ['Fertigungslöhne', 'Fertigungsmaterial', 'Herstellkosten', 'Selbstkosten'], a: 0, e: 'FGK % = FGK / FL.'},
      {q: 'Was ist die Basis für Verwaltungs- und Vertriebsgemeinkosten?', o: ['Herstellkosten', 'Fertigungsmaterial', 'Fertigungslöhne', 'Listenpreis'], a: 0, e: 'HK = FM + MGK + FL + FGK.'},
      {q: 'Abschreibungen 72.000 € im Verhältnis 1:2:3. Wie viel erhält die dritte Stelle?', o: ['36.000 €', '24.000 €', '12.000 €', '72.000 €'], a: 0, e: '72.000 / 6 = 12.000 je Teil, 3 Teile = 36.000.'},
      {q: 'Welche Kosten sind Einzelkosten?', o: ['Fertigungsmaterial', 'Miete', 'Strom der Verwaltung', 'Abschreibung Gebäude'], a: 0, e: 'Direkt dem Produkt zurechenbar.'},
      {q: 'Wie wird der Kundenskonto in der Verkaufskalkulation gerechnet?', o: ['Im Hundert', 'Vom Hundert', 'Auf Hundert', 'Gar nicht'], a: 0, e: 'Der Barverkaufspreis entspricht 98 % (bei 2 % Skonto).'},
    ]],
    ['see', ['ps-kostenarten', 'ps-angebot', 'ps-kosten']],
  ],
});
