AP2.page('ps-kostenarten', {
  b: 'ps', g: 'Kaufmännische Rechnungen', t: 'Fixe und variable Kosten, Deckungsbeitrag und Gewinnschwelle (Break-even)',
  d: '**Fixe Kosten (K_fix)** bleiben gleich, egal wie viel produziert oder verkauft wird (Miete, Gehälter, Entwicklungskosten). **Variable Kosten (K_var = k_v · x)** steigen mit jeder Einheit (Material, Verpflegung je Teilnehmer). Der **Deckungsbeitrag je Stück (db = p - k_v)** ist der Betrag, den jedes verkaufte Stück zur Deckung der Fixkosten beiträgt. Die **Gewinnschwelle (Break-even-Menge)** ist die Menge, bei der **Erlöse = Gesamtkosten** gelten: **x = K_fix / db**.',
  m: '**Gewinn = Erlös - Kosten = p · x - (K_fix + k_v · x).** **db = p - k_v.** **Break-even x = K_fix / db, immer AUFrunden** (11,25 Teilnehmer heißt: ab 12 gibt es Gewinn). In der Grafik: Kostenlinie beginnt **bei K_fix**, Erlöslinie beginnt **bei 0**; der Schnittpunkt ist die Gewinnschwelle, links davon **Verlustzone**, rechts **Gewinnzone**.',
  cheat: [
    ['Begriffe', ['**K_fix**: Fixkosten (gesamt)', '**k_v**: variable Kosten je Stück', '**K_var = k_v · x**', '**K = K_fix + k_v · x** (Gesamtkosten)', '**E = p · x** (Erlös, Umsatz)']],
    ['Formeln', ['**db = p - k_v**', '**DB gesamt = db · x**', '**Gewinn = DB gesamt - K_fix**', '**x_BE = K_fix / db**']],
    ['Prüfungsfallen', ['Kosten je **Tag** und je **Teilnehmer** sauber trennen', 'Kosten "unabhängig vom Abhalten" sind **fix**', 'Ergebnis mit **Einheit** und **Antwortsatz**', 'Bei Stückzahlen **aufrunden**']],
    ['Grafik', ['x-Achse: Menge, y-Achse: Euro', 'Fixkosten: waagrechte Linie', 'Kosten: Gerade ab K_fix', 'Erlös: Gerade ab 0', 'Schnittpunkt beschriften']],
  ],
  blocks: [
    ['h', 'Warum unterscheidet man fixe und variable Kosten?'],
    ['p', 'Stell dir eine Schulmensa vor. Die **Miete**, die **Gehälter** der Köche und die **Versicherung** muss die Mensa jeden Monat bezahlen, auch wenn niemand isst. Das sind **fixe Kosten**. Die **Lebensmittel** dagegen kauft sie nur für die Gerichte, die sie tatsächlich ausgibt. Jedes zusätzliche Gericht kostet zusätzliches Geld. Das sind **variable Kosten**.'],
    ['table', ['', 'Fixe Kosten', 'Variable Kosten'], [
      ['Abhängig von der Menge?', '**Nein**, bleiben gleich', '**Ja**, steigen proportional'],
      ['Beispiele Mensa', 'Miete, Gehälter, Versicherung, Wartung', 'Lebensmittel, Geschirrreinigung, Aushilfen pro Stunde'],
      ['Beispiele Fortbildung', 'Raummiete pro Tag, Dozent pro Tag, Verwaltung pauschal', 'Verpflegung, Mappe, Urkunde, Parkticket **je Teilnehmer**'],
      ['Beispiele Softwareprojekt', 'Entwicklungskosten (Personal), Lizenzen', 'Hardware-Bausatz je verkaufter Einheit'],
      ['Je Stück betrachtet', 'sinken mit steigender Menge (Fixkostendegression)', 'bleiben je Stück gleich'],
    ]],
    ['warn', 'Achtung bei Kosten "pro Tag": Die Raummiete von 500 € **pro Tag** ist trotzdem **fix**, denn sie hängt nicht von der Zahl der **Teilnehmer** ab. Sie hängt nur von der Zahl der Tage ab, und die steht fest. Entscheidend ist immer: **Ändern sich die Kosten, wenn ein Teilnehmer mehr kommt?**'],
    ['h', 'Deckungsbeitrag'],
    ['p', 'Der **Deckungsbeitrag je Stück** ist das, was von einem verkauften Stück übrig bleibt, nachdem man die **variablen** Kosten dieses Stücks bezahlt hat. Dieses Geld "deckt" zuerst die Fixkosten. Erst wenn alle Fixkosten gedeckt sind, entsteht Gewinn.'],
    ['ex', ['Mensa: Preis **p = 5,00 €**, variable Kosten **k_v = 2,50 €** je Gericht.', '**db = 5,00 € - 2,50 € = 2,50 €** je Gericht.', 'Jedes verkaufte Gericht trägt also 2,50 € zur Deckung der Fixkosten (10.000 € im Monat) bei.']],
    ['h', 'Gewinnschwelle (Break-even-Point) berechnen'],
    ['steps', [
      'Fixkosten **K_fix** zusammenrechnen (alles, was unabhängig von der Menge anfällt).',
      'Variable Kosten **je Stück k_v** zusammenrechnen (alles, was je Einheit/Teilnehmer anfällt).',
      'Deckungsbeitrag **db = p - k_v** berechnen.',
      'Gewinnschwelle **x = K_fix / db** berechnen.',
      'Ergebnis **aufrunden** und einen **Antwortsatz** schreiben.',
    ]],
    ['p', 'Herleitung: Gewinnschwelle heißt Gewinn = 0, also Erlös = Kosten: `p · x = K_fix + k_v · x`. Man zieht `k_v · x` ab: `(p - k_v) · x = K_fix`, also `x = K_fix / (p - k_v)`.'],
    ['h', 'Prüfungsbeispiel 1: Mensa (Sommer 2025)'],
    ['kv', [['Preis', '5,00 € je Gericht'], ['Fixkosten', '10.000 € pro Monat'], ['Variable Kosten', '2,50 € je Gericht'], ['Kapazität', '10.000 Gerichte (100 %), aktuell 63 % ausgelastet']]],
    ['table', ['Schritt', 'Rechnung', 'Ergebnis'], [
      ['Aktuelle Menge', '63 % von 10.000', '**6.300 Gerichte**'],
      ['Erlös', '5,00 € · 6.300', '31.500 €'],
      ['Gesamtkosten', '10.000 € + 2,50 € · 6.300', '25.750 €'],
      ['Gewinn', '31.500 € - 25.750 €', '**5.750 € pro Monat**'],
      ['Deckungsbeitrag', '5,00 € - 2,50 €', '2,50 € je Gericht'],
      ['Gewinnschwelle', '10.000 € / 2,50 €', '**4.000 Gerichte**'],
    ]],
    ['chart', {kind: 'line', w: 720, h: 340, labels: ['0', '1.000', '2.000', '3.000', '4.000', '5.000', '6.000', '7.000', '8.000'], series: [
      {n: 'Fixkosten', d: [10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000], k: 'text3', dash: '6 5'},
      {n: 'Gesamtkosten', d: [10000, 12500, 15000, 17500, 20000, 22500, 25000, 27500, 30000], k: 'bad'},
      {n: 'Erlöse', d: [0, 5000, 10000, 15000, 20000, 25000, 30000, 35000, 40000], k: 'accent'},
    ], ymax: 40000, yl: 'Euro', cap: 'Break-even-Analyse Mensa: Die Erlöslinie schneidet die Kostenlinie bei 4.000 Gerichten (20.000 €). Links davon liegt die Verlustzone, rechts die Gewinnzone.'}],
    ['table', ['Menge', 'Fixkosten', 'Variable Kosten', 'Gesamtkosten', 'Erlöse', 'Gewinn / Verlust'], [
      ['0', '10.000 €', '0 €', '10.000 €', '0 €', '-10.000 €'],
      ['2.000', '10.000 €', '5.000 €', '15.000 €', '10.000 €', '-5.000 €'],
      ['**4.000**', '10.000 €', '10.000 €', '**20.000 €**', '**20.000 €**', '**0 €**'],
      ['6.000', '10.000 €', '15.000 €', '25.000 €', '30.000 €', '+5.000 €'],
      ['8.000', '10.000 €', '20.000 €', '30.000 €', '40.000 €', '+10.000 €'],
    ]],
    ['tip', 'So zeichnest du die Grafik in der Prüfung: (1) Achsen beschriften mit **Größe und Einheit** ("Menge in Stück", "Kosten/Erlöse in €"). (2) Gleichmäßige Einteilung wählen. (3) Für eine Gerade reichen **zwei Punkte**: Kosten bei x = 0 (= K_fix) und bei der Höchstmenge; Erlös bei 0 (= 0 €) und bei der Höchstmenge. (4) Schnittpunkt markieren und mit "Gewinnschwelle" beschriften. (5) **Gewinnzone** und **Verlustzone** einzeichnen.'],
    ['h', 'Prüfungsbeispiel 2: Präsenz- oder Online-Fortbildung (Sommer 2023)'],
    ['p', 'Eintägige Präsenzfortbildung: Gebühr 380 € je Teilnehmer. Raummiete 750 €/Tag (fix), Dozent 800 €/Tag (fix), kaufmännische Betreuung 250 € (fix), Verpflegung 120 € je TN, Mappe/Urkunde 75 € je TN, Parkticket 25 € je TN.'],
    ['table', ['Schritt', 'Rechnung', 'Ergebnis'], [
      ['K_fix', '750 + 800 + 250', '**1.800 €**'],
      ['k_v', '120 + 75 + 25', '**220 € je TN**'],
      ['Gewinn bei 18 TN', '18 · 380 - 18 · 220 - 1.800', '**1.080 €**'],
      ['db Präsenz', '380 - 220', '**160 €**'],
      ['Gewinnschwelle', '1.800 / 160 = 11,25', '**ab 12 Teilnehmern Gewinn**'],
      ['db Online', 'Gebühr 250 - Urkunde 35', '**215 €** (lukrativer, weil höherer db)'],
      ['Neuer Online-Preis für gleichen db wie Präsenz', '160 + 35', '**195 €**'],
    ]],
    ['h', 'Prüfungsbeispiel 3: Entwicklungskosten decken (Winter 2024/25)'],
    ['p', 'Software plus Hardware wird für 200 € verkauft, der Elektronikbausatz kostet 50 € je Stück. Entwicklung: Projektleiter (30 €/h), Elektroniker (22 €/h), zwei Programmierer (26 €/h), 4 Wochen, 40-h-Woche, aber nur die **Hälfte** der Zeit im Projekt (also je 80 h).'],
    ['table', ['Position', 'Rechnung', 'Kosten'], [
      ['Projektleiter', '30 € · 80 h', '2.400 €'],
      ['Elektroniker', '22 € · 80 h', '1.760 €'],
      ['2 Programmierer', '2 · 26 € · 80 h', '4.160 €'],
      ['**Fixkosten**', '', '**8.320 €**'],
      ['db je Stück', '200 € - 50 €', '150 €'],
      ['Gewinnschwelle', '8.320 / 150 = 55,47', '**ab 56 verkauften Einheiten**'],
      ['Projekt dauert 6 statt 4 Wochen', '8.320 · 1,5 = 12.480 €; 12.480 / 150 = 83,2', '**ab 84 Einheiten** (Lösung: 83,2)'],
    ]],
    ['p', 'Funktionen dazu: **Kostenfunktion K(x) = 8.320 + 50x**, **Erlösfunktion E(x) = 200x**. Gleichsetzen: 8.320 + 50x = 200x, also 8.320 = 150x, x = 55,47.'],
    ['tool', 'breakeven'],
    ['h', 'Übungen'],
    ['qa', 'Erklären Sie den Unterschied zwischen fixen und variablen Kosten und nennen Sie je ein Beispiel aus einem Mensabetrieb.', ['**Fixe Kosten** sind unabhängig von der Ausbringungsmenge und fallen auch an, wenn nichts verkauft wird (z. B. Miete, Gehälter des Stammpersonals, Versicherungen).', '**Variable Kosten** steigen mit jeder zusätzlich hergestellten oder verkauften Einheit (z. B. Lebensmittel je Gericht, Reinigung von Geschirr, Aushilfen auf Stundenbasis).'], 4],
    ['qa', 'Ein Seminar kostet 2.500 € Gebühr je Teilnehmer. Raummiete 500 €/Tag, Dozent 800 €/Tag (5 Tage). Material 175 € je TN, Verpflegung 50 € je TN und Tag. Ab wie vielen Teilnehmern ist das Seminar kostendeckend? (Winter 2022/23)', ['K_fix = (500 + 800) · 5 = **6.500 €**', 'k_v = 175 + 50 · 5 = **425 € je TN**', 'db = 2.500 - 425 = **2.075 €**', 'x = 6.500 / 2.075 = 3,13, also **ab 4 Teilnehmern** ist das Seminar kostendeckend. Bei nur 3 Interessenten entsteht ein Verlust.'], 8],
    ['qa', 'Eine App kostet in der Entwicklung 24.000 € (fix). Sie wird für 12 € verkauft, je Verkauf fallen 30 % Provision an den App-Store an. Berechnen Sie die Gewinnschwelle.', ['k_v = 30 % von 12 € = 3,60 €', 'db = 12 € - 3,60 € = 8,40 €', 'x = 24.000 / 8,40 = 2.857,1, also **ab 2.858 Verkäufen** ist die Entwicklung gedeckt.'], 4],
    ['qa', 'Warum ist bei gleicher Gebühr ein Produkt mit höherem Deckungsbeitrag "lukrativer"?', 'Jede verkaufte Einheit trägt mehr zur Deckung der Fixkosten und danach zum Gewinn bei. Die Gewinnschwelle wird bei **kleinerer Menge** erreicht und jede weitere Einheit bringt **mehr Gewinn**.', 3],
    ['quiz', [
      {q: 'Wie berechnet man den Deckungsbeitrag je Stück?', o: ['Preis minus variable Stückkosten', 'Preis minus Fixkosten', 'Fixkosten durch Menge', 'Erlös minus Gesamtkosten'], a: 0, e: 'db = p - k_v.'},
      {q: 'Wo beginnt die Gesamtkostenlinie im Break-even-Diagramm?', o: ['Bei der Höhe der Fixkosten', 'Im Ursprung (0)', 'Bei der Gewinnschwelle', 'Bei den variablen Kosten'], a: 0, e: 'Auch bei Menge 0 fallen die Fixkosten an.'},
      {q: 'Rechnerische Gewinnschwelle 11,25 Teilnehmer. Ab wie vielen Teilnehmern gibt es Gewinn?', o: ['12', '11', '11,25', '10'], a: 0, e: 'Personen und Stücke sind ganze Zahlen: aufrunden.'},
      {q: 'Welche Kosten sind bei einer Fortbildung variabel?', o: ['Verpflegung je Teilnehmer', 'Raummiete pro Tag', 'Dozentenhonorar pro Tag', 'Pauschale Verwaltung'], a: 0, e: 'Nur sie steigt mit jedem zusätzlichen Teilnehmer.'},
      {q: 'K_fix = 10.000 €, p = 5 €, k_v = 2,50 €. Gewinnschwelle?', o: ['4.000 Stück', '2.000 Stück', '2.500 Stück', '5.000 Stück'], a: 0, e: '10.000 / 2,50 = 4.000.'},
      {q: 'Was passiert mit den Fixkosten JE STÜCK, wenn die Menge steigt?', o: ['Sie sinken', 'Sie steigen', 'Sie bleiben gleich', 'Sie werden negativ'], a: 0, e: 'Fixkostendegression: Die gleichen Fixkosten verteilen sich auf mehr Stücke.'},
    ]],
    ['see', ['ps-kosten', 'ps-kalkulation', 'ps-angebot', 'ps-tco']],
  ],
});
