AP2.add('ps-lastenheft', [
  ['h', 'Muss, Soll und Kann'],
  ['p', 'Anforderungen werden nach ihrer Verbindlichkeit eingeteilt. Das ist wichtig für Preis und Termin, denn Muss-Anforderungen sind Vertragspflicht.'],
  ['table', ['Stufe', 'Bedeutung', 'Beispiel'], [
    ['**Muss** (Musskriterium)', 'Zwingend. Ohne sie ist das Produkt nicht abnahmefähig.', 'Das System muss Rechnungen als PDF erzeugen.'],
    ['**Soll** (Sollkriterium)', 'Sehr wünschenswert, wird nach Möglichkeit umgesetzt.', 'Das System soll Rechnungen automatisch per E-Mail versenden.'],
    ['**Kann** (Kannkriterium)', 'Optional, bei Zeit und Budget.', 'Das System kann ein Dashboard mit Umsatzgrafiken anbieten.'],
    ['**Abgrenzung**', 'Ausdrücklich nicht Teil des Produkts.', 'Das System bietet keine Buchhaltung.'],
  ]],
  ['h', 'Funktionale und nichtfunktionale Anforderungen'],
  ['p', '**Funktionale Anforderungen** sagen, was das System tut ("Der Benutzer kann sich mit E-Mail und Passwort anmelden"). **Nichtfunktionale Anforderungen** sagen, **wie gut** es das tut. Der Katalog der Qualitätsmerkmale nach **ISO 25010** hilft, nichts zu vergessen:'],
  ['table', ['Merkmal', 'Frage', 'Beispiel'], [
    ['Funktionale Eignung', 'Tut es das Richtige?', 'Alle Rechenregeln stimmen'],
    ['Leistungseffizienz', 'Wie schnell, wie ressourcenschonend?', 'Antwort in unter 2 Sekunden bei 500 Nutzern'],
    ['Kompatibilität', 'Läuft es mit anderen Systemen?', 'Läuft in Chrome, Firefox, Edge'],
    ['Benutzbarkeit', 'Ist es einfach bedienbar?', 'Neuer Nutzer bucht in unter 3 Minuten'],
    ['Zuverlässigkeit', 'Fällt es aus? Erholt es sich?', 'Verfügbarkeit 99,9 Prozent'],
    ['Sicherheit', 'Sind Daten geschützt?', 'Passwörter nur als Hash gespeichert'],
    ['Wartbarkeit', 'Ist es änderbar und testbar?', 'Neue Funktion in unter 2 Tagen integrierbar'],
    ['Portabilität', 'Lässt es sich übertragen?', 'Läuft auf Windows und Linux'],
  ]],
  ['h', 'Wie ermittelt man Anforderungen?'],
  ['kv', [
    ['Interview', 'Gespräch mit Fachleuten. Gut für Tiefe, aber zeitaufwendig.'],
    ['Fragebogen', 'Viele Personen schnell befragen. Weniger Tiefe, Rückfragen schwer.'],
    ['Beobachtung', 'Man sieht, wie wirklich gearbeitet wird. Zeigt auch unausgesprochene Abläufe.'],
    ['Workshop', 'Gruppe erarbeitet gemeinsam Anforderungen, Konflikte werden früh sichtbar.'],
    ['Dokumentenanalyse', 'Vorhandene Formulare, Handbücher, Berichte auswerten.'],
    ['Prototyp / Mockup', 'Kunde reagiert auf Sichtbares. Findet Missverständnisse schnell.'],
  ]],
  ['h', 'Gute und schlechte Anforderungen'],
  ['table', ['Schlecht', 'Besser (messbar, eindeutig)'], [
    ['Das System soll schnell sein.', 'Die Startseite muss bei bis zu 500 gleichzeitigen Nutzern in höchstens 2 Sekunden geladen sein.'],
    ['Die Bedienung soll einfach sein.', 'Ein neuer Mitarbeiter muss nach 15 Minuten Einweisung einen Auftrag erfassen können.'],
    ['Das System soll sicher sein.', 'Die Anmeldung erfolgt über HTTPS, Passwörter werden mit einem Hash-Verfahren und Salt gespeichert.'],
  ], {first: false}],
  ['warn', 'Nach der Unterschrift ist das Pflichtenheft die Messlatte bei der **Abnahme**. Was nicht im Pflichtenheft steht, kann der Kunde später nicht einfach verlangen (aber vermeintlich Vereinbartes sollte genau dokumentiert sein).'],
  ['h', 'Aufgaben im Prüfungsstil'],
  ['qa', 'Erklären Sie den Unterschied zwischen Lastenheft und Pflichtenheft.', ['Das **Lastenheft** wird vom Auftraggeber erstellt und beschreibt, **was** er braucht und **wofür** (Anforderungen).', 'Das **Pflichtenheft** wird vom Auftragnehmer auf Basis des Lastenhefts erstellt und beschreibt, **wie und womit** die Anforderungen umgesetzt werden. Es ist meist Vertragsbestandteil.'], 4],
  ['qa', 'Ordnen Sie zu: a) "Das System muss Bestellungen in unter 3 Sekunden bestätigen." b) "Der Kunde kann Artikel in den Warenkorb legen." c) "Das System läuft auf Linux-Servern."', ['- a) nichtfunktionale Anforderung (Leistung)', '- b) funktionale Anforderung', '- c) Randbedingung bzw. technische Anforderung (Portabilität/Umgebung)'], 3],
  ['qa', 'Nennen Sie drei Inhalte, die in einem Pflichtenheft nicht fehlen dürfen.', ['- Zielbestimmung mit Muss-, Soll- und Kann-Kriterien', '- Produktfunktionen (zum Beispiel als Anwendungsfälle)', '- Produktdaten (Datenmodell) und technische Umgebung', '- Qualitätsanforderungen, Oberflächenkonzept, Abnahme- und Testszenarien'], 3],
  ['quiz', [
    {q: 'Wer erstellt normalerweise das Lastenheft?', o: ['Der Auftraggeber', 'Der Auftragnehmer', 'Der Betriebsrat', 'Die IHK'], a: 0, e: 'Das Lastenheft enthält die Anforderungen des Auftraggebers.'},
    {q: 'Welche Frage beantwortet das Pflichtenheft?', o: ['Wie und womit wird es umgesetzt?', 'Was kostet es?', 'Wer ist der Chef?', 'Wann wird es versendet?'], a: 0, e: 'Das Pflichtenheft beschreibt die Realisierung der Anforderungen.'},
    {q: 'Welche Anforderung ist nichtfunktional?', o: ['Die Seite muss in unter 2 Sekunden laden.', 'Der Nutzer kann ein Foto hochladen.', 'Das System berechnet die Mehrwertsteuer.', 'Das System druckt Etiketten.'], a: 0, e: 'Ladezeit beschreibt eine Qualität (Performance), nicht eine Funktion.'},
    {q: 'Was ist ein Kannkriterium?', o: ['Eine optionale Anforderung', 'Eine zwingende Anforderung', 'Ein Verbot', 'Ein Fehler'], a: 0, e: 'Kann-Kriterien werden nur bei ausreichend Zeit und Budget umgesetzt.'},
  ]],
]);
