AP2.page('ps-marketing', {
  b: 'ps', g: 'Kaufmännische Rechnungen', t: 'Marketing-Mix, Franchising und digitale Geschäftsmodelle',
  d: 'Der **Marketing-Mix** besteht aus vier Instrumenten (die **4 P**): **Produktpolitik** (Product: was biete ich an?), **Preispolitik** (Price: zu welchem Preis und welchen Konditionen?), **Kommunikationspolitik** (Promotion: wie mache ich es bekannt?) und **Distributionspolitik** (Place: wie kommt es zum Kunden?). **Franchising** ist eine Kooperation, bei der ein **Franchisegeber** sein Geschäftskonzept, seine Marke und sein Know-how gegen Gebühr an selbstständige **Franchisenehmer** überlässt.',
  m: '**4 P = Produkt, Preis, Promotion (Kommunikation), Place (Distribution).** Franchise: **Geber** bekommt Geld und schnelles Wachstum mit **wenig eigenem Risiko**; **Nehmer** bekommt **bewährtes Konzept, bekannte Marke**, zentralen Einkauf und Werbung, bleibt aber **selbstständig** und zahlt Gebühren.',
  cheat: [
    ['Produktpolitik', ['Produktgestaltung, Qualität, Design', 'Sortiment erweitern', 'Service, Garantie, Kundendienst', 'Neue Inhalte, Module, Updates']],
    ['Preispolitik', ['Preishöhe, Rabatte, Skonto', 'Zahlungsbedingungen, Ratenzahlung', 'Preisdifferenzierung (Schüler, Frühbucher)', 'Abo-Modelle, Freemium']],
    ['Kommunikationspolitik', ['Werbung (Radio, Social Media, SEA)', 'Verkaufsförderung (Probeabo, Gutschein)', 'Public Relations (Pressearbeit)', 'Sponsoring, Messen']],
    ['Distributionspolitik', ['Direktvertrieb (eigener Webshop)', 'Indirekt (Händler, Plattformen)', 'Vertriebspartner, Franchise', 'Logistik, Lieferzeiten']],
  ],
  blocks: [
    ['h', 'Der Marketing-Mix an einem Beispiel'],
    ['p', 'Eine IT-Fortbildungsfirma will ihre neue **Online-Fortbildung** besser verkaufen (Sommer 2023). Zu jedem der vier Bereiche gehört mindestens eine konkrete Maßnahme:'],
    ['table', ['Instrument', 'Leitfrage', 'Konkrete Maßnahme (Online-Fortbildung)'], [
      ['**Produktpolitik**', 'Was genau bieten wir an?', 'Fortbildung um zusätzliche Inhalte, Übungsaufgaben und ein Zertifikat ergänzen'],
      ['**Preispolitik**', 'Was kostet es den Kunden?', 'Preis von 250 € auf 195 € senken, Frühbucherrabatt, Gruppenrabatt'],
      ['**Kommunikationspolitik**', 'Wie erfährt der Kunde davon?', 'Werbung im Radio, auf LinkedIn, Newsletter, kostenloses Webinar als Kostprobe'],
      ['**Distributionspolitik**', 'Über welchen Weg kommt es zum Kunden?', 'Vertrieb über Partner wie Branchenplattformen, IHK, andere IT-Firmen'],
    ]],
    ['tip', 'Wenn die Aufgabe "Maßnahmen **aus anderen** Marketingbereichen" verlangt und die Preissenkung schon vorher berechnet wurde, dann nenne Maßnahmen aus **Produkt-, Kommunikations- und Distributionspolitik**, nicht noch einmal den Preis.'],
    ['h', 'Franchising'],
    ['p', 'Beispiele: McDonald\'s, Subway, Fressnapf, viele Fitnessstudios. Der Franchisegeber stellt **Marke, Konzept, Handbuch, Schulung, Einkauf und Werbung**. Der Franchisenehmer eröffnet auf **eigene Rechnung und eigenes Risiko** eine Filiale und zahlt eine **Einstiegsgebühr** und laufende **Gebühren** (oft prozentual vom Umsatz).'],
    ['table', ['Vorteile für den Franchisenehmer', 'Vorteile für den Franchisegeber'], [
      ['Bewährtes Geschäftsmodell, geringeres Gründungsrisiko', 'Schnelle Expansion ohne eigenes Kapital'],
      ['Bekannte Marke bringt sofort Kunden', 'Geringes unternehmerisches Risiko (trägt der Nehmer)'],
      ['Kostenersparnis durch zentralen Einkauf, Marketing, Buchhaltung', 'Laufende Einnahmen durch Gebühren'],
      ['Schulung, Unterstützung, oft geschütztes Gebiet', 'Motivierte Unternehmer statt Angestellte'],
    ]],
    ['table', ['Nachteile für den Franchisenehmer', 'Nachteile für den Franchisegeber'], [
      ['Hohe Gebühren, weniger Gewinn', 'Weniger Kontrolle über einzelne Filialen'],
      ['Wenig Freiheit (Vorgaben zu Sortiment, Preis, Design)', 'Fehler eines Nehmers schaden dem Image der Marke'],
      ['Abhängigkeit vom Geber', 'Gewinne der Filialen gehören dem Nehmer'],
    ]],
    ['h', 'Industrie 4.0 und Predictive Maintenance'],
    ['p', '**Industrie 4.0** heißt: Maschinen, Sensoren und Software sind vernetzt (Internet of Things) und tauschen Daten in Echtzeit aus. **Predictive Maintenance (vorausschauende Wartung)** nutzt diese Sensordaten, um **vorherzusagen**, wann ein Teil ausfallen wird, und es **vorher** auszutauschen. Gegensatz: **reaktive** Wartung (erst reparieren, wenn es kaputt ist) und **präventive** Wartung (nach festem Zeitplan, egal ob nötig).'],
    ['table', ['Vorteile für den Hersteller (Anbieter)', 'Vorteile für den Kunden'], [
      ['Kundenbindung, wiederkehrender Umsatz (Servicevertrag)', 'Weniger ungeplante Ausfälle, Kostenersparnis'],
      ['Kundenzufriedenheit, Image', 'Bessere Planbarkeit der Produktion'],
      ['Daten zur Verbesserung der eigenen Produkte', 'Längere Lebensdauer der Maschinen'],
      ['Planbarer Einsatz der Techniker und Ersatzteile', 'Wartung nur, wenn nötig'],
    ]],
    ['h', 'Content-Management-System (CMS) statt statischer Website'],
    ['p', 'Ein **CMS** (WordPress, TYPO3, Joomla) trennt **Inhalt** und **Gestaltung**. Redakteure pflegen Texte und Bilder über eine Weboberfläche, ohne HTML zu können.'],
    ['procon', 'CMS gegenüber statischen HTML-Seiten', ['Inhalte ohne Programmierkenntnisse pflegbar', 'Günstiger, viele kostenlose Themes und Plug-ins (Shop, Formulare)', 'Einheitliches Design, Rollen und Rechte für Redakteure', 'Einfache Erweiterung und Wartung'], ['Regelmäßige Updates nötig (Sicherheitslücken in Plug-ins)', 'Mehr Serverlast (Datenbank, PHP)', 'Weniger Freiheit im Design als individuelle Programmierung']],
    ['h', 'Übungen'],
    ['qa', 'Nennen Sie jeweils drei Vorteile für den Franchisenehmer und den Franchisegeber.', ['**Franchisenehmer:** bewährtes Geschäftsmodell, etablierte Marke, Kostenersparnis durch zentralen Einkauf/Marketing/Buchhaltung, geschütztes Vertriebsgebiet.', '**Franchisegeber:** kaum unternehmerisches Risiko, Finanzierung der Expansion durch die Nehmer, motivierte Partner, laufende Gebühreneinnahmen.'], 3],
    ['qa', 'Nennen Sie je zwei Vorteile von Predictive Maintenance für den Maschinenhersteller und für dessen Kunden.', ['**Hersteller:** Kundenbindung, Kundenzufriedenheit (zusätzlich: neue Serviceumsätze).', '**Kunde:** Kostenersparnis durch weniger Ausfallzeiten, höhere Planbarkeit der Produktion.'], 4],
    ['qa', 'Erläutern Sie drei Vorteile eines CMS gegenüber einer statischen HTML-Website.', ['- Einfache Bedienung: Mitarbeiter pflegen Inhalte ohne HTML-Kenntnisse', '- Viele (kostenlose) Erweiterungen und Vorlagen, dadurch geringere Kosten', '- Leichtere Wartung: einheitliches Layout, Änderungen am Design wirken auf alle Seiten'], 3],
    ['quiz', [
      {q: 'Zu welchem Bereich gehört eine Radiowerbung?', o: ['Kommunikationspolitik', 'Produktpolitik', 'Preispolitik', 'Distributionspolitik'], a: 0, e: 'Promotion.'},
      {q: 'Zu welchem Bereich gehört der Vertrieb über Partnerplattformen?', o: ['Distributionspolitik', 'Kommunikationspolitik', 'Preispolitik', 'Produktpolitik'], a: 0, e: 'Place: Absatzweg zum Kunden.'},
      {q: 'Wer trägt beim Franchising das Risiko der einzelnen Filiale?', o: ['Der Franchisenehmer', 'Der Franchisegeber', 'Die IHK', 'Die Bank'], a: 0, e: 'Er ist selbstständiger Unternehmer.'},
      {q: 'Was zeichnet Predictive Maintenance aus?', o: ['Wartung auf Basis von Sensordaten vor dem Ausfall', 'Reparatur erst nach dem Ausfall', 'Wartung nach festem Kalender', 'Keine Wartung'], a: 0, e: 'Vorausschauend statt reaktiv oder starr präventiv.'},
    ]],
    ['see', ['ps-kostenarten', 'eua-iot', 'ps-epk', 'eua-html']],
  ],
});
