AP2.add('ps-normalisierung', [
  ['h', 'Wie erkennt man die Normalform? Prüfschema'],
  ['steps', ['**1NF?** Gibt es Zellen mit mehreren Werten oder Wiederholungsgruppen (Telefon1, Telefon2)? Wenn ja: nicht in 1NF.', '**2NF?** Hat die Tabelle einen **zusammengesetzten** Schlüssel? Wenn ja: Hängt jedes Nicht-Schlüssel-Attribut vom **gesamten** Schlüssel ab? Wenn nicht: nicht in 2NF.', '**3NF?** Bestimmt ein Nicht-Schlüssel-Attribut ein anderes Nicht-Schlüssel-Attribut? (zum Beispiel PLZ bestimmt Ort). Wenn ja: nicht in 3NF.', 'Normalform ist die **höchste Stufe**, deren Bedingungen alle erfüllt sind.']],
  ['h', 'Aufgaben im Prüfungsstil'],
  ['qa', ['Gegeben ist die Tabelle Mitarbeiter(**MitarbeiterNr**, Name, AbteilungsNr, AbteilungsName, AbteilungsLeiter). In welcher Normalform befindet sich die Tabelle? Normalisieren Sie sie bis zur 3NF.'], ['Der Schlüssel ist einfach, die Zellen sind atomar: Die Tabelle ist in **1NF und 2NF**.', 'Es gibt eine **transitive Abhängigkeit**: MitarbeiterNr → AbteilungsNr → AbteilungsName, AbteilungsLeiter. Also **nicht in 3NF**.', '**Lösung:** Mitarbeiter(**MitarbeiterNr**, Name, #AbteilungsNr) und Abteilung(**AbteilungsNr**, AbteilungsName, AbteilungsLeiter).'], 6],
  ['qa', 'Nennen Sie je einen Nachteil einer nicht normalisierten Tabelle (Anomalie) für Einfügen, Ändern und Löschen.', ['- **Einfügen:** Ein neuer Kunde kann nicht gespeichert werden, solange er keine Bestellung hat (Einfügeanomalie).', '- **Ändern:** Zieht ein Kunde um, muss die Adresse in allen seinen Bestellzeilen geändert werden; bei Vergessen entstehen Widersprüche.', '- **Löschen:** Wird die einzige Bestellung eines Kunden gelöscht, gehen auch seine Kundendaten verloren.'], 6],
  ['qa', 'Warum werden Datenbanken manchmal bewusst denormalisiert?', 'Normalisierte Daten erfordern viele JOINs, was bei sehr großen Datenmengen langsam sein kann. Durch **bewusste Redundanz** (zum Beispiel Summe in der Bestellung zusätzlich speichern) werden Abfragen schneller. Nachteil: Der Entwickler muss selbst für Konsistenz sorgen.', 3],
  ['quiz', [
    {q: 'Was verlangt die 1. Normalform?', o: ['Atomare Werte in jeder Zelle', 'Keine Fremdschlüssel', 'Mindestens 3 Tabellen', 'Nur numerische Werte'], a: 0, e: 'Jede Zelle enthält genau einen unteilbaren Wert.'},
    {q: 'Wann kann eine Tabelle in 1NF die 2NF überhaupt verletzen?', o: ['Wenn der Primärschlüssel zusammengesetzt ist', 'Wenn sie keinen Primärschlüssel hat', 'Wenn sie zu viele Zeilen hat', 'Nie'], a: 0, e: 'Teilabhängigkeiten gibt es nur bei zusammengesetzten Schlüsseln.'},
    {q: 'PLZ bestimmt Ort, KundenNr bestimmt PLZ. Welche Normalform wird verletzt, wenn Ort in der Kundentabelle steht?', o: ['3NF (transitive Abhängigkeit)', '1NF', '2NF', 'Keine'], a: 0, e: 'KundenNr → PLZ → Ort ist eine transitive Abhängigkeit, verboten in der 3NF.'},
    {q: 'Was ist eine Änderungsanomalie?', o: ['Eine Information muss an mehreren Stellen geändert werden', 'Ein Datensatz kann nicht geändert werden', 'Die Datenbank stürzt ab', 'Daten verschwinden beim Einfügen'], a: 0, e: 'Durch Redundanz müssen Änderungen mehrfach erfolgen, sonst entstehen Widersprüche.'},
  ]],
]);
