AP2.add('ps-phasen', [
  ['h', 'Die vier Phasen im Detail'],
  ['diagram', AP2.dg.flow(['Initiierung', 'Planung', 'Durchführung', 'Abschluss'], {h: 100, styles: ['accent', 'accent', 'accent', 'accent'], edgeText: ['Auftrag', 'Plan', 'Ergebnis'], cap: 'Der Projektablauf als Kette von Phasen mit Meilensteinen dazwischen.'})],
  ['h3', '1. Initiierung (Start)'],
  ['p', 'Hier entsteht die Idee. Man klärt: Was ist das Problem? Was ist das Ziel? Lohnt sich das Projekt? Am Ende steht der **Projektauftrag** (englisch: project charter). Er enthält Ziel, grobe Kosten, Termin, Projektleiter und Befugnisse.'],
  ['list', ['**Ergebnisse:** Projektauftrag, Machbarkeitsstudie, Stakeholder-Liste, Ist-Analyse', '**Wichtige Methoden:** Wirtschaftlichkeitsbetrachtung (Kosten-Nutzen), Stakeholder-Analyse, grobe Risikoabschätzung']],
  ['h3', '2. Planung'],
  ['p', 'Der Projektleiter zerlegt das Projekt in kleine, überschaubare Teile und plant Zeit, Kosten, Personal und Risiken. Je besser die Planung, desto weniger Überraschungen später.'],
  ['list', ['**Projektstrukturplan (PSP):** Zerlegung in Teilaufgaben und Arbeitspakete (was?)', '**Ablauf- und Terminplan:** Reihenfolge, Dauer, Netzplan, Gantt-Diagramm (wann?)', '**Kosten- und Ressourcenplan:** Personal, Material, Budget (womit, wie viel?)', '**Risikoplan:** Was kann schiefgehen? Wie reagieren wir? (Risikoanalyse)', '**Qualitäts- und Kommunikationsplan:** Wer berichtet wem wann?']],
  ['h3', '3. Durchführung (Steuerung)'],
  ['p', 'Jetzt wird gearbeitet. Gleichzeitig vergleicht der Projektleiter ständig **Soll** (Plan) und **Ist** (Realität). Weicht es ab, steuert er gegen. Das nennt man **Projektcontrolling**.'],
  ['list', ['**Fortschrittskontrolle:** Meilensteintrendanalyse, Statusberichte, Soll-Ist-Vergleich', '**Änderungsmanagement (Change Requests):** Neue Wünsche werden bewertet, nicht einfach eingebaut', '**Risikomanagement läuft weiter** und die Dokumentation wird aktuell gehalten']],
  ['h3', '4. Abschluss'],
  ['p', 'Das Ergebnis wird vom Kunden **abgenommen** (Abnahmeprotokoll). Dann folgt die Übergabe (Handbuch, Schulung, Betrieb) und die **Abschlussbesprechung** mit Lessons Learned: Was lief gut? Was lief schlecht? Was machen wir beim nächsten Projekt anders?'],
  ['table', ['Phase', 'Leitfrage', 'Typisches Ergebnis'], [
    ['Initiierung', 'Was wollen wir und lohnt es sich?', 'Projektauftrag'],
    ['Planung', 'Wie, wann, womit machen wir es?', 'Projektplan (PSP, Netzplan, Budget)'],
    ['Durchführung', 'Sind wir im Plan?', 'Zwischenergebnisse, Statusberichte'],
    ['Abschluss', 'Haben wir erreicht, was vereinbart war?', 'Abnahmeprotokoll, Abschlussbericht'],
  ]],
  ['note', 'In DIN 69901 werden fünf Phasen genannt: Initialisierung, Definition, Planung, Steuerung, Abschluss. Die vier Phasen hier sind eine übliche Vereinfachung (Definition und Planung zusammen, Steuerung = Durchführung). Nenne in der Prüfung die Phasen, die in der Aufgabe vorkommen.'],
  ['h', 'Meilensteine'],
  ['p', 'Ein **Meilenstein** ist ein wichtiger Zeitpunkt ohne Dauer, an dem ein Ergebnis fertig sein muss, zum Beispiel "Pflichtenheft abgenommen" oder "Test abgeschlossen". Meilensteine dienen als Kontrollpunkte (englisch: Quality Gates): Hier entscheidet der Auftraggeber, ob das Projekt weitergeht.'],
  ['warn', 'Ein Meilenstein hat **keine Dauer** (0 Tage). Ein Vorgang oder Arbeitspaket dagegen hat immer eine Dauer.'],
]);
