AP2.page('ps-tco', {
  b: 'ps', g: 'Kaufmännische Rechnungen', t: 'TCO, Make-or-Buy, Outsourcing und Cloud',
  d: 'Die **Total Cost of Ownership (TCO)** ist die **Summe aller Kosten**, die ein IT-System über seine **gesamte Nutzungsdauer** verursacht: Anschaffung, Betrieb (Strom, Internet, Wartung, Personal, Lizenzen) und Entsorgung. Mit der TCO vergleicht man z. B. einen **eigenen Server** mit einem **gemieteten (Managed) Server** oder einer **Cloud-Lösung**. **Make-or-Buy** fragt allgemein: selbst erstellen/betreiben (**Inhouse**) oder einkaufen (**Outsourcing**)?',
  m: '**TCO = Anschaffung + Betriebskosten · Jahre (+ Entsorgung).** Alle Kosten auf **denselben Zeitraum** bringen (Monat · 12 · Jahre). Stromkosten: **kWh/Jahr · Preis/kWh · Jahre** (oder Watt · Stunden / 1000). Neben den Kosten immer **qualitative** Argumente nennen: Datenschutz, Verfügbarkeit, Know-how, Abhängigkeit.',
  cheat: [
    ['TCO-Bestandteile', ['**Direkt:** Hardware, Software, Lizenzen, Installation', '**Betrieb:** Strom, Kühlung, Internet, Wartung, Support', '**Personal:** Administration, Schulung', '**Indirekt:** Ausfallzeiten, Entsorgung']],
    ['Strom', ['Energie (kWh) = Leistung (kW) · Zeit (h)', '1 kW = 1000 W', '1 Jahr = 8.760 h (365 · 24)', 'Kosten = kWh · €/kWh']],
    ['Cloud-Modelle', ['**IaaS**: Infrastruktur (VM, Speicher)', '**PaaS**: Plattform (Laufzeit, DB)', '**SaaS**: fertige Software (Office 365)', 'Public, Private, Hybrid Cloud']],
    ['Make or Buy', ['Inhouse: Kontrolle, Know-how, Datenschutz', 'Outsourcing: Fachwissen, Fixkosten sinken', 'Risiko: Abhängigkeit, Datenschutz (AVV)']],
  ],
  blocks: [
    ['h', 'Was gehört zur TCO?'],
    ['p', 'Viele schauen nur auf den **Kaufpreis**. Der ist aber oft nur ein kleiner Teil. Ein Server braucht Strom, Kühlung, Internet, Updates, Backups, einen Administrator und irgendwann Ersatzteile. Die TCO macht diese **versteckten Kosten** sichtbar.'],
    ['h', 'Prüfungsbeispiel: Eigener Server oder Managed Server? (Sommer 2024)'],
    ['kv', [['Kaufpreis Server', '1.799 €'], ['Weitere Hardware/Software (Firewall, Schrank, Kabel)', '1.100 €'], ['Stromverbrauch', '450 kWh pro Jahr zu 0,29 €/kWh'], ['Schnellerer Internetanschluss', '5 € pro Monat'], ['Nutzungsdauer', '4 Jahre'], ['Managed Server (Miete)', '29 € pro Monat + 39 € Einrichtung']]],
    ['table', ['Kostenposition', 'Rechnung', 'Kosten (4 Jahre)'], [
      ['Server', '', '1.799 €'],
      ['Weitere Hard- und Software', '', '1.100 €'],
      ['Strom', '450 kWh · 0,29 €/kWh · 4 Jahre', '522 €'],
      ['Internetanbindung', '5 € · 12 Monate · 4 Jahre', '240 €'],
      ['**TCO eigener Server**', '', '**3.661 €**'],
      ['Managed Server', '29 € · 48 Monate + 39 €', '**1.431 €**'],
    ]],
    ['p', 'Die **Miete ist deutlich günstiger**. Weitere Punkte für die Entscheidung:'],
    ['procon', 'Managed Server / Cloud mieten', ['Professioneller Anbieter: **hohe Verfügbarkeit**, redundante Hardware, automatischer Hardwaretausch', 'Administration und Updates übernimmt der Anbieter (kein eigenes Know-how nötig)', 'Aktuelle Sicherheitstechnik und SSL-Zertifikat inklusive', 'Kosten **planbar** (monatliche Rate), keine Anfangsinvestition', 'Skalierbar: mehr Leistung bei Bedarf'], ['**Datenschutz**: personenbezogene Daten liegen beim Anbieter (Auftragsverarbeitungsvertrag nach DSGVO nötig, Serverstandort EU prüfen)', '**Abhängigkeit** vom Anbieter (Preiserhöhungen, Insolvenz, Vendor-Lock-in)', 'Zugriff nur über das **Internet**', 'Weniger Kontrolle über Hardware und Konfiguration']],
    ['h', 'Inhouse oder Outsourcing? (Sommer 2025)'],
    ['table', ['Argument für Inhouse-Entwicklung/-Betreuung', 'Erläuterung'], [
      ['Kosten', 'Langfristig oft günstiger, kein Gewinnaufschlag des Dienstleisters'],
      ['Kompatibilität', 'Eigenes Team kennt die übrige Software, Integration klappt besser'],
      ['Qualität und Image', 'Schlechte Leistung eines Dienstleisters fällt auf das eigene Unternehmen zurück'],
      ['Know-how', 'Wissen bleibt im Unternehmen und kann weiter genutzt werden'],
      ['Unabhängigkeit', 'Kein Risiko, dass der Dienstleister Preise erhöht oder ausfällt'],
      ['Auslastung', 'Eigene Mitarbeiter werden beschäftigt, Arbeitsplätze gesichert'],
    ]],
    ['table', ['Argument für Outsourcing', 'Erläuterung'], [
      ['Spezialwissen', 'Dienstleister hat Erfahrung und Fachleute'],
      ['Konzentration aufs Kerngeschäft', 'Eigene Mitarbeiter bleiben für wichtigere Aufgaben frei'],
      ['Fixkosten werden variabel', 'Man zahlt nur, was man braucht'],
      ['Schnellere Umsetzung', 'Keine eigene Einarbeitung nötig'],
    ]],
    ['h', 'Cloud-Servicemodelle'],
    ['table', ['Modell', 'Was mietet man?', 'Was macht man selbst?', 'Beispiel'], [
      ['**IaaS** (Infrastructure as a Service)', 'Virtuelle Server, Speicher, Netz', 'Betriebssystem, Software, Daten', 'Azure VM, AWS EC2'],
      ['**PaaS** (Platform as a Service)', 'Laufzeitumgebung, Datenbank, Webserver', 'Eigene Anwendung und Daten', 'Azure App Service, Heroku'],
      ['**SaaS** (Software as a Service)', 'Fertige Anwendung im Browser', 'Nur Nutzung und Daten', 'Microsoft 365, Salesforce'],
    ]],
    ['p', '**Public Cloud:** Anbieter-Rechenzentrum, von vielen Kunden geteilt. **Private Cloud:** nur für ein Unternehmen (eigenes oder dediziertes Rechenzentrum). **Hybrid Cloud:** Kombination, z. B. sensible Daten privat, Rest öffentlich.'],
    ['h', 'Stromkosten berechnen (AP1-Klassiker)'],
    ['ex', ['10 PCs mit je 120 W und ein Drucker mit 40 W laufen 8 Stunden an 220 Arbeitstagen. Strompreis 0,40 €/kWh.', 'Leistung gesamt = 10 · 120 W + 40 W = 1.240 W = 1,24 kW', 'Energie = 1,24 kW · 8 h · 220 = **2.182,4 kWh** pro Jahr', 'Kosten = 2.182,4 kWh · 0,40 €/kWh = **872,96 €** pro Jahr', 'Werden die PCs durch Geräte mit 60 W ersetzt: 10 · 60 + 40 = 640 W; Einsparung = (1.240 - 640) / 1.240 = **48,4 %**.']],
    ['h', 'Übungen'],
    ['qa', 'Berechnen Sie die TCO für 3 Jahre: Server 2.400 €, Lizenzen 300 € pro Jahr, Stromaufnahme durchgehend 150 W, Strompreis 0,30 €/kWh, Wartungsvertrag 20 € pro Monat.', ['Strom pro Jahr: 0,15 kW · 8.760 h = 1.314 kWh; · 0,30 € = 394,20 € → 3 Jahre: 1.182,60 €', 'Lizenzen: 3 · 300 = 900 €', 'Wartung: 20 · 36 = 720 €', '**TCO = 2.400 + 900 + 1.182,60 + 720 = 5.202,60 €**'], 6],
    ['qa', 'Nennen Sie zwei Sachverhalte außer den Kosten, die ein Verein bei der Entscheidung "eigener Server oder Miete" berücksichtigen sollte.', ['- **Datenschutz/Sicherheit** der Mitgliederdaten: Wer hat Zugriff, wo steht der Server, gibt es einen AV-Vertrag?', '- **Verfügbarkeit und Know-how**: Kann der Verein selbst Updates, Backups und Störungen zuverlässig betreuen?', '- **Abhängigkeit** vom Anbieter und Vertragslaufzeit.'], 4],
    ['quiz', [
      {q: 'Was gehört NICHT zur TCO eines Servers?', o: ['Umsatz des Unternehmens', 'Stromkosten', 'Wartungsvertrag', 'Anschaffungspreis'], a: 0, e: 'TCO umfasst nur Kosten über den Lebenszyklus.'},
      {q: 'Wie viele Stunden hat ein Jahr (ohne Schaltjahr)?', o: ['8.760', '8.640', '5.256', '10.000'], a: 0, e: '365 · 24 = 8.760.'},
      {q: 'Microsoft 365 im Browser ist ein Beispiel für ...', o: ['SaaS', 'IaaS', 'PaaS', 'On-Premises'], a: 0, e: 'Fertige Software als Dienst.'},
      {q: 'Welches ist ein typisches Risiko beim Outsourcing?', o: ['Abhängigkeit vom Dienstleister', 'Zu viel eigenes Know-how', 'Höhere Fixkosten', 'Mehr Kontrolle'], a: 0, e: 'Auch Datenschutz und Qualitätsverlust sind Risiken.'},
      {q: '200 W laufen 10 h. Wie viele kWh sind das?', o: ['2 kWh', '20 kWh', '2.000 kWh', '0,2 kWh'], a: 0, e: '0,2 kW · 10 h = 2 kWh.'},
    ]],
    ['see', ['ps-kosten', 'ps-kostenarten', 'infra-usv', 'ps-itsm', 'ps-dsgvo']],
  ],
});
