AP2.page('de-pruefung', {
  b: 'de', g: 'Prüfung', t: 'Die Deutschprüfung: Aufbau, Aufgabentypen und Schreibaufgaben 2022 bis 2024',
  d: 'Die schriftliche Deutschprüfung der Berufsschule (BW, FA 035/3, **120 Minuten**, Hilfsmittel: Rechtschreibwörterbuch) gibt es in zwei **Prüfungstypen**, von denen man **einen** bearbeitet: **Typ I** mit **nicht-fiktionalen Texten** (Zeitungsartikel, Schaubild) und **Typ II** mit einem **fiktionalen Text** (Romanauszug). Beide haben **Teil 1 "Textverständnis und Sprachgebrauch"** (25 Punkte: Aussagen prüfen, Schaubild lesen, Textstellen umformulieren, Redewendungen zuordnen, das/dass) und **Teil 2 "Schreibaufgabe"** (25 Punkte: ein adressatengerechter Text wie Forumsbeitrag, Brief, E-Mail oder Buchvorstellung, höchstens zwei Seiten).',
  m: '**Teil 1: genau lesen, Zeilen belegen, nichts hineininterpretieren.** **Teil 2: Situation + Adressat + alle Spiegelstriche abarbeiten = Punkte.** **Spiegelstriche der Aufgabe als Gliederung (oder Zwischenüberschriften) verwenden.** **Textsortenmerkmale einhalten** (Anrede, Gruß, Überschrift). **das = der/dieses/welches einsetzbar, dass = Konjunktion.**',
  cheat: [
    ['Teil 1 (25 P.)', ['Aussagen: aus Text ableitbar? (richtig/falsch)', 'Schaubild-Aussagen prüfen', 'Textstellen umformulieren (Sinn erhalten)', 'Redewendungen, das/dass, Wortarten']],
    ['Teil 2 (25 P.)', ['Forumsbeitrag / Homepage-Beitrag', 'Brief / E-Mail an eine Figur', 'Buchvorstellung "Auf den ersten Blick"', 'max. 2 Seiten']],
    ['Bewertung Teil 2', ['Inhalt: alle Aufgabenpunkte', 'Aufbau: Einleitung, Hauptteil, Schluss', 'Adressatenbezug, Textsorte', 'Sprache: Ausdruck, Rechtschreibung, Grammatik']],
    ['das oder dass?', ['Artikel: das Leben', 'Demonstrativ: Das stimmt.', 'Relativ: das Dorf, das ... (= welches)', 'Konjunktion: Ich weiß, dass ...']],
  ],
  blocks: [
    ['h', 'Überblick über die Prüfungen'],
    ['table', ['Prüfung', 'Typ I (Sachtexte): Material und Schreibaufgabe', 'Typ II (Roman): Material und Schreibaufgabe'], [
      ['Winter 2022/23', 'Texte zur **Pünktlichkeit** -> Beitrag für die Homepage www.azubi-info.de (sich vorstellen, Rolle der Pünktlichkeit in Ausbildung und Betrieb, Zwischenüberschriften, Beispiele)', 'Romanauszug über **Marlene** (Ritalin, Geld, Lügen, Überlastung) + Infotext -> **Brief** an Marlene: warum ich schreibe, ihre Probleme, Gefahren, was sie ändern soll'],
      ['Sommer 2023', 'Annonce der Zeitschrift "DEIN DING" -> Text **"Meine Ausbildung: Wunsch und Wirklichkeit"** (wer bin ich, Erwartungen, Erfahrungen, Ratschlag)', 'Cay Rademacher, **"Der Trümmermörder"** -> Romanvorstellung für "Auf den ersten Blick" auf Literatur-Check.de'],
      ['Winter 2023/24', 'FAZ-Artikel **"Mein Freund, der Roboter"** (Fachkräftemangel, Automatisierung) + Schaubild -> **Forumsbeitrag** "Dein Beruf in Gegenwart und Zukunft" (Vorstellung, Veränderung durch Digitalisierung, Empfehlung)', 'Sven Pfizenmaier, **"Draußen feiern die Leute"** (Richard, der andere lähmt) -> **Antwort-E-Mail** an Larissa, die ihre "Zustände" erklärt'],
      ['Sommer 2024', 'Texte zur **Jugendsprache** -> Beitrag für ein Jugendsprachelexikon (Freundeskreis und Beispiele, Haltung zu den Beispielen, Erfahrungen im Betrieb und privat)', 'Bonnie Garmus, **"Eine Frage der Chemie"** -> Romanvorstellung "Auf den ersten Blick"'],
    ]],
    ['h', 'Teil 1: Textverständnis und Sprachgebrauch'],
    ['table', ['Aufgabentyp', 'Worauf achten?'], [
      ['**"Welche Aussagen lassen sich aus dem Text ableiten?"**', 'Nur was **im Text steht oder sich zwingend daraus ergibt**. Eigenes Wissen zählt nicht. Achtung bei Verallgemeinerungen ("immer", "alle", "problemlos"). Falsche Kreuze geben Minuspunkte (aber nie unter 0 je Aufgabe).'],
      ['**Schaubild-Aussagen prüfen**', 'Titel, Einheit (Prozent oder absolut), Zeitraum und Quelle lesen. Prozent und Prozentpunkte unterscheiden.'],
      ['**Textverständnis (Typ II): Welche Deutung passt am besten?**', 'Ironie erkennen: Wenn die Lehrerin sagt "Ich bin sicher, Sie mussten das tun. Ihrer Gesundheit zuliebe", meint sie das Gegenteil: Sie **ärgert sich** über die Verspätung.'],
      ['**Umformulieren** ohne die unterstrichenen Wörter', 'Sinn genau erhalten, ganzer korrekter Satz. "Die Pandemie ist noch nicht ausgestanden" -> "Die Pandemie ist noch nicht vorbei."'],
      ['**Redewendungen zuordnen**', '"ins kalte Wasser geworfen werden" = unvorbereitet eine neue Aufgabe übernehmen; "mit allen Wassern gewaschen sein" = erfahren und gerissen; "nach jemandes Pfeife tanzen" = gehorchen; "aus der Reihe tanzen" = sich nicht anpassen; "etwas wächst einem über den Kopf" = überfordert sein; "den Kopf hängen lassen" = mutlos sein; "keinen Finger krumm machen" = faul sein; "die Finger im Spiel haben" = heimlich beteiligt sein.'],
      ['**das oder dass**', 'Ersatzprobe: Kann man **dieses, jenes oder welches** einsetzen, schreibt man **das** (Artikel, Demonstrativ- oder Relativpronomen). Sonst **dass** (Konjunktion, leitet einen Nebensatz ein, oft nach Verben wie wissen, glauben, hoffen).'],
    ]],
    ['ex', ['"Ich weiß, ___ Leben auf dem Land wird oft kritisiert." -> **das** (Artikel zu "Leben").', '"Es heißt, ___ Jugendliche dort wenige Freizeitangebote haben." -> **dass** (Konjunktion).', '"Das Dorf, ___ ich kenne, ..." -> **das** (Relativpronomen, = welches).', '"___ ist das Beste." -> **Das** (Demonstrativpronomen, = dieses).']],
    ['h', 'Teil 2: So holst du die 25 Punkte'],
    ['steps', [
      '**Situation und Adressat klären:** Wer schreibt (ich als Azubi, als Freundin), an wen (zukünftige Azubis, Romanfigur, Forumsleser), wo (Homepage, Zeitschrift, Brief)?',
      '**Alle Spiegelstriche/Punkte der Aufgabe** markieren und als **Gliederung** übernehmen. Jeder fehlende Punkt kostet Inhaltspunkte.',
      '**Material nutzen:** Informationen aus den Texten **in eigenen Worten** einbauen (nicht abschreiben); bei Romanaufgaben Inhalte des Auszugs korrekt wiedergeben, eventuell mit Zeilenangabe.',
      '**Textsorte beachten:** Brief/E-Mail mit Ort, Datum, Anrede, Grußformel; Forumsbeitrag mit Überschrift und persönlicher Ansprache; Buchvorstellung mit den vorgegebenen **Zwischenüberschriften**.',
      '**Konkret werden:** eigene Beispiele aus der Ausbildung (als Fachinformatiker/-in: Ticketsystem, Code-Reviews, KI-Assistenten, Homeoffice).',
      '**Umfang:** höchstens zwei Seiten. Lieber vollständig und sauber als lang. Am Ende 5 Minuten für Rechtschreibung.',
    ]],
    ['h3', 'Muster: Forumsbeitrag "Mein Beruf in Gegenwart und Zukunft" (Winter 2023/24, Typ I)'],
    ['ex', ['**Fachinformatikerin für Anwendungsentwicklung: ein Beruf mit Zukunft**', 'Hallo zusammen, ich bin Lea, 22 Jahre alt, und mache gerade den Abschluss meiner Ausbildung zur Fachinformatikerin für Anwendungsentwicklung bei einem Softwarehaus in Ulm. Ich entwickle Webanwendungen, schreibe Datenbankabfragen, teste Programme und betreue Kunden bei Fragen.', '**Wie sich mein Beruf verändert hat:** Als ich angefangen habe, haben wir viel Code noch komplett selbst geschrieben. Heute schlagen KI-Assistenten ganze Funktionen vor, und Routineaufgaben wie Tests oder Dokumentation laufen teilweise automatisch. Server betreiben wir kaum noch selbst, sondern in der Cloud. Dadurch ist meine Arbeit nicht weniger geworden, sondern anspruchsvoller: Ich muss die Vorschläge prüfen, Sicherheitslücken erkennen und verstehen, was der Kunde wirklich braucht.', '**Soll man den Beruf noch lernen?** Ja, unbedingt. Im Artikel "Mein Freund, der Roboter" steht, dass zwar Tätigkeiten automatisiert werden, aber neue Jobs mit höheren Anforderungen entstehen. Genau das erlebe ich: Wer bereit ist, sich ständig weiterzubilden, hat sehr gute Chancen, denn Fachkräfte werden überall gesucht.', 'Viel Erfolg bei eurer Entscheidung! Eure Lea']],
    ['h3', 'Muster-Gerüst: Buchvorstellung "Auf den ersten Blick" (Typ II, Sommer 2023 und 2024)'],
    ['list', [
      '**Autorin/Autor und Titel:** Name, Titel, Erscheinungsjahr, Genre (Krimi, Gesellschaftsroman), eventuell Infos aus dem Klappentext.',
      '**Wiedergabe des Inhalts:** Was passiert im Romananfang? Wer sind die Hauptfiguren, wo und wann spielt die Handlung? Im **Präsens**, in eigenen Worten, sachlich.',
      '**Vermutungen über den weiteren Verlauf:** begründete Vermutungen mit Bezug auf Hinweise im Text ("Da ... angedeutet wird, vermute ich, dass ...").',
      '**Abschließendes Urteil:** Lohnt sich das Weiterlesen? Begründung mit Sprache, Spannung, Figuren, Thema, und für wen das Buch geeignet ist.',
    ]],
    ['h3', 'Muster-Gerüst: Brief oder E-Mail an eine Romanfigur'],
    ['list', [
      '**Anlass:** Warum schreibe ich? ("Ich schreibe dir, weil ich mir Sorgen mache ...")',
      '**Inhalt des Romanauszugs** korrekt in eigenen Worten wiedergeben: Was weiß ich über die Probleme (Marlene) bzw. über Richards Wirkung auf andere (Larissas "Zustände")?',
      '**Eigene Einschätzung, Gefahren, Rat:** konkrete Vorschläge (Beratungsstelle, Gespräch, Arzt), einfühlsam formuliert.',
      '**Form:** Ort und Datum (Brief), persönliche Anrede ("Liebe Larissa,"), Du-Form, Grußformel ("Viele Grüße").',
    ]],
    ['quiz', [
      {q: 'Welche Form ist richtig: "Ich hoffe, ___ du kommst."?', o: ['dass', 'das', 'daß', 'des'], a: 0, e: 'Konjunktion, "welches" passt nicht.'},
      {q: 'Was bedeutet "ins kalte Wasser geworfen werden"?', o: ['Unvorbereitet eine neue Aufgabe bewältigen müssen', 'Bestraft werden', 'Im Urlaub sein', 'Sehr erfahren sein'], a: 0, e: 'Typische Redewendung aus Winter 2023/24.'},
      {q: 'Wie viele Punkte gibt es für Teil 2 (Schreibaufgabe)?', o: ['25', '10', '50', '15'], a: 0, e: 'Teil 1 und Teil 2 je 25 Punkte.'},
      {q: 'Welche Zeitform nutzt man für eine Inhaltswiedergabe?', o: ['Präsens', 'Präteritum', 'Plusquamperfekt', 'Futur II'], a: 0, e: 'Vorzeitiges im Perfekt.'},
    ]],
    ['see', ['de-text', 'de-eroerterung', 'de-brief', 'de-sprache', 'wiso-methoden']],
  ],
});
